const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const { dbConnect } = require("./config/config");
const dotenv = require("dotenv");
dotenv.config();

const app = express();

// Middleware
app.use(bodyParser.json());
app.use(cors());

// Dashboard routes
const user_orders = require("./routes/user_orders");
const RFQ = require("./routes/rfq");

// page routes
const { sessionsRoute } = require("./routes/sessions");
const usersRoute = require("./routes/users");
const configurationsRoute = require("./routes/configurations");
const draftsRoute = require("./routes/drafts");
const emailRoute = require("./routes/email");
const cartRoute = require("./routes/cart");
const fglmRoute = require("./routes/fglm");
const fgcoRoute = require("./routes/fgco");
const cc5clRoute = require("./routes/CC5_CL");
const cc5op4OeRoute = require("./routes/CC5_OP4OE");
const coeCdlRoute = require("./routes/COE_CDL");
const coeCelRoute = require("./routes/COE_CEL");
const coeOp4oeRoute = require("./routes/COE_OP4OE");
const eti807Route = require("./routes/ETI_807");
const eti9000invlRoute = require("./routes/ETI_9000INVL");
const eti91Route = require("./routes/ETI_91");
const etiOp48eRoute = require("./routes/ETI_OP48E");
const eto2100Route = require("./routes/ETO_2100");
const eto9000eRoute = require("./routes/ETO_9000E");
const etoOp48eRoute = require("./routes/ETO_OP48E");
const fc314Route = require("./routes/FC_314");
const fc317Route = require("./routes/FC_317");
const fro314Route = require("./routes/FRO_314");
const fro317Route = require("./routes/FRO_317");
const froEsRoute = require("./routes/FRO_ES");
const froOebRoute = require("./routes/FRO_OEB");
const froOp139aRoute = require("./routes/FRO_OP139A");
const ftFtlRoute = require("./routes/FT_FTL");
const ftOp40eRoute = require("./routes/FT_OP40E");
const ftOpcoRoute = require("./routes/FT_OPCO");
// const ibrOp4oeRoute = require("./routes/IBR_OP4OE");
// const ibrOpco300Route = require("./routes/IBR_OPCO300");
// const ibrRfcRoute = require("./routes/IBR_RFC");
// const iftIftlRoute = require("./routes/IFT_IFTL");
// const iftOp4oeRoute = require("./routes/IFT_OP4OE");
// const ohp001Route = require("./routes/OHP_001");
// const ohp2100iRoute = require("./routes/OHP_2100I");
// const ohp9000iRoute = require("./routes/OHP_9000I");
// const ohpCbsRoute = require("./routes/OHP_CBS");
// const ohpCdlRoute = require("./routes/OHP_CDL");
// const ohpEsRoute = require("./routes/OHP_ES");
// const ohpGpcRoute = require("./routes/OHP_GPC");
// const ohpMlpRoute = require("./routes/OHP_MLP");
// const ohpOebRoute = require("./routes/OHP_OEB");
// const ohpOp13Route = require("./routes/OHP_OP13");
// const ohpOp139aRoute = require("./routes/OHP_OP139A");
// const ohpOp4aRoute = require("./routes/OHP_OP4A");
// const ohpOp55Route = require("./routes/OHP_OP55");
// const ohpOp8Route = require("./routes/OHP_OP8");
// const ohpOp8npRoute = require("./routes/OHP_OP8NP");
// const ohpPmlRoute = require("./routes/OHP_PML");
// const ohpPmmRoute = require("./routes/OHP_PMM");
// const ohpYcbRoute = require("./routes/OHP_YCB");
// const paf001Route = require("./routes/PAF_001");
// const paf314Route = require("./routes/PAF_314");
// const paf317Route = require("./routes/PAF_317");
// const paf9000eRoute = require("./routes/PAF_9000E");
// const paf9000iRoute = require("./routes/PAF_9000I");
// const paf9000pfRoute = require("./routes/PAF_9000PF");
// const pafCdlRoute = require("./routes/PAF_CDL");
// const pafEsRoute = require("./routes/PAF_ES");
// const pafGpcRoute = require("./routes/PAF_GPC");
// const pafMlpRoute = require("./routes/PAF_MLP");
// const pafOp139aRoute = require("./routes/PAF_OP139A");
// const pafOp8Route = require("./routes/PAF_OP8");
// const pafOp8npRoute = require("./routes/PAF_OP8NP");
// const pafPmlRoute = require("./routes/PAF_PML");
// const pafPmmRoute = require("./routes/PAF_PMM");
// const pafSlsRoute = require("./routes/PAF_SLS");

// Dashboard route usage
app.use("/api/user_orders", user_orders);
app.use("/api/rfq", rfq);

// Route usage
app.use("/api/cart", cartRoute);
app.use("/api/configurations", configurationsRoute);
app.use("/api/drafts", draftsRoute);
app.use("/api/email", emailRoute);
app.use("/api/sessions", sessionsRoute);
app.use("/api/users", usersRoute);
app.use("/api/fglm", fglmRoute);
app.use("/api/fgco", fgcoRoute);
app.use("/api/cc5_cl", cc5clRoute);
app.use("/api/cc5_op40e", cc5op4OeRoute);
app.use("/api/coe_cdl", coeCdlRoute);
app.use("/api/coe_cel", coeCelRoute);
app.use("/api/coe_op4oe", coeOp4oeRoute);
app.use("/api/eti_807", eti807Route);
app.use("/api/eti_9000invl", eti9000invlRoute);
app.use("/api/eti_91", eti91Route);
app.use("/api/eti_op48e", etiOp48eRoute);
app.use("/api/eto_2100", eto2100Route);
app.use("/api/eto_9000e", eto9000eRoute);
app.use("/api/eto_op48e", etoOp48eRoute);
app.use("/api/fc_314", fc314Route);
app.use("/api/fc_317", fc317Route);
app.use("/api/fro_314", fro314Route);
app.use("/api/fro_317", fro317Route);
app.use("/api/fro_es", froEsRoute);
app.use("/api/fro_oeb", froOebRoute);
app.use("/api/fro_op139a", froOp139aRoute);
app.use("/api/ft_ftl", ftFtlRoute);
app.use("/api/ft_op40e", ftOp40eRoute);
app.use("/api/ft_opco", ftOpcoRoute);
// app.use("/api/ibr_op4oe", ibrOp4oeRoute);
// app.use("/api/ibr_opco300", ibrOpco300Route);
// app.use("/api/ibr_rfc", ibrRfcRoute);
// app.use("/api/ift_iftl", iftIftlRoute);
// app.use("/api/ift_op4oe", iftOp4oeRoute);
// app.use("/api/ohp_001", ohp001Route);
// app.use("/api/ohp_2100i", ohp2100iRoute);
// app.use("/api/ohp_9000i", ohp9000iRoute);
// app.use("/api/ohp_cbs", ohpCbsRoute);
// app.use("/api/ohp_cdl", ohpCdlRoute);
// app.use("/api/ohp_es", ohpEsRoute);
// app.use("/api/ohp_gpc", ohpGpcRoute);
// app.use("/api/ohp_mlp", ohpMlpRoute);
// app.use("/api/ohp_oeb", ohpOebRoute);
// app.use("/api/ohp_op13", ohpOp13Route);
// app.use("/api/ohp_op139a", ohpOp139aRoute);
// app.use("/api/ohp_op4a", ohpOp4aRoute);
// app.use("/api/ohp_op55", ohpOp55Route);
// app.use("/api/ohp_op8", ohpOp8Route);
// app.use("/api/ohp_op8np", ohpOp8npRoute);
// app.use("/api/ohp_pml", ohpPmlRoute);
// app.use("/api/ohp_pmm", ohpPmmRoute);
// app.use("/api/ohp_ycb", ohpYcbRoute);
// app.use("/api/paf_001", paf001Route);
// app.use("/api/paf_314", paf314Route);
// app.use("/api/paf_317", paf317Route);
// app.use("/api/paf_9000e", paf9000eRoute);
// app.use("/api/paf_9000i", paf9000iRoute);
// app.use("/api/paf_9000pf", paf9000pfRoute);
// app.use("/api/paf_cdl", pafCdlRoute);
// app.use("/api/paf_es", pafEsRoute);
// app.use("/api/paf_gpc", pafGpcRoute);
// app.use("/api/paf_mlp", pafMlpRoute);
// app.use("/api/paf_op139a", pafOp139aRoute);
// app.use("/api/paf_op8", pafOp8Route);
// app.use("/api/paf_op8np", pafOp8npRoute);
// app.use("/api/paf_pml", pafPmlRoute);
// app.use("/api/paf_pmm", pafPmmRoute);
// app.use("/api/paf_sls", pafSlsRoute);

// run app without .env vars
app.listen(8080, '0.0.0.0', () => {
	dbConnect();
	console.log(`Listening on port 8080...`);
});