const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const CCO_139A = require("../models/CCO_139A");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");
const templateD = require("../models/templateD.js");
const templateF = require("../models/templateF.js");

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { CCO_139AData, numRequested } = req.body;
        const order = new CCO_139A({
            conveyorName: CCO_139AData.conveyorName,
            chainSize: CCO_139AData.chainSize,
            ...(CCO_139AData.otherChainSize && { otherChainSize: CCO_139AData.otherChainSize }),
            industrialChainManufacturer: CCO_139AData.industrialChainManufacturer,
            ...(CCO_139AData.otherChainManufacturer && { otherChainManufacturer: CCO_139AData.otherChainManufacturer }),
            wheelManufacturer: CCO_139AData.wheelManufacturer,
            ...(CCO_139AData.otherWheelManufacturer && { otherWheelManufacturer: CCO_139AData.otherWheelManufacturer }),
            conveyorLength: CCO_139AData.conveyorLength,
            conveyorLengthUnit: CCO_139AData.conveyorLengthUnit,
            conveyorSpeed: CCO_139AData.conveyorSpeed,
            conveyorSpeedUnit: CCO_139AData.conveyorSpeedUnit,
            conveyorIndex: CCO_139AData.conveyorIndex,
            ...(CCO_139AData.travelDirection && { travelDirection: CCO_139AData.travelDirection }),
            appEnviroment: CCO_139AData.appEnviroment,
            ...(CCO_139AData.ovenStatus && { ovenStatus: CCO_139AData.ovenStatus }),
            ...(CCO_139AData.ovenTemp && { ovenTemp: CCO_139AData.ovenTemp }),
            ...(CCO_139AData.otherAppEnviroment && { otherAppEnviroment: CCO_139AData.otherAppEnviroment }),
            strandStatus: CCO_139AData.strandStatus,
            pointsOfLube: CCO_139AData.pointsOfLube,
            sensingMethod: CCO_139AData.sensingMethod,
            ...(CCO_139AData.surroundingTemp && { surroundingTemp: CCO_139AData.surroundingTemp }),
            ...(CCO_139AData.conveyorLoaded && { conveyorLoaded: CCO_139AData.conveyorLoaded }),
            ...(CCO_139AData.conveyorSwing && { conveyorSwing: CCO_139AData.conveyorSwing }),
            ...(CCO_139AData.compressedAir && { compressedAir: CCO_139AData.compressedAir }),
            ...(CCO_139AData.airSupplyType && { airSupplyType: CCO_139AData.airSupplyType }),
            operatingVoltSingle: CCO_139AData.operatingVoltSingle,
            controlVoltSingle: CCO_139AData.controlVoltSingle,

            monitorData: 
            {
                existingMonitor: CCO_139AData.templateA.existingMonitor,
                newMonitor: CCO_139AData.templateA.newMonitor,		
                ...(CCO_139AData.templateA.dcuStatus && { dcuStatus: CCO_139AData.dcuStatus }),
                ...(CCO_139AData.templateA.dcuNum && { dcuNum: CCO_139AData.dcuNum }),
                ...(CCO_139AData.templateA.existingWindows && { existingWindows: CCO_139AData.existingWindows }),
                ...(CCO_139AData.templateA.existingHeadUnit && { existingHeadUnit: CCO_139AData.existingHeadUnit }),
                ...(CCO_139AData.templateA.existingDCU && { existingDCU: CCO_139AData.existingDCU }),
                ...(CCO_139AData.templateA.existingPowerInterface && { existingPowerInterface: CCO_139AData.existingPowerInterface }),
                ...(CCO_139AData.templateA.newReservoir && { newReservoir: CCO_139AData.newReservoir }),
                ...(CCO_139AData.templateA.reservoirSize && { reservoirSize: CCO_139AData.reservoirSize }),
                ...(CCO_139AData.templateA.otherReservoirSize && { otherReservoirSize: CCO_139AData.otherReservoirSize }),
                ...(CCO_139AData.templateA.newReservoirNum && { newReservoirNum: CCO_139AData.newReservoirNum }),
                ...(CCO_139AData.templateA.typeMonitor && { typeMonitor: CCO_139AData.typeMonitor }),
                ...(CCO_139AData.templateA.driveMotorAmp && { driveMotorAmp: CCO_139AData.driveMotorAmp }),
                ...(CCO_139AData.templateA.driveMotorAmpNum && { driveMotorAmpNum: CCO_139AData.driveMotorAmpNum }),
                ...(CCO_139AData.templateA.driveTakeUpAir && { driveTakeUpAir: CCO_139AData.driveTakeUpAir }),
                ...(CCO_139AData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_139AData.driveTakeUpAirNum }),
                ...(CCO_139AData.templateA.takeUpDistance && { takeUpDistance: CCO_139AData.takeUpDistance }),
                ...(CCO_139AData.templateA.takeUpDistanceNum && { takeUpDistanceNum: CCO_139AData.takeUpDistanceNum }),
                ...(CCO_139AData.templateA.driveTemp && { driveTemp: CCO_139AData.driveTemp }),
                ...(CCO_139AData.templateA.driveTempNum && { driveTempNum: CCO_139AData.driveTempNum }),
                ...(CCO_139AData.templateA.driveVibration && { driveVibration: CCO_139AData.driveVibration }),
                ...(CCO_139AData.templateA.driveVibrationNum && { driveVibrationNum: CCO_139AData.driveVibrationNum }),
                ...(CCO_139AData.templateA.dogPitch && { dogPitch: CCO_139AData.dogPitch }),
                ...(CCO_139AData.templateA.dogPitchNum && { dogPitchNum: CCO_139AData.dogPitchNum }),
                ...(CCO_139AData.templateA.paintMarker && { paintMarker: CCO_139AData.paintMarker }),
                ...(CCO_139AData.templateA.paintMarkerNum && { paintMarkerNum: CCO_139AData.paintMarkerNum }),
                ...(CCO_139AData.templateA.chainVision && { chainVision: CCO_139AData.chainVision }),
                ...(CCO_139AData.templateA.lubeVision && { lubeVision: CCO_139AData.lubeVision }),
                ...(CCO_139AData.templateA.trolleyVision && { trolleyVision: CCO_139AData.trolleyVision }),
                ...(CCO_139AData.templateA.trolleyDetect && { trolleyDetect: CCO_139AData.trolleyDetect }),
                ...(CCO_139AData.templateA.omniView && { omniView: CCO_139AData.omniView }),
                ...(CCO_139AData.templateA.dcuUpgradeNum && { dcuUpgradeNum: CCO_139AData.dcuUpgradeNum }),
                ...(CCO_139AData.templateA.piuDistance && { piuDistance: CCO_139AData.piuDistance }),
                ...(CCO_139AData.templateA.switchDistance && { switchDistance: CCO_139AData.switchDistance }),
                ...(CCO_139AData.templateA.ampPickup && { ampPickup: CCO_139AData.ampPickup }),
                ...(CCO_139AData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_139AData.fromAirTakeUpDistance }),
                ...(CCO_139AData.templateA.specialControllerOptions && { specialControllerOptions: CCO_139AData.specialControllerOptions }),
                ...(CCO_139AData.templateA.operatingVoltage && { operatingVoltage: CCO_139AData.operatingVoltage })
            },

            addFreeCarrier: CCO_139AData.addFreeCarrier,

            templateBData: 
            {
                
                conveyorName: CCO_139AData.templateB.conveyorName,
                industrialChainManufacturer: CCO_139AData.templateB.industrialChainManufacturer,
                ...(CCO_139AData.templateB.otherChainManufacturer && { otherChainManufacturer: CCO_139AData.templateB.otherChainManufacturer }),
                wheelManufacturer: CCO_139AData.templateB.wheelManufacturer,
                ...(CCO_139AData.templateB.wheelManufacturer && { wheelManufacturer: CCO_139AData.templateB.wheelManufacturer}),
                conveyorSpeed: CCO_139AData.templateB.conveyorSpeed,
                conveyorSpeedUnit: CCO_139AData.templateB.conveyorSpeedUnit,
                conveyorIndex: CCO_139AData.templateB.conveyorIndex,
                ...(CCO_139AData.templateB.travelDirection && { travelDirection: CCO_139AData.templateB.travelDirection}),
                appEnviroment: CCO_139AData.templateB.appEnviroment,
                ...(CCO_139AData.templateB.otherAppEnviroment && { otherAppEnviroment: CCO_139AData.templateB.otherAppEnviroment}),
                surroundingTemp: CCO_139AData.templateB.surroundingTemp,
                orientationType: CCO_139AData.templateB.orientationType,
                operatingVoltage: CCO_139AData.templateB.operatingVoltage,
                controlVoltSingle: CCO_139AData.templateB.controlVoltSingle,
                compressedAir: CCO_139AData.templateB.compressedAir,
                ...(CCO_139AData.templateB.airSupplyType && { airSupplyType: CCO_139AData.templateB.airSupplyType}),

                templateA_BData: {
                    
                    existingMonitor: CCO_139AData.templateA.existingMonitor,
                    newMonitor: CCO_139AData.templateA.newMonitor,		
                    ...(CCO_139AData.templateA.dcuStatus && { dcuStatus: CCO_139AData.templateA.dcuStatus }),
                    ...(CCO_139AData.templateA.dcuNum && { dcuNum: CCO_139AData.templateA.dcuNum }),
                    ...(CCO_139AData.templateA.existingWindows && { existingWindows: CCO_139AData.templateA.existingWindows }),
                    ...(CCO_139AData.templateA.existingHeadUnit && { existingHeadUnit: CCO_139AData.templateA.existingHeadUnit }),
                    ...(CCO_139AData.templateA.existingDCU && { existingDCU: CCO_139AData.templateA.existingDCU }),
                    ...(CCO_139AData.templateA.existingPowerInterface && { existingPowerInterface: CCO_139AData.templateA.existingPowerInterface }),
                    ...(CCO_139AData.templateA.newReservoir && { newReservoir: CCO_139AData.templateA.newReservoir }),
                    ...(CCO_139AData.templateA.reservoirSize && { reservoirSize: CCO_139AData.templateA.reservoirSize }),
                    ...(CCO_139AData.templateA.otherReservoirSize && { otherReservoirSize: CCO_139AData.templateA.otherReservoirSize }),
                    ...(CCO_139AData.templateA.newReservoirNum && { newReservoirNum: CCO_139AData.templateA.newReservoirNum }),
                    ...(CCO_139AData.templateA.typeMonitor && { typeMonitor: CCO_139AData.templateA.typeMonitor }),
                    ...(CCO_139AData.templateA.driveMotorAmp && { driveMotorAmp: CCO_139AData.templateA.driveMotorAmp }),
                    ...(CCO_139AData.templateA.driveMotorAmpNum && { driveMotorAmpNum: CCO_139AData.templateA.driveMotorAmpNum }),
                    ...(CCO_139AData.templateA.driveTakeUpAir && { driveTakeUpAir: CCO_139AData.templateA.driveTakeUpAir }),
                    ...(CCO_139AData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_139AData.templateA.driveTakeUpAirNum }),
                    ...(CCO_139AData.templateA.takeUpDistance && { takeUpDistance: CCO_139AData.templateA.takeUpDistance }),
                    ...(CCO_139AData.templateA.takeUpDistanceNum && { takeUpDistanceNum: CCO_139AData.templateA.takeUpDistanceNum }),
                    ...(CCO_139AData.templateA.driveTemp && { driveTemp: CCO_139AData.templateA.driveTemp }),
                    ...(CCO_139AData.templateA.driveTempNum && { driveTempNum: CCO_139AData.templateA.driveTempNum }),
                    ...(CCO_139AData.templateA.driveVibration && { driveVibration: CCO_139AData.templateA.driveVibration }),
                    ...(CCO_139AData.templateA.driveVibrationNum && { driveVibrationNum: CCO_139AData.templateA.driveVibrationNum }),
                    ...(CCO_139AData.templateA.dogPitch && { dogPitch: CCO_139AData.templateA.dogPitch }),
                    ...(CCO_139AData.templateA.dogPitchNum && { dogPitchNum: CCO_139AData.templateA.dogPitchNum }),
                    ...(CCO_139AData.templateA.paintMarker && { paintMarker: CCO_139AData.templateA.paintMarker }),
                    ...(CCO_139AData.templateA.paintMarkerNum && { paintMarkerNum: CCO_139AData.templateA.paintMarkerNum }),
                    ...(CCO_139AData.templateA.chainVision && { chainVision: CCO_139AData.templateA.chainVision }),
                    ...(CCO_139AData.templateA.lubeVision && { lubeVision: CCO_139AData.templateA.lubeVision }),
                    ...(CCO_139AData.templateA.trolleyVision && { trolleyVision: CCO_139AData.templateA.trolleyVision }),
                    ...(CCO_139AData.templateA.trolleyDetect && { trolleyDetect: CCO_139AData.templateA.trolleyDetect }),
                    ...(CCO_139AData.templateA.omniView && { omniView: CCO_139AData.templateA.omniView }),
                    ...(CCO_139AData.templateA.dcuUpgradeNum && { dcuUpgradeNum: CCO_139AData.templateA.dcuUpgradeNum }),
                    ...(CCO_139AData.templateA.piuDistance && { piuDistance: CCO_139AData.templateA.piuDistance }),
                    ...(CCO_139AData.templateA.switchDistance && { switchDistance: CCO_139AData.templateA.switchDistance }),
                    ...(CCO_139AData.templateA.ampPickup && { ampPickup: CCO_139AData.templateA.ampPickup }),
                    ...(CCO_139AData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_139AData.templateA.fromAirTakeUpDistance }),
                    ...(CCO_139AData.templateA.specialControllerOptions && { specialControllerOptions: CCO_139AData.templateA.specialControllerOptions }),
                    ...(CCO_139AData.templateA.operatingVoltage && { operatingVoltage: CCO_139AData.templateA.operatingVoltage })

                },

                freeWheelStatus: CCO_139AData.templateB.freeWheelStatus,
                actuatorStatus: CCO_139AData.templateB.actuatorStatus,
                ...(CCO_139AData.templateB.pivotStatus && { pivotStatus: CCO_139AData.templateB.pivotStatus}),
                kingPinStatus: CCO_139AData.templateB.kingPinStatus,
                lubeBrand: CCO_139AData.templateB.lubeBrand,
                lubeViscosity: CCO_139AData.templateB.lubeViscosity,
                ...(CCO_139AData.templateB.lubeType && { lubeType: CCO_139AData.templateB.lubeType}),
                currentGrease: CCO_139AData.templateB.currentGrease,
                currentGreaseGrade: CCO_139AData.templateB.currentGreaseGrade,
                zerkDirection: CCO_139AData.templateB.zerkDirection,
                zerkLocationType: CCO_139AData.templateB.zerkLocationType,
                wheelDiameter: CCO_139AData.templateB.wheelDiameter,
                conveyorSwing: CCO_139AData.templateB.conveyorSwing,
                ...(CCO_139AData.templateB.chainMaster && { lubeType: CCO_139AData.templateB.chainMaster}),
                ...(CCO_139AData.templateB.remoteStatus && { lubeType: CCO_139AData.templateB.remoteStatus}),
                ...(CCO_139AData.templateB.mountStatus && { lubeType: CCO_139AData.templateB.mountStatus}),
                ...(CCO_139AData.templateB.otherUnitStatus && { lubeType: CCO_139AData.templateB.otherUnitStatus}),
                ...(CCO_139AData.templateB.timerStatus && { lubeType: CCO_139AData.templateB.timerStatus}),
                ...(CCO_139AData.templateB.electricStatus && { lubeType: CCO_139AData.templateB.electricStatus}),
                ...(CCO_139AData.templateB.mightyLubeMonitoring && { lubeType: CCO_139AData.templateB.mightyLubeMonitoring}),
                ...(CCO_139AData.templateB.preMountType && { lubeType: CCO_139AData.templateB.preMountType}),
                ...(CCO_139AData.templateB.otherPreMountType && { lubeType: CCO_139AData.templateB.otherPreMountType}),
                ...(CCO_139AData.templateB.plcConnection && { lubeType: CCO_139AData.templateB.plcConnection}),
                ...(CCO_139AData.templateB.otherControllerNotes && { lubeType: CCO_139AData.templateB.otherControllerNotes}),
                ...(CCO_139AData.templateB.templateB_UnitType && { lubeType: CCO_139AData_UnitType}),
                ...(CCO_139AData.templateB.templateB_InvertedB && { lubeType: CCO_139AData_InvertedB}),
                ...(CCO_139AData.templateB.templateB_InvertedE && { lubeType: CCO_139AData_InvertedE}),
                ...(CCO_139AData.templateB.templateB_InvertedG && { lubeType: CCO_139AData_InvertedG}),
                ...(CCO_139AData.templateB.templateB_InvertedH && { lubeType: CCO_139AData_InvertedH}),
                ...(CCO_139AData.templateB.templateB_InvertedK && { lubeType: CCO_139AData_InvertedK}),
                ...(CCO_139AData.templateB.templateB_InvertedT && { lubeType: CCO_139AData_InvertedT}),
                ...(CCO_139AData.templateB.templateB_InvertedU && { lubeType: CCO_139AData_InvertedU}),
                ...(CCO_139AData.templateB.templateB_InvertedV && { lubeType: CCO_139AData_InvertedV}),
                ...(CCO_139AData.templateB.templateB_InvertedW && { lubeType: CCO_139AData_InvertedW}),

            },

            templateCData: 
            {
                
            conveyorName: CCO_139AData.templateC.conveyorName,
            industrialChainManufacturer: CCO_139AData.templateC.industrialChainManufacturer,
            ...(CCO_139AData.templateC.otherChainManufacturer && { otherChainManufacturer: CCO_139AData.templateC.otherChainManufacturer }),
            wheelManufacturer: CCO_139AData.templateC.wheelManufacturer,
            ...(CCO_139AData.templateC.wheelManufacturer && { wheelManufacturer: CCO_139AData.templateC.wheelManufacturer}),
            conveyorSpeed: CCO_139AData.templateC.conveyorSpeed,
            conveyorSpeedUnit: CCO_139AData.templateC.conveyorSpeedUnit,
            conveyorIndex: CCO_139AData.templateC.conveyorIndex,
            ...(CCO_139AData.templateC.travelDirection && { travelDirection: CCO_139AData.templateC.travelDirection}),
            appEnviroment: CCO_139AData.templateC.appEnviroment,
            ...(CCO_139AData.templateC.otherAppEnviroment && { otherAppEnviroment: CCO_139AData.templateC.otherAppEnviroment}),
            surroundingTemp: CCO_139AData.templateC.surroundingTemp,
            orientationType: CCO_139AData.templateC.orientationType,
            guideWheelsEven: CCO_139AData.templateC.guideWheelsEven,
            operatingVoltage: CCO_139AData.templateC.operatingVoltage,
            controlVoltSingle: CCO_139AData.templateC.controlVoltSingle,
            compressedAir: CCO_139AData.templateC.compressedAir,
            ...(CCO_139AData.templateC.airSupplyType && { airSupplyType: CCO_139AData.templateC.airSupplyType}),

            templateA_CData: 
            {
                existingMonitor: CCO_139AData.templateA.existingMonitor,
                newMonitor: CCO_139AData.templateA.newMonitor,		
                ...(CCO_139AData.templateA.dcuStatus && { dcuStatus: CCO_139AData.templateA.dcuStatus }),
                ...(CCO_139AData.templateA.dcuNum && { dcuNum: CCO_139AData.templateA.dcuNum }),
                ...(CCO_139AData.templateA.existingWindows && { existingWindows: CCO_139AData.templateA.existingWindows }),
                ...(CCO_139AData.templateA.existingHeadUnit && { existingHeadUnit: CCO_139AData.templateA.existingHeadUnit }),
                ...(CCO_139AData.templateA.existingDCU && { existingDCU: CCO_139AData.templateA.existingDCU }),
                ...(CCO_139AData.templateA.existingPowerInterface && { existingPowerInterface: CCO_139AData.templateA.existingPowerInterface }),
                ...(CCO_139AData.templateA.newReservoir && { newReservoir: CCO_139AData.templateA.newReservoir }),
                ...(CCO_139AData.templateA.reservoirSize && { reservoirSize: CCO_139AData.templateA.reservoirSize }),
                ...(CCO_139AData.templateA.otherReservoirSize && { otherReservoirSize: CCO_139AData.templateA.otherReservoirSize }),
                ...(CCO_139AData.templateA.newReservoirNum && { newReservoirNum: CCO_139AData.templateA.newReservoirNum }),
                ...(CCO_139AData.templateA.typeMonitor && { typeMonitor: CCO_139AData.templateA.typeMonitor }),
                ...(CCO_139AData.templateA.driveMotorAmp && { driveMotorAmp: CCO_139AData.templateA.driveMotorAmp }),
                ...(CCO_139AData.templateA.driveMotorAmpNum && { driveMotorAmpNum: CCO_139AData.templateA.driveMotorAmpNum }),
                ...(CCO_139AData.templateA.driveTakeUpAir && { driveTakeUpAir: CCO_139AData.templateA.driveTakeUpAir }),
                ...(CCO_139AData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_139AData.templateA.driveTakeUpAirNum }),
                ...(CCO_139AData.templateA.takeUpDistance && { takeUpDistance: CCO_139AData.templateA.takeUpDistance }),
                ...(CCO_139AData.templateA.takeUpDistanceNum && { takeUpDistanceNum: CCO_139AData.templateA.takeUpDistanceNum }),
                ...(CCO_139AData.templateA.driveTemp && { driveTemp: CCO_139AData.templateA.driveTemp }),
                ...(CCO_139AData.templateA.driveTempNum && { driveTempNum: CCO_139AData.templateA.driveTempNum }),
                ...(CCO_139AData.templateA.driveVibration && { driveVibration: CCO_139AData.templateA.driveVibration }),
                ...(CCO_139AData.templateA.driveVibrationNum && { driveVibrationNum: CCO_139AData.templateA.driveVibrationNum }),
                ...(CCO_139AData.templateA.dogPitch && { dogPitch: CCO_139AData.templateA.dogPitch }),
                ...(CCO_139AData.templateA.dogPitchNum && { dogPitchNum: CCO_139AData.templateA.dogPitchNum }),
                ...(CCO_139AData.templateA.paintMarker && { paintMarker: CCO_139AData.templateA.paintMarker }),
                ...(CCO_139AData.templateA.paintMarkerNum && { paintMarkerNum: CCO_139AData.templateA.paintMarkerNum }),
                ...(CCO_139AData.templateA.chainVision && { chainVision: CCO_139AData.templateA.chainVision }),
                ...(CCO_139AData.templateA.lubeVision && { lubeVision: CCO_139AData.templateA.lubeVision }),
                ...(CCO_139AData.templateA.trolleyVision && { trolleyVision: CCO_139AData.templateA.trolleyVision }),
                ...(CCO_139AData.templateA.trolleyDetect && { trolleyDetect: CCO_139AData.templateA.trolleyDetect }),
                ...(CCO_139AData.templateA.omniView && { omniView: CCO_139AData.templateA.omniView }),
                ...(CCO_139AData.templateA.dcuUpgradeNum && { dcuUpgradeNum: CCO_139AData.templateA.dcuUpgradeNum }),
                ...(CCO_139AData.templateA.piuDistance && { piuDistance: CCO_139AData.templateA.piuDistance }),
                ...(CCO_139AData.templateA.switchDistance && { switchDistance: CCO_139AData.templateA.switchDistance }),
                ...(CCO_139AData.templateA.ampPickup && { ampPickup: CCO_139AData.templateA.ampPickup }),
                ...(CCO_139AData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_139AData.templateA.fromAirTakeUpDistance }),
                ...(CCO_139AData.templateA.specialControllerOptions && { specialControllerOptions: CCO_139AData.templateA.specialControllerOptions }),
                ...(CCO_139AData.templateA.operatingVoltage && { operatingVoltage: CCO_139AData.templateA.operatingVoltage })
            },
            
            freeWheelStatus: CCO_139AData.templateC.freeWheelStatus,
            actuatorStatus: CCO_139AData.templateC.actuatorStatus,
            ...(CCO_139AData.templateC.pivotStatus && { pivotStatus: CCO_139AData.templateC.pivotStatus}),
            kingPinStatus: CCO_139AData.templateC.kingPinStatus,
            lubeBrand: CCO_139AData.templateC.lubeBrand,
            lubeViscosity: CCO_139AData.templateC.lubeViscosity,
            ...(CCO_139AData.templateC.lubeType && { lubeType: CCO_139AData.templateC.lubeType}),
            currentGrease: CCO_139AData.templateC.currentGrease,
            currentGreaseGrade: CCO_139AData.templateC.currentGreaseGrade,
            zerkDirection: CCO_139AData.templateC.zerkDirection,
            zerkLocationType: CCO_139AData.templateC.zerkLocationType,
            wheelDiameter: CCO_139AData.templateC.wheelDiameter,
            conveyorSwing: CCO_139AData.templateC.conveyorSwing,
            ...(CCO_139AData.templateC.chainMaster && { lubeType: CCO_139AData.templateC.chainMaster}),
            ...(CCO_139AData.templateC.remoteStatus && { lubeType: CCO_139AData.templateC.remoteStatus}),
            ...(CCO_139AData.templateC.mountStatus && { lubeType: CCO_139AData.templateC.mountStatus}),
            ...(CCO_139AData.templateC.otherUnitStatus && { lubeType: CCO_139AData.templateC.otherUnitStatus}),
            ...(CCO_139AData.templateC.timerStatus && { lubeType: CCO_139AData.templateC.timerStatus}),
            ...(CCO_139AData.templateC.electricStatus && { lubeType: CCO_139AData.templateC.electricStatus}),
            ...(CCO_139AData.templateC.mightyLubeMonitoring && { lubeType: CCO_139AData.templateC.mightyLubeMonitoring}),
            ...(CCO_139AData.templateC.preMountType && { lubeType: CCO_139AData.templateC.preMountType}),
            ...(CCO_139AData.templateC.otherPreMountType && { lubeType: CCO_139AData.templateC.otherPreMountType}),
            ...(CCO_139AData.templateC.plcConnection && { lubeType: CCO_139AData.templateC.plcConnection}),
            ...(CCO_139AData.templateC.otherControllerNotes && { lubeType: CCO_139AData.templateC.otherControllerNotes}),
            ...(CCO_139AData.templateC.templateC_UnitType && { lubeType: CCO_139AData.templateC.templateC_UnitType}),
            templateC_InvertedA: CCO_139AData.templateC.templateC_InvertedA,
            templateC_InvertedB: CCO_139AData.templateC.templateC_InvertedB,
            templateC_InvertedE: CCO_139AData.templateC.templateC_InvertedE,
            templateC_InvertedS: CCO_139AData.templateC.templateC_InvertedS,
        },

            wheelsOnPowerChain: CCO_139AData.wheelsOnPowerChain,


            templateDData: 
            {
                conveyorName: CCO_139AData.templateD.conveyorName,
                wheelManufacturer: CCO_139AData.templateD.wheelManufacturer,
                ...(CCO_139AData.templateD.otherWheelManufacturer && { otherWheelManufacturer: CCO_139AData.templateD.otherWheelManufacturer }),
                conveyorLength: CCO_139AData.templateD.conveyorLength,
                conveyorLengthUnit: CCO_139AData.templateD.conveyorLengthUnit,
                chainSize: CCO_139AData.templateD.chainSize,
                ...(CCO_139AData.templateD.otherChainSize && { otherChainSize: CCO_139AData.templateD.otherChainSize }),
                industrialChainManufacturer: CCO_139AData.templateD.industrialChainManufacturer,
                ...(CCO_139AData.templateD.otherChainManufacturer && { otherChainManufacturer: CCO_139AData.templateD.otherChainManufacturer }),
                conveyorSpeed: CCO_139AData.templateD.conveyorSpeed,
                conveyorSpeedUnit: CCO_139AData.templateD.conveyorSpeedUnit,
                conveyorIndex: CCO_139AData.templateD.conveyorIndex,
                appEnviroment: CCO_139AData.templateD.appEnviroment,
                ...(CCO_139AData.templateD.otherAppEnviroment && { otherAppEnviroment: CCO_139AData.templateD.otherAppEnviroment }),
                surroundingTemp: CCO_139AData.templateD.surroundingTemp,
                orientationType: CCO_139AData.templateD.orientationType,
                ...(CCO_139AData.templateD.conveyorLoaded && { conveyorLoaded: CCO_139AData.templateD.conveyorLoaded }),
                conveyorSwing: CCO_139AData.templateD.conveyorSwing,
                operatingVoltage: CCO_139AData.templateD.operatingVoltage,
                controlVoltSingle: CCO_139AData.templateD.controlVoltSingle,
                compressedAir: CCO_139AData.templateD.compressedAir,
                ...(CCO_139AData.templateD.airSupplyType && { airSupplyType: CCO_139AData.templateD.airSupplyType }),

                templateA_DData: 
                {
                    existingMonitor: CCO_139AData.templateA.existingMonitor,
                    newMonitor: CCO_139AData.templateA.newMonitor,		
                    ...(CCO_139AData.templateA.dcuStatus && { dcuStatus: CCO_139AData.templateA.dcuStatus }),
                    ...(CCO_139AData.templateA.dcuNum && { dcuNum: CCO_139AData.templateA.dcuNum }),
                    ...(CCO_139AData.templateA.existingWindows && { existingWindows: CCO_139AData.templateA.existingWindows }),
                    ...(CCO_139AData.templateA.existingHeadUnit && { existingHeadUnit: CCO_139AData.templateA.existingHeadUnit }),
                    ...(CCO_139AData.templateA.existingDCU && { existingDCU: CCO_139AData.templateA.existingDCU }),
                    ...(CCO_139AData.templateA.existingPowerInterface && { existingPowerInterface: CCO_139AData.templateA.existingPowerInterface }),
                    ...(CCO_139AData.templateA.newReservoir && { newReservoir: CCO_139AData.templateA.newReservoir }),
                    ...(CCO_139AData.templateA.reservoirSize && { reservoirSize: CCO_139AData.templateA.reservoirSize }),
                    ...(CCO_139AData.templateA.otherReservoirSize && { otherReservoirSize: CCO_139AData.templateA.otherReservoirSize }),
                    ...(CCO_139AData.templateA.newReservoirNum && { newReservoirNum: CCO_139AData.templateA.newReservoirNum }),
                    ...(CCO_139AData.templateA.typeMonitor && { typeMonitor: CCO_139AData.templateA.typeMonitor }),
                    ...(CCO_139AData.templateA.driveMotorAmp && { driveMotorAmp: CCO_139AData.templateA.driveMotorAmp }),
                    ...(CCO_139AData.templateA.driveMotorAmpNum && { driveMotorAmpNum: CCO_139AData.templateA.driveMotorAmpNum }),
                    ...(CCO_139AData.templateA.driveTakeUpAir && { driveTakeUpAir: CCO_139AData.templateA.driveTakeUpAir }),
                    ...(CCO_139AData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_139AData.templateA.driveTakeUpAirNum }),
                    ...(CCO_139AData.templateA.takeUpDistance && { takeUpDistance: CCO_139AData.templateA.takeUpDistance }),
                    ...(CCO_139AData.templateA.takeUpDistanceNum && { takeUpDistanceNum: CCO_139AData.templateA.takeUpDistanceNum }),
                    ...(CCO_139AData.templateA.driveTemp && { driveTemp: CCO_139AData.templateA.driveTemp }),
                    ...(CCO_139AData.templateA.driveTempNum && { driveTempNum: CCO_139AData.templateA.driveTempNum }),
                    ...(CCO_139AData.templateA.driveVibration && { driveVibration: CCO_139AData.templateA.driveVibration }),
                    ...(CCO_139AData.templateA.driveVibrationNum && { driveVibrationNum: CCO_139AData.templateA.driveVibrationNum }),
                    ...(CCO_139AData.templateA.dogPitch && { dogPitch: CCO_139AData.templateA.dogPitch }),
                    ...(CCO_139AData.templateA.dogPitchNum && { dogPitchNum: CCO_139AData.templateA.dogPitchNum }),
                    ...(CCO_139AData.templateA.paintMarker && { paintMarker: CCO_139AData.templateA.paintMarker }),
                    ...(CCO_139AData.templateA.paintMarkerNum && { paintMarkerNum: CCO_139AData.templateA.paintMarkerNum }),
                    ...(CCO_139AData.templateA.chainVision && { chainVision: CCO_139AData.templateA.chainVision }),
                    ...(CCO_139AData.templateA.lubeVision && { lubeVision: CCO_139AData.templateA.lubeVision }),
                    ...(CCO_139AData.templateA.trolleyVision && { trolleyVision: CCO_139AData.templateA.trolleyVision }),
                    ...(CCO_139AData.templateA.trolleyDetect && { trolleyDetect: CCO_139AData.templateA.trolleyDetect }),
                    ...(CCO_139AData.templateA.omniView && { omniView: CCO_139AData.templateA.omniView }),
                    ...(CCO_139AData.templateA.dcuUpgradeNum && { dcuUpgradeNum: CCO_139AData.templateA.dcuUpgradeNum }),
                    ...(CCO_139AData.templateA.piuDistance && { piuDistance: CCO_139AData.templateA.piuDistance }),
                    ...(CCO_139AData.templateA.switchDistance && { switchDistance: CCO_139AData.templateA.switchDistance }),
                    ...(CCO_139AData.templateA.ampPickup && { ampPickup: CCO_139AData.templateA.ampPickup }),
                    ...(CCO_139AData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_139AData.templateA.fromAirTakeUpDistance }),
                    ...(CCO_139AData.templateA.specialControllerOptions && { specialControllerOptions: CCO_139AData.templateA.specialControllerOptions }),
                    ...(CCO_139AData.templateA.operatingVoltage && { operatingVoltage: CCO_139AData.templateA.operatingVoltage })
                },

                    lubeBrand: CCO_139AData.templateD.lubeBrand,
                    currentGrease: CCO_139AData.templateD.currentGrease,
                    currentGreaseGrade: CCO_139AData.templateD.currentGreaseGrade,
                    wheelDiameter: CCO_139AData.templateD.wheelDiameter,
                    ...(CCO_139AData.templateD.chainMaster && { chainMaster: CCO_139AData.templateD.chainMaster }),
                    ...(CCO_139AData.templateD.remoteStatus && { remoteStatus: CCO_139AData.templateD.remoteStatus }),
                    ...(CCO_139AData.templateD.mountStatus && { mountStatus: CCO_139AData.templateD.mountStatus }),
                    ...(CCO_139AData.templateD.otherUnitStatus && { otherUnitStatus: CCO_139AData.templateD.otherUnitStatus }),
                    ...(CCO_139AData.templateD.timerStatus && { timerStatus: CCO_139AData.templateD.timerStatus }),
                    ...(CCO_139AData.templateD.electricStatus && { electricStatus: CCO_139AData.templateD.electricStatus }),
                    ...(CCO_139AData.templateD.mightyLubeMonitoring && { mightyLubeMonitoring: CCO_139AData.templateD.mightyLubeMonitoring }),
                    ...(CCO_139AData.templateD.preMountType && { preMountType: CCO_139AData.templateD.preMountType }),
                    ...(CCO_139AData.templateD.otherControllerNotes && { otherControllerNotes: CCO_139AData.templateD.otherControllerNotes }),


            },


            templateFData: 
            {
                conveyorName: CCO_139AData.templateF.conveyorName,
                chainSize: CCO_139AData.templateF.chainSize,
                ...(CCO_139AData.templateF.otherChainSize && { otherChainSize: CCO_139AData.templateF.otherChainSize }),
                industrialChainManufacturer: CCO_139AData.templateF.industrialChainManufacturer,
                ...(CCO_139AData.templateF.otherChainManufacturer && { otherChainManufacturer: CCO_139AData.templateF.otherChainManufacturer }),
                wheelManufacturer: CCO_139AData.templateF.wheelManufacturer,
                ...(CCO_139AData.templateF.otherWheelManufacturer && { otherWheelManufacturer: CCO_139AData.templateF.otherWheelManufacturer }),
                conveyorLength: CCO_139AData.templateF.conveyorLength,
                conveyorLengthUnit: CCO_139AData.templateF.conveyorLengthUnit,
                brushApplicators: CCO_139AData.templateF.brushApplicators,
                m12Plugs: CCO_139AData.templateF.m12Plugs,
                oilStatus: CCO_139AData.templateF.oilStatus,
                operatingVoltage: CCO_139AData.templateF.operatingVoltage,
                controlVoltSingle: CCO_139AData.templateF.controlVoltSingle,
            },

            ...(CCO_139AData.railLubeStatus && { railLubeStatus: CCO_139AData.railLubeStatus }),
            ...(CCO_139AData.lubeBrand && { lubeBrand: CCO_139AData.lubeBrand }),
            ...(CCO_139AData.lubeType && { lubeType: CCO_139AData.lubeType }),
            ...(CCO_139AData.lubeViscosity && { lubeViscosity: CCO_139AData.lubeViscosity }),
            ...(CCO_139AData.sideLubeStatus && { sideLubeStatus: CCO_139AData.sideLubeStatus }),
            ...(CCO_139AData.topLubeStatus && { topLubeStatus: CCO_139AData.topLubeStatus }),
            ...(CCO_139AData.chainCleanStatus && { chainCleanStatus: CCO_139AData.chainCleanStatus }),
            ...(CCO_139AData.chainMaster && { chainMaster: CCO_139AData.chainMaster }),
            ...(CCO_139AData.otherUnitStatus && { otherUnitStatus: CCO_139AData.otherUnitStatus }),
            ...(CCO_139AData.timerStatus && { timerStatus: CCO_139AData.timerStatus }),
                electricStatus: CCO_139AData.electricStatus,
            ...(CCO_139AData.pneumaticStatus && { pneumaticStatus: CCO_139AData.pneumaticStatus }),
            ...(CCO_139AData.mightyLubeMonitoring && { mightyLubeMonitoring: CCO_139AData.mightyLubeMonitoring }),
            ...(CCO_139AData.plcConnection && { plcConnection: CCO_139AData.plcConnection }),
            ...(CCO_139AData.otherControllerNotes && { otherControllerNotes: CCO_139AData.otherControllerNotes }),
            ...(CCO_139AData.ohpUnitType && { ohpUnitType: CCO_139AData.ohpUnitType }),
            ...(CCO_139AData.ccoG && { ccoG: CCO_139AData.ccoG }),
            ...(CCO_139AData.ccoH && { ccoH: CCO_139AData.ccoH }),
            ...(CCO_139AData.ccoK && { ccoK: CCO_139AData.ccoK }),
            ...(CCO_139AData.ccoA && { ccoA: CCO_139AData.ccoA }),
            ...(CCO_139AData.ccoB && { ccoB: CCO_139AData.ccoB }),
            ...(CCO_139AData.ccoIG && { ccoIG: CCO_139AData.ccoIG }),
            ...(CCO_139AData.ccoIH && { ccoIH: CCO_139AData.ccoIH }),
            ...(CCO_139AData.ccoIK && { ccoIK: CCO_139AData.ccoIK }),
            ...(CCO_139AData.ccoL && { ccoL: CCO_139AData.ccoL }),
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "CCO_139A"
        });
        await req.user.save();
        return res.status(200).json({ message: "CCO_139A entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;