const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const CCO_ES = require("../models/CCO_ES");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");
const templateD = require("../models/templateD.js");
const templateF = require("../models/templateF.js");

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { CCO_ESData, numRequested } = req.body;
        const order = new CCO_ES({
            conveyorName: CCO_ESData.conveyorName,
            chainSize: CCO_ESData.chainSize,
            ...(CCO_ESData.otherChainSize && { otherChainSize: CCO_ESData.otherChainSize }),
            industrialChainManufacturer: CCO_ESData.industrialChainManufacturer,
            ...(CCO_ESData.otherChainManufacturer && { otherChainManufacturer: CCO_ESData.otherChainManufacturer }),
            wheelManufacturer: CCO_ESData.wheelManufacturer,
            ...(CCO_ESData.otherWheelManufacturer && { otherWheelManufacturer: CCO_ESData.otherWheelManufacturer }),
            conveyorLength: CCO_ESData.conveyorLength,
            conveyorLengthUnit: CCO_ESData.conveyorLengthUnit,
            conveyorSpeed: CCO_ESData.conveyorSpeed,
            conveyorSpeedUnit: CCO_ESData.conveyorSpeedUnit,
            conveyorIndex: CCO_ESData.conveyorIndex,
            ...(CCO_ESData.travelDirection && { travelDirection: CCO_ESData.travelDirection }),
            appEnviroment: CCO_ESData.appEnviroment,
            ...(CCO_ESData.ovenStatus && { ovenStatus: CCO_ESData.ovenStatus }),
            ...(CCO_ESData.ovenTemp && { ovenTemp: CCO_ESData.ovenTemp }),
            ...(CCO_ESData.otherAppEnviroment && { otherAppEnviroment: CCO_ESData.otherAppEnviroment }),
            ...(CCO_ESData.conveyorLoaded && { conveyorLoaded: CCO_ESData.conveyorLoaded }),
            ...(CCO_ESData.conveyorSwing && { conveyorSwing: CCO_ESData.conveyorSwing }),
            strandStatus: CCO_ESData.strandStatus,
            openBearings: CCO_ESData.openBearings,
            lubeStatus: CCO_ESData.lubeStatus,
            pointsOfLube: CCO_ESData.pointsOfLube,
            m12Plugs: CCO_ESData.m12Plugs,
            op201Controller: CCO_ESData.op201Controller,
            op201Order: CCO_ESData.op201Order,
            operatingVoltSingle: CCO_ESData.operatingVoltSingle,
            controlVoltSingle: CCO_ESData.controlVoltSingle,
            existingMonitor: CCO_ESData.existingMonitor,
            newMonitor: CCO_ESData.newMonitor,
            monitorData: {
                ...(CCO_ESData.dcuStatus && { dcuStatus: CCO_ESData.dcuStatus }),
                ...(CCO_ESData.dcuNum && { dcuNum: CCO_ESData.dcuNum }),
                ...(CCO_ESData.existingWindows && { existingWindows: CCO_ESData.existingWindows }),
                ...(CCO_ESData.existingHeadUnit && { existingHeadUnit: CCO_ESData.existingHeadUnit }),
                ...(CCO_ESData.existingDCU && { existingDCU: CCO_ESData.existingDCU }),
                ...(CCO_ESData.existingPowerInterface && { existingPowerInterface: CCO_ESData.existingPowerInterface }),
                ...(CCO_ESData.newReservoir && { newReservoir: CCO_ESData.newReservoir }),
                ...(CCO_ESData.reservoirSize && { reservoirSize: CCO_ESData.reservoirSize }),
                ...(CCO_ESData.otherReservoirSize && { otherReservoirSize: CCO_ESData.otherReservoirSize }),
                ...(CCO_ESData.newReservoirNum && { newReservoirNum: CCO_ESData.newReservoirNum }),
                ...(CCO_ESData.typeMonitor && { typeMonitor: CCO_ESData.typeMonitor }),
                ...(CCO_ESData.driveMotorAmp && { driveMotorAmp: CCO_ESData.driveMotorAmp }),
                ...(CCO_ESData.driveMotorAmpNum && { driveMotorAmpNum: CCO_ESData.driveMotorAmpNum }),
                ...(CCO_ESData.driveTakeUpAir && { driveTakeUpAir: CCO_ESData.driveTakeUpAir }),
                ...(CCO_ESData.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_ESData.driveTakeUpAirNum }),
                ...(CCO_ESData.takeUpDistance && { takeUpDistance: CCO_ESData.takeUpDistance }),
                ...(CCO_ESData.takeUpDistanceNum && { takeUpDistanceNum: CCO_ESData.takeUpDistanceNum }),
                ...(CCO_ESData.driveTemp && { driveTemp: CCO_ESData.driveTemp }),
                ...(CCO_ESData.driveTempNum && { driveTempNum: CCO_ESData.driveTempNum }),
                ...(CCO_ESData.driveVibration && { driveVibration: CCO_ESData.driveVibration }),
                ...(CCO_ESData.driveVibrationNum && { driveVibrationNum: CCO_ESData.driveVibrationNum }),
                ...(CCO_ESData.dogPitch && { dogPitch: CCO_ESData.dogPitch }), 
                ...(CCO_ESData.dogPitchNum && { dogPitchNum: CCO_ESData.dogPitchNum }),
                ...(CCO_ESData.paintMarker && { paintMarker: CCO_ESData.paintMarker }),
                ...(CCO_ESData.paintMarkerNum && { paintMarkerNum: CCO_ESData.paintMarkerNum }),
                ...(CCO_ESData.chainVision && { chainVision: CCO_ESData.chainVision }),
                ...(CCO_ESData.lubeVision && { lubeVision: CCO_ESData.lubeVision }),
                ...(CCO_ESData.trolleyVision && { trolleyVision: CCO_ESData.trolleyVision }),
                ...(CCO_ESData.trolleyDetect && { trolleyDetect: CCO_ESData.trolleyDetect }),
                ...(CCO_ESData.omniView && { omniView: CCO_ESData.omniView }),
                ...(CCO_ESData.dcuUpgradeNum && { dcuUpgradeNum: CCO_ESData.dcuUpgradeNum }),
                ...(CCO_ESData.itNameOne && { itNameOne: CCO_ESData.itNameOne }),
                ...(CCO_ESData.itIPOne && { itIPOne: CCO_ESData.itIPOne }),
                ...(CCO_ESData.itGatewayOne && { itGatewayOne: CCO_ESData.itGatewayOne }),
                ...(CCO_ESData.itSubnetOne && { itSubnetOne: CCO_ESData.itSubnetOne }),
                ...(CCO_ESData.itDNSOne && { itDNSOne: CCO_ESData.itDNSOne }),
                ...(CCO_ESData.itSMTPOne && { itSMTPOne: CCO_ESData.itSMTPOne }),
                ...(CCO_ESData.itNameTwo && { itNameTwo: CCO_ESData.itNameTwo }),
                ...(CCO_ESData.itIPTwo && { itIPTwo: CCO_ESData.itIPTwo }),
                ...(CCO_ESData.itGatewayTwo && { itGatewayTwo: CCO_ESData.itGatewayTwo }),
                ...(CCO_ESData.itSubnetTwo && { itSubnetTwo: CCO_ESData.itSubnetTwo }),
                ...(CCO_ESData.itDNSTwo && { itDNSTwo: CCO_ESData.itDNSTwo }),
                ...(CCO_ESData.itSMTPTwo && { itSMTPTwo: CCO_ESData.itSMTPTwo }),
                ...(CCO_ESData.itNameThree && { itNameThree: CCO_ESData.itNameThree }),
                ...(CCO_ESData.itIPThree && { itIPThree: CCO_ESData.itIPThree }),
                ...(CCO_ESData.itGatewayThree && { itGatewayThree: CCO_ESData.itGatewayThree }),
                ...(CCO_ESData.itSubnetThree && { itSubnetThree: CCO_ESData.itSubnetThree }),
                ...(CCO_ESData.itDNSThree && { itDNSThree: CCO_ESData.itDNSThree }),
                ...(CCO_ESData.itSMTPThree && { itSMTPThree: CCO_ESData.itSMTPThree }),
                ...(CCO_ESData.itAdditionalNotes && { itAdditionalNotes: CCO_ESData.itAdditionalNotes }),
                ...(CCO_ESData.piuDistance && { piuDistance: CCO_ESData.piuDistance }),
                ...(CCO_ESData.switchDistance && { switchDistance: CCO_ESData.switchDistance }),
                ...(CCO_ESData.ampPickup && { ampPickup: CCO_ESData.ampPickup }),
                ...(CCO_ESData.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_ESData.fromAirTakeUpDistance }),
                ...(CCO_ESData.specialControllerOptions && { specialControllerOptions: CCO_ESData.specialControllerOptions })
            },

            addFreeCarrier: CCO_ESData.addFreeCarrier,

            templateBData: {
                conveyorName: CCO_ESData.conveyorName,
                industrialChainManufacturer: CCO_ESData.industrialChainManufacturer,
                ...(CCO_ESData.otherChainManufacturer && { otherChainManufacturer: CCO_ESData.otherChainManufacturer }),
                wheelManufacturer: CCO_ESData.wheelManufacturer,
                ...(CCO_ESData.wheelManufacturer && { wheelManufacturer: CCO_ESData.wheelManufacturer}),
                conveyorSpeed: CCO_ESData.conveyorSpeed,
                conveyorSpeedUnit: CCO_ESData.conveyorSpeedUnit,
                conveyorIndex: CCO_ESData.conveyorIndex,
                ...(CCO_ESData.travelDirection && { travelDirection: CCO_ESData.travelDirection}),
                appEnviroment: CCO_ESData.appEnviroment,
                ...(CCO_ESData.otherAppEnviroment && { otherAppEnviroment: CCO_ESData.otherAppEnviroment}),
                surroundingTemp: CCO_ESData.surroundingTemp,
                orientationType: CCO_ESData.orientationType,
                operatingVoltage: CCO_ESData.operatingVoltage,
                controlVoltSingle: CCO_ESData.controlVoltSingle,
                compressedAir: CCO_ESData.compressedAir,
                ...(CCO_ESData.airSupplyType && { airSupplyType: CCO_ESData.airSupplyType}),
            existingMonitor: CCO_ESData.existingMonitor,
            newMonitor: CCO_ESData.newMonitor,
            templateA_BData: new templateA({
                ...(CCO_ESData.dcuStatus && { dcuStatus: CCO_ESData.dcuStatus }),
                ...(CCO_ESData.dcuNum && { dcuNum: CCO_ESData.dcuNum }),
                ...(CCO_ESData.existingWindows && { existingWindows: CCO_ESData.existingWindows }),
                ...(CCO_ESData.existingHeadUnit && { existingHeadUnit: CCO_ESData.existingHeadUnit }),
                ...(CCO_ESData.existingDCU && { existingDCU: CCO_ESData.existingDCU }),
                ...(CCO_ESData.existingPowerInterface && { existingPowerInterface: CCO_ESData.existingPowerInterface }),
                ...(CCO_ESData.newReservoir && { newReservoir: CCO_ESData.newReservoir }),
                ...(CCO_ESData.reservoirSize && { reservoirSize: CCO_ESData.reservoirSize }),
                ...(CCO_ESData.otherReservoirSize && { otherReservoirSize: CCO_ESData.otherReservoirSize }),
                ...(CCO_ESData.newReservoirNum && { newReservoirNum: CCO_ESData.newReservoirNum }),
                ...(CCO_ESData.typeMonitor && { typeMonitor: CCO_ESData.typeMonitor }),
                ...(CCO_ESData.driveMotorAmp && { driveMotorAmp: CCO_ESData.driveMotorAmp }),
                ...(CCO_ESData.driveMotorAmpNum && { driveMotorAmpNum: CCO_ESData.driveMotorAmpNum }),
                ...(CCO_ESData.driveTakeUpAir && { driveTakeUpAir: CCO_ESData.driveTakeUpAir }),
                ...(CCO_ESData.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_ESData.driveTakeUpAirNum }),
                ...(CCO_ESData.takeUpDistance && { takeUpDistance: CCO_ESData.takeUpDistance }),
                ...(CCO_ESData.takeUpDistanceNum && { takeUpDistanceNum: CCO_ESData.takeUpDistanceNum }),
                ...(CCO_ESData.driveTemp && { driveTemp: CCO_ESData.driveTemp }),
                ...(CCO_ESData.driveTempNum && { driveTempNum: CCO_ESData.driveTempNum }),
                ...(CCO_ESData.driveVibration && { driveVibration: CCO_ESData.driveVibration }),
                ...(CCO_ESData.driveVibrationNum && { driveVibrationNum: CCO_ESData.driveVibrationNum }),
                ...(CCO_ESData.dogPitch && { dogPitch: CCO_ESData.dogPitch }),
                ...(CCO_ESData.dogPitchNum && { dogPitchNum: CCO_ESData.dogPitchNum }),
                ...(CCO_ESData.paintMarker && { paintMarker: CCO_ESData.paintMarker }),
                ...(CCO_ESData.paintMarkerNum && { paintMarkerNum: CCO_ESData.paintMarkerNum }),
                ...(CCO_ESData.chainVision && { chainVision: CCO_ESData.chainVision }),
                ...(CCO_ESData.lubeVision && { lubeVision: CCO_ESData.lubeVision }),
                ...(CCO_ESData.trolleyVision && { trolleyVision: CCO_ESData.trolleyVision }),
                ...(CCO_ESData.trolleyDetect && { trolleyDetect: CCO_ESData.trolleyDetect }),
                ...(CCO_ESData.omniView && { omniView: CCO_ESData.omniView }),
                ...(CCO_ESData.dcuUpgradeNum && { dcuUpgradeNum: CCO_ESData.dcuUpgradeNum }),
                ...(CCO_ESData.itNameOne && { itNameOne: CCO_ESData.itNameOne }),
                ...(CCO_ESData.itIPOne && { itIPOne: CCO_ESData.itIPOne }),
                ...(CCO_ESData.itGatewayOne && { itGatewayOne: CCO_ESData.itGatewayOne }),
                ...(CCO_ESData.itSubnetOne && { itSubnetOne: CCO_ESData.itSubnetOne }),
                ...(CCO_ESData.itDNSOne && { itDNSOne: CCO_ESData.itDNSOne }),
                ...(CCO_ESData.itSMTPOne && { itSMTPOne: CCO_ESData.itSMTPOne }),
                ...(CCO_ESData.itNameTwo && { itNameTwo: CCO_ESData.itNameTwo }),
                ...(CCO_ESData.itIPTwo && { itIPTwo: CCO_ESData.itIPTwo }),
                ...(CCO_ESData.itGatewayTwo && { itGatewayTwo: CCO_ESData.itGatewayTwo }),
                ...(CCO_ESData.itSubnetTwo && { itSubnetTwo: CCO_ESData.itSubnetTwo }),
                ...(CCO_ESData.itDNSTwo && { itDNSTwo: CCO_ESData.itDNSTwo }),
                ...(CCO_ESData.itSMTPTwo && { itSMTPTwo: CCO_ESData.itSMTPTwo }),
                ...(CCO_ESData.itNameThree && { itNameThree: CCO_ESData.itNameThree }),
                ...(CCO_ESData.itIPThree && { itIPThree: CCO_ESData.itIPThree }),
                ...(CCO_ESData.itGatewayThree && { itGatewayThree: CCO_ESData.itGatewayThree }),
                ...(CCO_ESData.itSubnetThree && { itSubnetThree: CCO_ESData.itSubnetThree }),
                ...(CCO_ESData.itDNSThree && { itDNSThree: CCO_ESData.itDNSThree }),
                ...(CCO_ESData.itSMTPThree && { itSMTPThree: CCO_ESData.itSMTPThree }),
                ...(CCO_ESData.itAdditionalNotes && { itAdditionalNotes: CCO_ESData.itAdditionalNotes }),
                ...(CCO_ESData.piuDistance && { piuDistance: CCO_ESData.piuDistance }),
                ...(CCO_ESData.switchDistance && { switchDistance: CCO_ESData.switchDistance }),
                ...(CCO_ESData.ampPickup && { ampPickup: CCO_ESData.ampPickup }),
                ...(CCO_ESData.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_ESData.fromAirTakeUpDistance }),
                ...(CCO_ESData.specialControllerOptions && { specialControllerOptions: CCO_ESData.specialControllerOptions }),
                ...(CCO_ESData.operatingVoltage && { operatingVoltage: CCO_ESData.operatingVoltage })

                }),


                freeWheelStatus: CCO_ESData.freeWheelStatus,
                actuatorStatus: CCO_ESData.actuatorStatus,
                ...(CCO_ESData.pivotStatus && { pivotStatus: CCO_ESData.pivotStatus}),
                kingPinStatus: CCO_ESData.kingPinStatus,
                lubeBrand: CCO_ESData.lubeBrand,
                lubeViscosity: CCO_ESData.lubeViscosity,
                ...(CCO_ESData.lubeType && { lubeType: CCO_ESData.lubeType}),
                currentGrease: CCO_ESData.currentGrease,
                currentGreaseGrade: CCO_ESData.currentGreaseGrade,
                zerkDirection: CCO_ESData.zerkDirection,
                zerkLocationType: CCO_ESData.zerkLocationType,
                wheelDiameter: CCO_ESData.wheelDiameter,
                conveyorSwing: CCO_ESData.conveyorSwing,
                ...(CCO_ESData.chainMaster && { lubeType: CCO_ESData.chainMaster}),
                ...(CCO_ESData.remoteStatus && { lubeType: CCO_ESData.remoteStatus}),
                ...(CCO_ESData.mountStatus && { lubeType: CCO_ESData.mountStatus}),
                ...(CCO_ESData.otherUnitStatus && { lubeType: CCO_ESData.otherUnitStatus}),
                ...(CCO_ESData.timerStatus && { lubeType: CCO_ESData.timerStatus}),
                ...(CCO_ESData.electricStatus && { lubeType: CCO_ESData.electricStatus}),
                ...(CCO_ESData.mightyLubeMonitoring && { lubeType: CCO_ESData.mightyLubeMonitoring}),
                ...(CCO_ESData.preMountType && { lubeType: CCO_ESData.preMountType}),
                ...(CCO_ESData.otherPreMountType && { lubeType: CCO_ESData.otherPreMountType}),
                ...(CCO_ESData.plcConnection && { lubeType: CCO_ESData.plcConnection}),
                ...(CCO_ESData.otherControllerNotes && { lubeType: CCO_ESData.otherControllerNotes}),
                ...(CCO_ESData.templateB_UnitType && { lubeType: CCO_ESData.templateB_UnitType}),
                ...(CCO_ESData.templateB_InvertedB && { lubeType: CCO_ESData.templateB_InvertedB}),
                ...(CCO_ESData.templateB_InvertedE && { lubeType: CCO_ESData.templateB_InvertedE}),
                ...(CCO_ESData.templateB_InvertedG && { lubeType: CCO_ESData.templateB_InvertedG}),
                ...(CCO_ESData.templateB_InvertedH && { lubeType: CCO_ESData.templateB_InvertedH}),
                ...(CCO_ESData.templateB_InvertedK && { lubeType: CCO_ESData.templateB_InvertedK}),
                ...(CCO_ESData.templateB_InvertedT && { lubeType: CCO_ESData.templateB_InvertedT}),
                ...(CCO_ESData.templateB_InvertedU && { lubeType: CCO_ESData.templateB_InvertedU}),
                ...(CCO_ESData.templateB_InvertedV && { lubeType: CCO_ESData.templateB_InvertedV}),
                ...(CCO_ESData.templateB_InvertedW && { lubeType: CCO_ESData.templateB_InvertedW}),

            },



            templateCData: {
                conveyorName: CCO_ESData.conveyorName,
                industrialChainManufacturer: CCO_ESData.industrialChainManufacturer,
                ...(CCO_ESData.otherChainManufacturer && { otherChainManufacturer: CCO_ESData.otherChainManufacturer }),
                wheelManufacturer: CCO_ESData.wheelManufacturer,
                ...(CCO_ESData.wheelManufacturer && { wheelManufacturer: CCO_ESData.wheelManufacturer}),
                conveyorSpeed: CCO_ESData.conveyorSpeed,
                conveyorSpeedUnit: CCO_ESData.conveyorSpeedUnit,
                conveyorIndex: CCO_ESData.conveyorIndex,
                ...(CCO_ESData.travelDirection && { travelDirection: CCO_ESData.travelDirection}),
                appEnviroment: CCO_ESData.appEnviroment,
                ...(CCO_ESData.otherAppEnviroment && { otherAppEnviroment: CCO_ESData.otherAppEnviroment}),
                surroundingTemp: CCO_ESData.surroundingTemp,
                orientationType: CCO_ESData.orientationType,
                guideWheelsEven: CCO_ESData.guideWheelsEven,
                operatingVoltage: CCO_ESData.operatingVoltage,
                controlVoltSingle: CCO_ESData.controlVoltSingle,
                compressedAir: CCO_ESData.compressedAir,
                ...(CCO_ESData.airSupplyType && { airSupplyType: CCO_ESData.airSupplyType}),
                existingMonitor: CCO_ESData.existingMonitor,
                newMonitor: CCO_ESData.newMonitor,
                templateA_CData: new templateA({
                ...(CCO_ESData.dcuStatus && { dcuStatus: CCO_ESData.dcuStatus }),
                ...(CCO_ESData.dcuNum && { dcuNum: CCO_ESData.dcuNum }),
                ...(CCO_ESData.existingWindows && { existingWindows: CCO_ESData.existingWindows }),
                ...(CCO_ESData.existingHeadUnit && { existingHeadUnit: CCO_ESData.existingHeadUnit }),
                ...(CCO_ESData.existingDCU && { existingDCU: CCO_ESData.existingDCU }),
                ...(CCO_ESData.existingPowerInterface && { existingPowerInterface: CCO_ESData.existingPowerInterface }),
                ...(CCO_ESData.newReservoir && { newReservoir: CCO_ESData.newReservoir }),
                ...(CCO_ESData.reservoirSize && { reservoirSize: CCO_ESData.reservoirSize }),
                ...(CCO_ESData.otherReservoirSize && { otherReservoirSize: CCO_ESData.otherReservoirSize }),
                ...(CCO_ESData.newReservoirNum && { newReservoirNum: CCO_ESData.newReservoirNum }),
                ...(CCO_ESData.typeMonitor && { typeMonitor: CCO_ESData.typeMonitor }),
                ...(CCO_ESData.driveMotorAmp && { driveMotorAmp: CCO_ESData.driveMotorAmp }),
                ...(CCO_ESData.driveMotorAmpNum && { driveMotorAmpNum: CCO_ESData.driveMotorAmpNum }),
                ...(CCO_ESData.driveTakeUpAir && { driveTakeUpAir: CCO_ESData.driveTakeUpAir }),
                ...(CCO_ESData.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_ESData.driveTakeUpAirNum }),
                ...(CCO_ESData.takeUpDistance && { takeUpDistance: CCO_ESData.takeUpDistance }),
                ...(CCO_ESData.takeUpDistanceNum && { takeUpDistanceNum: CCO_ESData.takeUpDistanceNum }),
                ...(CCO_ESData.driveTemp && { driveTemp: CCO_ESData.driveTemp }),
                ...(CCO_ESData.driveTempNum && { driveTempNum: CCO_ESData.driveTempNum }),
                ...(CCO_ESData.driveVibration && { driveVibration: CCO_ESData.driveVibration }),
                ...(CCO_ESData.driveVibrationNum && { driveVibrationNum: CCO_ESData.driveVibrationNum }),
                ...(CCO_ESData.dogPitch && { dogPitch: CCO_ESData.dogPitch }),
                ...(CCO_ESData.dogPitchNum && { dogPitchNum: CCO_ESData.dogPitchNum }),
                ...(CCO_ESData.paintMarker && { paintMarker: CCO_ESData.paintMarker }),
                ...(CCO_ESData.paintMarkerNum && { paintMarkerNum: CCO_ESData.paintMarkerNum }),
                ...(CCO_ESData.chainVision && { chainVision: CCO_ESData.chainVision }),
                ...(CCO_ESData.lubeVision && { lubeVision: CCO_ESData.lubeVision }),
                ...(CCO_ESData.trolleyVision && { trolleyVision: CCO_ESData.trolleyVision }),
                ...(CCO_ESData.trolleyDetect && { trolleyDetect: CCO_ESData.trolleyDetect }),
                ...(CCO_ESData.omniView && { omniView: CCO_ESData.omniView }),
                ...(CCO_ESData.dcuUpgradeNum && { dcuUpgradeNum: CCO_ESData.dcuUpgradeNum }),
                ...(CCO_ESData.itNameOne && { itNameOne: CCO_ESData.itNameOne }),
                ...(CCO_ESData.itIPOne && { itIPOne: CCO_ESData.itIPOne }),
                ...(CCO_ESData.itGatewayOne && { itGatewayOne: CCO_ESData.itGatewayOne }),
                ...(CCO_ESData.itSubnetOne && { itSubnetOne: CCO_ESData.itSubnetOne }),
                ...(CCO_ESData.itDNSOne && { itDNSOne: CCO_ESData.itDNSOne }),
                ...(CCO_ESData.itSMTPOne && { itSMTPOne: CCO_ESData.itSMTPOne }),
                ...(CCO_ESData.itNameTwo && { itNameTwo: CCO_ESData.itNameTwo }),
                ...(CCO_ESData.itIPTwo && { itIPTwo: CCO_ESData.itIPTwo }),
                ...(CCO_ESData.itGatewayTwo && { itGatewayTwo: CCO_ESData.itGatewayTwo }),
                ...(CCO_ESData.itSubnetTwo && { itSubnetTwo: CCO_ESData.itSubnetTwo }),
                ...(CCO_ESData.itDNSTwo && { itDNSTwo: CCO_ESData.itDNSTwo }),
                ...(CCO_ESData.itSMTPTwo && { itSMTPTwo: CCO_ESData.itSMTPTwo }),
                ...(CCO_ESData.itNameThree && { itNameThree: CCO_ESData.itNameThree }),
                ...(CCO_ESData.itIPThree && { itIPThree: CCO_ESData.itIPThree }),
                ...(CCO_ESData.itGatewayThree && { itGatewayThree: CCO_ESData.itGatewayThree }),
                ...(CCO_ESData.itSubnetThree && { itSubnetThree: CCO_ESData.itSubnetThree }),
                ...(CCO_ESData.itDNSThree && { itDNSThree: CCO_ESData.itDNSThree }),
                ...(CCO_ESData.itSMTPThree && { itSMTPThree: CCO_ESData.itSMTPThree }),
                ...(CCO_ESData.itAdditionalNotes && { itAdditionalNotes: CCO_ESData.itAdditionalNotes }),
                ...(CCO_ESData.piuDistance && { piuDistance: CCO_ESData.piuDistance }),
                ...(CCO_ESData.switchDistance && { switchDistance: CCO_ESData.switchDistance }),
                ...(CCO_ESData.ampPickup && { ampPickup: CCO_ESData.ampPickup }),
                ...(CCO_ESData.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_ESData.fromAirTakeUpDistance }),
                ...(CCO_ESData.specialControllerOptions && { specialControllerOptions: CCO_ESData.specialControllerOptions }),
                ...(CCO_ESData.operatingVoltage && { operatingVoltage: CCO_ESData.operatingVoltage })

                }),
                freeWheelStatus: CCO_ESData.freeWheelStatus,
                actuatorStatus: CCO_ESData.actuatorStatus,
                ...(CCO_ESData.pivotStatus && { pivotStatus: CCO_ESData.pivotStatus}),
                kingPinStatus: CCO_ESData.kingPinStatus,
                lubeBrand: CCO_ESData.lubeBrand,
                lubeViscosity: CCO_ESData.lubeViscosity,
                ...(CCO_ESData.lubeType && { lubeType: CCO_ESData.lubeType}),
                currentGrease: CCO_ESData.currentGrease,
                currentGreaseGrade: CCO_ESData.currentGreaseGrade,
                zerkDirection: CCO_ESData.zerkDirection,
                zerkLocationType: CCO_ESData.zerkLocationType,
                wheelDiameter: CCO_ESData.wheelDiameter,
                conveyorSwing: CCO_ESData.conveyorSwing,
                ...(CCO_ESData.chainMaster && { lubeType: CCO_ESData.chainMaster}),
                ...(CCO_ESData.remoteStatus && { lubeType: CCO_ESData.remoteStatus}),
                ...(CCO_ESData.mountStatus && { lubeType: CCO_ESData.mountStatus}),
                ...(CCO_ESData.otherUnitStatus && { lubeType: CCO_ESData.otherUnitStatus}),
                ...(CCO_ESData.timerStatus && { lubeType: CCO_ESData.timerStatus}),
                ...(CCO_ESData.electricStatus && { lubeType: CCO_ESData.electricStatus}),
                ...(CCO_ESData.mightyLubeMonitoring && { lubeType: CCO_ESData.mightyLubeMonitoring}),
                ...(CCO_ESData.preMountType && { lubeType: CCO_ESData.preMountType}),
                ...(CCO_ESData.otherPreMountType && { lubeType: CCO_ESData.otherPreMountType}),
                ...(CCO_ESData.plcConnection && { lubeType: CCO_ESData.plcConnection}),
                ...(CCO_ESData.otherControllerNotes && { lubeType: CCO_ESData.otherControllerNotes}),
                ...(CCO_ESData.templateC_UnitType && { lubeType: CCO_ESData.templateC_UnitType}),
                templateC_InvertedA: CCO_ESData.templateC_InvertedA,
                templateC_InvertedB: CCO_ESData.templateC_InvertedB,
                templateC_InvertedE: CCO_ESData.templateC_InvertedE,
                templateC_InvertedS: CCO_ESData.templateC_InvertedS,
            }),

            wheelsOnPowerChain: CCO_ESData.wheelsOnPowerChain,


            templateDData: new templateD({
            conveyorName: CCO_ESData.conveyorName,
            wheelManufacturer: CCO_ESData.wheelManufacturer,
            ...(CCO_ESData.otherWheelManufacturer && { otherWheelManufacturer: CCO_ESData.otherWheelManufacturer }),
            conveyorLength: CCO_ESData.conveyorLength,
            conveyorLengthUnit: CCO_ESData.conveyorLengthUnit,
            chainSize: CCO_ESData.chainSize,
            ...(CCO_ESData.otherChainSize && { otherChainSize: CCO_ESData.otherChainSize }),
            industrialChainManufacturer: CCO_ESData.industrialChainManufacturer,
            ...(CCO_ESData.otherChainManufacturer && { otherChainManufacturer: CCO_ESData.otherChainManufacturer }),
            conveyorSpeed: CCO_ESData.conveyorSpeed,
            conveyorSpeedUnit: CCO_ESData.conveyorSpeedUnit,
            conveyorIndex: CCO_ESData.conveyorIndex,
            appEnviroment: CCO_ESData.appEnviroment,
            ...(CCO_ESData.otherAppEnviroment && { otherAppEnviroment: CCO_ESData.otherAppEnviroment }),
            surroundingTemp: CCO_ESData.surroundingTemp,
            orientationType: CCO_ESData.orientationType,
            ...(CCO_ESData.conveyorLoaded && { conveyorLoaded: CCO_ESData.conveyorLoaded }),
            conveyorSwing: CCO_ESData.conveyorSwing,
            operatingVoltage: CCO_ESData.operatingVoltage,
            controlVoltSingle: CCO_ESData.controlVoltSingle,
            compressedAir: CCO_ESData.compressedAir,
            ...(CCO_ESData.airSupplyType && { airSupplyType: CCO_ESData.airSupplyType }),
            existingMonitor: CCO_ESData.existingMonitor,
            newMonitor: CCO_ESData.newMonitor,
            templateA_DData: new templateA({
                ...(CCO_ESData.dcuStatus && { dcuStatus: CCO_ESData.dcuStatus }),
                ...(CCO_ESData.dcuNum && { dcuNum: CCO_ESData.dcuNum }),
                ...(CCO_ESData.existingWindows && { existingWindows: CCO_ESData.existingWindows }),
                ...(CCO_ESData.existingHeadUnit && { existingHeadUnit: CCO_ESData.existingHeadUnit }),
                ...(CCO_ESData.existingDCU && { existingDCU: CCO_ESData.existingDCU }),
                ...(CCO_ESData.existingPowerInterface && { existingPowerInterface: CCO_ESData.existingPowerInterface }),
                ...(CCO_ESData.newReservoir && { newReservoir: CCO_ESData.newReservoir }),
                ...(CCO_ESData.reservoirSize && { reservoirSize: CCO_ESData.reservoirSize }),
                ...(CCO_ESData.otherReservoirSize && { otherReservoirSize: CCO_ESData.otherReservoirSize }),
                ...(CCO_ESData.newReservoirNum && { newReservoirNum: CCO_ESData.newReservoirNum }),
                ...(CCO_ESData.typeMonitor && { typeMonitor: CCO_ESData.typeMonitor }),
                ...(CCO_ESData.driveMotorAmp && { driveMotorAmp: CCO_ESData.driveMotorAmp }),
                ...(CCO_ESData.driveMotorAmpNum && { driveMotorAmpNum: CCO_ESData.driveMotorAmpNum }),
                ...(CCO_ESData.driveTakeUpAir && { driveTakeUpAir: CCO_ESData.driveTakeUpAir }),
                ...(CCO_ESData.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_ESData.driveTakeUpAirNum }),
                ...(CCO_ESData.takeUpDistance && { takeUpDistance: CCO_ESData.takeUpDistance }),
                ...(CCO_ESData.takeUpDistanceNum && { takeUpDistanceNum: CCO_ESData.takeUpDistanceNum }),
                ...(CCO_ESData.driveTemp && { driveTemp: CCO_ESData.driveTemp }),
                ...(CCO_ESData.driveTempNum && { driveTempNum: CCO_ESData.driveTempNum }),
                ...(CCO_ESData.driveVibration && { driveVibration: CCO_ESData.driveVibration }),
                ...(CCO_ESData.driveVibrationNum && { driveVibrationNum: CCO_ESData.driveVibrationNum }),
                ...(CCO_ESData.dogPitch && { dogPitch: CCO_ESData.dogPitch }),
                ...(CCO_ESData.dogPitchNum && { dogPitchNum: CCO_ESData.dogPitchNum }),
                ...(CCO_ESData.paintMarker && { paintMarker: CCO_ESData.paintMarker }),
                ...(CCO_ESData.paintMarkerNum && { paintMarkerNum: CCO_ESData.paintMarkerNum }),
                ...(CCO_ESData.chainVision && { chainVision: CCO_ESData.chainVision }),
                ...(CCO_ESData.lubeVision && { lubeVision: CCO_ESData.lubeVision }),
                ...(CCO_ESData.trolleyVision && { trolleyVision: CCO_ESData.trolleyVision }),
                ...(CCO_ESData.trolleyDetect && { trolleyDetect: CCO_ESData.trolleyDetect }),
                ...(CCO_ESData.omniView && { omniView: CCO_ESData.omniView }),
                ...(CCO_ESData.dcuUpgradeNum && { dcuUpgradeNum: CCO_ESData.dcuUpgradeNum }),
                ...(CCO_ESData.itNameOne && { itNameOne: CCO_ESData.itNameOne }),
                ...(CCO_ESData.itIPOne && { itIPOne: CCO_ESData.itIPOne }),
                ...(CCO_ESData.itGatewayOne && { itGatewayOne: CCO_ESData.itGatewayOne }),
                ...(CCO_ESData.itSubnetOne && { itSubnetOne: CCO_ESData.itSubnetOne }),
                ...(CCO_ESData.itDNSOne && { itDNSOne: CCO_ESData.itDNSOne }),
                ...(CCO_ESData.itSMTPOne && { itSMTPOne: CCO_ESData.itSMTPOne }),
                ...(CCO_ESData.itNameTwo && { itNameTwo: CCO_ESData.itNameTwo }),
                ...(CCO_ESData.itIPTwo && { itIPTwo: CCO_ESData.itIPTwo }),
                ...(CCO_ESData.itGatewayTwo && { itGatewayTwo: CCO_ESData.itGatewayTwo }),
                ...(CCO_ESData.itSubnetTwo && { itSubnetTwo: CCO_ESData.itSubnetTwo }),
                ...(CCO_ESData.itDNSTwo && { itDNSTwo: CCO_ESData.itDNSTwo }),
                ...(CCO_ESData.itSMTPTwo && { itSMTPTwo: CCO_ESData.itSMTPTwo }),
                ...(CCO_ESData.itNameThree && { itNameThree: CCO_ESData.itNameThree }),
                ...(CCO_ESData.itIPThree && { itIPThree: CCO_ESData.itIPThree }),
                ...(CCO_ESData.itGatewayThree && { itGatewayThree: CCO_ESData.itGatewayThree }),
                ...(CCO_ESData.itSubnetThree && { itSubnetThree: CCO_ESData.itSubnetThree }),
                ...(CCO_ESData.itDNSThree && { itDNSThree: CCO_ESData.itDNSThree }),
                ...(CCO_ESData.itSMTPThree && { itSMTPThree: CCO_ESData.itSMTPThree }),
                ...(CCO_ESData.itAdditionalNotes && { itAdditionalNotes: CCO_ESData.itAdditionalNotes }),
                ...(CCO_ESData.piuDistance && { piuDistance: CCO_ESData.piuDistance }),
                ...(CCO_ESData.switchDistance && { switchDistance: CCO_ESData.switchDistance }),
                ...(CCO_ESData.ampPickup && { ampPickup: CCO_ESData.ampPickup }),
                ...(CCO_ESData.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_ESData.fromAirTakeUpDistance }),
                ...(CCO_ESData.specialControllerOptions && { specialControllerOptions: CCO_ESData.specialControllerOptions }),
                ...(CCO_ESData.operatingVoltage && { operatingVoltage: CCO_ESData.operatingVoltage })

                }),

                lubeBrand: CCO_ESData.lubeBrand,
                currentGrease: CCO_ESData.currentGrease,
                currentGreaseGrade: CCO_ESData.currentGreaseGrade,
                wheelDiameter: CCO_ESData.wheelDiameter,
                ...(CCO_ESData.chainMaster && { chainMaster: CCO_ESData.chainMaster }),
                ...(CCO_ESData.remoteStatus && { remoteStatus: CCO_ESData.remoteStatus }),
                ...(CCO_ESData.mountStatus && { mountStatus: CCO_ESData.mountStatus }),
                ...(CCO_ESData.otherUnitStatus && { otherUnitStatus: CCO_ESData.otherUnitStatus }),
                ...(CCO_ESData.timerStatus && { timerStatus: CCO_ESData.timerStatus }),
                ...(CCO_ESData.electricStatus && { electricStatus: CCO_ESData.electricStatus }),
                ...(CCO_ESData.mightyLubeMonitoring && { mightyLubeMonitoring: CCO_ESData.mightyLubeMonitoring }),
                ...(CCO_ESData.preMountType && { preMountType: CCO_ESData.preMountType }),
                ...(CCO_ESData.otherControllerNotes && { otherControllerNotes: CCO_ESData.otherControllerNotes }),


            }),



            templateFData: {
                conveyorName: ETI_OP48EData.conveyorName,
                chainSize: ETI_OP48EData.chainSize,
                ...(ETI_OP48EData.otherChainSize && { otherChainSize: ETI_OP48EData.otherChainSize }),
                industrialChainManufacturer: ETI_OP48EData.industrialChainManufacturer,
                ...(ETI_OP48EData.otherChainManufacturer && { otherChainManufacturer: ETI_OP48EData.otherChainManufacturer }),
                wheelManufacturer: ETI_OP48EData.wheelManufacturer,
                ...(ETI_OP48EData.otherWheelManufacturer && { otherWheelManufacturer: ETI_OP48EData.otherWheelManufacturer }),
                conveyorLength: ETI_OP48EData.conveyorLength,
                conveyorLengthUnit: ETI_OP48EData.conveyorLengthUnit,
                brushApplicators: ETI_OP48EData.brushApplicators,
                m12Plugs: ETI_OP48EData.m12Plugs,
                oilStatus: ETI_OP48EData.oilStatus,
                operatingVoltage: ETI_OP48EData.operatingVoltage,
                controlVoltSingle: ETI_OP48EData.controlVoltSingle,
            }),

            ...(CCO_ESData.wheelOpenType && { wheelOpenType: CCO_ESData.wheelOpenType }),
            ...(CCO_ESData.wheelClosedType && { wheelClosedType: CCO_ESData.wheelClosedType }),
            ...(CCO_ESData.openStatus && { openStatus: CCO_ESData.openStatus }),
            ...(CCO_ESData.freeWheelStatus && { freeWheelStatus: CCO_ESData.freeWheelStatus }),
            ...(CCO_ESData.guideRollerStatus && { guideRollerStatus: CCO_ESData.guideRollerStatus }),
            ...(CCO_ESData.openRaceStyleType && { openRaceStyleType: CCO_ESData.openRaceStyleType }),
            ...(CCO_ESData.closedRaceStyleType && { closedRaceStyleType: CCO_ESData.closedRaceStyleType }),
            ...(CCO_ESData.holeStatus && { holeStatus: CCO_ESData.holeStatus }),
            ...(CCO_ESData.actuatorStatus && { actuatorStatus: CCO_ESData.actuatorStatus }),
            ...(CCO_ESData.pivotStatus && { pivotStatus: CCO_ESData.pivotStatus }),
            ...(CCO_ESData.kingPinStatus && { kingPinStatus: CCO_ESData.kingPinStatus }),
            ...(CCO_ESData.railLubeStatus && { railLubeStatus: CCO_ESData.railLubeStatus }),
            ...(CCO_ESData.externalLubeStatus && { externalLubeStatus: CCO_ESData.externalLubeStatus }),
            ...(CCO_ESData.lubeBrand && { lubeBrand: CCO_ESData.lubeBrand }),
            ...(CCO_ESData.lubeViscosity && { lubeViscosity: CCO_ESData.lubeViscosity }),
            ...(CCO_ESData.sideLubeStatus && { sideLubeStatus: CCO_ESData.sideLubeStatus }),
            ...(CCO_ESData.topLubeStatus && { topLubeStatus: CCO_ESData.topLubeStatus }),
            ...(CCO_ESData.chainMaster && { chainMaster: CCO_ESData.chainMaster }),
            ...(CCO_ESData.timerStatus && { timerStatus: CCO_ESData.timerStatus }),
            ...(CCO_ESData.electricStatus && { electricStatus: CCO_ESData.electricStatus }),
            ...(CCO_ESData.pneumaticStatus && { pneumaticStatus: CCO_ESData.pneumaticStatus }),
            ...(CCO_ESData.mightyLubeMonitoring && { mightyLubeMonitoring: CCO_ESData.mightyLubeMonitoring }),
            ...(CCO_ESData.plcConnection && { plcConnection: CCO_ESData.plcConnection }),
            ...(CCO_ESData.otherControllerNotes && { otherControllerNotes: CCO_ESData.otherControllerNotes }),
            ...(CCO_ESData.ohpUnitType && { ohpUnitType: CCO_ESData.ohpUnitType }),
            ...(CCO_ESData.ccoG && { ccoG: CCO_ESData.ccoG }),
            ...(CCO_ESData.ccoH && { ccoH: CCO_ESData.ccoH }),
            ...(CCO_ESData.ccoK && { ccoK: CCO_ESData.ccoK }),
            ...(CCO_ESData.ccoA && { ccoA: CCO_ESData.ccoA }),
            ...(CCO_ESData.ccoB && { ccoB: CCO_ESData.ccoB }),
            ...(CCO_ESData.ccoIG && { ccoIG: CCO_ESData.ccoIG }),
            ...(CCO_ESData.ccoIH && { ccoIH: CCO_ESData.ccoIH }),
            ...(CCO_ESData.ccoIK && { ccoIK: CCO_ESData.ccoIK }),
            ...(CCO_ESData.ccoL && { ccoL: CCO_ESData.ccoL }),

        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "CCO_ES"
        });
        await req.user.save();
        return res.status(200).json({ message: "CCO_ES entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;