const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const CCO_139A = require("../models/CCO_139A");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");
const templateD = require("../models/templateD.js");
const templateF = require("../models/templateF.js");

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { CCO_139AData, numRequested } = req.body;
        const order = new CCO_139A({
            conveyorName: CCO_139AData.conveyorName,
            chainSize: CCO_139AData.chainSize,
            ...(CCO_139AData.otherChainSize && { otherChainSize: CCO_139AData.otherChainSize }),
            industrialChainManufacturer: CCO_139AData.industrialChainManufacturer,
            ...(CCO_139AData.otherChainManufacturer && { otherChainManufacturer: CCO_139AData.otherChainManufacturer }),
            wheelManufacturer: CCO_139AData.wheelManufacturer,
            ...(CCO_139AData.otherWheelManufacturer && { otherWheelManufacturer: CCO_139AData.otherWheelManufacturer }),
            conveyorLength: CCO_139AData.conveyorLength,
            conveyorLengthUnit: CCO_139AData.conveyorLengthUnit,
            conveyorSpeed: CCO_139AData.conveyorSpeed,
            conveyorSpeedUnit: CCO_139AData.conveyorSpeedUnit,
            conveyorIndex: CCO_139AData.conveyorIndex,
            ...(CCO_139AData.travelDirection && { travelDirection: CCO_139AData.travelDirection }),
            appEnviroment: CCO_139AData.appEnviroment,
            ...(CCO_139AData.ovenStatus && { ovenStatus: CCO_139AData.ovenStatus }),
            ...(CCO_139AData.ovenTemp && { ovenTemp: CCO_139AData.ovenTemp }),
            ...(CCO_139AData.otherAppEnviroment && { otherAppEnviroment: CCO_139AData.otherAppEnviroment }),
            strandStatus: CCO_139AData.strandStatus,
            pointsOfLube: CCO_139AData.pointsOfLube,
            sensingMethod: CCO_139AData.sensingMethod,
            ...(CCO_139AData.surroundingTemp && { surroundingTemp: CCO_139AData.surroundingTemp }),
            ...(CCO_139AData.conveyorLoaded && { conveyorLoaded: CCO_139AData.conveyorLoaded }),
            ...(CCO_139AData.conveyorSwing && { conveyorSwing: CCO_139AData.conveyorSwing }),
            ...(CCO_139AData.compressedAir && { compressedAir: CCO_139AData.compressedAir }),
            ...(CCO_139AData.airSupplyType && { airSupplyType: CCO_139AData.airSupplyType }),
            operatingVoltSingle: CCO_139AData.operatingVoltSingle,
            controlVoltSingle: CCO_139AData.controlVoltSingle,
            existingMonitor: CCO_139AData.existingMonitor,
            newMonitor: CCO_139AData.newMonitor,
            monitorData: {
                ...(CCO_139AData.dcuStatus && { dcuStatus: CCO_139AData.dcuStatus }),
                ...(CCO_139AData.dcuNum && { dcuNum: CCO_139AData.dcuNum }),
                ...(CCO_139AData.existingWindows && { existingWindows: CCO_139AData.existingWindows }),
                ...(CCO_139AData.existingHeadUnit && { existingHeadUnit: CCO_139AData.existingHeadUnit }),
                ...(CCO_139AData.existingDCU && { existingDCU: CCO_139AData.existingDCU }),
                ...(CCO_139AData.existingPowerInterface && { existingPowerInterface: CCO_139AData.existingPowerInterface }),
                ...(CCO_139AData.newReservoir && { newReservoir: CCO_139AData.newReservoir }),
                ...(CCO_139AData.reservoirSize && { reservoirSize: CCO_139AData.reservoirSize }),
                ...(CCO_139AData.otherReservoirSize && { otherReservoirSize: CCO_139AData.otherReservoirSize }),
                ...(CCO_139AData.newReservoirNum && { newReservoirNum: CCO_139AData.newReservoirNum }),
                ...(CCO_139AData.typeMonitor && { typeMonitor: CCO_139AData.typeMonitor }),
                ...(CCO_139AData.driveMotorAmp && { driveMotorAmp: CCO_139AData.driveMotorAmp }),
                ...(CCO_139AData.driveMotorAmpNum && { driveMotorAmpNum: CCO_139AData.driveMotorAmpNum }),
                ...(CCO_139AData.driveTakeUpAir && { driveTakeUpAir: CCO_139AData.driveTakeUpAir }),
                ...(CCO_139AData.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_139AData.driveTakeUpAirNum }),
                ...(CCO_139AData.takeUpDistance && { takeUpDistance: CCO_139AData.takeUpDistance }),
                ...(CCO_139AData.takeUpDistanceNum && { takeUpDistanceNum: CCO_139AData.takeUpDistanceNum }),
                ...(CCO_139AData.driveTemp && { driveTemp: CCO_139AData.driveTemp }),
                ...(CCO_139AData.driveTempNum && { driveTempNum: CCO_139AData.driveTempNum }),
                ...(CCO_139AData.driveVibration && { driveVibration: CCO_139AData.driveVibration }),
                ...(CCO_139AData.driveVibrationNum && { driveVibrationNum: CCO_139AData.driveVibrationNum }),
                ...(CCO_139AData.dogPitch && { dogPitch: CCO_139AData.dogPitch }), 
                ...(CCO_139AData.dogPitchNum && { dogPitchNum: CCO_139AData.dogPitchNum }),
                ...(CCO_139AData.paintMarker && { paintMarker: CCO_139AData.paintMarker }),
                ...(CCO_139AData.paintMarkerNum && { paintMarkerNum: CCO_139AData.paintMarkerNum }),
                ...(CCO_139AData.chainVision && { chainVision: CCO_139AData.chainVision }),
                ...(CCO_139AData.lubeVision && { lubeVision: CCO_139AData.lubeVision }),
                ...(CCO_139AData.trolleyVision && { trolleyVision: CCO_139AData.trolleyVision }),
                ...(CCO_139AData.trolleyDetect && { trolleyDetect: CCO_139AData.trolleyDetect }),
                ...(CCO_139AData.omniView && { omniView: CCO_139AData.omniView }),
                ...(CCO_139AData.dcuUpgradeNum && { dcuUpgradeNum: CCO_139AData.dcuUpgradeNum }),
                ...(CCO_139AData.itNameOne && { itNameOne: CCO_139AData.itNameOne }),
                ...(CCO_139AData.itIPOne && { itIPOne: CCO_139AData.itIPOne }),
                ...(CCO_139AData.itGatewayOne && { itGatewayOne: CCO_139AData.itGatewayOne }),
                ...(CCO_139AData.itSubnetOne && { itSubnetOne: CCO_139AData.itSubnetOne }),
                ...(CCO_139AData.itDNSOne && { itDNSOne: CCO_139AData.itDNSOne }),
                ...(CCO_139AData.itSMTPOne && { itSMTPOne: CCO_139AData.itSMTPOne }),
                ...(CCO_139AData.itNameTwo && { itNameTwo: CCO_139AData.itNameTwo }),
                ...(CCO_139AData.itIPTwo && { itIPTwo: CCO_139AData.itIPTwo }),
                ...(CCO_139AData.itGatewayTwo && { itGatewayTwo: CCO_139AData.itGatewayTwo }),
                ...(CCO_139AData.itSubnetTwo && { itSubnetTwo: CCO_139AData.itSubnetTwo }),
                ...(CCO_139AData.itDNSTwo && { itDNSTwo: CCO_139AData.itDNSTwo }),
                ...(CCO_139AData.itSMTPTwo && { itSMTPTwo: CCO_139AData.itSMTPTwo }),
                ...(CCO_139AData.itNameThree && { itNameThree: CCO_139AData.itNameThree }),
                ...(CCO_139AData.itIPThree && { itIPThree: CCO_139AData.itIPThree }),
                ...(CCO_139AData.itGatewayThree && { itGatewayThree: CCO_139AData.itGatewayThree }),
                ...(CCO_139AData.itSubnetThree && { itSubnetThree: CCO_139AData.itSubnetThree }),
                ...(CCO_139AData.itDNSThree && { itDNSThree: CCO_139AData.itDNSThree }),
                ...(CCO_139AData.itSMTPThree && { itSMTPThree: CCO_139AData.itSMTPThree }),
                ...(CCO_139AData.itAdditionalNotes && { itAdditionalNotes: CCO_139AData.itAdditionalNotes }),
                ...(CCO_139AData.piuDistance && { piuDistance: CCO_139AData.piuDistance }),
                ...(CCO_139AData.switchDistance && { switchDistance: CCO_139AData.switchDistance }),
                ...(CCO_139AData.ampPickup && { ampPickup: CCO_139AData.ampPickup }),
                ...(CCO_139AData.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_139AData.fromAirTakeUpDistance }),
                ...(CCO_139AData.specialControllerOptions && { specialControllerOptions: CCO_139AData.specialControllerOptions })
            },

            addFreeCarrier: CCO_139AData.addFreeCarrier,

            templateBData: {
                conveyorName: CCO_139AData.conveyorName,
                industrialChainManufacturer: CCO_139AData.industrialChainManufacturer,
                ...(CCO_139AData.otherChainManufacturer && { otherChainManufacturer: CCO_139AData.otherChainManufacturer }),
                wheelManufacturer: CCO_139AData.wheelManufacturer,
                ...(CCO_139AData.wheelManufacturer && { wheelManufacturer: CCO_139AData.wheelManufacturer}),
                conveyorSpeed: CCO_139AData.conveyorSpeed,
                conveyorSpeedUnit: CCO_139AData.conveyorSpeedUnit,
                conveyorIndex: CCO_139AData.conveyorIndex,
                ...(CCO_139AData.travelDirection && { travelDirection: CCO_139AData.travelDirection}),
                appEnviroment: CCO_139AData.appEnviroment,
                ...(CCO_139AData.otherAppEnviroment && { otherAppEnviroment: CCO_139AData.otherAppEnviroment}),
                surroundingTemp: CCO_139AData.surroundingTemp,
                orientationType: CCO_139AData.orientationType,
                operatingVoltage: CCO_139AData.operatingVoltage,
                controlVoltSingle: CCO_139AData.controlVoltSingle,
                compressedAir: CCO_139AData.compressedAir,
                ...(CCO_139AData.airSupplyType && { airSupplyType: CCO_139AData.airSupplyType}),
            existingMonitor: CCO_139AData.existingMonitor,
            newMonitor: CCO_139AData.newMonitor,
            templateA_BData: {
                ...(CCO_139AData.dcuStatus && { dcuStatus: CCO_139AData.dcuStatus }),
                ...(CCO_139AData.dcuNum && { dcuNum: CCO_139AData.dcuNum }),
                ...(CCO_139AData.existingWindows && { existingWindows: CCO_139AData.existingWindows }),
                ...(CCO_139AData.existingHeadUnit && { existingHeadUnit: CCO_139AData.existingHeadUnit }),
                ...(CCO_139AData.existingDCU && { existingDCU: CCO_139AData.existingDCU }),
                ...(CCO_139AData.existingPowerInterface && { existingPowerInterface: CCO_139AData.existingPowerInterface }),
                ...(CCO_139AData.newReservoir && { newReservoir: CCO_139AData.newReservoir }),
                ...(CCO_139AData.reservoirSize && { reservoirSize: CCO_139AData.reservoirSize }),
                ...(CCO_139AData.otherReservoirSize && { otherReservoirSize: CCO_139AData.otherReservoirSize }),
                ...(CCO_139AData.newReservoirNum && { newReservoirNum: CCO_139AData.newReservoirNum }),
                ...(CCO_139AData.typeMonitor && { typeMonitor: CCO_139AData.typeMonitor }),
                ...(CCO_139AData.driveMotorAmp && { driveMotorAmp: CCO_139AData.driveMotorAmp }),
                ...(CCO_139AData.driveMotorAmpNum && { driveMotorAmpNum: CCO_139AData.driveMotorAmpNum }),
                ...(CCO_139AData.driveTakeUpAir && { driveTakeUpAir: CCO_139AData.driveTakeUpAir }),
                ...(CCO_139AData.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_139AData.driveTakeUpAirNum }),
                ...(CCO_139AData.takeUpDistance && { takeUpDistance: CCO_139AData.takeUpDistance }),
                ...(CCO_139AData.takeUpDistanceNum && { takeUpDistanceNum: CCO_139AData.takeUpDistanceNum }),
                ...(CCO_139AData.driveTemp && { driveTemp: CCO_139AData.driveTemp }),
                ...(CCO_139AData.driveTempNum && { driveTempNum: CCO_139AData.driveTempNum }),
                ...(CCO_139AData.driveVibration && { driveVibration: CCO_139AData.driveVibration }),
                ...(CCO_139AData.driveVibrationNum && { driveVibrationNum: CCO_139AData.driveVibrationNum }),
                ...(CCO_139AData.dogPitch && { dogPitch: CCO_139AData.dogPitch }),
                ...(CCO_139AData.dogPitchNum && { dogPitchNum: CCO_139AData.dogPitchNum }),
                ...(CCO_139AData.paintMarker && { paintMarker: CCO_139AData.paintMarker }),
                ...(CCO_139AData.paintMarkerNum && { paintMarkerNum: CCO_139AData.paintMarkerNum }),
                ...(CCO_139AData.chainVision && { chainVision: CCO_139AData.chainVision }),
                ...(CCO_139AData.lubeVision && { lubeVision: CCO_139AData.lubeVision }),
                ...(CCO_139AData.trolleyVision && { trolleyVision: CCO_139AData.trolleyVision }),
                ...(CCO_139AData.trolleyDetect && { trolleyDetect: CCO_139AData.trolleyDetect }),
                ...(CCO_139AData.omniView && { omniView: CCO_139AData.omniView }),
                ...(CCO_139AData.dcuUpgradeNum && { dcuUpgradeNum: CCO_139AData.dcuUpgradeNum }),
                ...(CCO_139AData.itNameOne && { itNameOne: CCO_139AData.itNameOne }),
                ...(CCO_139AData.itIPOne && { itIPOne: CCO_139AData.itIPOne }),
                ...(CCO_139AData.itGatewayOne && { itGatewayOne: CCO_139AData.itGatewayOne }),
                ...(CCO_139AData.itSubnetOne && { itSubnetOne: CCO_139AData.itSubnetOne }),
                ...(CCO_139AData.itDNSOne && { itDNSOne: CCO_139AData.itDNSOne }),
                ...(CCO_139AData.itSMTPOne && { itSMTPOne: CCO_139AData.itSMTPOne }),
                ...(CCO_139AData.itNameTwo && { itNameTwo: CCO_139AData.itNameTwo }),
                ...(CCO_139AData.itIPTwo && { itIPTwo: CCO_139AData.itIPTwo }),
                ...(CCO_139AData.itGatewayTwo && { itGatewayTwo: CCO_139AData.itGatewayTwo }),
                ...(CCO_139AData.itSubnetTwo && { itSubnetTwo: CCO_139AData.itSubnetTwo }),
                ...(CCO_139AData.itDNSTwo && { itDNSTwo: CCO_139AData.itDNSTwo }),
                ...(CCO_139AData.itSMTPTwo && { itSMTPTwo: CCO_139AData.itSMTPTwo }),
                ...(CCO_139AData.itNameThree && { itNameThree: CCO_139AData.itNameThree }),
                ...(CCO_139AData.itIPThree && { itIPThree: CCO_139AData.itIPThree }),
                ...(CCO_139AData.itGatewayThree && { itGatewayThree: CCO_139AData.itGatewayThree }),
                ...(CCO_139AData.itSubnetThree && { itSubnetThree: CCO_139AData.itSubnetThree }),
                ...(CCO_139AData.itDNSThree && { itDNSThree: CCO_139AData.itDNSThree }),
                ...(CCO_139AData.itSMTPThree && { itSMTPThree: CCO_139AData.itSMTPThree }),
                ...(CCO_139AData.itAdditionalNotes && { itAdditionalNotes: CCO_139AData.itAdditionalNotes }),
                ...(CCO_139AData.piuDistance && { piuDistance: CCO_139AData.piuDistance }),
                ...(CCO_139AData.switchDistance && { switchDistance: CCO_139AData.switchDistance }),
                ...(CCO_139AData.ampPickup && { ampPickup: CCO_139AData.ampPickup }),
                ...(CCO_139AData.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_139AData.fromAirTakeUpDistance }),
                ...(CCO_139AData.specialControllerOptions && { specialControllerOptions: CCO_139AData.specialControllerOptions }),
                ...(CCO_139AData.operatingVoltage && { operatingVoltage: CCO_139AData.operatingVoltage })

                },


                freeWheelStatus: CCO_139AData.freeWheelStatus,
                actuatorStatus: CCO_139AData.actuatorStatus,
                ...(CCO_139AData.pivotStatus && { pivotStatus: CCO_139AData.pivotStatus}),
                kingPinStatus: CCO_139AData.kingPinStatus,
                lubeBrand: CCO_139AData.lubeBrand,
                lubeViscosity: CCO_139AData.lubeViscosity,
                ...(CCO_139AData.lubeType && { lubeType: CCO_139AData.lubeType}),
                currentGrease: CCO_139AData.currentGrease,
                currentGreaseGrade: CCO_139AData.currentGreaseGrade,
                zerkDirection: CCO_139AData.zerkDirection,
                zerkLocationType: CCO_139AData.zerkLocationType,
                wheelDiameter: CCO_139AData.wheelDiameter,
                conveyorSwing: CCO_139AData.conveyorSwing,
                ...(CCO_139AData.chainMaster && { lubeType: CCO_139AData.chainMaster}),
                ...(CCO_139AData.remoteStatus && { lubeType: CCO_139AData.remoteStatus}),
                ...(CCO_139AData.mountStatus && { lubeType: CCO_139AData.mountStatus}),
                ...(CCO_139AData.otherUnitStatus && { lubeType: CCO_139AData.otherUnitStatus}),
                ...(CCO_139AData.timerStatus && { lubeType: CCO_139AData.timerStatus}),
                ...(CCO_139AData.electricStatus && { lubeType: CCO_139AData.electricStatus}),
                ...(CCO_139AData.mightyLubeMonitoring && { lubeType: CCO_139AData.mightyLubeMonitoring}),
                ...(CCO_139AData.preMountType && { lubeType: CCO_139AData.preMountType}),
                ...(CCO_139AData.otherPreMountType && { lubeType: CCO_139AData.otherPreMountType}),
                ...(CCO_139AData.plcConnection && { lubeType: CCO_139AData.plcConnection}),
                ...(CCO_139AData.otherControllerNotes && { lubeType: CCO_139AData.otherControllerNotes}),
                ...(CCO_139AData.templateB_UnitType && { lubeType: CCO_139AData.templateB_UnitType}),
                ...(CCO_139AData.templateB_InvertedB && { lubeType: CCO_139AData.templateB_InvertedB}),
                ...(CCO_139AData.templateB_InvertedE && { lubeType: CCO_139AData.templateB_InvertedE}),
                ...(CCO_139AData.templateB_InvertedG && { lubeType: CCO_139AData.templateB_InvertedG}),
                ...(CCO_139AData.templateB_InvertedH && { lubeType: CCO_139AData.templateB_InvertedH}),
                ...(CCO_139AData.templateB_InvertedK && { lubeType: CCO_139AData.templateB_InvertedK}),
                ...(CCO_139AData.templateB_InvertedT && { lubeType: CCO_139AData.templateB_InvertedT}),
                ...(CCO_139AData.templateB_InvertedU && { lubeType: CCO_139AData.templateB_InvertedU}),
                ...(CCO_139AData.templateB_InvertedV && { lubeType: CCO_139AData.templateB_InvertedV}),
                ...(CCO_139AData.templateB_InvertedW && { lubeType: CCO_139AData.templateB_InvertedW}),

            },



            templateCData: {
                conveyorName: CCO_139AData.conveyorName,
                industrialChainManufacturer: CCO_139AData.industrialChainManufacturer,
                ...(CCO_139AData.otherChainManufacturer && { otherChainManufacturer: CCO_139AData.otherChainManufacturer }),
                wheelManufacturer: CCO_139AData.wheelManufacturer,
                ...(CCO_139AData.wheelManufacturer && { wheelManufacturer: CCO_139AData.wheelManufacturer}),
                conveyorSpeed: CCO_139AData.conveyorSpeed,
                conveyorSpeedUnit: CCO_139AData.conveyorSpeedUnit,
                conveyorIndex: CCO_139AData.conveyorIndex,
                ...(CCO_139AData.travelDirection && { travelDirection: CCO_139AData.travelDirection}),
                appEnviroment: CCO_139AData.appEnviroment,
                ...(CCO_139AData.otherAppEnviroment && { otherAppEnviroment: CCO_139AData.otherAppEnviroment}),
                surroundingTemp: CCO_139AData.surroundingTemp,
                orientationType: CCO_139AData.orientationType,
                guideWheelsEven: CCO_139AData.guideWheelsEven,
                operatingVoltage: CCO_139AData.operatingVoltage,
                controlVoltSingle: CCO_139AData.controlVoltSingle,
                compressedAir: CCO_139AData.compressedAir,
                ...(CCO_139AData.airSupplyType && { airSupplyType: CCO_139AData.airSupplyType}),
                existingMonitor: CCO_139AData.existingMonitor,
                newMonitor: CCO_139AData.newMonitor,
                templateA_CData: {
                ...(CCO_139AData.dcuStatus && { dcuStatus: CCO_139AData.dcuStatus }),
                ...(CCO_139AData.dcuNum && { dcuNum: CCO_139AData.dcuNum }),
                ...(CCO_139AData.existingWindows && { existingWindows: CCO_139AData.existingWindows }),
                ...(CCO_139AData.existingHeadUnit && { existingHeadUnit: CCO_139AData.existingHeadUnit }),
                ...(CCO_139AData.existingDCU && { existingDCU: CCO_139AData.existingDCU }),
                ...(CCO_139AData.existingPowerInterface && { existingPowerInterface: CCO_139AData.existingPowerInterface }),
                ...(CCO_139AData.newReservoir && { newReservoir: CCO_139AData.newReservoir }),
                ...(CCO_139AData.reservoirSize && { reservoirSize: CCO_139AData.reservoirSize }),
                ...(CCO_139AData.otherReservoirSize && { otherReservoirSize: CCO_139AData.otherReservoirSize }),
                ...(CCO_139AData.newReservoirNum && { newReservoirNum: CCO_139AData.newReservoirNum }),
                ...(CCO_139AData.typeMonitor && { typeMonitor: CCO_139AData.typeMonitor }),
                ...(CCO_139AData.driveMotorAmp && { driveMotorAmp: CCO_139AData.driveMotorAmp }),
                ...(CCO_139AData.driveMotorAmpNum && { driveMotorAmpNum: CCO_139AData.driveMotorAmpNum }),
                ...(CCO_139AData.driveTakeUpAir && { driveTakeUpAir: CCO_139AData.driveTakeUpAir }),
                ...(CCO_139AData.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_139AData.driveTakeUpAirNum }),
                ...(CCO_139AData.takeUpDistance && { takeUpDistance: CCO_139AData.takeUpDistance }),
                ...(CCO_139AData.takeUpDistanceNum && { takeUpDistanceNum: CCO_139AData.takeUpDistanceNum }),
                ...(CCO_139AData.driveTemp && { driveTemp: CCO_139AData.driveTemp }),
                ...(CCO_139AData.driveTempNum && { driveTempNum: CCO_139AData.driveTempNum }),
                ...(CCO_139AData.driveVibration && { driveVibration: CCO_139AData.driveVibration }),
                ...(CCO_139AData.driveVibrationNum && { driveVibrationNum: CCO_139AData.driveVibrationNum }),
                ...(CCO_139AData.dogPitch && { dogPitch: CCO_139AData.dogPitch }),
                ...(CCO_139AData.dogPitchNum && { dogPitchNum: CCO_139AData.dogPitchNum }),
                ...(CCO_139AData.paintMarker && { paintMarker: CCO_139AData.paintMarker }),
                ...(CCO_139AData.paintMarkerNum && { paintMarkerNum: CCO_139AData.paintMarkerNum }),
                ...(CCO_139AData.chainVision && { chainVision: CCO_139AData.chainVision }),
                ...(CCO_139AData.lubeVision && { lubeVision: CCO_139AData.lubeVision }),
                ...(CCO_139AData.trolleyVision && { trolleyVision: CCO_139AData.trolleyVision }),
                ...(CCO_139AData.trolleyDetect && { trolleyDetect: CCO_139AData.trolleyDetect }),
                ...(CCO_139AData.omniView && { omniView: CCO_139AData.omniView }),
                ...(CCO_139AData.dcuUpgradeNum && { dcuUpgradeNum: CCO_139AData.dcuUpgradeNum }),
                ...(CCO_139AData.itNameOne && { itNameOne: CCO_139AData.itNameOne }),
                ...(CCO_139AData.itIPOne && { itIPOne: CCO_139AData.itIPOne }),
                ...(CCO_139AData.itGatewayOne && { itGatewayOne: CCO_139AData.itGatewayOne }),
                ...(CCO_139AData.itSubnetOne && { itSubnetOne: CCO_139AData.itSubnetOne }),
                ...(CCO_139AData.itDNSOne && { itDNSOne: CCO_139AData.itDNSOne }),
                ...(CCO_139AData.itSMTPOne && { itSMTPOne: CCO_139AData.itSMTPOne }),
                ...(CCO_139AData.itNameTwo && { itNameTwo: CCO_139AData.itNameTwo }),
                ...(CCO_139AData.itIPTwo && { itIPTwo: CCO_139AData.itIPTwo }),
                ...(CCO_139AData.itGatewayTwo && { itGatewayTwo: CCO_139AData.itGatewayTwo }),
                ...(CCO_139AData.itSubnetTwo && { itSubnetTwo: CCO_139AData.itSubnetTwo }),
                ...(CCO_139AData.itDNSTwo && { itDNSTwo: CCO_139AData.itDNSTwo }),
                ...(CCO_139AData.itSMTPTwo && { itSMTPTwo: CCO_139AData.itSMTPTwo }),
                ...(CCO_139AData.itNameThree && { itNameThree: CCO_139AData.itNameThree }),
                ...(CCO_139AData.itIPThree && { itIPThree: CCO_139AData.itIPThree }),
                ...(CCO_139AData.itGatewayThree && { itGatewayThree: CCO_139AData.itGatewayThree }),
                ...(CCO_139AData.itSubnetThree && { itSubnetThree: CCO_139AData.itSubnetThree }),
                ...(CCO_139AData.itDNSThree && { itDNSThree: CCO_139AData.itDNSThree }),
                ...(CCO_139AData.itSMTPThree && { itSMTPThree: CCO_139AData.itSMTPThree }),
                ...(CCO_139AData.itAdditionalNotes && { itAdditionalNotes: CCO_139AData.itAdditionalNotes }),
                ...(CCO_139AData.piuDistance && { piuDistance: CCO_139AData.piuDistance }),
                ...(CCO_139AData.switchDistance && { switchDistance: CCO_139AData.switchDistance }),
                ...(CCO_139AData.ampPickup && { ampPickup: CCO_139AData.ampPickup }),
                ...(CCO_139AData.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_139AData.fromAirTakeUpDistance }),
                ...(CCO_139AData.specialControllerOptions && { specialControllerOptions: CCO_139AData.specialControllerOptions }),
                ...(CCO_139AData.operatingVoltage && { operatingVoltage: CCO_139AData.operatingVoltage })

                },
                freeWheelStatus: CCO_139AData.freeWheelStatus,
                actuatorStatus: CCO_139AData.actuatorStatus,
                ...(CCO_139AData.pivotStatus && { pivotStatus: CCO_139AData.pivotStatus}),
                kingPinStatus: CCO_139AData.kingPinStatus,
                lubeBrand: CCO_139AData.lubeBrand,
                lubeViscosity: CCO_139AData.lubeViscosity,
                ...(CCO_139AData.lubeType && { lubeType: CCO_139AData.lubeType}),
                currentGrease: CCO_139AData.currentGrease,
                currentGreaseGrade: CCO_139AData.currentGreaseGrade,
                zerkDirection: CCO_139AData.zerkDirection,
                zerkLocationType: CCO_139AData.zerkLocationType,
                wheelDiameter: CCO_139AData.wheelDiameter,
                conveyorSwing: CCO_139AData.conveyorSwing,
                ...(CCO_139AData.chainMaster && { lubeType: CCO_139AData.chainMaster}),
                ...(CCO_139AData.remoteStatus && { lubeType: CCO_139AData.remoteStatus}),
                ...(CCO_139AData.mountStatus && { lubeType: CCO_139AData.mountStatus}),
                ...(CCO_139AData.otherUnitStatus && { lubeType: CCO_139AData.otherUnitStatus}),
                ...(CCO_139AData.timerStatus && { lubeType: CCO_139AData.timerStatus}),
                ...(CCO_139AData.electricStatus && { lubeType: CCO_139AData.electricStatus}),
                ...(CCO_139AData.mightyLubeMonitoring && { lubeType: CCO_139AData.mightyLubeMonitoring}),
                ...(CCO_139AData.preMountType && { lubeType: CCO_139AData.preMountType}),
                ...(CCO_139AData.otherPreMountType && { lubeType: CCO_139AData.otherPreMountType}),
                ...(CCO_139AData.plcConnection && { lubeType: CCO_139AData.plcConnection}),
                ...(CCO_139AData.otherControllerNotes && { lubeType: CCO_139AData.otherControllerNotes}),
                ...(CCO_139AData.templateC_UnitType && { lubeType: CCO_139AData.templateC_UnitType}),
                templateC_InvertedA: CCO_139AData.templateC_InvertedA,
                templateC_InvertedB: CCO_139AData.templateC_InvertedB,
                templateC_InvertedE: CCO_139AData.templateC_InvertedE,
                templateC_InvertedS: CCO_139AData.templateC_InvertedS,
            },

            wheelsOnPowerChain: CCO_139AData.wheelsOnPowerChain,


            templateDData: {
            conveyorName: CCO_139AData.conveyorName,
            wheelManufacturer: CCO_139AData.wheelManufacturer,
            ...(CCO_139AData.otherWheelManufacturer && { otherWheelManufacturer: CCO_139AData.otherWheelManufacturer }),
            conveyorLength: CCO_139AData.conveyorLength,
            conveyorLengthUnit: CCO_139AData.conveyorLengthUnit,
            chainSize: CCO_139AData.chainSize,
            ...(CCO_139AData.otherChainSize && { otherChainSize: CCO_139AData.otherChainSize }),
            industrialChainManufacturer: CCO_139AData.industrialChainManufacturer,
            ...(CCO_139AData.otherChainManufacturer && { otherChainManufacturer: CCO_139AData.otherChainManufacturer }),
            conveyorSpeed: CCO_139AData.conveyorSpeed,
            conveyorSpeedUnit: CCO_139AData.conveyorSpeedUnit,
            conveyorIndex: CCO_139AData.conveyorIndex,
            appEnviroment: CCO_139AData.appEnviroment,
            ...(CCO_139AData.otherAppEnviroment && { otherAppEnviroment: CCO_139AData.otherAppEnviroment }),
            surroundingTemp: CCO_139AData.surroundingTemp,
            orientationType: CCO_139AData.orientationType,
            ...(CCO_139AData.conveyorLoaded && { conveyorLoaded: CCO_139AData.conveyorLoaded }),
            conveyorSwing: CCO_139AData.conveyorSwing,
            operatingVoltage: CCO_139AData.operatingVoltage,
            controlVoltSingle: CCO_139AData.controlVoltSingle,
            compressedAir: CCO_139AData.compressedAir,
            ...(CCO_139AData.airSupplyType && { airSupplyType: CCO_139AData.airSupplyType }),
            existingMonitor: CCO_139AData.existingMonitor,
            newMonitor: CCO_139AData.newMonitor,
            templateA_DData: {
                ...(CCO_139AData.dcuStatus && { dcuStatus: CCO_139AData.dcuStatus }),
                ...(CCO_139AData.dcuNum && { dcuNum: CCO_139AData.dcuNum }),
                ...(CCO_139AData.existingWindows && { existingWindows: CCO_139AData.existingWindows }),
                ...(CCO_139AData.existingHeadUnit && { existingHeadUnit: CCO_139AData.existingHeadUnit }),
                ...(CCO_139AData.existingDCU && { existingDCU: CCO_139AData.existingDCU }),
                ...(CCO_139AData.existingPowerInterface && { existingPowerInterface: CCO_139AData.existingPowerInterface }),
                ...(CCO_139AData.newReservoir && { newReservoir: CCO_139AData.newReservoir }),
                ...(CCO_139AData.reservoirSize && { reservoirSize: CCO_139AData.reservoirSize }),
                ...(CCO_139AData.otherReservoirSize && { otherReservoirSize: CCO_139AData.otherReservoirSize }),
                ...(CCO_139AData.newReservoirNum && { newReservoirNum: CCO_139AData.newReservoirNum }),
                ...(CCO_139AData.typeMonitor && { typeMonitor: CCO_139AData.typeMonitor }),
                ...(CCO_139AData.driveMotorAmp && { driveMotorAmp: CCO_139AData.driveMotorAmp }),
                ...(CCO_139AData.driveMotorAmpNum && { driveMotorAmpNum: CCO_139AData.driveMotorAmpNum }),
                ...(CCO_139AData.driveTakeUpAir && { driveTakeUpAir: CCO_139AData.driveTakeUpAir }),
                ...(CCO_139AData.driveTakeUpAirNum && { driveTakeUpAirNum: CCO_139AData.driveTakeUpAirNum }),
                ...(CCO_139AData.takeUpDistance && { takeUpDistance: CCO_139AData.takeUpDistance }),
                ...(CCO_139AData.takeUpDistanceNum && { takeUpDistanceNum: CCO_139AData.takeUpDistanceNum }),
                ...(CCO_139AData.driveTemp && { driveTemp: CCO_139AData.driveTemp }),
                ...(CCO_139AData.driveTempNum && { driveTempNum: CCO_139AData.driveTempNum }),
                ...(CCO_139AData.driveVibration && { driveVibration: CCO_139AData.driveVibration }),
                ...(CCO_139AData.driveVibrationNum && { driveVibrationNum: CCO_139AData.driveVibrationNum }),
                ...(CCO_139AData.dogPitch && { dogPitch: CCO_139AData.dogPitch }),
                ...(CCO_139AData.dogPitchNum && { dogPitchNum: CCO_139AData.dogPitchNum }),
                ...(CCO_139AData.paintMarker && { paintMarker: CCO_139AData.paintMarker }),
                ...(CCO_139AData.paintMarkerNum && { paintMarkerNum: CCO_139AData.paintMarkerNum }),
                ...(CCO_139AData.chainVision && { chainVision: CCO_139AData.chainVision }),
                ...(CCO_139AData.lubeVision && { lubeVision: CCO_139AData.lubeVision }),
                ...(CCO_139AData.trolleyVision && { trolleyVision: CCO_139AData.trolleyVision }),
                ...(CCO_139AData.trolleyDetect && { trolleyDetect: CCO_139AData.trolleyDetect }),
                ...(CCO_139AData.omniView && { omniView: CCO_139AData.omniView }),
                ...(CCO_139AData.dcuUpgradeNum && { dcuUpgradeNum: CCO_139AData.dcuUpgradeNum }),
                ...(CCO_139AData.itNameOne && { itNameOne: CCO_139AData.itNameOne }),
                ...(CCO_139AData.itIPOne && { itIPOne: CCO_139AData.itIPOne }),
                ...(CCO_139AData.itGatewayOne && { itGatewayOne: CCO_139AData.itGatewayOne }),
                ...(CCO_139AData.itSubnetOne && { itSubnetOne: CCO_139AData.itSubnetOne }),
                ...(CCO_139AData.itDNSOne && { itDNSOne: CCO_139AData.itDNSOne }),
                ...(CCO_139AData.itSMTPOne && { itSMTPOne: CCO_139AData.itSMTPOne }),
                ...(CCO_139AData.itNameTwo && { itNameTwo: CCO_139AData.itNameTwo }),
                ...(CCO_139AData.itIPTwo && { itIPTwo: CCO_139AData.itIPTwo }),
                ...(CCO_139AData.itGatewayTwo && { itGatewayTwo: CCO_139AData.itGatewayTwo }),
                ...(CCO_139AData.itSubnetTwo && { itSubnetTwo: CCO_139AData.itSubnetTwo }),
                ...(CCO_139AData.itDNSTwo && { itDNSTwo: CCO_139AData.itDNSTwo }),
                ...(CCO_139AData.itSMTPTwo && { itSMTPTwo: CCO_139AData.itSMTPTwo }),
                ...(CCO_139AData.itNameThree && { itNameThree: CCO_139AData.itNameThree }),
                ...(CCO_139AData.itIPThree && { itIPThree: CCO_139AData.itIPThree }),
                ...(CCO_139AData.itGatewayThree && { itGatewayThree: CCO_139AData.itGatewayThree }),
                ...(CCO_139AData.itSubnetThree && { itSubnetThree: CCO_139AData.itSubnetThree }),
                ...(CCO_139AData.itDNSThree && { itDNSThree: CCO_139AData.itDNSThree }),
                ...(CCO_139AData.itSMTPThree && { itSMTPThree: CCO_139AData.itSMTPThree }),
                ...(CCO_139AData.itAdditionalNotes && { itAdditionalNotes: CCO_139AData.itAdditionalNotes }),
                ...(CCO_139AData.piuDistance && { piuDistance: CCO_139AData.piuDistance }),
                ...(CCO_139AData.switchDistance && { switchDistance: CCO_139AData.switchDistance }),
                ...(CCO_139AData.ampPickup && { ampPickup: CCO_139AData.ampPickup }),
                ...(CCO_139AData.fromAirTakeUpDistance && { fromAirTakeUpDistance: CCO_139AData.fromAirTakeUpDistance }),
                ...(CCO_139AData.specialControllerOptions && { specialControllerOptions: CCO_139AData.specialControllerOptions }),
                ...(CCO_139AData.operatingVoltage && { operatingVoltage: CCO_139AData.operatingVoltage })

                },

                lubeBrand: CCO_139AData.lubeBrand,
                currentGrease: CCO_139AData.currentGrease,
                currentGreaseGrade: CCO_139AData.currentGreaseGrade,
                wheelDiameter: CCO_139AData.wheelDiameter,
                ...(CCO_139AData.chainMaster && { chainMaster: CCO_139AData.chainMaster }),
                ...(CCO_139AData.remoteStatus && { remoteStatus: CCO_139AData.remoteStatus }),
                ...(CCO_139AData.mountStatus && { mountStatus: CCO_139AData.mountStatus }),
                ...(CCO_139AData.otherUnitStatus && { otherUnitStatus: CCO_139AData.otherUnitStatus }),
                ...(CCO_139AData.timerStatus && { timerStatus: CCO_139AData.timerStatus }),
                ...(CCO_139AData.electricStatus && { electricStatus: CCO_139AData.electricStatus }),
                ...(CCO_139AData.mightyLubeMonitoring && { mightyLubeMonitoring: CCO_139AData.mightyLubeMonitoring }),
                ...(CCO_139AData.preMountType && { preMountType: CCO_139AData.preMountType }),
                ...(CCO_139AData.otherControllerNotes && { otherControllerNotes: CCO_139AData.otherControllerNotes }),


            },



            templateFData: {
                conveyorName: ETI_OP48EData.conveyorName,
                chainSize: ETI_OP48EData.chainSize,
                ...(ETI_OP48EData.otherChainSize && { otherChainSize: ETI_OP48EData.otherChainSize }),
                industrialChainManufacturer: ETI_OP48EData.industrialChainManufacturer,
                ...(ETI_OP48EData.otherChainManufacturer && { otherChainManufacturer: ETI_OP48EData.otherChainManufacturer }),
                wheelManufacturer: ETI_OP48EData.wheelManufacturer,
                ...(ETI_OP48EData.otherWheelManufacturer && { otherWheelManufacturer: ETI_OP48EData.otherWheelManufacturer }),
                conveyorLength: ETI_OP48EData.conveyorLength,
                conveyorLengthUnit: ETI_OP48EData.conveyorLengthUnit,
                brushApplicators: ETI_OP48EData.brushApplicators,
                m12Plugs: ETI_OP48EData.m12Plugs,
                oilStatus: ETI_OP48EData.oilStatus,
                operatingVoltage: ETI_OP48EData.operatingVoltage,
                controlVoltSingle: ETI_OP48EData.controlVoltSingle,
            },

            ...(CCO_139AData.railLubeStatus && { railLubeStatus: CCO_139AData.railLubeStatus }),
            ...(CCO_139AData.lubeBrand && { lubeBrand: CCO_139AData.lubeBrand }),
            ...(CCO_139AData.lubeType && { lubeType: CCO_139AData.lubeType }),
            ...(CCO_139AData.lubeViscosity && { lubeViscosity: CCO_139AData.lubeViscosity }),
            ...(CCO_139AData.sideLubeStatus && { sideLubeStatus: CCO_139AData.sideLubeStatus }),
            ...(CCO_139AData.topLubeStatus && { topLubeStatus: CCO_139AData.topLubeStatus }),
            ...(CCO_139AData.chainCleanStatus && { chainCleanStatus: CCO_139AData.chainCleanStatus }),
            ...(CCO_139AData.chainMaster && { chainMaster: CCO_139AData.chainMaster }),
            ...(CCO_139AData.otherUnitStatus && { otherUnitStatus: CCO_139AData.otherUnitStatus }),
            ...(CCO_139AData.timerStatus && { timerStatus: CCO_139AData.timerStatus }),
                electricStatus: CCO_139AData.electricStatus,
            ...(CCO_139AData.pneumaticStatus && { pneumaticStatus: CCO_139AData.pneumaticStatus }),
            ...(CCO_139AData.mightyLubeMonitoring && { mightyLubeMonitoring: CCO_139AData.mightyLubeMonitoring }),
            ...(CCO_139AData.plcConnection && { plcConnection: CCO_139AData.plcConnection }),
            ...(CCO_139AData.otherControllerNotes && { otherControllerNotes: CCO_139AData.otherControllerNotes }),
            ...(CCO_139AData.ohpUnitType && { ohpUnitType: CCO_139AData.ohpUnitType }),
            ...(CCO_139AData.ccoG && { ccoG: CCO_139AData.ccoG }),
            ...(CCO_139AData.ccoH && { ccoH: CCO_139AData.ccoH }),
            ...(CCO_139AData.ccoK && { ccoK: CCO_139AData.ccoK }),
            ...(CCO_139AData.ccoA && { ccoA: CCO_139AData.ccoA }),
            ...(CCO_139AData.ccoB && { ccoB: CCO_139AData.ccoB }),
            ...(CCO_139AData.ccoIG && { ccoIG: CCO_139AData.ccoIG }),
            ...(CCO_139AData.ccoIH && { ccoIH: CCO_139AData.ccoIH }),
            ...(CCO_139AData.ccoIK && { ccoIK: CCO_139AData.ccoIK }),
            ...(CCO_139AData.ccoL && { ccoL: CCO_139AData.ccoL }),
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "CCO_139A"
        });
        await req.user.save();
        return res.status(200).json({ message: "CCO_139A entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;