// routes/COE_CEL.js
const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const COE_CEL = require("../models/COE_CEL");
const templateA = require("../models/templateA");
const templateD = require("../models/templateD");
const templateE = require("../models/templateE");
 
const router = express.Router();
 
router.post("/", authenticate, async (req, res) => {
    try {
        const { COE_CELData, numRequested } = req.body;

        const order = new COE_CEL({
            ...(COE_CELData.conveyorName && { conveyorName: COE_CELData.conveyorName }),
            chainSize: COE_CELData.chainSize,
            industrialChainManufacturer: COE_CELData.industrialChainManufacturer,
            ...(COE_CELData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: COE_CELData.otherIndustrialChainManufacturer }),
            conveyorLength: COE_CELData.conveyorLength,
            conveyorLengthUnit: COE_CELData.conveyorLengthUnit,
            conveyorSpeed: COE_CELData.conveyorSpeed,
            conveyorSpeedUnit: COE_CELData.conveyorSpeedUnit,
            ...(COE_CELData.conveyorIndex && { conveyorIndex: COE_CELData.conveyorIndex }),
            ...(COE_CELData.travelDirection && { travelDirection: COE_CELData.travelDirection }),
            appEnviroment: COE_CELData.appEnviroment,
            ...(COE_CELData.ovenStatus && { ovenStatus: COE_CELData.ovenStatus }),
            ...(COE_CELData.ovenTemp && { ovenTemp: COE_CELData.ovenTemp }),
            ...(COE_CELData.surroundingTemp && { surroundingTemp: COE_CELData.surroundingTemp }),
            ...(COE_CELData.conveyorLoaded && { conveyorLoaded: COE_CELData.conveyorLoaded }),
            ...(COE_CELData.conveyorSwing && { conveyorSwing: COE_CELData.conveyorSwing }),
            ...(COE_CELData.plantLayout && { plantLayout: COE_CELData.plantLayout }),
            ...(COE_CELData.requiredPics && { requiredPics: COE_CELData.requiredPics }),
            operatingVoltage: COE_CELData.operatingVoltage,
            existingMonitor: COE_CELData.existingMonitor,
            newMonitor: COE_CELData.newMonitor,
            monitorData: {
                ...(COE_CELData.dcuStatus && { dcuStatus: COE_CELData.dcuStatus }),
                ...(COE_CELData.dcuNum && { dcuNum: COE_CELData.dcuNum }),
                ...(COE_CELData.existingWindows && { existingWindows: COE_CELData.existingWindows }),
                ...(COE_CELData.existingHeadUnit && { existingHeadUnit: COE_CELData.existingHeadUnit }),
                ...(COE_CELData.existingDCU && { existingDCU: COE_CELData.existingDCU }),
                ...(COE_CELData.existingPowerInterface && { existingPowerInterface: COE_CELData.existingPowerInterface }),
                ...(COE_CELData.newReservoir && { newReservoir: COE_CELData.newReservoir }),
                ...(COE_CELData.reservoirSize && { reservoirSize: COE_CELData.reservoirSize }),
                ...(COE_CELData.otherReservoirSize && { otherReservoirSize: COE_CELData.otherReservoirSize }),
                ...(COE_CELData.newReservoirNum && { newReservoirNum: COE_CELData.newReservoirNum }),
                ...(COE_CELData.typeMonitor && { typeMonitor: COE_CELData.typeMonitor }),
                ...(COE_CELData.driveMotorAmp && { driveMotorAmp: COE_CELData.driveMotorAmp }),
                ...(COE_CELData.driveMotorAmpNum && { driveMotorAmpNum: COE_CELData.driveMotorAmpNum }),
                ...(COE_CELData.driveTakeUpAir && { driveTakeUpAir: COE_CELData.driveTakeUpAir }),
                ...(COE_CELData.driveTakeUpAirNum && { driveTakeUpAirNum: COE_CELData.driveTakeUpAirNum }),
                ...(COE_CELData.takeUpDistance && { takeUpDistance: COE_CELData.takeUpDistance }),
                ...(COE_CELData.takeUpDistanceNum && { takeUpDistanceNum: COE_CELData.takeUpDistanceNum }),
                ...(COE_CELData.driveTemp && { driveTemp: COE_CELData.driveTemp }),
                ...(COE_CELData.driveTempNum && { driveTempNum: COE_CELData.driveTempNum }),
                ...(COE_CELData.driveVibration && { driveVibration: COE_CELData.driveVibration }),
                ...(COE_CELData.driveVibrationNum && { driveVibrationNum: COE_CELData.driveVibrationNum }),
                ...(COE_CELData.dogPitch && { dogPitch: COE_CELData.dogPitch }),
                ...(COE_CELData.dogPitchNum && { dogPitchNum: COE_CELData.dogPitchNum }),
                ...(COE_CELData.paintMarker && { paintMarker: COE_CELData.paintMarker }),
                ...(COE_CELData.paintMarkerNum && { paintMarkerNum: COE_CELData.paintMarkerNum }),
                ...(COE_CELData.chainVision && { chainVision: COE_CELData.chainVision }),
                ...(COE_CELData.lubeVision && { lubeVision: COE_CELData.lubeVision }),
                ...(COE_CELData.trolleyVision && { trolleyVision: COE_CELData.trolleyVision }),
                ...(COE_CELData.trolleyDetect && { trolleyDetect: COE_CELData.trolleyDetect }),
                ...(COE_CELData.omniView && { omniView: COE_CELData.omniView }),
                ...(COE_CELData.dcuUpgradeNum && { dcuUpgradeNum: COE_CELData.dcuUpgradeNum }),
                ...(COE_CELData.itNameOne && { itNameOne: COE_CELData.itNameOne }),
                ...(COE_CELData.itIPOne && { itIPOne: COE_CELData.itIPOne }),
                ...(COE_CELData.itGatewayOne && { itGatewayOne: COE_CELData.itGatewayOne }),
                ...(COE_CELData.itSubnetOne && { itSubnetOne: COE_CELData.itSubnetOne }),
                ...(COE_CELData.itDNSOne && { itDNSOne: COE_CELData.itDNSOne }),
                ...(COE_CELData.itSMTPOne && { itSMTPOne: COE_CELData.itSMTPOne }),
                ...(COE_CELData.itNameTwo && { itNameTwo: COE_CELData.itNameTwo }),
                ...(COE_CELData.itIPTwo && { itIPTwo: COE_CELData.itIPTwo }),
                ...(COE_CELData.itGatewayTwo && { itGatewayTwo: COE_CELData.itGatewayTwo }),
                ...(COE_CELData.itSubnetTwo && { itSubnetTwo: COE_CELData.itSubnetTwo }),
                ...(COE_CELData.itDNSTwo && { itDNSTwo: COE_CELData.itDNSTwo }),
                ...(COE_CELData.itSMTPTwo && { itSMTPTwo: COE_CELData.itSMTPTwo }),
                ...(COE_CELData.itNameThree && { itNameThree: COE_CELData.itNameThree }),
                ...(COE_CELData.itIPThree && { itIPThree: COE_CELData.itIPThree }),
                ...(COE_CELData.itGatewayThree && { itGatewayThree: COE_CELData.itGatewayThree }),
                ...(COE_CELData.itSubnetThree && { itSubnetThree: COE_CELData.itSubnetThree }),
                ...(COE_CELData.itDNSThree && { itDNSThree: COE_CELData.itDNSThree }),
                ...(COE_CELData.itSMTPThree && { itSMTPThree: COE_CELData.itSMTPThree }),
                ...(COE_CELData.itAdditionalNotes && { itAdditionalNotes: COE_CELData.itAdditionalNotes }),
                ...(COE_CELData.piuDistance && { piuDistance: COE_CELData.piuDistance }),
                ...(COE_CELData.switchDistance && { switchDistance: COE_CELData.switchDistance }),
                ...(COE_CELData.ampPickup && { ampPickup: COE_CELData.ampPickup }),
                ...(COE_CELData.fromAirTakeUpDistance && { fromAirTakeUpDistance: COE_CELData.fromAirTakeUpDistance }),
                ...(COE_CELData.specialControllerOptions && { specialControllerOptions: COE_CELData.specialControllerOptions }),
                ...(COE_CELData.operatingVoltage && { operatingVoltage: COE_CELData.operatingVoltage })

            },


            wheelSealedChain: COE_CELData.wheelSealedChain,

            templateDData: {
            conveyorName: COE_CELData.conveyorName,
            wheelManufacturer: COE_CELData.wheelManufacturer,
            ...(COE_CELData.otherWheelManufacturer && { otherWheelManufacturer: COE_CELData.otherWheelManufacturer }),
            conveyorLength: COE_CELData.conveyorLength,
            conveyorLengthUnit: COE_CELData.conveyorLengthUnit,
            chainSize: COE_CELData.chainSize,
            ...(COE_CELData.otherChainSize && { otherChainSize: COE_CELData.otherChainSize }),
            industrialChainManufacturer: COE_CELData.industrialChainManufacturer,
            ...(COE_CELData.otherChainManufacturer && { otherChainManufacturer: COE_CELData.otherChainManufacturer }),
            conveyorSpeed: COE_CELData.conveyorSpeed,
            conveyorSpeedUnit: COE_CELData.conveyorSpeedUnit,
            conveyorIndex: COE_CELData.conveyorIndex,
            appEnviroment: COE_CELData.appEnviroment,
            ...(COE_CELData.otherAppEnviroment && { otherAppEnviroment: COE_CELData.otherAppEnviroment }),
            surroundingTemp: COE_CELData.surroundingTemp,
            orientationType: COE_CELData.orientationType,
            ...(COE_CELData.conveyorLoaded && { conveyorLoaded: COE_CELData.conveyorLoaded }),
            conveyorSwing: COE_CELData.conveyorSwing,
            operatingVoltage: COE_CELData.operatingVoltage,
            controlVoltSingle: COE_CELData.controlVoltSingle,
            compressedAir: COE_CELData.compressedAir,
            ...(COE_CELData.airSupplyType && { airSupplyType: COE_CELData.airSupplyType }),
            existingMonitor: COE_CELData.existingMonitor,
            newMonitor: COE_CELData.newMonitor,
            templateA_DData: {
                ...(COE_CELData.dcuStatus && { dcuStatus: COE_CELData.dcuStatus }),
                ...(COE_CELData.dcuNum && { dcuNum: COE_CELData.dcuNum }),
                ...(COE_CELData.existingWindows && { existingWindows: COE_CELData.existingWindows }),
                ...(COE_CELData.existingHeadUnit && { existingHeadUnit: COE_CELData.existingHeadUnit }),
                ...(COE_CELData.existingDCU && { existingDCU: COE_CELData.existingDCU }),
                ...(COE_CELData.existingPowerInterface && { existingPowerInterface: COE_CELData.existingPowerInterface }),
                ...(COE_CELData.newReservoir && { newReservoir: COE_CELData.newReservoir }),
                ...(COE_CELData.reservoirSize && { reservoirSize: COE_CELData.reservoirSize }),
                ...(COE_CELData.otherReservoirSize && { otherReservoirSize: COE_CELData.otherReservoirSize }),
                ...(COE_CELData.newReservoirNum && { newReservoirNum: COE_CELData.newReservoirNum }),
                ...(COE_CELData.typeMonitor && { typeMonitor: COE_CELData.typeMonitor }),
                ...(COE_CELData.driveMotorAmp && { driveMotorAmp: COE_CELData.driveMotorAmp }),
                ...(COE_CELData.driveMotorAmpNum && { driveMotorAmpNum: COE_CELData.driveMotorAmpNum }),
                ...(COE_CELData.driveTakeUpAir && { driveTakeUpAir: COE_CELData.driveTakeUpAir }),
                ...(COE_CELData.driveTakeUpAirNum && { driveTakeUpAirNum: COE_CELData.driveTakeUpAirNum }),
                ...(COE_CELData.takeUpDistance && { takeUpDistance: COE_CELData.takeUpDistance }),
                ...(COE_CELData.takeUpDistanceNum && { takeUpDistanceNum: COE_CELData.takeUpDistanceNum }),
                ...(COE_CELData.driveTemp && { driveTemp: COE_CELData.driveTemp }),
                ...(COE_CELData.driveTempNum && { driveTempNum: COE_CELData.driveTempNum }),
                ...(COE_CELData.driveVibration && { driveVibration: COE_CELData.driveVibration }),
                ...(COE_CELData.driveVibrationNum && { driveVibrationNum: COE_CELData.driveVibrationNum }),
                ...(COE_CELData.dogPitch && { dogPitch: COE_CELData.dogPitch }),
                ...(COE_CELData.dogPitchNum && { dogPitchNum: COE_CELData.dogPitchNum }),
                ...(COE_CELData.paintMarker && { paintMarker: COE_CELData.paintMarker }),
                ...(COE_CELData.paintMarkerNum && { paintMarkerNum: COE_CELData.paintMarkerNum }),
                ...(COE_CELData.chainVision && { chainVision: COE_CELData.chainVision }),
                ...(COE_CELData.lubeVision && { lubeVision: COE_CELData.lubeVision }),
                ...(COE_CELData.trolleyVision && { trolleyVision: COE_CELData.trolleyVision }),
                ...(COE_CELData.trolleyDetect && { trolleyDetect: COE_CELData.trolleyDetect }),
                ...(COE_CELData.omniView && { omniView: COE_CELData.omniView }),
                ...(COE_CELData.dcuUpgradeNum && { dcuUpgradeNum: COE_CELData.dcuUpgradeNum }),
                ...(COE_CELData.itNameOne && { itNameOne: COE_CELData.itNameOne }),
                ...(COE_CELData.itIPOne && { itIPOne: COE_CELData.itIPOne }),
                ...(COE_CELData.itGatewayOne && { itGatewayOne: COE_CELData.itGatewayOne }),
                ...(COE_CELData.itSubnetOne && { itSubnetOne: COE_CELData.itSubnetOne }),
                ...(COE_CELData.itDNSOne && { itDNSOne: COE_CELData.itDNSOne }),
                ...(COE_CELData.itSMTPOne && { itSMTPOne: COE_CELData.itSMTPOne }),
                ...(COE_CELData.itNameTwo && { itNameTwo: COE_CELData.itNameTwo }),
                ...(COE_CELData.itIPTwo && { itIPTwo: COE_CELData.itIPTwo }),
                ...(COE_CELData.itGatewayTwo && { itGatewayTwo: COE_CELData.itGatewayTwo }),
                ...(COE_CELData.itSubnetTwo && { itSubnetTwo: COE_CELData.itSubnetTwo }),
                ...(COE_CELData.itDNSTwo && { itDNSTwo: COE_CELData.itDNSTwo }),
                ...(COE_CELData.itSMTPTwo && { itSMTPTwo: COE_CELData.itSMTPTwo }),
                ...(COE_CELData.itNameThree && { itNameThree: COE_CELData.itNameThree }),
                ...(COE_CELData.itIPThree && { itIPThree: COE_CELData.itIPThree }),
                ...(COE_CELData.itGatewayThree && { itGatewayThree: COE_CELData.itGatewayThree }),
                ...(COE_CELData.itSubnetThree && { itSubnetThree: COE_CELData.itSubnetThree }),
                ...(COE_CELData.itDNSThree && { itDNSThree: COE_CELData.itDNSThree }),
                ...(COE_CELData.itSMTPThree && { itSMTPThree: COE_CELData.itSMTPThree }),
                ...(COE_CELData.itAdditionalNotes && { itAdditionalNotes: COE_CELData.itAdditionalNotes }),
                ...(COE_CELData.piuDistance && { piuDistance: COE_CELData.piuDistance }),
                ...(COE_CELData.switchDistance && { switchDistance: COE_CELData.switchDistance }),
                ...(COE_CELData.ampPickup && { ampPickup: COE_CELData.ampPickup }),
                ...(COE_CELData.fromAirTakeUpDistance && { fromAirTakeUpDistance: COE_CELData.fromAirTakeUpDistance }),
                ...(COE_CELData.specialControllerOptions && { specialControllerOptions: COE_CELData.specialControllerOptions }),
                ...(COE_CELData.operatingVoltage && { operatingVoltage: COE_CELData.operatingVoltage })

                },

                lubeBrand: COE_CELData.lubeBrand,
                currentGrease: COE_CELData.currentGrease,
                currentGreaseGrade: COE_CELData.currentGreaseGrade,
                wheelDiameter: COE_CELData.wheelDiameter,
                ...(COE_CELData.chainMaster && { chainMaster: COE_CELData.chainMaster }),
                ...(COE_CELData.remoteStatus && { remoteStatus: COE_CELData.remoteStatus }),
                ...(COE_CELData.mountStatus && { mountStatus: COE_CELData.mountStatus }),
                ...(COE_CELData.otherUnitStatus && { otherUnitStatus: COE_CELData.otherUnitStatus }),
                ...(COE_CELData.timerStatus && { timerStatus: COE_CELData.timerStatus }),
                ...(COE_CELData.electricStatus && { electricStatus: COE_CELData.electricStatus }),
                ...(COE_CELData.mightyLubeMonitoring && { mightyLubeMonitoring: COE_CELData.mightyLubeMonitoring }),
                ...(COE_CELData.preMountType && { preMountType: COE_CELData.preMountType }),
                ...(COE_CELData.otherControllerNotes && { otherControllerNotes: COE_CELData.otherControllerNotes }),


            },
             
            ...(COE_CELData.wheelOpenType && { wheelOpenType: COE_CELData.wheelOpenType }),
            ...(COE_CELData.wheelClosedType && { wheelClosedType: COE_CELData.wheelClosedType }),
            ...(COE_CELData.openStatus && { openStatus: COE_CELData.openStatus }),


            templateEData: {
                conveyorName: COE_CELData.conveyorName,
                chainSize: COE_CELData.chainSize,
                ...(COE_CELData.otherChainSize && { otherChainSize: COE_CELData.otherChainSize }),
                ...(COE_CELData.industrialChainManufacturer && { industrialChainManufacturer: COE_CELData.industrialChainManufacturer }),
                ...(COE_CELData.otherChainManufacturer && { otherChainManufacturer: COE_CELData.otherChainManufacturer }),
                ...(COE_CELData.conveyorLength && { conveyorLength: COE_CELData.conveyorLength }),
                ...(COE_CELData.conveyorLengthUnit && { conveyorLengthUnit: COE_CELData.conveyorLengthUnit }),
                ...(COE_CELData.appEnviroment && { appEnviroment: COE_CELData.appEnviroment }),
                ...(COE_CELData.otherAppEnviroment && { otherAppEnviroment: COE_CELData.otherAppEnviroment }),
                ...(COE_CELData.lubeBrand && { lubeBrand: COE_CELData.lubeBrand }),
                ...(COE_CELData.lubeType && { lubeType: COE_CELData.lubeType }),
                ...(COE_CELData.lubeViscosity && { lubeViscosity: COE_CELData.lubeViscosity }),
                ...(COE_CELData.specialControllerOptions && { specialControllerOptions: COE_CELData.specialControllerOptions }),
                ...(COE_CELData.wireMeasurementUnit && { wireMeasurementUnit: COE_CELData.wireMeasurementUnit }),
                ...(COE_CELData.conductor2 && { conductor2: COE_CELData.conductor2 }),
                ...(COE_CELData.conductor4 && { conductor4: COE_CELData.conductor4 }),
                ...(COE_CELData.conductor7 && { conductor7: COE_CELData.conductor7 }),
                ...(COE_CELData.conductor12 && { conductor12: COE_CELData.conductor12 }),
                ...(COE_CELData.junctionBoxNum && { junctionBoxNum: COE_CELData.junctionBoxNum }),

            },

            ...(COE_CELData.wheelOpenType && { wheelOpenType: COE_CELData.wheelOpenType }),
            ...(COE_CELData.wheelClosedType && { wheelClosedType: COE_CELData.wheelClosedType }),
            ...(COE_CELData.openStatus && { openStatus: COE_CELData.openStatus }),
            ...(COE_CELData.catDriveStatus && { catDriveStatus: COE_CELData.catDriveStatus }),
            ...(COE_CELData.railLubeStatus && { railLubeStatus: COE_CELData.railLubeStatus }),
            ...(COE_CELData.externalLubeStatus && { externalLubeStatus: COE_CELData.externalLubeStatus }),
            ...(COE_CELData.lubeBrand && { lubeBrand: COE_CELData.lubeBrand }),
            ...(COE_CELData.lubeType && { lubeType: COE_CELData.lubeType }),
            ...(COE_CELData.lubeViscosity && { lubeViscosity: COE_CELData.lubeViscosity }),
            ...(COE_CELData.chainCleanStatus && { chainCleanStatus: COE_CELData.chainCleanStatus }),
            ...(COE_CELData.wireMeasurementUnit && { wireMeasurementUnit: COE_CELData.wireMeasurementUnit }),
            ...(COE_CELData.conductor2 && { conductor2: COE_CELData.conductor2 }),
            ...(COE_CELData.conductor4 && { conductor4: COE_CELData.conductor4 }),
            ...(COE_CELData.conductor7 && { conductor7: COE_CELData.conductor7 }),
            ...(COE_CELData.conductor12 && { conductor12: COE_CELData.conductor12 }),
            ...(COE_CELData.junctionBoxNum && { junctionBoxNum: COE_CELData.junctionBoxNum }),
            ...(COE_CELData.coeUnitType && { coeUnitType: COE_CELData.coeUnitType }),
            ...(COE_CELData.coeLineA && { coeLineA: COE_CELData.coeLineA }),
            ...(COE_CELData.coeLineG && { coeLineG: COE_CELData.coeLineG }),
            ...(COE_CELData.coeLineH && { coeLineH: COE_CELData.coeLineH }),
            ...(COE_CELData.coeLineJ && { coeLineJ: COE_CELData.coeLineJ }),
            ...(COE_CELData.coeLineX && { coeLineX: COE_CELData.coeLineX }),
            ...(COE_CELData.coeLineY && { coeLineY: COE_CELData.coeLineY }),
        });

        req.user.cart.push({ numRequested, productConfigurationInfo: order, productType: "COE_CEL" });
        await req.user.save();

        return res.status(200).json({ message: "COE_CEL entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;
