// routes/COE_OP4OE.js
const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const COE_OP4OE = require("../models/COE_OP4OE");
const templateA = require("../models/templateA");
const templateD = require("../models/templateD");
const templateF = require("../models/templateF");


const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { COE_OP4OEData, numRequested } = req.body;

        const order = new COE_OP4OE({
            conveyorName: COE_OP4OEData.conveyorName,
            chainSize: COE_OP4OEData.chainSize,
            ...(COE_OP4OEData.otherChainSize && { otherChainSize: COE_OP4OEData.otherChainSize }),
            industrialChainManufacturer: COE_OP4OEData.industrialChainManufacturer,
            ...(COE_OP4OEData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: COE_OP4OEData.otherIndustrialChainManufacturer }),
            conveyorLength: COE_OP4OEData.conveyorLength,
            conveyorLengthUnit: COE_OP4OEData.conveyorLengthUnit,
            conveyorSpeed: COE_OP4OEData.conveyorSpeed,
            conveyorSpeedUnit: COE_OP4OEData.conveyorSpeedUnit,
            ...(COE_OP4OEData.conveyorIndex && { conveyorIndex: COE_OP4OEData.conveyorIndex }),
            ...(COE_OP4OEData.travelDirection && { travelDirection: COE_OP4OEData.travelDirection }),
            appEnviroment: COE_OP4OEData.appEnviroment,
            ...(COE_OP4OEData.ovenStatus && { ovenStatus: COE_OP4OEData.ovenStatus }),
            ...(COE_OP4OEData.ovenTemp && { ovenTemp: COE_OP4OEData.ovenTemp }),
            ...(COE_OP4OEData.otherAppEnviroment && { otherAppEnviroment: COE_OP4OEData.otherAppEnviroment }),
            ...(COE_OP4OEData.surroundingTemp && { surroundingTemp: COE_OP4OEData.surroundingTemp }),
            ...(COE_OP4OEData.conveyorLoaded && { conveyorLoaded: COE_OP4OEData.conveyorLoaded }),
            ...(COE_OP4OEData.conveyorSwing && { conveyorSwing: COE_OP4OEData.conveyorSwing }),
            ...(COE_OP4OEData.plantLayout && { plantLayout: COE_OP4OEData.plantLayout }),
            ...(COE_OP4OEData.requiredPics && { requiredPics: COE_OP4OEData.requiredPics }),
            operatingVoltage: COE_OP4OEData.operatingVoltage,
            existingMonitor: COE_OP4OEData.existingMonitor,
            newMonitor: COE_OP4OEData.newMonitor,

            monitorData: {
                ...(COE_OP4OEData.dcuStatus && { dcuStatus: COE_OP4OEData.dcuStatus }),
                ...(COE_OP4OEData.dcuNum && { dcuNum: COE_OP4OEData.dcuNum }),
                ...(COE_OP4OEData.existingWindows && { existingWindows: COE_OP4OEData.existingWindows }),
                ...(COE_OP4OEData.existingHeadUnit && { existingHeadUnit: COE_OP4OEData.existingHeadUnit }),
                ...(COE_OP4OEData.existingDCU && { existingDCU: COE_OP4OEData.existingDCU }),
                ...(COE_OP4OEData.existingPowerInterface && { existingPowerInterface: COE_OP4OEData.existingPowerInterface }),
                ...(COE_OP4OEData.newReservoir && { newReservoir: COE_OP4OEData.newReservoir }),
                ...(COE_OP4OEData.reservoirSize && { reservoirSize: COE_OP4OEData.reservoirSize }),
                ...(COE_OP4OEData.otherReservoirSize && { otherReservoirSize: COE_OP4OEData.otherReservoirSize }),
                ...(COE_OP4OEData.newReservoirNum && { newReservoirNum: COE_OP4OEData.newReservoirNum }),
                ...(COE_OP4OEData.typeMonitor && { typeMonitor: COE_OP4OEData.typeMonitor }),
                ...(COE_OP4OEData.driveMotorAmp && { driveMotorAmp: COE_OP4OEData.driveMotorAmp }),
                ...(COE_OP4OEData.driveMotorAmpNum && { driveMotorAmpNum: COE_OP4OEData.driveMotorAmpNum }),
                ...(COE_OP4OEData.driveTakeUpAir && { driveTakeUpAir: COE_OP4OEData.driveTakeUpAir }),
                ...(COE_OP4OEData.driveTakeUpAirNum && { driveTakeUpAirNum: COE_OP4OEData.driveTakeUpAirNum }),
                ...(COE_OP4OEData.takeUpDistance && { takeUpDistance: COE_OP4OEData.takeUpDistance }),
                ...(COE_OP4OEData.takeUpDistanceNum && { takeUpDistanceNum: COE_OP4OEData.takeUpDistanceNum }),
                ...(COE_OP4OEData.driveTemp && { driveTemp: COE_OP4OEData.driveTemp }),
                ...(COE_OP4OEData.driveTempNum && { driveTempNum: COE_OP4OEData.driveTempNum }),
                ...(COE_OP4OEData.driveVibration && { driveVibration: COE_OP4OEData.driveVibration }),
                ...(COE_OP4OEData.driveVibrationNum && { driveVibrationNum: COE_OP4OEData.driveVibrationNum }),
                ...(COE_OP4OEData.dogPitch && { dogPitch: COE_OP4OEData.dogPitch }),
                ...(COE_OP4OEData.dogPitchNum && { dogPitchNum: COE_OP4OEData.dogPitchNum }),
                ...(COE_OP4OEData.paintMarker && { paintMarker: COE_OP4OEData.paintMarker }),
                ...(COE_OP4OEData.paintMarkerNum && { paintMarkerNum: COE_OP4OEData.paintMarkerNum }),
                ...(COE_OP4OEData.chainVision && { chainVision: COE_OP4OEData.chainVision }),
                ...(COE_OP4OEData.lubeVision && { lubeVision: COE_OP4OEData.lubeVision }),
                ...(COE_OP4OEData.trolleyVision && { trolleyVision: COE_OP4OEData.trolleyVision }),
                ...(COE_OP4OEData.trolleyDetect && { trolleyDetect: COE_OP4OEData.trolleyDetect }),
                ...(COE_OP4OEData.omniView && { omniView: COE_OP4OEData.omniView }),
                ...(COE_OP4OEData.dcuUpgradeNum && { dcuUpgradeNum: COE_OP4OEData.dcuUpgradeNum }),
                ...(COE_OP4OEData.itNameOne && { itNameOne: COE_OP4OEData.itNameOne }),
                ...(COE_OP4OEData.itIPOne && { itIPOne: COE_OP4OEData.itIPOne }),
                ...(COE_OP4OEData.itGatewayOne && { itGatewayOne: COE_OP4OEData.itGatewayOne }),
                ...(COE_OP4OEData.itSubnetOne && { itSubnetOne: COE_OP4OEData.itSubnetOne }),
                ...(COE_OP4OEData.itDNSOne && { itDNSOne: COE_OP4OEData.itDNSOne }),
                ...(COE_OP4OEData.itSMTPOne && { itSMTPOne: COE_OP4OEData.itSMTPOne }),
                ...(COE_OP4OEData.itNameTwo && { itNameTwo: COE_OP4OEData.itNameTwo }),
                ...(COE_OP4OEData.itIPTwo && { itIPTwo: COE_OP4OEData.itIPTwo }),
                ...(COE_OP4OEData.itGatewayTwo && { itGatewayTwo: COE_OP4OEData.itGatewayTwo }),
                ...(COE_OP4OEData.itSubnetTwo && { itSubnetTwo: COE_OP4OEData.itSubnetTwo }),
                ...(COE_OP4OEData.itDNSTwo && { itDNSTwo: COE_OP4OEData.itDNSTwo }),
                ...(COE_OP4OEData.itSMTPTwo && { itSMTPTwo: COE_OP4OEData.itSMTPTwo }),
                ...(COE_OP4OEData.itNameThree && { itNameThree: COE_OP4OEData.itNameThree }),
                ...(COE_OP4OEData.itIPThree && { itIPThree: COE_OP4OEData.itIPThree }),
                ...(COE_OP4OEData.itGatewayThree && { itGatewayThree: COE_OP4OEData.itGatewayThree }),
                ...(COE_OP4OEData.itSubnetThree && { itSubnetThree: COE_OP4OEData.itSubnetThree }),
                ...(COE_OP4OEData.itDNSThree && { itDNSThree: COE_OP4OEData.itDNSThree }),
                ...(COE_OP4OEData.itSMTPThree && { itSMTPThree: COE_OP4OEData.itSMTPThree }),
                ...(COE_OP4OEData.itAdditionalNotes && { itAdditionalNotes: COE_OP4OEData.itAdditionalNotes }),
                ...(COE_OP4OEData.piuDistance && { piuDistance: COE_OP4OEData.piuDistance }),
                ...(COE_OP4OEData.switchDistance && { switchDistance: COE_OP4OEData.switchDistance }),
                ...(COE_OP4OEData.ampPickup && { ampPickup: COE_OP4OEData.ampPickup }),
                ...(COE_OP4OEData.fromAirTakeUpDistance && { fromAirTakeUpDistance: COE_OP4OEData.fromAirTakeUpDistance }),
                ...(COE_OP4OEData.specialControllerOptions && { specialControllerOptions: COE_OP4OEData.specialControllerOptions }),
                ...(COE_OP4OEData.operatingVoltage && { operatingVoltage: COE_OP4OEData.operatingVoltage })

            },
            wheelSealedChain: COE_OP4OEData.wheelSealedChain,

            templateDData: {
            conveyorName: COE_OP4OEData.conveyorName,
            wheelManufacturer: COE_OP4OEData.wheelManufacturer,
            ...(COE_OP4OEData.otherWheelManufacturer && { otherWheelManufacturer: COE_OP4OEData.otherWheelManufacturer }),
            conveyorLength: COE_OP4OEData.conveyorLength,
            conveyorLengthUnit: COE_OP4OEData.conveyorLengthUnit,
            chainSize: COE_OP4OEData.chainSize,
            ...(COE_OP4OEData.otherChainSize && { otherChainSize: COE_OP4OEData.otherChainSize }),
            industrialChainManufacturer: COE_OP4OEData.industrialChainManufacturer,
            ...(COE_OP4OEData.otherChainManufacturer && { otherChainManufacturer: COE_OP4OEData.otherChainManufacturer }),
            conveyorSpeed: COE_OP4OEData.conveyorSpeed,
            conveyorSpeedUnit: COE_OP4OEData.conveyorSpeedUnit,
            conveyorIndex: COE_OP4OEData.conveyorIndex,
            appEnviroment: COE_OP4OEData.appEnviroment,
            ...(COE_OP4OEData.otherAppEnviroment && { otherAppEnviroment: COE_OP4OEData.otherAppEnviroment }),
            surroundingTemp: COE_OP4OEData.surroundingTemp,
            orientationType: COE_OP4OEData.orientationType,
            ...(COE_OP4OEData.conveyorLoaded && { conveyorLoaded: COE_OP4OEData.conveyorLoaded }),
            conveyorSwing: COE_OP4OEData.conveyorSwing,
            operatingVoltage: COE_OP4OEData.operatingVoltage,
            controlVoltSingle: COE_OP4OEData.controlVoltSingle,
            compressedAir: COE_OP4OEData.compressedAir,
            ...(COE_OP4OEData.airSupplyType && { airSupplyType: COE_OP4OEData.airSupplyType }),
            existingMonitor: COE_OP4OEData.existingMonitor,
            newMonitor: COE_OP4OEData.newMonitor,
            templateA_DData: {
                ...(COE_OP4OEData.dcuStatus && { dcuStatus: COE_OP4OEData.dcuStatus }),
                ...(COE_OP4OEData.dcuNum && { dcuNum: COE_OP4OEData.dcuNum }),
                ...(COE_OP4OEData.existingWindows && { existingWindows: COE_OP4OEData.existingWindows }),
                ...(COE_OP4OEData.existingHeadUnit && { existingHeadUnit: COE_OP4OEData.existingHeadUnit }),
                ...(COE_OP4OEData.existingDCU && { existingDCU: COE_OP4OEData.existingDCU }),
                ...(COE_OP4OEData.existingPowerInterface && { existingPowerInterface: COE_OP4OEData.existingPowerInterface }),
                ...(COE_OP4OEData.newReservoir && { newReservoir: COE_OP4OEData.newReservoir }),
                ...(COE_OP4OEData.reservoirSize && { reservoirSize: COE_OP4OEData.reservoirSize }),
                ...(COE_OP4OEData.otherReservoirSize && { otherReservoirSize: COE_OP4OEData.otherReservoirSize }),
                ...(COE_OP4OEData.newReservoirNum && { newReservoirNum: COE_OP4OEData.newReservoirNum }),
                ...(COE_OP4OEData.typeMonitor && { typeMonitor: COE_OP4OEData.typeMonitor }),
                ...(COE_OP4OEData.driveMotorAmp && { driveMotorAmp: COE_OP4OEData.driveMotorAmp }),
                ...(COE_OP4OEData.driveMotorAmpNum && { driveMotorAmpNum: COE_OP4OEData.driveMotorAmpNum }),
                ...(COE_OP4OEData.driveTakeUpAir && { driveTakeUpAir: COE_OP4OEData.driveTakeUpAir }),
                ...(COE_OP4OEData.driveTakeUpAirNum && { driveTakeUpAirNum: COE_OP4OEData.driveTakeUpAirNum }),
                ...(COE_OP4OEData.takeUpDistance && { takeUpDistance: COE_OP4OEData.takeUpDistance }),
                ...(COE_OP4OEData.takeUpDistanceNum && { takeUpDistanceNum: COE_OP4OEData.takeUpDistanceNum }),
                ...(COE_OP4OEData.driveTemp && { driveTemp: COE_OP4OEData.driveTemp }),
                ...(COE_OP4OEData.driveTempNum && { driveTempNum: COE_OP4OEData.driveTempNum }),
                ...(COE_OP4OEData.driveVibration && { driveVibration: COE_OP4OEData.driveVibration }),
                ...(COE_OP4OEData.driveVibrationNum && { driveVibrationNum: COE_OP4OEData.driveVibrationNum }),
                ...(COE_OP4OEData.dogPitch && { dogPitch: COE_OP4OEData.dogPitch }),
                ...(COE_OP4OEData.dogPitchNum && { dogPitchNum: COE_OP4OEData.dogPitchNum }),
                ...(COE_OP4OEData.paintMarker && { paintMarker: COE_OP4OEData.paintMarker }),
                ...(COE_OP4OEData.paintMarkerNum && { paintMarkerNum: COE_OP4OEData.paintMarkerNum }),
                ...(COE_OP4OEData.chainVision && { chainVision: COE_OP4OEData.chainVision }),
                ...(COE_OP4OEData.lubeVision && { lubeVision: COE_OP4OEData.lubeVision }),
                ...(COE_OP4OEData.trolleyVision && { trolleyVision: COE_OP4OEData.trolleyVision }),
                ...(COE_OP4OEData.trolleyDetect && { trolleyDetect: COE_OP4OEData.trolleyDetect }),
                ...(COE_OP4OEData.omniView && { omniView: COE_OP4OEData.omniView }),
                ...(COE_OP4OEData.dcuUpgradeNum && { dcuUpgradeNum: COE_OP4OEData.dcuUpgradeNum }),
                ...(COE_OP4OEData.itNameOne && { itNameOne: COE_OP4OEData.itNameOne }),
                ...(COE_OP4OEData.itIPOne && { itIPOne: COE_OP4OEData.itIPOne }),
                ...(COE_OP4OEData.itGatewayOne && { itGatewayOne: COE_OP4OEData.itGatewayOne }),
                ...(COE_OP4OEData.itSubnetOne && { itSubnetOne: COE_OP4OEData.itSubnetOne }),
                ...(COE_OP4OEData.itDNSOne && { itDNSOne: COE_OP4OEData.itDNSOne }),
                ...(COE_OP4OEData.itSMTPOne && { itSMTPOne: COE_OP4OEData.itSMTPOne }),
                ...(COE_OP4OEData.itNameTwo && { itNameTwo: COE_OP4OEData.itNameTwo }),
                ...(COE_OP4OEData.itIPTwo && { itIPTwo: COE_OP4OEData.itIPTwo }),
                ...(COE_OP4OEData.itGatewayTwo && { itGatewayTwo: COE_OP4OEData.itGatewayTwo }),
                ...(COE_OP4OEData.itSubnetTwo && { itSubnetTwo: COE_OP4OEData.itSubnetTwo }),
                ...(COE_OP4OEData.itDNSTwo && { itDNSTwo: COE_OP4OEData.itDNSTwo }),
                ...(COE_OP4OEData.itSMTPTwo && { itSMTPTwo: COE_OP4OEData.itSMTPTwo }),
                ...(COE_OP4OEData.itNameThree && { itNameThree: COE_OP4OEData.itNameThree }),
                ...(COE_OP4OEData.itIPThree && { itIPThree: COE_OP4OEData.itIPThree }),
                ...(COE_OP4OEData.itGatewayThree && { itGatewayThree: COE_OP4OEData.itGatewayThree }),
                ...(COE_OP4OEData.itSubnetThree && { itSubnetThree: COE_OP4OEData.itSubnetThree }),
                ...(COE_OP4OEData.itDNSThree && { itDNSThree: COE_OP4OEData.itDNSThree }),
                ...(COE_OP4OEData.itSMTPThree && { itSMTPThree: COE_OP4OEData.itSMTPThree }),
                ...(COE_OP4OEData.itAdditionalNotes && { itAdditionalNotes: COE_OP4OEData.itAdditionalNotes }),
                ...(COE_OP4OEData.piuDistance && { piuDistance: COE_OP4OEData.piuDistance }),
                ...(COE_OP4OEData.switchDistance && { switchDistance: COE_OP4OEData.switchDistance }),
                ...(COE_OP4OEData.ampPickup && { ampPickup: COE_OP4OEData.ampPickup }),
                ...(COE_OP4OEData.fromAirTakeUpDistance && { fromAirTakeUpDistance: COE_OP4OEData.fromAirTakeUpDistance }),
                ...(COE_OP4OEData.specialControllerOptions && { specialControllerOptions: COE_OP4OEData.specialControllerOptions }),
                ...(COE_OP4OEData.operatingVoltage && { operatingVoltage: COE_OP4OEData.operatingVoltage })

                },

                lubeBrand: COE_OP4OEData.lubeBrand,
                currentGrease: COE_OP4OEData.currentGrease,
                currentGreaseGrade: COE_OP4OEData.currentGreaseGrade,
                wheelDiameter: COE_OP4OEData.wheelDiameter,
                ...(COE_OP4OEData.chainMaster && { chainMaster: COE_OP4OEData.chainMaster }),
                ...(COE_OP4OEData.remoteStatus && { remoteStatus: COE_OP4OEData.remoteStatus }),
                ...(COE_OP4OEData.mountStatus && { mountStatus: COE_OP4OEData.mountStatus }),
                ...(COE_OP4OEData.otherUnitStatus && { otherUnitStatus: COE_OP4OEData.otherUnitStatus }),
                ...(COE_OP4OEData.timerStatus && { timerStatus: COE_OP4OEData.timerStatus }),
                ...(COE_OP4OEData.electricStatus && { electricStatus: COE_OP4OEData.electricStatus }),
                ...(COE_OP4OEData.mightyLubeMonitoring && { mightyLubeMonitoring: COE_OP4OEData.mightyLubeMonitoring }),
                ...(COE_OP4OEData.preMountType && { preMountType: COE_OP4OEData.preMountType }),
                ...(COE_OP4OEData.otherControllerNotes && { otherControllerNotes: COE_OP4OEData.otherControllerNotes }),


            },


            templateFData: {

                conveyorName: COE_OP4OEData.conveyorName,
                chainSize: COE_OP4OEData.chainSize,
                ...(COE_OP4OEData.otherChainSize && { otherChainSize: COE_OP4OEData.otherChainSize }),
                industrialChainManufacturer: COE_OP4OEData.industrialChainManufacturer,
                ...(COE_OP4OEData.otherChainManufacturer && { otherChainManufacturer: COE_OP4OEData.otherChainManufacturer }),
                wheelManufacturer: COE_OP4OEData.wheelManufacturer,
                ...(COE_OP4OEData.otherWheelManufacturer && { otherWheelManufacturer: COE_OP4OEData.otherWheelManufacturer }),
                conveyorLength: COE_OP4OEData.conveyorLength,
                conveyorLengthUnit: COE_OP4OEData.conveyorLengthUnit,
                brushApplicators: COE_OP4OEData.brushApplicators,
                m12Plugs: COE_OP4OEData.m12Plugs,
                oilStatus: COE_OP4OEData.oilStatus,
                operatingVoltage: COE_OP4OEData.operatingVoltage,
                controlVoltSingle: COE_OP4OEData.controlVoltSingle,

            },


    
            ...(COE_OP4OEData.catDriveStatus && { catDriveStatus: COE_OP4OEData.catDriveStatus }),
            ...(COE_OP4OEData.wheelOpenType && { wheelOpenType: COE_OP4OEData.wheelOpenType }),
            ...(COE_OP4OEData.wheelClosedType && { wheelClosedType: COE_OP4OEData.wheelClosedType }),
            ...(COE_OP4OEData.openStatus && { openStatus: COE_OP4OEData.openStatus }),
            ...(COE_OP4OEData.holeStatus && { holeStatus: COE_OP4OEData.holeStatus }),
            ...(COE_OP4OEData.railLubeStatus && { railLubeStatus: COE_OP4OEData.railLubeStatus }),
            ...(COE_OP4OEData.lubeBrand && { lubeBrand: COE_OP4OEData.lubeBrand }),
            ...(COE_OP4OEData.lubeType && { lubeType: COE_OP4OEData.lubeType }),
            ...(COE_OP4OEData.lubeViscosity && { lubeViscosity: COE_OP4OEData.lubeViscosity }),
            chainMaster: COE_OP4OEData.chainMaster,
            timerStatus: COE_OP4OEData.timerStatus,
            electricStatus: COE_OP4OEData.electricStatus,
            pneumaticStatus: COE_OP4OEData.pneumaticStatus,
            mightyLubeMonitoring: COE_OP4OEData.mightyLubeMonitoring,
            plcConnection: COE_OP4OEData.plcConnection,
            otherControllerInfo: COE_OP4OEData.otherControllerInfo,
            ...(COE_OP4OEData.coeUnitType && { coeUnitType: COE_OP4OEData.coeUnitType }),
            ...(COE_OP4OEData.coeLineA && { coeLineA: COE_OP4OEData.coeLineA }),
            ...(COE_OP4OEData.coeLineG && { coeLineG: COE_OP4OEData.coeLineG }),
            ...(COE_OP4OEData.coeLineH && { coeLineH: COE_OP4OEData.coeLineH }),
            ...(COE_OP4OEData.coeLineJ && { coeLineJ: COE_OP4OEData.coeLineJ }),
            ...(COE_OP4OEData.coeLineX && { coeLineX: COE_OP4OEData.coeLineX }),
            ...(COE_OP4OEData.coeLineY && { coeLineY: COE_OP4OEData.coeLineY }),
            ...(COE_OP4OEData.coeLineZ && { coeLineZ: COE_OP4OEData.coeLineZ }),
        });

        req.user.cart.push({ numRequested, productConfigurationInfo: order, productType: "COE_OP4OE" });
        await req.user.save();

        return res.status(200).json({ message: "COE_OP4OE entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;
