// routes/COE_OP4OE.js
const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const COE_OP4OE = require("../models/COE_OP4OE");
const templateA = require("../models/templateA");
const templateD = require("../models/templateD");
const templateF = require("../models/templateF");


const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { COE_OP4OEData, numRequested } = req.body;

        const order = new COE_OP4OE({
            conveyorName: COE_OP4OEData.conveyorName,
            chainSize: COE_OP4OEData.chainSize,
            ...(COE_OP4OEData.otherChainSize && { otherChainSize: COE_OP4OEData.otherChainSize }),
            industrialChainManufacturer: COE_OP4OEData.industrialChainManufacturer,
            ...(COE_OP4OEData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: COE_OP4OEData.otherIndustrialChainManufacturer }),
            conveyorLength: COE_OP4OEData.conveyorLength,
            conveyorLengthUnit: COE_OP4OEData.conveyorLengthUnit,
            conveyorSpeed: COE_OP4OEData.conveyorSpeed,
            conveyorSpeedUnit: COE_OP4OEData.conveyorSpeedUnit,
            ...(COE_OP4OEData.conveyorIndex && { conveyorIndex: COE_OP4OEData.conveyorIndex }),
            ...(COE_OP4OEData.travelDirection && { travelDirection: COE_OP4OEData.travelDirection }),
            appEnviroment: COE_OP4OEData.appEnviroment,
            ...(COE_OP4OEData.ovenStatus && { ovenStatus: COE_OP4OEData.ovenStatus }),
            ...(COE_OP4OEData.ovenTemp && { ovenTemp: COE_OP4OEData.ovenTemp }),
            ...(COE_OP4OEData.otherAppEnviroment && { otherAppEnviroment: COE_OP4OEData.otherAppEnviroment }),
            ...(COE_OP4OEData.surroundingTemp && { surroundingTemp: COE_OP4OEData.surroundingTemp }),
            ...(COE_OP4OEData.conveyorLoaded && { conveyorLoaded: COE_OP4OEData.conveyorLoaded }),
            ...(COE_OP4OEData.conveyorSwing && { conveyorSwing: COE_OP4OEData.conveyorSwing }),
            ...(COE_OP4OEData.plantLayout && { plantLayout: COE_OP4OEData.plantLayout }),
            ...(COE_OP4OEData.requiredPics && { requiredPics: COE_OP4OEData.requiredPics }),
            operatingVoltage: COE_OP4OEData.operatingVoltage,
            existingMonitor: COE_OP4OEData.existingMonitor,
            newMonitor: COE_OP4OEData.newMonitor,

            monitorData: new templateA({
                ...(COE_OP4OEData.templateA.dcuStatus && { dcuStatus: COE_OP4OEData.templateA.dcuStatus }),
                ...(COE_OP4OEData.templateA.dcuNum && { dcuNum: COE_OP4OEData.templateA.dcuNum }),
                ...(COE_OP4OEData.templateA.existingWindows && { existingWindows: COE_OP4OEData.templateA.existingWindows }),
                ...(COE_OP4OEData.templateA.existingHeadUnit && { existingHeadUnit: COE_OP4OEData.templateA.existingHeadUnit }),
                ...(COE_OP4OEData.templateA.existingDCU && { existingDCU: COE_OP4OEData.templateA.existingDCU }),
                ...(COE_OP4OEData.templateA.existingPowerInterface && { existingPowerInterface: COE_OP4OEData.templateA.existingPowerInterface }),
                ...(COE_OP4OEData.templateA.newReservoir && { newReservoir: COE_OP4OEData.templateA.newReservoir }),
                ...(COE_OP4OEData.templateA.reservoirSize && { reservoirSize: COE_OP4OEData.templateA.reservoirSize }),
                ...(COE_OP4OEData.templateA.otherReservoirSize && { otherReservoirSize: COE_OP4OEData.templateA.otherReservoirSize }),
                ...(COE_OP4OEData.templateA.newReservoirNum && { newReservoirNum: COE_OP4OEData.templateA.newReservoirNum }),
                ...(COE_OP4OEData.templateA.typeMonitor && { typeMonitor: COE_OP4OEData.templateA.typeMonitor }),
                ...(COE_OP4OEData.templateA.driveMotorAmp && { driveMotorAmp: COE_OP4OEData.templateA.driveMotorAmp }),
                ...(COE_OP4OEData.templateA.driveMotorAmpNum && { driveMotorAmpNum: COE_OP4OEData.templateA.driveMotorAmpNum }),
                ...(COE_OP4OEData.templateA.driveTakeUpAir && { driveTakeUpAir: COE_OP4OEData.templateA.driveTakeUpAir }),
                ...(COE_OP4OEData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: COE_OP4OEData.templateA.driveTakeUpAirNum }),
                ...(COE_OP4OEData.templateA.takeUpDistance && { takeUpDistance: COE_OP4OEData.templateA.takeUpDistance }),
                ...(COE_OP4OEData.templateA.takeUpDistanceNum && { takeUpDistanceNum: COE_OP4OEData.templateA.takeUpDistanceNum }),
                ...(COE_OP4OEData.templateA.driveTemp && { driveTemp: COE_OP4OEData.templateA.driveTemp }),
                ...(COE_OP4OEData.templateA.driveTempNum && { driveTempNum: COE_OP4OEData.templateA.driveTempNum }),
                ...(COE_OP4OEData.templateA.driveVibration && { driveVibration: COE_OP4OEData.templateA.driveVibration }),
                ...(COE_OP4OEData.templateA.driveVibrationNum && { driveVibrationNum: COE_OP4OEData.templateA.driveVibrationNum }),
                ...(COE_OP4OEData.templateA.dogPitch && { dogPitch: COE_OP4OEData.templateA.dogPitch }),
                ...(COE_OP4OEData.templateA.dogPitchNum && { dogPitchNum: COE_OP4OEData.templateA.dogPitchNum }),
                ...(COE_OP4OEData.templateA.paintMarker && { paintMarker: COE_OP4OEData.templateA.paintMarker }),
                ...(COE_OP4OEData.templateA.paintMarkerNum && { paintMarkerNum: COE_OP4OEData.templateA.paintMarkerNum }),
                ...(COE_OP4OEData.templateA.chainVision && { chainVision: COE_OP4OEData.templateA.chainVision }),
                ...(COE_OP4OEData.templateA.lubeVision && { lubeVision: COE_OP4OEData.templateA.lubeVision }),
                ...(COE_OP4OEData.templateA.trolleyVision && { trolleyVision: COE_OP4OEData.templateA.trolleyVision }),
                ...(COE_OP4OEData.templateA.trolleyDetect && { trolleyDetect: COE_OP4OEData.templateA.trolleyDetect }),
                ...(COE_OP4OEData.templateA.omniView && { omniView: COE_OP4OEData.templateA.omniView }),
                ...(COE_OP4OEData.templateA.dcuUpgradeNum && { dcuUpgradeNum: COE_OP4OEData.templateA.dcuUpgradeNum }),
                ...(COE_OP4OEData.templateA.itNameOne && { itNameOne: COE_OP4OEData.templateA.itNameOne }),
                ...(COE_OP4OEData.templateA.itIPOne && { itIPOne: COE_OP4OEData.templateA.itIPOne }),
                ...(COE_OP4OEData.templateA.itGatewayOne && { itGatewayOne: COE_OP4OEData.templateA.itGatewayOne }),
                ...(COE_OP4OEData.templateA.itSubnetOne && { itSubnetOne: COE_OP4OEData.templateA.itSubnetOne }),
                ...(COE_OP4OEData.templateA.itDNSOne && { itDNSOne: COE_OP4OEData.templateA.itDNSOne }),
                ...(COE_OP4OEData.templateA.itSMTPOne && { itSMTPOne: COE_OP4OEData.templateA.itSMTPOne }),
                ...(COE_OP4OEData.templateA.itNameTwo && { itNameTwo: COE_OP4OEData.templateA.itNameTwo }),
                ...(COE_OP4OEData.templateA.itIPTwo && { itIPTwo: COE_OP4OEData.templateA.itIPTwo }),
                ...(COE_OP4OEData.templateA.itGatewayTwo && { itGatewayTwo: COE_OP4OEData.templateA.itGatewayTwo }),
                ...(COE_OP4OEData.templateA.itSubnetTwo && { itSubnetTwo: COE_OP4OEData.templateA.itSubnetTwo }),
                ...(COE_OP4OEData.templateA.itDNSTwo && { itDNSTwo: COE_OP4OEData.templateA.itDNSTwo }),
                ...(COE_OP4OEData.templateA.itSMTPTwo && { itSMTPTwo: COE_OP4OEData.templateA.itSMTPTwo }),
                ...(COE_OP4OEData.templateA.itNameThree && { itNameThree: COE_OP4OEData.templateA.itNameThree }),
                ...(COE_OP4OEData.templateA.itIPThree && { itIPThree: COE_OP4OEData.templateA.itIPThree }),
                ...(COE_OP4OEData.templateA.itGatewayThree && { itGatewayThree: COE_OP4OEData.templateA.itGatewayThree }),
                ...(COE_OP4OEData.templateA.itSubnetThree && { itSubnetThree: COE_OP4OEData.templateA.itSubnetThree }),
                ...(COE_OP4OEData.templateA.itDNSThree && { itDNSThree: COE_OP4OEData.templateA.itDNSThree }),
                ...(COE_OP4OEData.templateA.itSMTPThree && { itSMTPThree: COE_OP4OEData.templateA.itSMTPThree }),
                ...(COE_OP4OEData.templateA.itAdditionalNotes && { itAdditionalNotes: COE_OP4OEData.templateA.itAdditionalNotes }),
                ...(COE_OP4OEData.templateA.piuDistance && { piuDistance: COE_OP4OEData.templateA.piuDistance }),
                ...(COE_OP4OEData.templateA.switchDistance && { switchDistance: COE_OP4OEData.templateA.switchDistance }),
                ...(COE_OP4OEData.templateA.ampPickup && { ampPickup: COE_OP4OEData.templateA.ampPickup }),
                ...(COE_OP4OEData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: COE_OP4OEData.templateA.fromAirTakeUpDistance }),
                ...(COE_OP4OEData.templateA.specialControllerOptions && { specialControllerOptions: COE_OP4OEData.templateA.specialControllerOptions }),
                ...(COE_OP4OEData.templateA.operatingVoltage && { operatingVoltage: COE_OP4OEData.templateA.operatingVoltage })

            }),
            wheelSealedChain: COE_OP4OEData.wheelSealedChain,

            templateDData: new templateD({
            conveyorName: COE_OP4OEData.templateD.conveyorName,
            wheelManufacturer: COE_OP4OEData.templateD.wheelManufacturer,
            ...(COE_OP4OEData.templateD.otherWheelManufacturer && { otherWheelManufacturer: COE_OP4OEData.templateD.otherWheelManufacturer }),
            conveyorLength: COE_OP4OEData.templateD.conveyorLength,
            conveyorLengthUnit: COE_OP4OEData.templateD.conveyorLengthUnit,
            chainSize: COE_OP4OEData.templateD.chainSize,
            ...(COE_OP4OEData.templateD.otherChainSize && { otherChainSize: COE_OP4OEData.templateD.otherChainSize }),
            industrialChainManufacturer: COE_OP4OEData.templateD.industrialChainManufacturer,
            ...(COE_OP4OEData.templateD.otherChainManufacturer && { otherChainManufacturer: COE_OP4OEData.templateD.otherChainManufacturer }),
            conveyorSpeed: COE_OP4OEData.templateD.conveyorSpeed,
            conveyorSpeedUnit: COE_OP4OEData.templateD.conveyorSpeedUnit,
            conveyorIndex: COE_OP4OEData.templateD.conveyorIndex,
            appEnviroment: COE_OP4OEData.templateD.appEnviroment,
            ...(COE_OP4OEData.templateD.otherAppEnviroment && { otherAppEnviroment: COE_OP4OEData.templateD.otherAppEnviroment }),
            surroundingTemp: COE_OP4OEData.templateD.surroundingTemp,
            orientationType: COE_OP4OEData.templateD.orientationType,
            ...(COE_OP4OEData.templateD.conveyorLoaded && { conveyorLoaded: COE_OP4OEData.templateD.conveyorLoaded }),
            conveyorSwing: COE_OP4OEData.templateD.conveyorSwing,
            operatingVoltage: COE_OP4OEData.templateD.operatingVoltage,
            controlVoltSingle: COE_OP4OEData.templateD.controlVoltSingle,
            compressedAir: COE_OP4OEData.templateD.compressedAir,
            ...(COE_OP4OEData.templateD.airSupplyType && { airSupplyType: COE_OP4OEData.templateD.airSupplyType }),
            existingMonitor: COE_OP4OEData.templateD.existingMonitor,
            newMonitor: COE_OP4OEData.templateD.newMonitor,
            templateA_DData: new templateA({
                ...(COE_OP4OEData.templateA.dcuStatus && { dcuStatus: COE_OP4OEData.templateA.dcuStatus }),
                ...(COE_OP4OEData.templateA.dcuNum && { dcuNum: COE_OP4OEData.templateA.dcuNum }),
                ...(COE_OP4OEData.templateA.existingWindows && { existingWindows: COE_OP4OEData.templateA.existingWindows }),
                ...(COE_OP4OEData.templateA.existingHeadUnit && { existingHeadUnit: COE_OP4OEData.templateA.existingHeadUnit }),
                ...(COE_OP4OEData.templateA.existingDCU && { existingDCU: COE_OP4OEData.templateA.existingDCU }),
                ...(COE_OP4OEData.templateA.existingPowerInterface && { existingPowerInterface: COE_OP4OEData.templateA.existingPowerInterface }),
                ...(COE_OP4OEData.templateA.newReservoir && { newReservoir: COE_OP4OEData.templateA.newReservoir }),
                ...(COE_OP4OEData.templateA.reservoirSize && { reservoirSize: COE_OP4OEData.templateA.reservoirSize }),
                ...(COE_OP4OEData.templateA.otherReservoirSize && { otherReservoirSize: COE_OP4OEData.templateA.otherReservoirSize }),
                ...(COE_OP4OEData.templateA.newReservoirNum && { newReservoirNum: COE_OP4OEData.templateA.newReservoirNum }),
                ...(COE_OP4OEData.templateA.typeMonitor && { typeMonitor: COE_OP4OEData.templateA.typeMonitor }),
                ...(COE_OP4OEData.templateA.driveMotorAmp && { driveMotorAmp: COE_OP4OEData.templateA.driveMotorAmp }),
                ...(COE_OP4OEData.templateA.driveMotorAmpNum && { driveMotorAmpNum: COE_OP4OEData.templateA.driveMotorAmpNum }),
                ...(COE_OP4OEData.templateA.driveTakeUpAir && { driveTakeUpAir: COE_OP4OEData.templateA.driveTakeUpAir }),
                ...(COE_OP4OEData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: COE_OP4OEData.templateA.driveTakeUpAirNum }),
                ...(COE_OP4OEData.templateA.takeUpDistance && { takeUpDistance: COE_OP4OEData.templateA.takeUpDistance }),
                ...(COE_OP4OEData.templateA.takeUpDistanceNum && { takeUpDistanceNum: COE_OP4OEData.templateA.takeUpDistanceNum }),
                ...(COE_OP4OEData.templateA.driveTemp && { driveTemp: COE_OP4OEData.templateA.driveTemp }),
                ...(COE_OP4OEData.templateA.driveTempNum && { driveTempNum: COE_OP4OEData.templateA.driveTempNum }),
                ...(COE_OP4OEData.templateA.driveVibration && { driveVibration: COE_OP4OEData.templateA.driveVibration }),
                ...(COE_OP4OEData.templateA.driveVibrationNum && { driveVibrationNum: COE_OP4OEData.templateA.driveVibrationNum }),
                ...(COE_OP4OEData.templateA.dogPitch && { dogPitch: COE_OP4OEData.templateA.dogPitch }),
                ...(COE_OP4OEData.templateA.dogPitchNum && { dogPitchNum: COE_OP4OEData.templateA.dogPitchNum }),
                ...(COE_OP4OEData.templateA.paintMarker && { paintMarker: COE_OP4OEData.templateA.paintMarker }),
                ...(COE_OP4OEData.templateA.paintMarkerNum && { paintMarkerNum: COE_OP4OEData.templateA.paintMarkerNum }),
                ...(COE_OP4OEData.templateA.chainVision && { chainVision: COE_OP4OEData.templateA.chainVision }),
                ...(COE_OP4OEData.templateA.lubeVision && { lubeVision: COE_OP4OEData.templateA.lubeVision }),
                ...(COE_OP4OEData.templateA.trolleyVision && { trolleyVision: COE_OP4OEData.templateA.trolleyVision }),
                ...(COE_OP4OEData.templateA.trolleyDetect && { trolleyDetect: COE_OP4OEData.templateA.trolleyDetect }),
                ...(COE_OP4OEData.templateA.omniView && { omniView: COE_OP4OEData.templateA.omniView }),
                ...(COE_OP4OEData.templateA.dcuUpgradeNum && { dcuUpgradeNum: COE_OP4OEData.templateA.dcuUpgradeNum }),
                ...(COE_OP4OEData.templateA.itNameOne && { itNameOne: COE_OP4OEData.templateA.itNameOne }),
                ...(COE_OP4OEData.templateA.itIPOne && { itIPOne: COE_OP4OEData.templateA.itIPOne }),
                ...(COE_OP4OEData.templateA.itGatewayOne && { itGatewayOne: COE_OP4OEData.templateA.itGatewayOne }),
                ...(COE_OP4OEData.templateA.itSubnetOne && { itSubnetOne: COE_OP4OEData.templateA.itSubnetOne }),
                ...(COE_OP4OEData.templateA.itDNSOne && { itDNSOne: COE_OP4OEData.templateA.itDNSOne }),
                ...(COE_OP4OEData.templateA.itSMTPOne && { itSMTPOne: COE_OP4OEData.templateA.itSMTPOne }),
                ...(COE_OP4OEData.templateA.itNameTwo && { itNameTwo: COE_OP4OEData.templateA.itNameTwo }),
                ...(COE_OP4OEData.templateA.itIPTwo && { itIPTwo: COE_OP4OEData.templateA.itIPTwo }),
                ...(COE_OP4OEData.templateA.itGatewayTwo && { itGatewayTwo: COE_OP4OEData.templateA.itGatewayTwo }),
                ...(COE_OP4OEData.templateA.itSubnetTwo && { itSubnetTwo: COE_OP4OEData.templateA.itSubnetTwo }),
                ...(COE_OP4OEData.templateA.itDNSTwo && { itDNSTwo: COE_OP4OEData.templateA.itDNSTwo }),
                ...(COE_OP4OEData.templateA.itSMTPTwo && { itSMTPTwo: COE_OP4OEData.templateA.itSMTPTwo }),
                ...(COE_OP4OEData.templateA.itNameThree && { itNameThree: COE_OP4OEData.templateA.itNameThree }),
                ...(COE_OP4OEData.templateA.itIPThree && { itIPThree: COE_OP4OEData.templateA.itIPThree }),
                ...(COE_OP4OEData.templateA.itGatewayThree && { itGatewayThree: COE_OP4OEData.templateA.itGatewayThree }),
                ...(COE_OP4OEData.templateA.itSubnetThree && { itSubnetThree: COE_OP4OEData.templateA.itSubnetThree }),
                ...(COE_OP4OEData.templateA.itDNSThree && { itDNSThree: COE_OP4OEData.templateA.itDNSThree }),
                ...(COE_OP4OEData.templateA.itSMTPThree && { itSMTPThree: COE_OP4OEData.templateA.itSMTPThree }),
                ...(COE_OP4OEData.templateA.itAdditionalNotes && { itAdditionalNotes: COE_OP4OEData.templateA.itAdditionalNotes }),
                ...(COE_OP4OEData.templateA.piuDistance && { piuDistance: COE_OP4OEData.templateA.piuDistance }),
                ...(COE_OP4OEData.templateA.switchDistance && { switchDistance: COE_OP4OEData.templateA.switchDistance }),
                ...(COE_OP4OEData.templateA.ampPickup && { ampPickup: COE_OP4OEData.templateA.ampPickup }),
                ...(COE_OP4OEData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: COE_OP4OEData.templateA.fromAirTakeUpDistance }),
                ...(COE_OP4OEData.templateA.specialControllerOptions && { specialControllerOptions: COE_OP4OEData.templateA.specialControllerOptions }),
                ...(COE_OP4OEData.templateA.operatingVoltage && { operatingVoltage: COE_OP4OEData.templateA.operatingVoltage })

                }),

                lubeBrand: COE_OP4OEData.templateD.lubeBrand,
                currentGrease: COE_OP4OEData.templateD.currentGrease,
                currentGreaseGrade: COE_OP4OEData.templateD.currentGreaseGrade,
                wheelDiameter: COE_OP4OEData.templateD.wheelDiameter,
                ...(COE_OP4OEData.templateD.chainMaster && { chainMaster: COE_OP4OEData.templateD.chainMaster }),
                ...(COE_OP4OEData.templateD.remoteStatus && { remoteStatus: COE_OP4OEData.templateD.remoteStatus }),
                ...(COE_OP4OEData.templateD.mountStatus && { mountStatus: COE_OP4OEData.templateD.mountStatus }),
                ...(COE_OP4OEData.templateD.otherUnitStatus && { otherUnitStatus: COE_OP4OEData.templateD.otherUnitStatus }),
                ...(COE_OP4OEData.templateD.timerStatus && { timerStatus: COE_OP4OEData.templateD.timerStatus }),
                ...(COE_OP4OEData.templateD.electricStatus && { electricStatus: COE_OP4OEData.templateD.electricStatus }),
                ...(COE_OP4OEData.templateD.mightyLubeMonitoring && { mightyLubeMonitoring: COE_OP4OEData.templateD.mightyLubeMonitoring }),
                ...(COE_OP4OEData.templateD.preMountType && { preMountType: COE_OP4OEData.templateD.preMountType }),
                ...(COE_OP4OEData.templateD.otherControllerNotes && { otherControllerNotes: COE_OP4OEData.templateD.otherControllerNotes }),


            }),


            templateFData: new templateF ({

                conveyorName: COE_OP4OEData.templateF.conveyorName,
                chainSize: COE_OP4OEData.templateF.chainSize,
                ...(COE_OP4OEData.templateF.otherChainSize && { otherChainSize: COE_OP4OEData.templateF.otherChainSize }),
                industrialChainManufacturer: COE_OP4OEData.templateF.industrialChainManufacturer,
                ...(COE_OP4OEData.templateF.otherChainManufacturer && { otherChainManufacturer: COE_OP4OEData.templateF.otherChainManufacturer }),
                wheelManufacturer: COE_OP4OEData.templateF.wheelManufacturer,
                ...(COE_OP4OEData.templateF.otherWheelManufacturer && { otherWheelManufacturer: COE_OP4OEData.templateF.otherWheelManufacturer }),
                conveyorLength: COE_OP4OEData.templateF.conveyorLength,
                conveyorLengthUnit: COE_OP4OEData.templateF.conveyorLengthUnit,
                brushApplicators: COE_OP4OEData.templateF.brushApplicators,
                m12Plugs: COE_OP4OEData.templateF.m12Plugs,
                oilStatus: COE_OP4OEData.templateF.oilStatus,
                operatingVoltage: COE_OP4OEData.templateF.operatingVoltage,
                controlVoltSingle: COE_OP4OEData.templateF.controlVoltSingle,

            }),


    
            ...(COE_OP4OEData.catDriveStatus && { catDriveStatus: COE_OP4OEData.catDriveStatus }),
            ...(COE_OP4OEData.wheelOpenType && { wheelOpenType: COE_OP4OEData.wheelOpenType }),
            ...(COE_OP4OEData.wheelClosedType && { wheelClosedType: COE_OP4OEData.wheelClosedType }),
            ...(COE_OP4OEData.openStatus && { openStatus: COE_OP4OEData.openStatus }),
            ...(COE_OP4OEData.holeStatus && { holeStatus: COE_OP4OEData.holeStatus }),
            ...(COE_OP4OEData.railLubeStatus && { railLubeStatus: COE_OP4OEData.railLubeStatus }),
            ...(COE_OP4OEData.lubeBrand && { lubeBrand: COE_OP4OEData.lubeBrand }),
            ...(COE_OP4OEData.lubeType && { lubeType: COE_OP4OEData.lubeType }),
            ...(COE_OP4OEData.lubeViscosity && { lubeViscosity: COE_OP4OEData.lubeViscosity }),
            chainMaster: COE_OP4OEData.chainMaster,
            timerStatus: COE_OP4OEData.timerStatus,
            electricStatus: COE_OP4OEData.electricStatus,
            pneumaticStatus: COE_OP4OEData.pneumaticStatus,
            mightyLubeMonitoring: COE_OP4OEData.mightyLubeMonitoring,
            plcConnection: COE_OP4OEData.plcConnection,
            otherControllerInfo: COE_OP4OEData.otherControllerInfo,
            ...(COE_OP4OEData.coeUnitType && { coeUnitType: COE_OP4OEData.coeUnitType }),
            ...(COE_OP4OEData.coeLineA && { coeLineA: COE_OP4OEData.coeLineA }),
            ...(COE_OP4OEData.coeLineG && { coeLineG: COE_OP4OEData.coeLineG }),
            ...(COE_OP4OEData.coeLineH && { coeLineH: COE_OP4OEData.coeLineH }),
            ...(COE_OP4OEData.coeLineJ && { coeLineJ: COE_OP4OEData.coeLineJ }),
            ...(COE_OP4OEData.coeLineX && { coeLineX: COE_OP4OEData.coeLineX }),
            ...(COE_OP4OEData.coeLineY && { coeLineY: COE_OP4OEData.coeLineY }),
            ...(COE_OP4OEData.coeLineZ && { coeLineZ: COE_OP4OEData.coeLineZ }),
        });

        req.user.cart.push({ numRequested, productConfigurationInfo: order, productType: "COE_OP4OE" });
        await req.user.save();

        return res.status(200).json({ message: "COE_OP4OE entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;
