const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const ETI_9000INVL = require("../models/ETI_9000INVL");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");
const templateE= require("../models/templateE");
 

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { ETI_9000INVLData, numRequested } = req.body;

        const order = new ETI_9000INVL({
            conveyorName: ETI_9000INVLData.conveyorName,
            industrialChainManufacturer: ETI_9000INVLData.industrialChainManufacturer,
            ...(ETI_9000INVLData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: ETI_9000INVLData.otherIndustrialChainManufacturer }),
            ...(ETI_9000INVLData.conveyorLength && { conveyorLength: ETI_9000INVLData.conveyorLength }),
            ...(ETI_9000INVLData.conveyorLengthUnit && { conveyorLengthUnit: ETI_9000INVLData.conveyorLengthUnit }),
            ...(ETI_9000INVLData.conveyorSpeed && { conveyorSpeed: ETI_9000INVLData.conveyorSpeed }),
            ...(ETI_9000INVLData.conveyorSpeedUnit && { conveyorSpeedUnit: ETI_9000INVLData.conveyorSpeedUnit }),
            ...(ETI_9000INVLData.conveyorIndex && { conveyorIndex: ETI_9000INVLData.conveyorIndex }),
            ...(ETI_9000INVLData.travelDirection && { travelDirection: ETI_9000INVLData.travelDirection }),
            appEnviroment: ETI_9000INVLData.appEnviroment,
            ...(ETI_9000INVLData.ovenStatus && { ovenStatus: ETI_9000INVLData.ovenStatus }),
            ...(ETI_9000INVLData.ovenTemp && { ovenTemp: ETI_9000INVLData.ovenTemp }),
            ...(ETI_9000INVLData.otherAppEnviroment && { otherAppEnviroment: ETI_9000INVLData.otherAppEnviroment }),
            ...(ETI_9000INVLData.surroundingTemp && { surroundingTemp: ETI_9000INVLData.surroundingTemp }),
            ...(ETI_9000INVLData.conveyorLoaded && { conveyorLoaded: ETI_9000INVLData.conveyorLoaded }),
            ...(ETI_9000INVLData.conveyorSwing && { conveyorSwing: ETI_9000INVLData.conveyorSwing }),
            operatingVoltage: ETI_9000INVLData.operatingVoltage,
            monitorData: 
            {
                existingMonitor: ETI_9000INVLData.templateA.existingMonitor,
                newMonitor: ETI_9000INVLData.templateA.newMonitor,		
                ...(ETI_9000INVLData.templateA.dcuStatus && { dcuStatus: ETI_9000INVLData.templateA.dcuStatus }),
                ...(ETI_9000INVLData.templateA.dcuNum && { dcuNum: ETI_9000INVLData.templateA.dcuNum }),
                ...(ETI_9000INVLData.templateA.existingWindows && { existingWindows: ETI_9000INVLData.templateA.existingWindows }),
                ...(ETI_9000INVLData.templateA.existingHeadUnit && { existingHeadUnit: ETI_9000INVLData.templateA.existingHeadUnit }),
                ...(ETI_9000INVLData.templateA.existingDCU && { existingDCU: ETI_9000INVLData.templateA.existingDCU }),
                ...(ETI_9000INVLData.templateA.existingPowerInterface && { existingPowerInterface: ETI_9000INVLData.templateA.existingPowerInterface }),
                ...(ETI_9000INVLData.templateA.newReservoir && { newReservoir: ETI_9000INVLData.templateA.newReservoir }),
                ...(ETI_9000INVLData.templateA.reservoirSize && { reservoirSize: ETI_9000INVLData.templateA.reservoirSize }),
                ...(ETI_9000INVLData.templateA.otherReservoirSize && { otherReservoirSize: ETI_9000INVLData.templateA.otherReservoirSize }),
                ...(ETI_9000INVLData.templateA.newReservoirNum && { newReservoirNum: ETI_9000INVLData.templateA.newReservoirNum }),
                ...(ETI_9000INVLData.templateA.typeMonitor && { typeMonitor: ETI_9000INVLData.templateA.typeMonitor }),
                ...(ETI_9000INVLData.templateA.driveMotorAmp && { driveMotorAmp: ETI_9000INVLData.templateA.driveMotorAmp }),
                ...(ETI_9000INVLData.templateA.driveMotorAmpNum && { driveMotorAmpNum: ETI_9000INVLData.templateA.driveMotorAmpNum }),
                ...(ETI_9000INVLData.templateA.driveTakeUpAir && { driveTakeUpAir: ETI_9000INVLData.templateA.driveTakeUpAir }),
                ...(ETI_9000INVLData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: ETI_9000INVLData.templateA.driveTakeUpAirNum }),
                ...(ETI_9000INVLData.templateA.takeUpDistance && { takeUpDistance: ETI_9000INVLData.templateA.takeUpDistance }),
                ...(ETI_9000INVLData.templateA.takeUpDistanceNum && { takeUpDistanceNum: ETI_9000INVLData.templateA.takeUpDistanceNum }),
                ...(ETI_9000INVLData.templateA.driveTemp && { driveTemp: ETI_9000INVLData.templateA.driveTemp }),
                ...(ETI_9000INVLData.templateA.driveTempNum && { driveTempNum: ETI_9000INVLData.templateA.driveTempNum }),
                ...(ETI_9000INVLData.templateA.driveVibration && { driveVibration: ETI_9000INVLData.templateA.driveVibration }),
                ...(ETI_9000INVLData.templateA.driveVibrationNum && { driveVibrationNum: ETI_9000INVLData.templateA.driveVibrationNum }),
                ...(ETI_9000INVLData.templateA.dogPitch && { dogPitch: ETI_9000INVLData.templateA.dogPitch }),
                ...(ETI_9000INVLData.templateA.dogPitchNum && { dogPitchNum: ETI_9000INVLData.templateA.dogPitchNum }),
                ...(ETI_9000INVLData.templateA.paintMarker && { paintMarker: ETI_9000INVLData.templateA.paintMarker }),
                ...(ETI_9000INVLData.templateA.paintMarkerNum && { paintMarkerNum: ETI_9000INVLData.templateA.paintMarkerNum }),
                ...(ETI_9000INVLData.templateA.chainVision && { chainVision: ETI_9000INVLData.templateA.chainVision }),
                ...(ETI_9000INVLData.templateA.lubeVision && { lubeVision: ETI_9000INVLData.templateA.lubeVision }),
                ...(ETI_9000INVLData.templateA.trolleyVision && { trolleyVision: ETI_9000INVLData.templateA.trolleyVision }),
                ...(ETI_9000INVLData.templateA.trolleyDetect && { trolleyDetect: ETI_9000INVLData.templateA.trolleyDetect }),
                ...(ETI_9000INVLData.templateA.omniView && { omniView: ETI_9000INVLData.templateA.omniView }),
                ...(ETI_9000INVLData.templateA.dcuUpgradeNum && { dcuUpgradeNum: ETI_9000INVLData.templateA.dcuUpgradeNum }),
                ...(ETI_9000INVLData.templateA.piuDistance && { piuDistance: ETI_9000INVLData.templateA.piuDistance }),
                ...(ETI_9000INVLData.templateA.switchDistance && { switchDistance: ETI_9000INVLData.templateA.switchDistance }),
                ...(ETI_9000INVLData.templateA.ampPickup && { ampPickup: ETI_9000INVLData.templateA.ampPickup }),
                ...(ETI_9000INVLData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETI_9000INVLData.templateA.fromAirTakeUpDistance }),
                ...(ETI_9000INVLData.templateA.specialControllerOptions && { specialControllerOptions: ETI_9000INVLData.templateA.specialControllerOptions }),
                ...(ETI_9000INVLData.templateA.operatingVoltage && { operatingVoltage: ETI_9000INVLData.templateA.operatingVoltage })
            },

            addFreeCarrier: ETI_9000INVLData.addFreeCarrier,

            templateBData: 
            {
                
                conveyorName: ETI_9000INVLData.templateB.conveyorName,
                industrialChainManufacturer: ETI_9000INVLData.templateB.industrialChainManufacturer,
                ...(ETI_9000INVLData.templateB.otherChainManufacturer && { otherChainManufacturer: ETI_9000INVLData.templateB.otherChainManufacturer }),
                wheelManufacturer: ETI_9000INVLData.templateB.wheelManufacturer,
                ...(ETI_9000INVLData.templateB.wheelManufacturer && { wheelManufacturer: ETI_9000INVLData.templateB.wheelManufacturer}),
                conveyorSpeed: ETI_9000INVLData.templateB.conveyorSpeed,
                conveyorSpeedUnit: ETI_9000INVLData.templateB.conveyorSpeedUnit,
                conveyorIndex: ETI_9000INVLData.templateB.conveyorIndex,
                ...(ETI_9000INVLData.templateB.travelDirection && { travelDirection: ETI_9000INVLData.templateB.travelDirection}),
                appEnviroment: ETI_9000INVLData.templateB.appEnviroment,
                ...(ETI_9000INVLData.templateB.otherAppEnviroment && { otherAppEnviroment: ETI_9000INVLData.templateB.otherAppEnviroment}),
                surroundingTemp: ETI_9000INVLData.templateB.surroundingTemp,
                orientationType: ETI_9000INVLData.templateB.orientationType,
                operatingVoltage: ETI_9000INVLData.templateB.operatingVoltage,
                controlVoltSingle: ETI_9000INVLData.templateB.controlVoltSingle,
                compressedAir: ETI_9000INVLData.templateB.compressedAir,
                ...(ETI_9000INVLData.templateB.airSupplyType && { airSupplyType: ETI_9000INVLData.templateB.airSupplyType}),

                templateA_BData: {
                    
                    existingMonitor: ETI_9000INVLData.templateA.existingMonitor,
                    newMonitor: ETI_9000INVLData.templateA.newMonitor,		
                    ...(ETI_9000INVLData.templateA.dcuStatus && { dcuStatus: ETI_9000INVLData.templateA.dcuStatus }),
                    ...(ETI_9000INVLData.templateA.dcuNum && { dcuNum: ETI_9000INVLData.templateA.dcuNum }),
                    ...(ETI_9000INVLData.templateA.existingWindows && { existingWindows: ETI_9000INVLData.templateA.existingWindows }),
                    ...(ETI_9000INVLData.templateA.existingHeadUnit && { existingHeadUnit: ETI_9000INVLData.templateA.existingHeadUnit }),
                    ...(ETI_9000INVLData.templateA.existingDCU && { existingDCU: ETI_9000INVLData.templateA.existingDCU }),
                    ...(ETI_9000INVLData.templateA.existingPowerInterface && { existingPowerInterface: ETI_9000INVLData.templateA.existingPowerInterface }),
                    ...(ETI_9000INVLData.templateA.newReservoir && { newReservoir: ETI_9000INVLData.templateA.newReservoir }),
                    ...(ETI_9000INVLData.templateA.reservoirSize && { reservoirSize: ETI_9000INVLData.templateA.reservoirSize }),
                    ...(ETI_9000INVLData.templateA.otherReservoirSize && { otherReservoirSize: ETI_9000INVLData.templateA.otherReservoirSize }),
                    ...(ETI_9000INVLData.templateA.newReservoirNum && { newReservoirNum: ETI_9000INVLData.templateA.newReservoirNum }),
                    ...(ETI_9000INVLData.templateA.typeMonitor && { typeMonitor: ETI_9000INVLData.templateA.typeMonitor }),
                    ...(ETI_9000INVLData.templateA.driveMotorAmp && { driveMotorAmp: ETI_9000INVLData.templateA.driveMotorAmp }),
                    ...(ETI_9000INVLData.templateA.driveMotorAmpNum && { driveMotorAmpNum: ETI_9000INVLData.templateA.driveMotorAmpNum }),
                    ...(ETI_9000INVLData.templateA.driveTakeUpAir && { driveTakeUpAir: ETI_9000INVLData.templateA.driveTakeUpAir }),
                    ...(ETI_9000INVLData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: ETI_9000INVLData.templateA.driveTakeUpAirNum }),
                    ...(ETI_9000INVLData.templateA.takeUpDistance && { takeUpDistance: ETI_9000INVLData.templateA.takeUpDistance }),
                    ...(ETI_9000INVLData.templateA.takeUpDistanceNum && { takeUpDistanceNum: ETI_9000INVLData.templateA.takeUpDistanceNum }),
                    ...(ETI_9000INVLData.templateA.driveTemp && { driveTemp: ETI_9000INVLData.templateA.driveTemp }),
                    ...(ETI_9000INVLData.templateA.driveTempNum && { driveTempNum: ETI_9000INVLData.templateA.driveTempNum }),
                    ...(ETI_9000INVLData.templateA.driveVibration && { driveVibration: ETI_9000INVLData.templateA.driveVibration }),
                    ...(ETI_9000INVLData.templateA.driveVibrationNum && { driveVibrationNum: ETI_9000INVLData.templateA.driveVibrationNum }),
                    ...(ETI_9000INVLData.templateA.dogPitch && { dogPitch: ETI_9000INVLData.templateA.dogPitch }),
                    ...(ETI_9000INVLData.templateA.dogPitchNum && { dogPitchNum: ETI_9000INVLData.templateA.dogPitchNum }),
                    ...(ETI_9000INVLData.templateA.paintMarker && { paintMarker: ETI_9000INVLData.templateA.paintMarker }),
                    ...(ETI_9000INVLData.templateA.paintMarkerNum && { paintMarkerNum: ETI_9000INVLData.templateA.paintMarkerNum }),
                    ...(ETI_9000INVLData.templateA.chainVision && { chainVision: ETI_9000INVLData.templateA.chainVision }),
                    ...(ETI_9000INVLData.templateA.lubeVision && { lubeVision: ETI_9000INVLData.templateA.lubeVision }),
                    ...(ETI_9000INVLData.templateA.trolleyVision && { trolleyVision: ETI_9000INVLData.templateA.trolleyVision }),
                    ...(ETI_9000INVLData.templateA.trolleyDetect && { trolleyDetect: ETI_9000INVLData.templateA.trolleyDetect }),
                    ...(ETI_9000INVLData.templateA.omniView && { omniView: ETI_9000INVLData.templateA.omniView }),
                    ...(ETI_9000INVLData.templateA.dcuUpgradeNum && { dcuUpgradeNum: ETI_9000INVLData.templateA.dcuUpgradeNum }),
                    ...(ETI_9000INVLData.templateA.piuDistance && { piuDistance: ETI_9000INVLData.templateA.piuDistance }),
                    ...(ETI_9000INVLData.templateA.switchDistance && { switchDistance: ETI_9000INVLData.templateA.switchDistance }),
                    ...(ETI_9000INVLData.templateA.ampPickup && { ampPickup: ETI_9000INVLData.templateA.ampPickup }),
                    ...(ETI_9000INVLData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETI_9000INVLData.templateA.fromAirTakeUpDistance }),
                    ...(ETI_9000INVLData.templateA.specialControllerOptions && { specialControllerOptions: ETI_9000INVLData.templateA.specialControllerOptions }),
                    ...(ETI_9000INVLData.templateA.operatingVoltage && { operatingVoltage: ETI_9000INVLData.templateA.operatingVoltage })

                },

                freeWheelStatus: ETI_9000INVLData.templateB.freeWheelStatus,
                actuatorStatus: ETI_9000INVLData.templateB.actuatorStatus,
                ...(ETI_9000INVLData.templateB.pivotStatus && { pivotStatus: ETI_9000INVLData.templateB.pivotStatus}),
                kingPinStatus: ETI_9000INVLData.templateB.kingPinStatus,
                lubeBrand: ETI_9000INVLData.templateB.lubeBrand,
                lubeViscosity: ETI_9000INVLData.templateB.lubeViscosity,
                ...(ETI_9000INVLData.templateB.lubeType && { lubeType: ETI_9000INVLData.templateB.lubeType}),
                currentGrease: ETI_9000INVLData.templateB.currentGrease,
                currentGreaseGrade: ETI_9000INVLData.templateB.currentGreaseGrade,
                zerkDirection: ETI_9000INVLData.templateB.zerkDirection,
                zerkLocationType: ETI_9000INVLData.templateB.zerkLocationType,
                wheelDiameter: ETI_9000INVLData.templateB.wheelDiameter,
                conveyorSwing: ETI_9000INVLData.templateB.conveyorSwing,
                ...(ETI_9000INVLData.templateB.chainMaster && { lubeType: ETI_9000INVLData.templateB.chainMaster}),
                ...(ETI_9000INVLData.templateB.remoteStatus && { lubeType: ETI_9000INVLData.templateB.remoteStatus}),
                ...(ETI_9000INVLData.templateB.mountStatus && { lubeType: ETI_9000INVLData.templateB.mountStatus}),
                ...(ETI_9000INVLData.templateB.otherUnitStatus && { lubeType: ETI_9000INVLData.templateB.otherUnitStatus}),
                ...(ETI_9000INVLData.templateB.timerStatus && { lubeType: ETI_9000INVLData.templateB.timerStatus}),
                ...(ETI_9000INVLData.templateB.electricStatus && { lubeType: ETI_9000INVLData.templateB.electricStatus}),
                ...(ETI_9000INVLData.templateB.mightyLubeMonitoring && { lubeType: ETI_9000INVLData.templateB.mightyLubeMonitoring}),
                ...(ETI_9000INVLData.templateB.preMountType && { lubeType: ETI_9000INVLData.templateB.preMountType}),
                ...(ETI_9000INVLData.templateB.otherPreMountType && { lubeType: ETI_9000INVLData.templateB.otherPreMountType}),
                ...(ETI_9000INVLData.templateB.plcConnection && { lubeType: ETI_9000INVLData.templateB.plcConnection}),
                ...(ETI_9000INVLData.templateB.otherControllerNotes && { lubeType: ETI_9000INVLData.templateB.otherControllerNotes}),
                ...(ETI_9000INVLData.templateB.templateB_UnitType && { lubeType: ETI_9000INVLData_UnitType}),
                ...(ETI_9000INVLData.templateB.templateB_InvertedB && { lubeType: ETI_9000INVLData_InvertedB}),
                ...(ETI_9000INVLData.templateB.templateB_InvertedE && { lubeType: ETI_9000INVLData_InvertedE}),
                ...(ETI_9000INVLData.templateB.templateB_InvertedG && { lubeType: ETI_9000INVLData_InvertedG}),
                ...(ETI_9000INVLData.templateB.templateB_InvertedH && { lubeType: ETI_9000INVLData_InvertedH}),
                ...(ETI_9000INVLData.templateB.templateB_InvertedK && { lubeType: ETI_9000INVLData_InvertedK}),
                ...(ETI_9000INVLData.templateB.templateB_InvertedT && { lubeType: ETI_9000INVLData_InvertedT}),
                ...(ETI_9000INVLData.templateB.templateB_InvertedU && { lubeType: ETI_9000INVLData_InvertedU}),
                ...(ETI_9000INVLData.templateB.templateB_InvertedV && { lubeType: ETI_9000INVLData_InvertedV}),
                ...(ETI_9000INVLData.templateB.templateB_InvertedW && { lubeType: ETI_9000INVLData_InvertedW}),

            },


            templateCData: {
                conveyorName: ETI_9000INVLData.conveyorName,
                industrialChainManufacturer: ETI_9000INVLData.industrialChainManufacturer,
                ...(ETI_9000INVLData.otherChainManufacturer && { otherChainManufacturer: ETI_9000INVLData.otherChainManufacturer }),
                wheelManufacturer: ETI_9000INVLData.wheelManufacturer,
                ...(ETI_9000INVLData.wheelManufacturer && { wheelManufacturer: ETI_9000INVLData.wheelManufacturer}),
                conveyorSpeed: ETI_9000INVLData.conveyorSpeed,
                conveyorSpeedUnit: ETI_9000INVLData.conveyorSpeedUnit,
                conveyorIndex: ETI_9000INVLData.conveyorIndex,
                ...(ETI_9000INVLData.travelDirection && { travelDirection: ETI_9000INVLData.travelDirection}),
                appEnviroment: ETI_9000INVLData.appEnviroment,
                ...(ETI_9000INVLData.otherAppEnviroment && { otherAppEnviroment: ETI_9000INVLData.otherAppEnviroment}),
                surroundingTemp: ETI_9000INVLData.surroundingTemp,
                orientationType: ETI_9000INVLData.orientationType,
                guideWheelsEven: ETI_9000INVLData.guideWheelsEven,
                operatingVoltage: ETI_9000INVLData.operatingVoltage,
                controlVoltSingle: ETI_9000INVLData.controlVoltSingle,
                compressedAir: ETI_9000INVLData.compressedAir,
                ...(ETI_9000INVLData.airSupplyType && { airSupplyType: ETI_9000INVLData.airSupplyType}),
                existingMonitor: ETI_9000INVLData.existingMonitor,
                newMonitor: ETI_9000INVLData.newMonitor,
                templateA_CData: {
                ...(ETI_9000INVLData.dcuStatus && { dcuStatus: ETI_9000INVLData.dcuStatus }),
                ...(ETI_9000INVLData.dcuNum && { dcuNum: ETI_9000INVLData.dcuNum }),
                ...(ETI_9000INVLData.existingWindows && { existingWindows: ETI_9000INVLData.existingWindows }),
                ...(ETI_9000INVLData.existingHeadUnit && { existingHeadUnit: ETI_9000INVLData.existingHeadUnit }),
                ...(ETI_9000INVLData.existingDCU && { existingDCU: ETI_9000INVLData.existingDCU }),
                ...(ETI_9000INVLData.existingPowerInterface && { existingPowerInterface: ETI_9000INVLData.existingPowerInterface }),
                ...(ETI_9000INVLData.newReservoir && { newReservoir: ETI_9000INVLData.newReservoir }),
                ...(ETI_9000INVLData.reservoirSize && { reservoirSize: ETI_9000INVLData.reservoirSize }),
                ...(ETI_9000INVLData.otherReservoirSize && { otherReservoirSize: ETI_9000INVLData.otherReservoirSize }),
                ...(ETI_9000INVLData.newReservoirNum && { newReservoirNum: ETI_9000INVLData.newReservoirNum }),
                ...(ETI_9000INVLData.typeMonitor && { typeMonitor: ETI_9000INVLData.typeMonitor }),
                ...(ETI_9000INVLData.driveMotorAmp && { driveMotorAmp: ETI_9000INVLData.driveMotorAmp }),
                ...(ETI_9000INVLData.driveMotorAmpNum && { driveMotorAmpNum: ETI_9000INVLData.driveMotorAmpNum }),
                ...(ETI_9000INVLData.driveTakeUpAir && { driveTakeUpAir: ETI_9000INVLData.driveTakeUpAir }),
                ...(ETI_9000INVLData.driveTakeUpAirNum && { driveTakeUpAirNum: ETI_9000INVLData.driveTakeUpAirNum }),
                ...(ETI_9000INVLData.takeUpDistance && { takeUpDistance: ETI_9000INVLData.takeUpDistance }),
                ...(ETI_9000INVLData.takeUpDistanceNum && { takeUpDistanceNum: ETI_9000INVLData.takeUpDistanceNum }),
                ...(ETI_9000INVLData.driveTemp && { driveTemp: ETI_9000INVLData.driveTemp }),
                ...(ETI_9000INVLData.driveTempNum && { driveTempNum: ETI_9000INVLData.driveTempNum }),
                ...(ETI_9000INVLData.driveVibration && { driveVibration: ETI_9000INVLData.driveVibration }),
                ...(ETI_9000INVLData.driveVibrationNum && { driveVibrationNum: ETI_9000INVLData.driveVibrationNum }),
                ...(ETI_9000INVLData.dogPitch && { dogPitch: ETI_9000INVLData.dogPitch }),
                ...(ETI_9000INVLData.dogPitchNum && { dogPitchNum: ETI_9000INVLData.dogPitchNum }),
                ...(ETI_9000INVLData.paintMarker && { paintMarker: ETI_9000INVLData.paintMarker }),
                ...(ETI_9000INVLData.paintMarkerNum && { paintMarkerNum: ETI_9000INVLData.paintMarkerNum }),
                ...(ETI_9000INVLData.chainVision && { chainVision: ETI_9000INVLData.chainVision }),
                ...(ETI_9000INVLData.lubeVision && { lubeVision: ETI_9000INVLData.lubeVision }),
                ...(ETI_9000INVLData.trolleyVision && { trolleyVision: ETI_9000INVLData.trolleyVision }),
                ...(ETI_9000INVLData.trolleyDetect && { trolleyDetect: ETI_9000INVLData.trolleyDetect }),
                ...(ETI_9000INVLData.omniView && { omniView: ETI_9000INVLData.omniView }),
                ...(ETI_9000INVLData.dcuUpgradeNum && { dcuUpgradeNum: ETI_9000INVLData.dcuUpgradeNum }),
                ...(ETI_9000INVLData.itNameOne && { itNameOne: ETI_9000INVLData.itNameOne }),
                ...(ETI_9000INVLData.itIPOne && { itIPOne: ETI_9000INVLData.itIPOne }),
                ...(ETI_9000INVLData.itGatewayOne && { itGatewayOne: ETI_9000INVLData.itGatewayOne }),
                ...(ETI_9000INVLData.itSubnetOne && { itSubnetOne: ETI_9000INVLData.itSubnetOne }),
                ...(ETI_9000INVLData.itDNSOne && { itDNSOne: ETI_9000INVLData.itDNSOne }),
                ...(ETI_9000INVLData.itSMTPOne && { itSMTPOne: ETI_9000INVLData.itSMTPOne }),
                ...(ETI_9000INVLData.itNameTwo && { itNameTwo: ETI_9000INVLData.itNameTwo }),
                ...(ETI_9000INVLData.itIPTwo && { itIPTwo: ETI_9000INVLData.itIPTwo }),
                ...(ETI_9000INVLData.itGatewayTwo && { itGatewayTwo: ETI_9000INVLData.itGatewayTwo }),
                ...(ETI_9000INVLData.itSubnetTwo && { itSubnetTwo: ETI_9000INVLData.itSubnetTwo }),
                ...(ETI_9000INVLData.itDNSTwo && { itDNSTwo: ETI_9000INVLData.itDNSTwo }),
                ...(ETI_9000INVLData.itSMTPTwo && { itSMTPTwo: ETI_9000INVLData.itSMTPTwo }),
                ...(ETI_9000INVLData.itNameThree && { itNameThree: ETI_9000INVLData.itNameThree }),
                ...(ETI_9000INVLData.itIPThree && { itIPThree: ETI_9000INVLData.itIPThree }),
                ...(ETI_9000INVLData.itGatewayThree && { itGatewayThree: ETI_9000INVLData.itGatewayThree }),
                ...(ETI_9000INVLData.itSubnetThree && { itSubnetThree: ETI_9000INVLData.itSubnetThree }),
                ...(ETI_9000INVLData.itDNSThree && { itDNSThree: ETI_9000INVLData.itDNSThree }),
                ...(ETI_9000INVLData.itSMTPThree && { itSMTPThree: ETI_9000INVLData.itSMTPThree }),
                ...(ETI_9000INVLData.itAdditionalNotes && { itAdditionalNotes: ETI_9000INVLData.itAdditionalNotes }),
                ...(ETI_9000INVLData.piuDistance && { piuDistance: ETI_9000INVLData.piuDistance }),
                ...(ETI_9000INVLData.switchDistance && { switchDistance: ETI_9000INVLData.switchDistance }),
                ...(ETI_9000INVLData.ampPickup && { ampPickup: ETI_9000INVLData.ampPickup }),
                ...(ETI_9000INVLData.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETI_9000INVLData.fromAirTakeUpDistance }),
                ...(ETI_9000INVLData.specialControllerOptions && { specialControllerOptions: ETI_9000INVLData.specialControllerOptions }),
                ...(ETI_9000INVLData.operatingVoltage && { operatingVoltage: ETI_9000INVLData.operatingVoltage })

                },
                freeWheelStatus: ETI_9000INVLData.freeWheelStatus,
                actuatorStatus: ETI_9000INVLData.actuatorStatus,
                ...(ETI_9000INVLData.pivotStatus && { pivotStatus: ETI_9000INVLData.pivotStatus}),
                kingPinStatus: ETI_9000INVLData.kingPinStatus,
                lubeBrand: ETI_9000INVLData.lubeBrand,
                lubeViscosity: ETI_9000INVLData.lubeViscosity,
                ...(ETI_9000INVLData.lubeType && { lubeType: ETI_9000INVLData.lubeType}),
                currentGrease: ETI_9000INVLData.currentGrease,
                currentGreaseGrade: ETI_9000INVLData.currentGreaseGrade,
                zerkDirection: ETI_9000INVLData.zerkDirection,
                zerkLocationType: ETI_9000INVLData.zerkLocationType,
                wheelDiameter: ETI_9000INVLData.wheelDiameter,
                conveyorSwing: ETI_9000INVLData.conveyorSwing,
                ...(ETI_9000INVLData.chainMaster && { lubeType: ETI_9000INVLData.chainMaster}),
                ...(ETI_9000INVLData.remoteStatus && { lubeType: ETI_9000INVLData.remoteStatus}),
                ...(ETI_9000INVLData.mountStatus && { lubeType: ETI_9000INVLData.mountStatus}),
                ...(ETI_9000INVLData.otherUnitStatus && { lubeType: ETI_9000INVLData.otherUnitStatus}),
                ...(ETI_9000INVLData.timerStatus && { lubeType: ETI_9000INVLData.timerStatus}),
                ...(ETI_9000INVLData.electricStatus && { lubeType: ETI_9000INVLData.electricStatus}),
                ...(ETI_9000INVLData.mightyLubeMonitoring && { lubeType: ETI_9000INVLData.mightyLubeMonitoring}),
                ...(ETI_9000INVLData.preMountType && { lubeType: ETI_9000INVLData.preMountType}),
                ...(ETI_9000INVLData.otherPreMountType && { lubeType: ETI_9000INVLData.otherPreMountType}),
                ...(ETI_9000INVLData.plcConnection && { lubeType: ETI_9000INVLData.plcConnection}),
                ...(ETI_9000INVLData.otherControllerNotes && { lubeType: ETI_9000INVLData.otherControllerNotes}),
                ...(ETI_9000INVLData.templateC_UnitType && { lubeType: ETI_9000INVLData.templateC_UnitType}),
                templateC_InvertedA: ETI_9000INVLData.templateC_InvertedA,
                templateC_InvertedB: ETI_9000INVLData.templateC_InvertedB,
                templateC_InvertedE: ETI_9000INVLData.templateC_InvertedE,
                templateC_InvertedS: ETI_9000INVLData.templateC_InvertedS,
            },

            catDriveStatus: ETI_9000INVLData.catDriveStatus,


            templateEData: 
            {
                conveyorName: ETI_9000INVLData.templateE.conveyorName,
                ...(ETI_9000INVLData.templateE.chainSize && { chainSize: ETI_9000INVLData.templateE.chainSize }),
                ...(ETI_9000INVLData.templateE.otherChainSize && { otherChainSize: ETI_9000INVLData.templateE.otherChainSize }),
                ...(ETI_9000INVLData.templateE.industrialChainManufacturer && { industrialChainManufacturer: ETI_9000INVLData.templateE.industrialChainManufacturer }),
                ...(ETI_9000INVLData.templateE.otherChainManufacturer && { otherChainManufacturer: ETI_9000INVLData.templateE.otherChainManufacturer }),
                ...(ETI_9000INVLData.templateE.conveyorLength && { conveyorLength: ETI_9000INVLData.templateE.conveyorLength }),
                ...(ETI_9000INVLData.templateE.conveyorLengthUnit && { conveyorLengthUnit: ETI_9000INVLData.templateE.conveyorLengthUnit }),
                ...(ETI_9000INVLData.templateE.appEnviroment && { appEnviroment: ETI_9000INVLData.templateE.appEnviroment }),
                ...(ETI_9000INVLData.templateE.otherAppEnviroment && { otherAppEnviroment: ETI_9000INVLData.templateE.otherAppEnviroment }),
                ...(ETI_9000INVLData.templateE.lubeBrand && { lubeBrand: ETI_9000INVLData.templateE.lubeBrand }),
                ...(ETI_9000INVLData.templateE.lubeType && { lubeType: ETI_9000INVLData.templateE.lubeType }),
                ...(ETI_9000INVLData.templateE.lubeViscosity && { lubeViscosity: ETI_9000INVLData.templateE.lubeViscosity }),
                ...(ETI_9000INVLData.templateE.specialControllerOptions && { specialControllerOptions: ETI_9000INVLData.templateE.specialControllerOptions }),
                ...(ETI_9000INVLData.templateE.wireMeasurementUnit && { wireMeasurementUnit: ETI_9000INVLData.templateE.wireMeasurementUnit }),
                ...(ETI_9000INVLData.templateE.conductor2 && { conductor2: ETI_9000INVLData.templateE.conductor2 }),
                ...(ETI_9000INVLData.templateE.conductor4 && { conductor4: ETI_9000INVLData.templateE.conductor4 }),
                ...(ETI_9000INVLData.templateE.conductor7 && { conductor7: ETI_9000INVLData.templateE.conductor7 }),
                ...(ETI_9000INVLData.templateE.conductor12 && { conductor12: ETI_9000INVLData.templateE.conductor12 }),
                ...(ETI_9000INVLData.templateE.junctionBoxNum && { junctionBoxNum: ETI_9000INVLData.templateE.junctionBoxNum }),

            },
            
            ...(ETI_9000INVLData.catDriveNum && { catDriveNum: ETI_9000INVLData.catDriveNum }),
            ...(ETI_9000INVLData.externalLubeStatus && { externalLubeStatus: ETI_9000INVLData.externalLubeStatus }),
            ...(ETI_9000INVLData.lubeBrand && { lubeBrand: ETI_9000INVLData.lubeBrand }),
            ...(ETI_9000INVLData.lubeType && { lubeType: ETI_9000INVLData.lubeType }),
            ...(ETI_9000INVLData.lubeViscosity && { lubeViscosity: ETI_9000INVLData.lubeViscosity }),
            ...(ETI_9000INVLData.sideLubeStatus && { sideLubeStatus: ETI_9000INVLData.sideLubeStatus }),
            ...(ETI_9000INVLData.chainCleanStatus && { chainCleanStatus: ETI_9000INVLData.chainCleanStatus }),
            ...(ETI_9000INVLData.mightyLubeMonitoring && { mightyLubeMonitoring: ETI_9000INVLData.mightyLubeMonitoring }),
            ...(ETI_9000INVLData.ctrStatus && { ctrStatus: ETI_9000INVLData.ctrStatus }),
            ...(ETI_9000INVLData.plcConnection && { plcConnection: ETI_9000INVLData.plcConnection }),
            ...(ETI_9000INVLData.monitorControlStatus && { monitorControlStatus: ETI_9000INVLData.monitorControlStatus }),
            ...(ETI_9000INVLData.otherControllerInfo && { otherControllerInfo: ETI_9000INVLData.otherControllerInfo }),
            ...(ETI_9000INVLData.wireMeasurementUnit && { wireMeasurementUnit: ETI_9000INVLData.wireMeasurementUnit }),
            ...(ETI_9000INVLData.conductor2 && { conductor2: ETI_9000INVLData.conductor2 }),
            ...(ETI_9000INVLData.conductor4 && { conductor4: ETI_9000INVLData.conductor4 }),
            ...(ETI_9000INVLData.conductor7 && { conductor7: ETI_9000INVLData.conductor7 }),
            ...(ETI_9000INVLData.conductor12 && { conductor12: ETI_9000INVLData.conductor12 }),
            ...(ETI_9000INVLData.junctionBoxNum && { junctionBoxNum: ETI_9000INVLData.junctionBoxNum }),
            ...(ETI_9000INVLData.enclosedUnitType && { enclosedUnitType: ETI_9000INVLData.enclosedUnitType }),
            ...(ETI_9000INVLData.enclosedTrackB && { enclosedTrackB: ETI_9000INVLData.enclosedTrackB }),
            ...(ETI_9000INVLData.enclosedTrackG && { enclosedTrackG: ETI_9000INVLData.enclosedTrackG }),
            ...(ETI_9000INVLData.enclosedTrackH && { enclosedTrackH: ETI_9000INVLData.enclosedTrackH }),
            ...(ETI_9000INVLData.enclosedTrackS && { enclosedTrackS: ETI_9000INVLData.enclosedTrackS }),
            ...(ETI_9000INVLData.enclosedTrackK2 && { enclosedTrackK2: ETI_9000INVLData.enclosedTrackK2 }),
            ...(ETI_9000INVLData.enclosedTrackL2 && { enclosedTrackL2: ETI_9000INVLData.enclosedTrackL2 }),
            ...(ETI_9000INVLData.enclosedTrackM2 && { enclosedTrackM2: ETI_9000INVLData.enclosedTrackM2 }),
            ...(ETI_9000INVLData.enclosedTrackN2 && { enclosedTrackN2: ETI_9000INVLData.enclosedTrackN2 }),
            ...(ETI_9000INVLData.enclosedTrackS2 && { enclosedTrackS2: ETI_9000INVLData.enclosedTrackS2 }),
        });

        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "ETI_9000INVL"
        });
        await req.user.save();

        return res.status(200).json({ message: "ETI_9000INVL entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;
