const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const ETI_OP48E = require("../models/ETI_OP48E");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");
const templateF= require("../models/templateF"); 

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { ETI_OP48EData, numRequested } = req.body;
        const order = new ETI_OP48E({
            ...(ETI_OP48EData.chainSize && { chainSize: ETI_OP48EData.chainSize }),
            ...(ETI_OP48EData.otherChainSize && { otherChainSize: ETI_OP48EData.otherChainSize }),            
            industrialChainManufacturer: ETI_OP48EData.industrialChainManufacturer,
            ...(ETI_OP48EData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: ETI_OP48EData.otherIndustrialChainManufacturer }),
            ...(ETI_OP48EData.conveyorLength && { conveyorLength: ETI_OP48EData.conveyorLength }),
            ...(ETI_OP48EData.conveyorLengthUnit && { conveyorLengthUnit: ETI_OP48EData.conveyorLengthUnit }),
            ...(ETI_OP48EData.conveyorSpeed && { conveyorSpeed: ETI_OP48EData.conveyorSpeed }),
            ...(ETI_OP48EData.conveyorSpeedUnit && { conveyorSpeedUnit: ETI_OP48EData.conveyorSpeedUnit }),
            ...(ETI_OP48EData.conveyorIndex && { conveyorIndex: ETI_OP48EData.conveyorIndex }),
            ...(ETI_OP48EData.travelDirection && { travelDirection: ETI_OP48EData.travelDirection }),
            appEnviroment: ETI_OP48EData.appEnviroment,
            ...(ETI_OP48EData.ovenStatus && { ovenStatus: ETI_OP48EData.ovenStatus }),
            ...(ETI_OP48EData.ovenTemp && { ovenTemp: ETI_OP48EData.ovenTemp }),
            ...(ETI_OP48EData.otherAppEnviroment && { otherAppEnviroment: ETI_OP48EData.otherAppEnviroment }),
            ...(ETI_OP48EData.surroundingTemp && { surroundingTemp: ETI_OP48EData.surroundingTemp }),
            ...(ETI_OP48EData.conveyorLoaded && { conveyorLoaded: ETI_OP48EData.conveyorLoaded }),
            ...(ETI_OP48EData.conveyorSwing && { conveyorSwing: ETI_OP48EData.conveyorSwing }),

            operatingVoltage: ETI_OP48EData.operatingVoltage,
            controlVoltage: ETI_OP48EData.controlVoltage,


            existingMonitor: ETI_OP48EData.existingMonitor,
            newMonitor: ETI_OP48EData.newMonitor,
            monitorData: {
                ...(ETI_OP48EData.dcuStatus && { dcuStatus: ETI_OP48EData.dcuStatus }),
                ...(ETI_OP48EData.dcuNum && { dcuNum: ETI_OP48EData.dcuNum }),
                ...(ETI_OP48EData.existingWindows && { existingWindows: ETI_OP48EData.existingWindows }),
                ...(ETI_OP48EData.existingHeadUnit && { existingHeadUnit: ETI_OP48EData.existingHeadUnit }),
                ...(ETI_OP48EData.existingDCU && { existingDCU: ETI_OP48EData.existingDCU }),
                ...(ETI_OP48EData.existingPowerInterface && { existingPowerInterface: ETI_OP48EData.existingPowerInterface }),
                ...(ETI_OP48EData.newReservoir && { newReservoir: ETI_OP48EData.newReservoir }),
                ...(ETI_OP48EData.reservoirSize && { reservoirSize: ETI_OP48EData.reservoirSize }),
                ...(ETI_OP48EData.otherReservoirSize && { otherReservoirSize: ETI_OP48EData.otherReservoirSize }),
                ...(ETI_OP48EData.newReservoirNum && { newReservoirNum: ETI_OP48EData.newReservoirNum }),
                ...(ETI_OP48EData.typeMonitor && { typeMonitor: ETI_OP48EData.typeMonitor }),
                ...(ETI_OP48EData.driveMotorAmp && { driveMotorAmp: ETI_OP48EData.driveMotorAmp }),
                ...(ETI_OP48EData.driveMotorAmpNum && { driveMotorAmpNum: ETI_OP48EData.driveMotorAmpNum }),
                ...(ETI_OP48EData.driveTakeUpAir && { driveTakeUpAir: ETI_OP48EData.driveTakeUpAir }),
                ...(ETI_OP48EData.driveTakeUpAirNum && { driveTakeUpAirNum: ETI_OP48EData.driveTakeUpAirNum }),
                ...(ETI_OP48EData.takeUpDistance && { takeUpDistance: ETI_OP48EData.takeUpDistance }),
                ...(ETI_OP48EData.takeUpDistanceNum && { takeUpDistanceNum: ETI_OP48EData.takeUpDistanceNum }),
                ...(ETI_OP48EData.driveTemp && { driveTemp: ETI_OP48EData.driveTemp }),
                ...(ETI_OP48EData.driveTempNum && { driveTempNum: ETI_OP48EData.driveTempNum }),
                ...(ETI_OP48EData.driveVibration && { driveVibration: ETI_OP48EData.driveVibration }),
                ...(ETI_OP48EData.driveVibrationNum && { driveVibrationNum: ETI_OP48EData.driveVibrationNum }),
                ...(ETI_OP48EData.dogPitch && { dogPitch: ETI_OP48EData.dogPitch }),
                ...(ETI_OP48EData.dogPitchNum && { dogPitchNum: ETI_OP48EData.dogPitchNum }),
                ...(ETI_OP48EData.paintMarker && { paintMarker: ETI_OP48EData.paintMarker }),
                ...(ETI_OP48EData.paintMarkerNum && { paintMarkerNum: ETI_OP48EData.paintMarkerNum }),
                ...(ETI_OP48EData.chainVision && { chainVision: ETI_OP48EData.chainVision }),
                ...(ETI_OP48EData.lubeVision && { lubeVision: ETI_OP48EData.lubeVision }),
                ...(ETI_OP48EData.trolleyVision && { trolleyVision: ETI_OP48EData.trolleyVision }),
                ...(ETI_OP48EData.trolleyDetect && { trolleyDetect: ETI_OP48EData.trolleyDetect }),
                ...(ETI_OP48EData.omniView && { omniView: ETI_OP48EData.omniView }),
                ...(ETI_OP48EData.dcuUpgradeNum && { dcuUpgradeNum: ETI_OP48EData.dcuUpgradeNum }),
                ...(ETI_OP48EData.itNameOne && { itNameOne: ETI_OP48EData.itNameOne }),
                ...(ETI_OP48EData.itIPOne && { itIPOne: ETI_OP48EData.itIPOne }),
                ...(ETI_OP48EData.itGatewayOne && { itGatewayOne: ETI_OP48EData.itGatewayOne }),
                ...(ETI_OP48EData.itSubnetOne && { itSubnetOne: ETI_OP48EData.itSubnetOne }),
                ...(ETI_OP48EData.itDNSOne && { itDNSOne: ETI_OP48EData.itDNSOne }),
                ...(ETI_OP48EData.itSMTPOne && { itSMTPOne: ETI_OP48EData.itSMTPOne }),
                ...(ETI_OP48EData.itNameTwo && { itNameTwo: ETI_OP48EData.itNameTwo }),
                ...(ETI_OP48EData.itIPTwo && { itIPTwo: ETI_OP48EData.itIPTwo }),
                ...(ETI_OP48EData.itGatewayTwo && { itGatewayTwo: ETI_OP48EData.itGatewayTwo }),
                ...(ETI_OP48EData.itSubnetTwo && { itSubnetTwo: ETI_OP48EData.itSubnetTwo }),
                ...(ETI_OP48EData.itDNSTwo && { itDNSTwo: ETI_OP48EData.itDNSTwo }),
                ...(ETI_OP48EData.itSMTPTwo && { itSMTPTwo: ETI_OP48EData.itSMTPTwo }),
                ...(ETI_OP48EData.itNameThree && { itNameThree: ETI_OP48EData.itNameThree }),
                ...(ETI_OP48EData.itIPThree && { itIPThree: ETI_OP48EData.itIPThree }),
                ...(ETI_OP48EData.itGatewayThree && { itGatewayThree: ETI_OP48EData.itGatewayThree }),
                ...(ETI_OP48EData.itSubnetThree && { itSubnetThree: ETI_OP48EData.itSubnetThree }),
                ...(ETI_OP48EData.itDNSThree && { itDNSThree: ETI_OP48EData.itDNSThree }),
                ...(ETI_OP48EData.itSMTPThree && { itSMTPThree: ETI_OP48EData.itSMTPThree }),
                ...(ETI_OP48EData.itAdditionalNotes && { itAdditionalNotes: ETI_OP48EData.itAdditionalNotes }),
                ...(ETI_OP48EData.piuDistance && { piuDistance: ETI_OP48EData.piuDistance }),
                ...(ETI_OP48EData.switchDistance && { switchDistance: ETI_OP48EData.switchDistance }),
                ...(ETI_OP48EData.ampPickup && { ampPickup: ETI_OP48EData.ampPickup }),
                ...(ETI_OP48EData.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETI_OP48EData.fromAirTakeUpDistance }),
                ...(ETI_OP48EData.specialControllerOptions && { specialControllerOptions: ETI_OP48EData.specialControllerOptions }),
                ...(ETI_OP48EData.operatingVoltage && { operatingVoltage: ETI_OP48EData.operatingVoltage })

            },

            addFreeCarrier: ETI_OP48EData.addFreeCarrier,

            templateBData: {
                conveyorName: ETI_OP48EData.conveyorName,
                industrialChainManufacturer: ETI_OP48EData.industrialChainManufacturer,
                ...(ETI_OP48EData.otherChainManufacturer && { otherChainManufacturer: ETI_OP48EData.otherChainManufacturer }),
                wheelManufacturer: ETI_OP48EData.wheelManufacturer,
                ...(ETI_OP48EData.wheelManufacturer && { wheelManufacturer: ETI_OP48EData.wheelManufacturer}),
                conveyorSpeed: ETI_OP48EData.conveyorSpeed,
                conveyorSpeedUnit: ETI_OP48EData.conveyorSpeedUnit,
                conveyorIndex: ETI_OP48EData.conveyorIndex,
                ...(ETI_OP48EData.travelDirection && { travelDirection: ETI_OP48EData.travelDirection}),
                appEnviroment: ETI_OP48EData.appEnviroment,
                ...(ETI_OP48EData.otherAppEnviroment && { otherAppEnviroment: ETI_OP48EData.otherAppEnviroment}),
                surroundingTemp: ETI_OP48EData.surroundingTemp,
                orientationType: ETI_OP48EData.orientationType,
                operatingVoltage: ETI_OP48EData.operatingVoltage,
                controlVoltSingle: ETI_OP48EData.controlVoltSingle,
                compressedAir: ETI_OP48EData.compressedAir,
                ...(ETI_OP48EData.airSupplyType && { airSupplyType: ETI_OP48EData.airSupplyType}),
            existingMonitor: ETI_OP48EData.existingMonitor,
            newMonitor: ETI_OP48EData.newMonitor,
            templateA_BData: {
                ...(ETI_OP48EData.dcuStatus && { dcuStatus: ETI_OP48EData.dcuStatus }),
                ...(ETI_OP48EData.dcuNum && { dcuNum: ETI_OP48EData.dcuNum }),
                ...(ETI_OP48EData.existingWindows && { existingWindows: ETI_OP48EData.existingWindows }),
                ...(ETI_OP48EData.existingHeadUnit && { existingHeadUnit: ETI_OP48EData.existingHeadUnit }),
                ...(ETI_OP48EData.existingDCU && { existingDCU: ETI_OP48EData.existingDCU }),
                ...(ETI_OP48EData.existingPowerInterface && { existingPowerInterface: ETI_OP48EData.existingPowerInterface }),
                ...(ETI_OP48EData.newReservoir && { newReservoir: ETI_OP48EData.newReservoir }),
                ...(ETI_OP48EData.reservoirSize && { reservoirSize: ETI_OP48EData.reservoirSize }),
                ...(ETI_OP48EData.otherReservoirSize && { otherReservoirSize: ETI_OP48EData.otherReservoirSize }),
                ...(ETI_OP48EData.newReservoirNum && { newReservoirNum: ETI_OP48EData.newReservoirNum }),
                ...(ETI_OP48EData.typeMonitor && { typeMonitor: ETI_OP48EData.typeMonitor }),
                ...(ETI_OP48EData.driveMotorAmp && { driveMotorAmp: ETI_OP48EData.driveMotorAmp }),
                ...(ETI_OP48EData.driveMotorAmpNum && { driveMotorAmpNum: ETI_OP48EData.driveMotorAmpNum }),
                ...(ETI_OP48EData.driveTakeUpAir && { driveTakeUpAir: ETI_OP48EData.driveTakeUpAir }),
                ...(ETI_OP48EData.driveTakeUpAirNum && { driveTakeUpAirNum: ETI_OP48EData.driveTakeUpAirNum }),
                ...(ETI_OP48EData.takeUpDistance && { takeUpDistance: ETI_OP48EData.takeUpDistance }),
                ...(ETI_OP48EData.takeUpDistanceNum && { takeUpDistanceNum: ETI_OP48EData.takeUpDistanceNum }),
                ...(ETI_OP48EData.driveTemp && { driveTemp: ETI_OP48EData.driveTemp }),
                ...(ETI_OP48EData.driveTempNum && { driveTempNum: ETI_OP48EData.driveTempNum }),
                ...(ETI_OP48EData.driveVibration && { driveVibration: ETI_OP48EData.driveVibration }),
                ...(ETI_OP48EData.driveVibrationNum && { driveVibrationNum: ETI_OP48EData.driveVibrationNum }),
                ...(ETI_OP48EData.dogPitch && { dogPitch: ETI_OP48EData.dogPitch }),
                ...(ETI_OP48EData.dogPitchNum && { dogPitchNum: ETI_OP48EData.dogPitchNum }),
                ...(ETI_OP48EData.paintMarker && { paintMarker: ETI_OP48EData.paintMarker }),
                ...(ETI_OP48EData.paintMarkerNum && { paintMarkerNum: ETI_OP48EData.paintMarkerNum }),
                ...(ETI_OP48EData.chainVision && { chainVision: ETI_OP48EData.chainVision }),
                ...(ETI_OP48EData.lubeVision && { lubeVision: ETI_OP48EData.lubeVision }),
                ...(ETI_OP48EData.trolleyVision && { trolleyVision: ETI_OP48EData.trolleyVision }),
                ...(ETI_OP48EData.trolleyDetect && { trolleyDetect: ETI_OP48EData.trolleyDetect }),
                ...(ETI_OP48EData.omniView && { omniView: ETI_OP48EData.omniView }),
                ...(ETI_OP48EData.dcuUpgradeNum && { dcuUpgradeNum: ETI_OP48EData.dcuUpgradeNum }),
                ...(ETI_OP48EData.itNameOne && { itNameOne: ETI_OP48EData.itNameOne }),
                ...(ETI_OP48EData.itIPOne && { itIPOne: ETI_OP48EData.itIPOne }),
                ...(ETI_OP48EData.itGatewayOne && { itGatewayOne: ETI_OP48EData.itGatewayOne }),
                ...(ETI_OP48EData.itSubnetOne && { itSubnetOne: ETI_OP48EData.itSubnetOne }),
                ...(ETI_OP48EData.itDNSOne && { itDNSOne: ETI_OP48EData.itDNSOne }),
                ...(ETI_OP48EData.itSMTPOne && { itSMTPOne: ETI_OP48EData.itSMTPOne }),
                ...(ETI_OP48EData.itNameTwo && { itNameTwo: ETI_OP48EData.itNameTwo }),
                ...(ETI_OP48EData.itIPTwo && { itIPTwo: ETI_OP48EData.itIPTwo }),
                ...(ETI_OP48EData.itGatewayTwo && { itGatewayTwo: ETI_OP48EData.itGatewayTwo }),
                ...(ETI_OP48EData.itSubnetTwo && { itSubnetTwo: ETI_OP48EData.itSubnetTwo }),
                ...(ETI_OP48EData.itDNSTwo && { itDNSTwo: ETI_OP48EData.itDNSTwo }),
                ...(ETI_OP48EData.itSMTPTwo && { itSMTPTwo: ETI_OP48EData.itSMTPTwo }),
                ...(ETI_OP48EData.itNameThree && { itNameThree: ETI_OP48EData.itNameThree }),
                ...(ETI_OP48EData.itIPThree && { itIPThree: ETI_OP48EData.itIPThree }),
                ...(ETI_OP48EData.itGatewayThree && { itGatewayThree: ETI_OP48EData.itGatewayThree }),
                ...(ETI_OP48EData.itSubnetThree && { itSubnetThree: ETI_OP48EData.itSubnetThree }),
                ...(ETI_OP48EData.itDNSThree && { itDNSThree: ETI_OP48EData.itDNSThree }),
                ...(ETI_OP48EData.itSMTPThree && { itSMTPThree: ETI_OP48EData.itSMTPThree }),
                ...(ETI_OP48EData.itAdditionalNotes && { itAdditionalNotes: ETI_OP48EData.itAdditionalNotes }),
                ...(ETI_OP48EData.piuDistance && { piuDistance: ETI_OP48EData.piuDistance }),
                ...(ETI_OP48EData.switchDistance && { switchDistance: ETI_OP48EData.switchDistance }),
                ...(ETI_OP48EData.ampPickup && { ampPickup: ETI_OP48EData.ampPickup }),
                ...(ETI_OP48EData.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETI_OP48EData.fromAirTakeUpDistance }),
                ...(ETI_OP48EData.specialControllerOptions && { specialControllerOptions: ETI_OP48EData.specialControllerOptions }),
                ...(ETI_OP48EData.operatingVoltage && { operatingVoltage: ETI_OP48EData.operatingVoltage })

                },
                freeWheelStatus: ETI_OP48EData.freeWheelStatus,
                actuatorStatus: ETI_OP48EData.actuatorStatus,
                ...(ETI_OP48EData.pivotStatus && { pivotStatus: ETI_OP48EData.pivotStatus}),
                kingPinStatus: ETI_OP48EData.kingPinStatus,
                lubeBrand: ETI_OP48EData.lubeBrand,
                lubeViscosity: ETI_OP48EData.lubeViscosity,
                ...(ETI_OP48EData.lubeType && { lubeType: ETI_OP48EData.lubeType}),
                currentGrease: ETI_OP48EData.currentGrease,
                currentGreaseGrade: ETI_OP48EData.currentGreaseGrade,
                zerkDirection: ETI_OP48EData.zerkDirection,
                zerkLocationType: ETI_OP48EData.zerkLocationType,
                wheelDiameter: ETI_OP48EData.wheelDiameter,
                conveyorSwing: ETI_OP48EData.conveyorSwing,
                ...(ETI_OP48EData.chainMaster && { lubeType: ETI_OP48EData.chainMaster}),
                ...(ETI_OP48EData.remoteStatus && { lubeType: ETI_OP48EData.remoteStatus}),
                ...(ETI_OP48EData.mountStatus && { lubeType: ETI_OP48EData.mountStatus}),
                ...(ETI_OP48EData.otherUnitStatus && { lubeType: ETI_OP48EData.otherUnitStatus}),
                ...(ETI_OP48EData.timerStatus && { lubeType: ETI_OP48EData.timerStatus}),
                ...(ETI_OP48EData.electricStatus && { lubeType: ETI_OP48EData.electricStatus}),
                ...(ETI_OP48EData.mightyLubeMonitoring && { lubeType: ETI_OP48EData.mightyLubeMonitoring}),
                ...(ETI_OP48EData.preMountType && { lubeType: ETI_OP48EData.preMountType}),
                ...(ETI_OP48EData.otherPreMountType && { lubeType: ETI_OP48EData.otherPreMountType}),
                ...(ETI_OP48EData.plcConnection && { lubeType: ETI_OP48EData.plcConnection}),
                ...(ETI_OP48EData.otherControllerNotes && { lubeType: ETI_OP48EData.otherControllerNotes}),
                ...(ETI_OP48EData.templateB_UnitType && { lubeType: ETI_OP48EData.templateB_UnitType}),
                ...(ETI_OP48EData.templateB_InvertedB && { lubeType: ETI_OP48EData.templateB_InvertedB}),
                ...(ETI_OP48EData.templateB_InvertedE && { lubeType: ETI_OP48EData.templateB_InvertedE}),
                ...(ETI_OP48EData.templateB_InvertedG && { lubeType: ETI_OP48EData.templateB_InvertedG}),
                ...(ETI_OP48EData.templateB_InvertedH && { lubeType: ETI_OP48EData.templateB_InvertedH}),
                ...(ETI_OP48EData.templateB_InvertedK && { lubeType: ETI_OP48EData.templateB_InvertedK}),
                ...(ETI_OP48EData.templateB_InvertedT && { lubeType: ETI_OP48EData.templateB_InvertedT}),
                ...(ETI_OP48EData.templateB_InvertedU && { lubeType: ETI_OP48EData.templateB_InvertedU}),
                ...(ETI_OP48EData.templateB_InvertedV && { lubeType: ETI_OP48EData.templateB_InvertedV}),
                ...(ETI_OP48EData.templateB_InvertedW && { lubeType: ETI_OP48EData.templateB_InvertedW}),

            },

            templateCData: {
                conveyorName: ETI_OP48EData.conveyorName,
                industrialChainManufacturer: ETI_OP48EData.industrialChainManufacturer,
                ...(ETI_OP48EData.otherChainManufacturer && { otherChainManufacturer: ETI_OP48EData.otherChainManufacturer }),
                wheelManufacturer: ETI_OP48EData.wheelManufacturer,
                ...(ETI_OP48EData.wheelManufacturer && { wheelManufacturer: ETI_OP48EData.wheelManufacturer}),
                conveyorSpeed: ETI_OP48EData.conveyorSpeed,
                conveyorSpeedUnit: ETI_OP48EData.conveyorSpeedUnit,
                conveyorIndex: ETI_OP48EData.conveyorIndex,
                ...(ETI_OP48EData.travelDirection && { travelDirection: ETI_OP48EData.travelDirection}),
                appEnviroment: ETI_OP48EData.appEnviroment,
                ...(ETI_OP48EData.otherAppEnviroment && { otherAppEnviroment: ETI_OP48EData.otherAppEnviroment}),
                surroundingTemp: ETI_OP48EData.surroundingTemp,
                orientationType: ETI_OP48EData.orientationType,
                guideWheelsEven: ETI_OP48EData.guideWheelsEven,
                operatingVoltage: ETI_OP48EData.operatingVoltage,
                controlVoltSingle: ETI_OP48EData.controlVoltSingle,
                compressedAir: ETI_OP48EData.compressedAir,
                ...(ETI_OP48EData.airSupplyType && { airSupplyType: ETI_OP48EData.airSupplyType}),
                existingMonitor: ETI_OP48EData.existingMonitor,
                newMonitor: ETI_OP48EData.newMonitor,
                templateA_CData: {
                ...(ETI_OP48EData.dcuStatus && { dcuStatus: ETI_OP48EData.dcuStatus }),
                ...(ETI_OP48EData.dcuNum && { dcuNum: ETI_OP48EData.dcuNum }),
                ...(ETI_OP48EData.existingWindows && { existingWindows: ETI_OP48EData.existingWindows }),
                ...(ETI_OP48EData.existingHeadUnit && { existingHeadUnit: ETI_OP48EData.existingHeadUnit }),
                ...(ETI_OP48EData.existingDCU && { existingDCU: ETI_OP48EData.existingDCU }),
                ...(ETI_OP48EData.existingPowerInterface && { existingPowerInterface: ETI_OP48EData.existingPowerInterface }),
                ...(ETI_OP48EData.newReservoir && { newReservoir: ETI_OP48EData.newReservoir }),
                ...(ETI_OP48EData.reservoirSize && { reservoirSize: ETI_OP48EData.reservoirSize }),
                ...(ETI_OP48EData.otherReservoirSize && { otherReservoirSize: ETI_OP48EData.otherReservoirSize }),
                ...(ETI_OP48EData.newReservoirNum && { newReservoirNum: ETI_OP48EData.newReservoirNum }),
                ...(ETI_OP48EData.typeMonitor && { typeMonitor: ETI_OP48EData.typeMonitor }),
                ...(ETI_OP48EData.driveMotorAmp && { driveMotorAmp: ETI_OP48EData.driveMotorAmp }),
                ...(ETI_OP48EData.driveMotorAmpNum && { driveMotorAmpNum: ETI_OP48EData.driveMotorAmpNum }),
                ...(ETI_OP48EData.driveTakeUpAir && { driveTakeUpAir: ETI_OP48EData.driveTakeUpAir }),
                ...(ETI_OP48EData.driveTakeUpAirNum && { driveTakeUpAirNum: ETI_OP48EData.driveTakeUpAirNum }),
                ...(ETI_OP48EData.takeUpDistance && { takeUpDistance: ETI_OP48EData.takeUpDistance }),
                ...(ETI_OP48EData.takeUpDistanceNum && { takeUpDistanceNum: ETI_OP48EData.takeUpDistanceNum }),
                ...(ETI_OP48EData.driveTemp && { driveTemp: ETI_OP48EData.driveTemp }),
                ...(ETI_OP48EData.driveTempNum && { driveTempNum: ETI_OP48EData.driveTempNum }),
                ...(ETI_OP48EData.driveVibration && { driveVibration: ETI_OP48EData.driveVibration }),
                ...(ETI_OP48EData.driveVibrationNum && { driveVibrationNum: ETI_OP48EData.driveVibrationNum }),
                ...(ETI_OP48EData.dogPitch && { dogPitch: ETI_OP48EData.dogPitch }),
                ...(ETI_OP48EData.dogPitchNum && { dogPitchNum: ETI_OP48EData.dogPitchNum }),
                ...(ETI_OP48EData.paintMarker && { paintMarker: ETI_OP48EData.paintMarker }),
                ...(ETI_OP48EData.paintMarkerNum && { paintMarkerNum: ETI_OP48EData.paintMarkerNum }),
                ...(ETI_OP48EData.chainVision && { chainVision: ETI_OP48EData.chainVision }),
                ...(ETI_OP48EData.lubeVision && { lubeVision: ETI_OP48EData.lubeVision }),
                ...(ETI_OP48EData.trolleyVision && { trolleyVision: ETI_OP48EData.trolleyVision }),
                ...(ETI_OP48EData.trolleyDetect && { trolleyDetect: ETI_OP48EData.trolleyDetect }),
                ...(ETI_OP48EData.omniView && { omniView: ETI_OP48EData.omniView }),
                ...(ETI_OP48EData.dcuUpgradeNum && { dcuUpgradeNum: ETI_OP48EData.dcuUpgradeNum }),
                ...(ETI_OP48EData.itNameOne && { itNameOne: ETI_OP48EData.itNameOne }),
                ...(ETI_OP48EData.itIPOne && { itIPOne: ETI_OP48EData.itIPOne }),
                ...(ETI_OP48EData.itGatewayOne && { itGatewayOne: ETI_OP48EData.itGatewayOne }),
                ...(ETI_OP48EData.itSubnetOne && { itSubnetOne: ETI_OP48EData.itSubnetOne }),
                ...(ETI_OP48EData.itDNSOne && { itDNSOne: ETI_OP48EData.itDNSOne }),
                ...(ETI_OP48EData.itSMTPOne && { itSMTPOne: ETI_OP48EData.itSMTPOne }),
                ...(ETI_OP48EData.itNameTwo && { itNameTwo: ETI_OP48EData.itNameTwo }),
                ...(ETI_OP48EData.itIPTwo && { itIPTwo: ETI_OP48EData.itIPTwo }),
                ...(ETI_OP48EData.itGatewayTwo && { itGatewayTwo: ETI_OP48EData.itGatewayTwo }),
                ...(ETI_OP48EData.itSubnetTwo && { itSubnetTwo: ETI_OP48EData.itSubnetTwo }),
                ...(ETI_OP48EData.itDNSTwo && { itDNSTwo: ETI_OP48EData.itDNSTwo }),
                ...(ETI_OP48EData.itSMTPTwo && { itSMTPTwo: ETI_OP48EData.itSMTPTwo }),
                ...(ETI_OP48EData.itNameThree && { itNameThree: ETI_OP48EData.itNameThree }),
                ...(ETI_OP48EData.itIPThree && { itIPThree: ETI_OP48EData.itIPThree }),
                ...(ETI_OP48EData.itGatewayThree && { itGatewayThree: ETI_OP48EData.itGatewayThree }),
                ...(ETI_OP48EData.itSubnetThree && { itSubnetThree: ETI_OP48EData.itSubnetThree }),
                ...(ETI_OP48EData.itDNSThree && { itDNSThree: ETI_OP48EData.itDNSThree }),
                ...(ETI_OP48EData.itSMTPThree && { itSMTPThree: ETI_OP48EData.itSMTPThree }),
                ...(ETI_OP48EData.itAdditionalNotes && { itAdditionalNotes: ETI_OP48EData.itAdditionalNotes }),
                ...(ETI_OP48EData.piuDistance && { piuDistance: ETI_OP48EData.piuDistance }),
                ...(ETI_OP48EData.switchDistance && { switchDistance: ETI_OP48EData.switchDistance }),
                ...(ETI_OP48EData.ampPickup && { ampPickup: ETI_OP48EData.ampPickup }),
                ...(ETI_OP48EData.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETI_OP48EData.fromAirTakeUpDistance }),
                ...(ETI_OP48EData.specialControllerOptions && { specialControllerOptions: ETI_OP48EData.specialControllerOptions }),
                ...(ETI_OP48EData.operatingVoltage && { operatingVoltage: ETI_OP48EData.operatingVoltage })

                },
                freeWheelStatus: ETI_OP48EData.freeWheelStatus,
                actuatorStatus: ETI_OP48EData.actuatorStatus,
                ...(ETI_OP48EData.pivotStatus && { pivotStatus: ETI_OP48EData.pivotStatus}),
                kingPinStatus: ETI_OP48EData.kingPinStatus,
                lubeBrand: ETI_OP48EData.lubeBrand,
                lubeViscosity: ETI_OP48EData.lubeViscosity,
                ...(ETI_OP48EData.lubeType && { lubeType: ETI_OP48EData.lubeType}),
                currentGrease: ETI_OP48EData.currentGrease,
                currentGreaseGrade: ETI_OP48EData.currentGreaseGrade,
                zerkDirection: ETI_OP48EData.zerkDirection,
                zerkLocationType: ETI_OP48EData.zerkLocationType,
                wheelDiameter: ETI_OP48EData.wheelDiameter,
                conveyorSwing: ETI_OP48EData.conveyorSwing,
                ...(ETI_OP48EData.chainMaster && { lubeType: ETI_OP48EData.chainMaster}),
                ...(ETI_OP48EData.remoteStatus && { lubeType: ETI_OP48EData.remoteStatus}),
                ...(ETI_OP48EData.mountStatus && { lubeType: ETI_OP48EData.mountStatus}),
                ...(ETI_OP48EData.otherUnitStatus && { lubeType: ETI_OP48EData.otherUnitStatus}),
                ...(ETI_OP48EData.timerStatus && { lubeType: ETI_OP48EData.timerStatus}),
                ...(ETI_OP48EData.electricStatus && { lubeType: ETI_OP48EData.electricStatus}),
                ...(ETI_OP48EData.mightyLubeMonitoring && { lubeType: ETI_OP48EData.mightyLubeMonitoring}),
                ...(ETI_OP48EData.preMountType && { lubeType: ETI_OP48EData.preMountType}),
                ...(ETI_OP48EData.otherPreMountType && { lubeType: ETI_OP48EData.otherPreMountType}),
                ...(ETI_OP48EData.plcConnection && { lubeType: ETI_OP48EData.plcConnection}),
                ...(ETI_OP48EData.otherControllerNotes && { lubeType: ETI_OP48EData.otherControllerNotes}),
                ...(ETI_OP48EData.templateC_UnitType && { lubeType: ETI_OP48EData.templateC_UnitType}),
                templateC_InvertedA: ETI_OP48EData.templateC_InvertedA,
                templateC_InvertedB: ETI_OP48EData.templateC_InvertedB,
                templateC_InvertedE: ETI_OP48EData.templateC_InvertedE,
                templateC_InvertedS: ETI_OP48EData.templateC_InvertedS,
            },

            catDriveStatus: ETI_OP48EData.catDriveStatus,

            templateFData: {
                conveyorName: ETI_OP48EData.conveyorName,
                chainSize: ETI_OP48EData.chainSize,
                ...(ETI_OP48EData.otherChainSize && { otherChainSize: ETI_OP48EData.otherChainSize }),
                industrialChainManufacturer: ETI_OP48EData.industrialChainManufacturer,
                ...(ETI_OP48EData.otherChainManufacturer && { otherChainManufacturer: ETI_OP48EData.otherChainManufacturer }),
                wheelManufacturer: ETI_OP48EData.wheelManufacturer,
                ...(ETI_OP48EData.otherWheelManufacturer && { otherWheelManufacturer: ETI_OP48EData.otherWheelManufacturer }),
                conveyorLength: ETI_OP48EData.conveyorLength,
                conveyorLengthUnit: ETI_OP48EData.conveyorLengthUnit,
                brushApplicators: ETI_OP48EData.brushApplicators,
                m12Plugs: ETI_OP48EData.m12Plugs,
                oilStatus: ETI_OP48EData.oilStatus,
                operatingVoltage: ETI_OP48EData.operatingVoltage,
                controlVoltSingle: ETI_OP48EData.controlVoltSingle,
            },

            ...(ETI_OP48EData.catDriveNum && { catDriveNum: ETI_OP48EData.catDriveNum }),
            ...(ETI_OP48EData.externalLubeStatus && { externalLubeStatus: ETI_OP48EData.externalLubeStatus }),
            ...(ETI_OP48EData.lubeBrand && { lubeBrand: ETI_OP48EData.lubeBrand }),
            ...(ETI_OP48EData.lubeType && { lubeType: ETI_OP48EData.lubeType }),
            ...(ETI_OP48EData.lubeViscosity && { lubeViscosity: ETI_OP48EData.lubeViscosity }),
            ...(ETI_OP48EData.sideLubeStatus && { sideLubeStatus: ETI_OP48EData.sideLubeStatus }),
            ...(ETI_OP48EData.chainMaster && { chainMaster: ETI_OP48EData.chainMaster }),
            ...(ETI_OP48EData.timerStatus && { timerStatus: ETI_OP48EData.timerStatus }),
            ...(ETI_OP48EData.electricStatus && { electricStatus: ETI_OP48EData.electricStatus }),
            ...(ETI_OP48EData.pneumaticStatus && { pneumaticStatus: ETI_OP48EData.pneumaticStatus }),
            ...(ETI_OP48EData.mightyLubeMonitoring && { mightyLubeMonitoring: ETI_OP48EData.mightyLubeMonitoring }),
            ...(ETI_OP48EData.plcConnection && { plcConnection: ETI_OP48EData.plcConnection }),
            ...(ETI_OP48EData.otherControllerInfo && { otherControllerInfo: ETI_OP48EData.otherControllerInfo }),
            ...(ETI_OP48EData.enclosedUnitType && { enclosedUnitType: ETI_OP48EData.enclosedUnitType }),
            ...(ETI_OP48EData.enclosedTrackB && { enclosedTrackB: ETI_OP48EData.enclosedTrackB }),
            ...(ETI_OP48EData.enclosedTrackG && { enclosedTrackG: ETI_OP48EData.enclosedTrackG }),
            ...(ETI_OP48EData.enclosedTrackH && { enclosedTrackH: ETI_OP48EData.enclosedTrackH }),
            ...(ETI_OP48EData.enclosedTrackS && { enclosedTrackS: ETI_OP48EData.enclosedTrackS }),
            ...(ETI_OP48EData.enclosedTrackK2 && { enclosedTrackK2: ETI_OP48EData.enclosedTrackK2 }),
            ...(ETI_OP48EData.enclosedTrackL2 && { enclosedTrackL2: ETI_OP48EData.enclosedTrackL2 }),
            ...(ETI_OP48EData.enclosedTrackM2 && { enclosedTrackM2: ETI_OP48EData.enclosedTrackM2 }),
            ...(ETI_OP48EData.enclosedTrackN2 && { enclosedTrackN2: ETI_OP48EData.enclosedTrackN2 }),
            ...(ETI_OP48EData.enclosedTrackS2 && { enclosedTrackS2: ETI_OP48EData.enclosedTrackS2 })
        });

        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "ETI_OP48E"
        });
        await req.user.save();

        return res.status(200).json({ message: "ETI_OP48E entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;
