const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const ETO_2100 = require("../models/ETO_2100");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");
const templateE= require("../models/templateE");
const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { ETO_2100Data, numRequested } = req.body;
        const order = new ETO_2100({
            ...(ETO_2100Data.chainSize && { chainSize: ETO_2100Data.chainSize }),
            ...(ETO_2100Data.otherChainSize && { otherChainSize: ETO_2100Data.otherChainSize }),
            industrialChainManufacturer: ETO_2100Data.industrialChainManufacturer,
            ...(ETO_2100Data.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: ETO_2100Data.otherIndustrialChainManufacturer }),
            ...(ETO_2100Data.conveyorLength && { conveyorLength: ETO_2100Data.conveyorLength }),
            ...(ETO_2100Data.conveyorLengthUnit && { conveyorLengthUnit: ETO_2100Data.conveyorLengthUnit }),
            ...(ETO_2100Data.conveyorSpeed && { conveyorSpeed: ETO_2100Data.conveyorSpeed }),
            ...(ETO_2100Data.conveyorSpeedUnit && { conveyorSpeedUnit: ETO_2100Data.conveyorSpeedUnit }),
            ...(ETO_2100Data.conveyorIndex && { conveyorIndex: ETO_2100Data.conveyorIndex }),
            ...(ETO_2100Data.travelDirection && { travelDirection: ETO_2100Data.travelDirection }),
            appEnviroment: ETO_2100Data.appEnviroment,
            ...(ETO_2100Data.ovenStatus && { ovenStatus: ETO_2100Data.ovenStatus }),
            ...(ETO_2100Data.ovenTemp && { ovenTemp: ETO_2100Data.ovenTemp }),
            ...(ETO_2100Data.otherAppEnviroment && { otherAppEnviroment: ETO_2100Data.otherAppEnviroment }),
            ...(ETO_2100Data.surroundingTemp && { surroundingTemp: ETO_2100Data.surroundingTemp }),
            ...(ETO_2100Data.conveyorLoaded && { conveyorLoaded: ETO_2100Data.conveyorLoaded }),
            ...(ETO_2100Data.conveyorSwing && { conveyorSwing: ETO_2100Data.conveyorSwing }),
            operatingVoltage: ETO_2100Data.operatingVoltage,

            existingMonitor: ETO_2100Data.existingMonitor,
            newMonitor: ETO_2100Data.newMonitor,
            monitorData: {
                ...(ETO_2100Data.dcuStatus && { dcuStatus: ETO_2100Data.dcuStatus }),
                ...(ETO_2100Data.dcuNum && { dcuNum: ETO_2100Data.dcuNum }),
                ...(ETO_2100Data.existingWindows && { existingWindows: ETO_2100Data.existingWindows }),
                ...(ETO_2100Data.existingHeadUnit && { existingHeadUnit: ETO_2100Data.existingHeadUnit }),
                ...(ETO_2100Data.existingDCU && { existingDCU: ETO_2100Data.existingDCU }),
                ...(ETO_2100Data.existingPowerInterface && { existingPowerInterface: ETO_2100Data.existingPowerInterface }),
                ...(ETO_2100Data.newReservoir && { newReservoir: ETO_2100Data.newReservoir }),
                ...(ETO_2100Data.reservoirSize && { reservoirSize: ETO_2100Data.reservoirSize }),
                ...(ETO_2100Data.otherReservoirSize && { otherReservoirSize: ETO_2100Data.otherReservoirSize }),
                ...(ETO_2100Data.newReservoirNum && { newReservoirNum: ETO_2100Data.newReservoirNum }),
                ...(ETO_2100Data.typeMonitor && { typeMonitor: ETO_2100Data.typeMonitor }),
                ...(ETO_2100Data.driveMotorAmp && { driveMotorAmp: ETO_2100Data.driveMotorAmp }),
                ...(ETO_2100Data.driveMotorAmpNum && { driveMotorAmpNum: ETO_2100Data.driveMotorAmpNum }),
                ...(ETO_2100Data.driveTakeUpAir && { driveTakeUpAir: ETO_2100Data.driveTakeUpAir }),
                ...(ETO_2100Data.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_2100Data.driveTakeUpAirNum }),
                ...(ETO_2100Data.takeUpDistance && { takeUpDistance: ETO_2100Data.takeUpDistance }),
                ...(ETO_2100Data.takeUpDistanceNum && { takeUpDistanceNum: ETO_2100Data.takeUpDistanceNum }),
                ...(ETO_2100Data.driveTemp && { driveTemp: ETO_2100Data.driveTemp }),
                ...(ETO_2100Data.driveTempNum && { driveTempNum: ETO_2100Data.driveTempNum }),
                ...(ETO_2100Data.driveVibration && { driveVibration: ETO_2100Data.driveVibration }),
                ...(ETO_2100Data.driveVibrationNum && { driveVibrationNum: ETO_2100Data.driveVibrationNum }),
                ...(ETO_2100Data.dogPitch && { dogPitch: ETO_2100Data.dogPitch }),
                ...(ETO_2100Data.dogPitchNum && { dogPitchNum: ETO_2100Data.dogPitchNum }),
                ...(ETO_2100Data.paintMarker && { paintMarker: ETO_2100Data.paintMarker }),
                ...(ETO_2100Data.paintMarkerNum && { paintMarkerNum: ETO_2100Data.paintMarkerNum }),
                ...(ETO_2100Data.chainVision && { chainVision: ETO_2100Data.chainVision }),
                ...(ETO_2100Data.lubeVision && { lubeVision: ETO_2100Data.lubeVision }),
                ...(ETO_2100Data.trolleyVision && { trolleyVision: ETO_2100Data.trolleyVision }),
                ...(ETO_2100Data.trolleyDetect && { trolleyDetect: ETO_2100Data.trolleyDetect }),
                ...(ETO_2100Data.omniView && { omniView: ETO_2100Data.omniView }),
                ...(ETO_2100Data.dcuUpgradeNum && { dcuUpgradeNum: ETO_2100Data.dcuUpgradeNum }),
                ...(ETO_2100Data.itNameOne && { itNameOne: ETO_2100Data.itNameOne }),
                ...(ETO_2100Data.itIPOne && { itIPOne: ETO_2100Data.itIPOne }),
                ...(ETO_2100Data.itGatewayOne && { itGatewayOne: ETO_2100Data.itGatewayOne }),
                ...(ETO_2100Data.itSubnetOne && { itSubnetOne: ETO_2100Data.itSubnetOne }),
                ...(ETO_2100Data.itDNSOne && { itDNSOne: ETO_2100Data.itDNSOne }),
                ...(ETO_2100Data.itSMTPOne && { itSMTPOne: ETO_2100Data.itSMTPOne }),
                ...(ETO_2100Data.itNameTwo && { itNameTwo: ETO_2100Data.itNameTwo }),
                ...(ETO_2100Data.itIPTwo && { itIPTwo: ETO_2100Data.itIPTwo }),
                ...(ETO_2100Data.itGatewayTwo && { itGatewayTwo: ETO_2100Data.itGatewayTwo }),
                ...(ETO_2100Data.itSubnetTwo && { itSubnetTwo: ETO_2100Data.itSubnetTwo }),
                ...(ETO_2100Data.itDNSTwo && { itDNSTwo: ETO_2100Data.itDNSTwo }),
                ...(ETO_2100Data.itSMTPTwo && { itSMTPTwo: ETO_2100Data.itSMTPTwo }),
                ...(ETO_2100Data.itNameThree && { itNameThree: ETO_2100Data.itNameThree }),
                ...(ETO_2100Data.itIPThree && { itIPThree: ETO_2100Data.itIPThree }),
                ...(ETO_2100Data.itGatewayThree && { itGatewayThree: ETO_2100Data.itGatewayThree }),
                ...(ETO_2100Data.itSubnetThree && { itSubnetThree: ETO_2100Data.itSubnetThree }),
                ...(ETO_2100Data.itDNSThree && { itDNSThree: ETO_2100Data.itDNSThree }),
                ...(ETO_2100Data.itSMTPThree && { itSMTPThree: ETO_2100Data.itSMTPThree }),
                ...(ETO_2100Data.itAdditionalNotes && { itAdditionalNotes: ETO_2100Data.itAdditionalNotes }),
                ...(ETO_2100Data.piuDistance && { piuDistance: ETO_2100Data.piuDistance }),
                ...(ETO_2100Data.switchDistance && { switchDistance: ETO_2100Data.switchDistance }),
                ...(ETO_2100Data.ampPickup && { ampPickup: ETO_2100Data.ampPickup }),
                ...(ETO_2100Data.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_2100Data.fromAirTakeUpDistance }),
                ...(ETO_2100Data.specialControllerOptions && { specialControllerOptions: ETO_2100Data.specialControllerOptions }),
                ...(ETO_2100Data.operatingVoltage && { operatingVoltage: ETO_2100Data.operatingVoltage })

            },

            addFreeCarrier: ETO_2100Data.addFreeCarrier,

            templateBData: {
                conveyorName: ETO_2100Data.conveyorName,
                industrialChainManufacturer: ETO_2100Data.industrialChainManufacturer,
                ...(ETO_2100Data.otherChainManufacturer && { otherChainManufacturer: ETO_2100Data.otherChainManufacturer }),
                wheelManufacturer: ETO_2100Data.wheelManufacturer,
                ...(ETO_2100Data.wheelManufacturer && { wheelManufacturer: ETO_2100Data.wheelManufacturer}),
                conveyorSpeed: ETO_2100Data.conveyorSpeed,
                conveyorSpeedUnit: ETO_2100Data.conveyorSpeedUnit,
                conveyorIndex: ETO_2100Data.conveyorIndex,
                ...(ETO_2100Data.travelDirection && { travelDirection: ETO_2100Data.travelDirection}),
                appEnviroment: ETO_2100Data.appEnviroment,
                ...(ETO_2100Data.otherAppEnviroment && { otherAppEnviroment: ETO_2100Data.otherAppEnviroment}),
                surroundingTemp: ETO_2100Data.surroundingTemp,
                orientationType: ETO_2100Data.orientationType,
                operatingVoltage: ETO_2100Data.operatingVoltage,
                controlVoltSingle: ETO_2100Data.controlVoltSingle,
                compressedAir: ETO_2100Data.compressedAir,
                ...(ETO_2100Data.airSupplyType && { airSupplyType: ETO_2100Data.airSupplyType}),
            existingMonitor: ETO_2100Data.existingMonitor,
            newMonitor: ETO_2100Data.newMonitor,
            templateA_BData: {
                ...(ETO_2100Data.dcuStatus && { dcuStatus: ETO_2100Data.dcuStatus }),
                ...(ETO_2100Data.dcuNum && { dcuNum: ETO_2100Data.dcuNum }),
                ...(ETO_2100Data.existingWindows && { existingWindows: ETO_2100Data.existingWindows }),
                ...(ETO_2100Data.existingHeadUnit && { existingHeadUnit: ETO_2100Data.existingHeadUnit }),
                ...(ETO_2100Data.existingDCU && { existingDCU: ETO_2100Data.existingDCU }),
                ...(ETO_2100Data.existingPowerInterface && { existingPowerInterface: ETO_2100Data.existingPowerInterface }),
                ...(ETO_2100Data.newReservoir && { newReservoir: ETO_2100Data.newReservoir }),
                ...(ETO_2100Data.reservoirSize && { reservoirSize: ETO_2100Data.reservoirSize }),
                ...(ETO_2100Data.otherReservoirSize && { otherReservoirSize: ETO_2100Data.otherReservoirSize }),
                ...(ETO_2100Data.newReservoirNum && { newReservoirNum: ETO_2100Data.newReservoirNum }),
                ...(ETO_2100Data.typeMonitor && { typeMonitor: ETO_2100Data.typeMonitor }),
                ...(ETO_2100Data.driveMotorAmp && { driveMotorAmp: ETO_2100Data.driveMotorAmp }),
                ...(ETO_2100Data.driveMotorAmpNum && { driveMotorAmpNum: ETO_2100Data.driveMotorAmpNum }),
                ...(ETO_2100Data.driveTakeUpAir && { driveTakeUpAir: ETO_2100Data.driveTakeUpAir }),
                ...(ETO_2100Data.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_2100Data.driveTakeUpAirNum }),
                ...(ETO_2100Data.takeUpDistance && { takeUpDistance: ETO_2100Data.takeUpDistance }),
                ...(ETO_2100Data.takeUpDistanceNum && { takeUpDistanceNum: ETO_2100Data.takeUpDistanceNum }),
                ...(ETO_2100Data.driveTemp && { driveTemp: ETO_2100Data.driveTemp }),
                ...(ETO_2100Data.driveTempNum && { driveTempNum: ETO_2100Data.driveTempNum }),
                ...(ETO_2100Data.driveVibration && { driveVibration: ETO_2100Data.driveVibration }),
                ...(ETO_2100Data.driveVibrationNum && { driveVibrationNum: ETO_2100Data.driveVibrationNum }),
                ...(ETO_2100Data.dogPitch && { dogPitch: ETO_2100Data.dogPitch }),
                ...(ETO_2100Data.dogPitchNum && { dogPitchNum: ETO_2100Data.dogPitchNum }),
                ...(ETO_2100Data.paintMarker && { paintMarker: ETO_2100Data.paintMarker }),
                ...(ETO_2100Data.paintMarkerNum && { paintMarkerNum: ETO_2100Data.paintMarkerNum }),
                ...(ETO_2100Data.chainVision && { chainVision: ETO_2100Data.chainVision }),
                ...(ETO_2100Data.lubeVision && { lubeVision: ETO_2100Data.lubeVision }),
                ...(ETO_2100Data.trolleyVision && { trolleyVision: ETO_2100Data.trolleyVision }),
                ...(ETO_2100Data.trolleyDetect && { trolleyDetect: ETO_2100Data.trolleyDetect }),
                ...(ETO_2100Data.omniView && { omniView: ETO_2100Data.omniView }),
                ...(ETO_2100Data.dcuUpgradeNum && { dcuUpgradeNum: ETO_2100Data.dcuUpgradeNum }),
                ...(ETO_2100Data.itNameOne && { itNameOne: ETO_2100Data.itNameOne }),
                ...(ETO_2100Data.itIPOne && { itIPOne: ETO_2100Data.itIPOne }),
                ...(ETO_2100Data.itGatewayOne && { itGatewayOne: ETO_2100Data.itGatewayOne }),
                ...(ETO_2100Data.itSubnetOne && { itSubnetOne: ETO_2100Data.itSubnetOne }),
                ...(ETO_2100Data.itDNSOne && { itDNSOne: ETO_2100Data.itDNSOne }),
                ...(ETO_2100Data.itSMTPOne && { itSMTPOne: ETO_2100Data.itSMTPOne }),
                ...(ETO_2100Data.itNameTwo && { itNameTwo: ETO_2100Data.itNameTwo }),
                ...(ETO_2100Data.itIPTwo && { itIPTwo: ETO_2100Data.itIPTwo }),
                ...(ETO_2100Data.itGatewayTwo && { itGatewayTwo: ETO_2100Data.itGatewayTwo }),
                ...(ETO_2100Data.itSubnetTwo && { itSubnetTwo: ETO_2100Data.itSubnetTwo }),
                ...(ETO_2100Data.itDNSTwo && { itDNSTwo: ETO_2100Data.itDNSTwo }),
                ...(ETO_2100Data.itSMTPTwo && { itSMTPTwo: ETO_2100Data.itSMTPTwo }),
                ...(ETO_2100Data.itNameThree && { itNameThree: ETO_2100Data.itNameThree }),
                ...(ETO_2100Data.itIPThree && { itIPThree: ETO_2100Data.itIPThree }),
                ...(ETO_2100Data.itGatewayThree && { itGatewayThree: ETO_2100Data.itGatewayThree }),
                ...(ETO_2100Data.itSubnetThree && { itSubnetThree: ETO_2100Data.itSubnetThree }),
                ...(ETO_2100Data.itDNSThree && { itDNSThree: ETO_2100Data.itDNSThree }),
                ...(ETO_2100Data.itSMTPThree && { itSMTPThree: ETO_2100Data.itSMTPThree }),
                ...(ETO_2100Data.itAdditionalNotes && { itAdditionalNotes: ETO_2100Data.itAdditionalNotes }),
                ...(ETO_2100Data.piuDistance && { piuDistance: ETO_2100Data.piuDistance }),
                ...(ETO_2100Data.switchDistance && { switchDistance: ETO_2100Data.switchDistance }),
                ...(ETO_2100Data.ampPickup && { ampPickup: ETO_2100Data.ampPickup }),
                ...(ETO_2100Data.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_2100Data.fromAirTakeUpDistance }),
                ...(ETO_2100Data.specialControllerOptions && { specialControllerOptions: ETO_2100Data.specialControllerOptions }),
                ...(ETO_2100Data.operatingVoltage && { operatingVoltage: ETO_2100Data.operatingVoltage })

                },
                freeWheelStatus: ETO_2100Data.freeWheelStatus,
                actuatorStatus: ETO_2100Data.actuatorStatus,
                ...(ETO_2100Data.pivotStatus && { pivotStatus: ETO_2100Data.pivotStatus}),
                kingPinStatus: ETO_2100Data.kingPinStatus,
                lubeBrand: ETO_2100Data.lubeBrand,
                lubeViscosity: ETO_2100Data.lubeViscosity,
                ...(ETO_2100Data.lubeType && { lubeType: ETO_2100Data.lubeType}),
                currentGrease: ETO_2100Data.currentGrease,
                currentGreaseGrade: ETO_2100Data.currentGreaseGrade,
                zerkDirection: ETO_2100Data.zerkDirection,
                zerkLocationType: ETO_2100Data.zerkLocationType,
                wheelDiameter: ETO_2100Data.wheelDiameter,
                conveyorSwing: ETO_2100Data.conveyorSwing,
                ...(ETO_2100Data.chainMaster && { lubeType: ETO_2100Data.chainMaster}),
                ...(ETO_2100Data.remoteStatus && { lubeType: ETO_2100Data.remoteStatus}),
                ...(ETO_2100Data.mountStatus && { lubeType: ETO_2100Data.mountStatus}),
                ...(ETO_2100Data.otherUnitStatus && { lubeType: ETO_2100Data.otherUnitStatus}),
                ...(ETO_2100Data.timerStatus && { lubeType: ETO_2100Data.timerStatus}),
                ...(ETO_2100Data.electricStatus && { lubeType: ETO_2100Data.electricStatus}),
                ...(ETO_2100Data.mightyLubeMonitoring && { lubeType: ETO_2100Data.mightyLubeMonitoring}),
                ...(ETO_2100Data.preMountType && { lubeType: ETO_2100Data.preMountType}),
                ...(ETO_2100Data.otherPreMountType && { lubeType: ETO_2100Data.otherPreMountType}),
                ...(ETO_2100Data.plcConnection && { lubeType: ETO_2100Data.plcConnection}),
                ...(ETO_2100Data.otherControllerNotes && { lubeType: ETO_2100Data.otherControllerNotes}),
                ...(ETO_2100Data.templateB_UnitType && { lubeType: ETO_2100Data.templateB_UnitType}),
                ...(ETO_2100Data.templateB_InvertedB && { lubeType: ETO_2100Data.templateB_InvertedB}),
                ...(ETO_2100Data.templateB_InvertedE && { lubeType: ETO_2100Data.templateB_InvertedE}),
                ...(ETO_2100Data.templateB_InvertedG && { lubeType: ETO_2100Data.templateB_InvertedG}),
                ...(ETO_2100Data.templateB_InvertedH && { lubeType: ETO_2100Data.templateB_InvertedH}),
                ...(ETO_2100Data.templateB_InvertedK && { lubeType: ETO_2100Data.templateB_InvertedK}),
                ...(ETO_2100Data.templateB_InvertedT && { lubeType: ETO_2100Data.templateB_InvertedT}),
                ...(ETO_2100Data.templateB_InvertedU && { lubeType: ETO_2100Data.templateB_InvertedU}),
                ...(ETO_2100Data.templateB_InvertedV && { lubeType: ETO_2100Data.templateB_InvertedV}),
                ...(ETO_2100Data.templateB_InvertedW && { lubeType: ETO_2100Data.templateB_InvertedW}),

            },

            templateCData: {
                conveyorName: ETO_2100Data.conveyorName,
                industrialChainManufacturer: ETO_2100Data.industrialChainManufacturer,
                ...(ETO_2100Data.otherChainManufacturer && { otherChainManufacturer: ETO_2100Data.otherChainManufacturer }),
                wheelManufacturer: ETO_2100Data.wheelManufacturer,
                ...(ETO_2100Data.wheelManufacturer && { wheelManufacturer: ETO_2100Data.wheelManufacturer}),
                conveyorSpeed: ETO_2100Data.conveyorSpeed,
                conveyorSpeedUnit: ETO_2100Data.conveyorSpeedUnit,
                conveyorIndex: ETO_2100Data.conveyorIndex,
                ...(ETO_2100Data.travelDirection && { travelDirection: ETO_2100Data.travelDirection}),
                appEnviroment: ETO_2100Data.appEnviroment,
                ...(ETO_2100Data.otherAppEnviroment && { otherAppEnviroment: ETO_2100Data.otherAppEnviroment}),
                surroundingTemp: ETO_2100Data.surroundingTemp,
                orientationType: ETO_2100Data.orientationType,
                guideWheelsEven: ETO_2100Data.guideWheelsEven,
                operatingVoltage: ETO_2100Data.operatingVoltage,
                controlVoltSingle: ETO_2100Data.controlVoltSingle,
                compressedAir: ETO_2100Data.compressedAir,
                ...(ETO_2100Data.airSupplyType && { airSupplyType: ETO_2100Data.airSupplyType}),
                existingMonitor: ETO_2100Data.existingMonitor,
                newMonitor: ETO_2100Data.newMonitor,
                templateA_CData: {
                ...(ETO_2100Data.dcuStatus && { dcuStatus: ETO_2100Data.dcuStatus }),
                ...(ETO_2100Data.dcuNum && { dcuNum: ETO_2100Data.dcuNum }),
                ...(ETO_2100Data.existingWindows && { existingWindows: ETO_2100Data.existingWindows }),
                ...(ETO_2100Data.existingHeadUnit && { existingHeadUnit: ETO_2100Data.existingHeadUnit }),
                ...(ETO_2100Data.existingDCU && { existingDCU: ETO_2100Data.existingDCU }),
                ...(ETO_2100Data.existingPowerInterface && { existingPowerInterface: ETO_2100Data.existingPowerInterface }),
                ...(ETO_2100Data.newReservoir && { newReservoir: ETO_2100Data.newReservoir }),
                ...(ETO_2100Data.reservoirSize && { reservoirSize: ETO_2100Data.reservoirSize }),
                ...(ETO_2100Data.otherReservoirSize && { otherReservoirSize: ETO_2100Data.otherReservoirSize }),
                ...(ETO_2100Data.newReservoirNum && { newReservoirNum: ETO_2100Data.newReservoirNum }),
                ...(ETO_2100Data.typeMonitor && { typeMonitor: ETO_2100Data.typeMonitor }),
                ...(ETO_2100Data.driveMotorAmp && { driveMotorAmp: ETO_2100Data.driveMotorAmp }),
                ...(ETO_2100Data.driveMotorAmpNum && { driveMotorAmpNum: ETO_2100Data.driveMotorAmpNum }),
                ...(ETO_2100Data.driveTakeUpAir && { driveTakeUpAir: ETO_2100Data.driveTakeUpAir }),
                ...(ETO_2100Data.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_2100Data.driveTakeUpAirNum }),
                ...(ETO_2100Data.takeUpDistance && { takeUpDistance: ETO_2100Data.takeUpDistance }),
                ...(ETO_2100Data.takeUpDistanceNum && { takeUpDistanceNum: ETO_2100Data.takeUpDistanceNum }),
                ...(ETO_2100Data.driveTemp && { driveTemp: ETO_2100Data.driveTemp }),
                ...(ETO_2100Data.driveTempNum && { driveTempNum: ETO_2100Data.driveTempNum }),
                ...(ETO_2100Data.driveVibration && { driveVibration: ETO_2100Data.driveVibration }),
                ...(ETO_2100Data.driveVibrationNum && { driveVibrationNum: ETO_2100Data.driveVibrationNum }),
                ...(ETO_2100Data.dogPitch && { dogPitch: ETO_2100Data.dogPitch }),
                ...(ETO_2100Data.dogPitchNum && { dogPitchNum: ETO_2100Data.dogPitchNum }),
                ...(ETO_2100Data.paintMarker && { paintMarker: ETO_2100Data.paintMarker }),
                ...(ETO_2100Data.paintMarkerNum && { paintMarkerNum: ETO_2100Data.paintMarkerNum }),
                ...(ETO_2100Data.chainVision && { chainVision: ETO_2100Data.chainVision }),
                ...(ETO_2100Data.lubeVision && { lubeVision: ETO_2100Data.lubeVision }),
                ...(ETO_2100Data.trolleyVision && { trolleyVision: ETO_2100Data.trolleyVision }),
                ...(ETO_2100Data.trolleyDetect && { trolleyDetect: ETO_2100Data.trolleyDetect }),
                ...(ETO_2100Data.omniView && { omniView: ETO_2100Data.omniView }),
                ...(ETO_2100Data.dcuUpgradeNum && { dcuUpgradeNum: ETO_2100Data.dcuUpgradeNum }),
                ...(ETO_2100Data.itNameOne && { itNameOne: ETO_2100Data.itNameOne }),
                ...(ETO_2100Data.itIPOne && { itIPOne: ETO_2100Data.itIPOne }),
                ...(ETO_2100Data.itGatewayOne && { itGatewayOne: ETO_2100Data.itGatewayOne }),
                ...(ETO_2100Data.itSubnetOne && { itSubnetOne: ETO_2100Data.itSubnetOne }),
                ...(ETO_2100Data.itDNSOne && { itDNSOne: ETO_2100Data.itDNSOne }),
                ...(ETO_2100Data.itSMTPOne && { itSMTPOne: ETO_2100Data.itSMTPOne }),
                ...(ETO_2100Data.itNameTwo && { itNameTwo: ETO_2100Data.itNameTwo }),
                ...(ETO_2100Data.itIPTwo && { itIPTwo: ETO_2100Data.itIPTwo }),
                ...(ETO_2100Data.itGatewayTwo && { itGatewayTwo: ETO_2100Data.itGatewayTwo }),
                ...(ETO_2100Data.itSubnetTwo && { itSubnetTwo: ETO_2100Data.itSubnetTwo }),
                ...(ETO_2100Data.itDNSTwo && { itDNSTwo: ETO_2100Data.itDNSTwo }),
                ...(ETO_2100Data.itSMTPTwo && { itSMTPTwo: ETO_2100Data.itSMTPTwo }),
                ...(ETO_2100Data.itNameThree && { itNameThree: ETO_2100Data.itNameThree }),
                ...(ETO_2100Data.itIPThree && { itIPThree: ETO_2100Data.itIPThree }),
                ...(ETO_2100Data.itGatewayThree && { itGatewayThree: ETO_2100Data.itGatewayThree }),
                ...(ETO_2100Data.itSubnetThree && { itSubnetThree: ETO_2100Data.itSubnetThree }),
                ...(ETO_2100Data.itDNSThree && { itDNSThree: ETO_2100Data.itDNSThree }),
                ...(ETO_2100Data.itSMTPThree && { itSMTPThree: ETO_2100Data.itSMTPThree }),
                ...(ETO_2100Data.itAdditionalNotes && { itAdditionalNotes: ETO_2100Data.itAdditionalNotes }),
                ...(ETO_2100Data.piuDistance && { piuDistance: ETO_2100Data.piuDistance }),
                ...(ETO_2100Data.switchDistance && { switchDistance: ETO_2100Data.switchDistance }),
                ...(ETO_2100Data.ampPickup && { ampPickup: ETO_2100Data.ampPickup }),
                ...(ETO_2100Data.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_2100Data.fromAirTakeUpDistance }),
                ...(ETO_2100Data.specialControllerOptions && { specialControllerOptions: ETO_2100Data.specialControllerOptions }),
                ...(ETO_2100Data.operatingVoltage && { operatingVoltage: ETO_2100Data.operatingVoltage })

                },
                freeWheelStatus: ETO_2100Data.freeWheelStatus,
                actuatorStatus: ETO_2100Data.actuatorStatus,
                ...(ETO_2100Data.pivotStatus && { pivotStatus: ETO_2100Data.pivotStatus}),
                kingPinStatus: ETO_2100Data.kingPinStatus,
                lubeBrand: ETO_2100Data.lubeBrand,
                lubeViscosity: ETO_2100Data.lubeViscosity,
                ...(ETO_2100Data.lubeType && { lubeType: ETO_2100Data.lubeType}),
                currentGrease: ETO_2100Data.currentGrease,
                currentGreaseGrade: ETO_2100Data.currentGreaseGrade,
                zerkDirection: ETO_2100Data.zerkDirection,
                zerkLocationType: ETO_2100Data.zerkLocationType,
                wheelDiameter: ETO_2100Data.wheelDiameter,
                conveyorSwing: ETO_2100Data.conveyorSwing,
                ...(ETO_2100Data.chainMaster && { lubeType: ETO_2100Data.chainMaster}),
                ...(ETO_2100Data.remoteStatus && { lubeType: ETO_2100Data.remoteStatus}),
                ...(ETO_2100Data.mountStatus && { lubeType: ETO_2100Data.mountStatus}),
                ...(ETO_2100Data.otherUnitStatus && { lubeType: ETO_2100Data.otherUnitStatus}),
                ...(ETO_2100Data.timerStatus && { lubeType: ETO_2100Data.timerStatus}),
                ...(ETO_2100Data.electricStatus && { lubeType: ETO_2100Data.electricStatus}),
                ...(ETO_2100Data.mightyLubeMonitoring && { lubeType: ETO_2100Data.mightyLubeMonitoring}),
                ...(ETO_2100Data.preMountType && { lubeType: ETO_2100Data.preMountType}),
                ...(ETO_2100Data.otherPreMountType && { lubeType: ETO_2100Data.otherPreMountType}),
                ...(ETO_2100Data.plcConnection && { lubeType: ETO_2100Data.plcConnection}),
                ...(ETO_2100Data.otherControllerNotes && { lubeType: ETO_2100Data.otherControllerNotes}),
                ...(ETO_2100Data.templateC_UnitType && { lubeType: ETO_2100Data.templateC_UnitType}),
                templateC_InvertedA: ETO_2100Data.templateC_InvertedA,
                templateC_InvertedB: ETO_2100Data.templateC_InvertedB,
                templateC_InvertedE: ETO_2100Data.templateC_InvertedE,
                templateC_InvertedS: ETO_2100Data.templateC_InvertedS,
            },

            catDriveStatus: ETO_2100Data.catDriveStatus,

                templateEData: {
                conveyorName: ETO_2100Data.conveyorName,
                chainSize: ETO_2100Data.chainSize,
                ...(ETO_2100Data.otherChainSize && { otherChainSize: ETO_2100Data.otherChainSize }),
                ...(ETO_2100Data.industrialChainManufacturer && { industrialChainManufacturer: ETO_2100Data.industrialChainManufacturer }),
                ...(ETO_2100Data.otherChainManufacturer && { otherChainManufacturer: ETO_2100Data.otherChainManufacturer }),
                ...(ETO_2100Data.conveyorLength && { conveyorLength: ETO_2100Data.conveyorLength }),
                ...(ETO_2100Data.conveyorLengthUnit && { conveyorLengthUnit: ETO_2100Data.conveyorLengthUnit }),
                ...(ETO_2100Data.appEnviroment && { appEnviroment: ETO_2100Data.appEnviroment }),
                ...(ETO_2100Data.otherAppEnviroment && { otherAppEnviroment: ETO_2100Data.otherAppEnviroment }),
                ...(ETO_2100Data.lubeBrand && { lubeBrand: ETO_2100Data.lubeBrand }),
                ...(ETO_2100Data.lubeType && { lubeType: ETO_2100Data.lubeType }),
                ...(ETO_2100Data.lubeViscosity && { lubeViscosity: ETO_2100Data.lubeViscosity }),
                ...(ETO_2100Data.specialControllerOptions && { specialControllerOptions: ETO_2100Data.specialControllerOptions }),
                ...(ETO_2100Data.wireMeasurementUnit && { wireMeasurementUnit: ETO_2100Data.wireMeasurementUnit }),
                ...(ETO_2100Data.conductor2 && { conductor2: ETO_2100Data.conductor2 }),
                ...(ETO_2100Data.conductor4 && { conductor4: ETO_2100Data.conductor4 }),
                ...(ETO_2100Data.conductor7 && { conductor7: ETO_2100Data.conductor7 }),
                ...(ETO_2100Data.conductor12 && { conductor12: ETO_2100Data.conductor12 }),
                ...(ETO_2100Data.junctionBoxNum && { junctionBoxNum: ETO_2100Data.junctionBoxNum }),

            },
            ...(ETO_2100Data.catDriveNum && { catDriveNum: ETO_2100Data.catDriveNum }),
            ...(ETO_2100Data.lubeBrand && { lubeBrand: ETO_2100Data.lubeBrand }),
            ...(ETO_2100Data.lubeType && { lubeType: ETO_2100Data.lubeType }),
            ...(ETO_2100Data.lubeViscosity && { lubeViscosity: ETO_2100Data.lubeViscosity }),
            ...(ETO_2100Data.chainCleanStatus && { chainCleanStatus: ETO_2100Data.chainCleanStatus }),
            ...(ETO_2100Data.wireMeasurementUnit && { wireMeasurementUnit: ETO_2100Data.wireMeasurementUnit }),
            ...(ETO_2100Data.conductor2 && { conductor2: ETO_2100Data.conductor2 }),
            ...(ETO_2100Data.conductor4 && { conductor4: ETO_2100Data.conductor4 }),
            ...(ETO_2100Data.conductor7 && { conductor7: ETO_2100Data.conductor7 }),
            ...(ETO_2100Data.conductor12 && { conductor12: ETO_2100Data.conductor12 }),
            ...(ETO_2100Data.junctionBoxNum && { junctionBoxNum: ETO_2100Data.junctionBoxNum }),
            ...(ETO_2100Data.etUnitType && { etUnitType: ETO_2100Data.etUnitType }),
            ...(ETO_2100Data.etOverheadB && { etOverheadB: ETO_2100Data.etOverheadB }),
            ...(ETO_2100Data.etOverheadG && { etOverheadG: ETO_2100Data.etOverheadG }),
            ...(ETO_2100Data.etOverheadH && { etOverheadH: ETO_2100Data.etOverheadH }),
            ...(ETO_2100Data.etOverheadS && { etOverheadS: ETO_2100Data.etOverheadS }),
            ...(ETO_2100Data.etOverheadK2 && { etOverheadK2: ETO_2100Data.etOverheadK2 }),
            ...(ETO_2100Data.etOverheadLS && { etOverheadLS: ETO_2100Data.etOverheadLS }),
            ...(ETO_2100Data.etOverheadM2 && { etOverheadM2: ETO_2100Data.etOverheadM2 }),
            ...(ETO_2100Data.etOverheadN2 && { etOverheadN2: ETO_2100Data.etOverheadN2 }),
            ...(ETO_2100Data.etOverheadS2 && { etOverheadS2: ETO_2100Data.etOverheadS2 })
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "ETO_2100"
        });
        await req.user.save();
        return res.status(200).json({ message: "ETO_2100 entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;
