const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const ETO_9000E = require("../models/ETO_9000E");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");
const templateE= require("../models/templateE");
const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { ETO_9000EData, numRequested } = req.body;
        const order = new ETO_9000E({
            ...(ETO_9000EData.chainSize && { chainSize: ETO_9000EData.chainSize }),
            ...(ETO_9000EData.otherChainSize && { otherChainSize: ETO_9000EData.otherChainSize }),
            industrialChainManufacturer: ETO_9000EData.industrialChainManufacturer,
            ...(ETO_9000EData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: ETO_9000EData.otherIndustrialChainManufacturer }),
            ...(ETO_9000EData.conveyorLength && { conveyorLength: ETO_9000EData.conveyorLength }),
            ...(ETO_9000EData.conveyorLengthUnit && { conveyorLengthUnit: ETO_9000EData.conveyorLengthUnit }),
            ...(ETO_9000EData.conveyorSpeed && { conveyorSpeed: ETO_9000EData.conveyorSpeed }),
            ...(ETO_9000EData.conveyorSpeedUnit && { conveyorSpeedUnit: ETO_9000EData.conveyorSpeedUnit }),
            ...(ETO_9000EData.conveyorIndex && { conveyorIndex: ETO_9000EData.conveyorIndex }),
            ...(ETO_9000EData.travelDirection && { travelDirection: ETO_9000EData.travelDirection }),
            appEnviroment: ETO_9000EData.appEnviroment,
            ...(ETO_9000EData.ovenStatus && { ovenStatus: ETO_9000EData.ovenStatus }),
            ...(ETO_9000EData.ovenTemp && { ovenTemp: ETO_9000EData.ovenTemp }),
            ...(ETO_9000EData.otherAppEnviroment && { otherAppEnviroment: ETO_9000EData.otherAppEnviroment }),
            ...(ETO_9000EData.surroundingTemp && { surroundingTemp: ETO_9000EData.surroundingTemp }),
            ...(ETO_9000EData.conveyorLoaded && { conveyorLoaded: ETO_9000EData.conveyorLoaded }),
            ...(ETO_9000EData.conveyorSwing && { conveyorSwing: ETO_9000EData.conveyorSwing }),
            operatingVoltage: ETO_9000EData.operatingVoltage,
        monitorData: 
        {
                existingMonitor: ETO_9000EData.templateA.existingMonitor,
                newMonitor: ETO_9000EData.templateA.newMonitor,		
                ...(ETO_9000EData.templateA.dcuStatus && { dcuStatus: ETO_9000EData.templateA.dcuStatus }),
                ...(ETO_9000EData.templateA.dcuNum && { dcuNum: ETO_9000EData.templateA.dcuNum }),
                ...(ETO_9000EData.templateA.existingWindows && { existingWindows: ETO_9000EData.templateA.existingWindows }),
                ...(ETO_9000EData.templateA.existingHeadUnit && { existingHeadUnit: ETO_9000EData.templateA.existingHeadUnit }),
                ...(ETO_9000EData.templateA.existingDCU && { existingDCU: ETO_9000EData.templateA.existingDCU }),
                ...(ETO_9000EData.templateA.existingPowerInterface && { existingPowerInterface: ETO_9000EData.templateA.existingPowerInterface }),
                ...(ETO_9000EData.templateA.newReservoir && { newReservoir: ETO_9000EData.templateA.newReservoir }),
                ...(ETO_9000EData.templateA.reservoirSize && { reservoirSize: ETO_9000EData.templateA.reservoirSize }),
                ...(ETO_9000EData.templateA.otherReservoirSize && { otherReservoirSize: ETO_9000EData.templateA.otherReservoirSize }),
                ...(ETO_9000EData.templateA.newReservoirNum && { newReservoirNum: ETO_9000EData.templateA.newReservoirNum }),
                ...(ETO_9000EData.templateA.typeMonitor && { typeMonitor: ETO_9000EData.templateA.typeMonitor }),
                ...(ETO_9000EData.templateA.driveMotorAmp && { driveMotorAmp: ETO_9000EData.templateA.driveMotorAmp }),
                ...(ETO_9000EData.templateA.driveMotorAmpNum && { driveMotorAmpNum: ETO_9000EData.templateA.driveMotorAmpNum }),
                ...(ETO_9000EData.templateA.driveTakeUpAir && { driveTakeUpAir: ETO_9000EData.templateA.driveTakeUpAir }),
                ...(ETO_9000EData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_9000EData.templateA.driveTakeUpAirNum }),
                ...(ETO_9000EData.templateA.takeUpDistance && { takeUpDistance: ETO_9000EData.templateA.takeUpDistance }),
                ...(ETO_9000EData.templateA.takeUpDistanceNum && { takeUpDistanceNum: ETO_9000EData.templateA.takeUpDistanceNum }),
                ...(ETO_9000EData.templateA.driveTemp && { driveTemp: ETO_9000EData.templateA.driveTemp }),
                ...(ETO_9000EData.templateA.driveTempNum && { driveTempNum: ETO_9000EData.templateA.driveTempNum }),
                ...(ETO_9000EData.templateA.driveVibration && { driveVibration: ETO_9000EData.templateA.driveVibration }),
                ...(ETO_9000EData.templateA.driveVibrationNum && { driveVibrationNum: ETO_9000EData.templateA.driveVibrationNum }),
                ...(ETO_9000EData.templateA.dogPitch && { dogPitch: ETO_9000EData.templateA.dogPitch }),
                ...(ETO_9000EData.templateA.dogPitchNum && { dogPitchNum: ETO_9000EData.templateA.dogPitchNum }),
                ...(ETO_9000EData.templateA.paintMarker && { paintMarker: ETO_9000EData.templateA.paintMarker }),
                ...(ETO_9000EData.templateA.paintMarkerNum && { paintMarkerNum: ETO_9000EData.templateA.paintMarkerNum }),
                ...(ETO_9000EData.templateA.chainVision && { chainVision: ETO_9000EData.templateA.chainVision }),
                ...(ETO_9000EData.templateA.lubeVision && { lubeVision: ETO_9000EData.templateA.lubeVision }),
                ...(ETO_9000EData.templateA.trolleyVision && { trolleyVision: ETO_9000EData.templateA.trolleyVision }),
                ...(ETO_9000EData.templateA.trolleyDetect && { trolleyDetect: ETO_9000EData.templateA.trolleyDetect }),
                ...(ETO_9000EData.templateA.omniView && { omniView: ETO_9000EData.templateA.omniView }),
                ...(ETO_9000EData.templateA.dcuUpgradeNum && { dcuUpgradeNum: ETO_9000EData.templateA.dcuUpgradeNum }),
                ...(ETO_9000EData.templateA.piuDistance && { piuDistance: ETO_9000EData.templateA.piuDistance }),
                ...(ETO_9000EData.templateA.switchDistance && { switchDistance: ETO_9000EData.templateA.switchDistance }),
                ...(ETO_9000EData.templateA.ampPickup && { ampPickup: ETO_9000EData.templateA.ampPickup }),
                ...(ETO_9000EData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_9000EData.templateA.fromAirTakeUpDistance }),
                ...(ETO_9000EData.templateA.specialControllerOptions && { specialControllerOptions: ETO_9000EData.templateA.specialControllerOptions }),
                ...(ETO_9000EData.templateA.operatingVoltage && { operatingVoltage: ETO_9000EData.templateA.operatingVoltage })
            },

            addFreeCarrier: ETO_9000EData.addFreeCarrier,

            templateBData: 
            {
                
                conveyorName: ETO_9000EData.templateB.conveyorName,
                industrialChainManufacturer: ETO_9000EData.templateB.industrialChainManufacturer,
                ...(ETO_9000EData.templateB.otherChainManufacturer && { otherChainManufacturer: ETO_9000EData.templateB.otherChainManufacturer }),
                wheelManufacturer: ETO_9000EData.templateB.wheelManufacturer,
                ...(ETO_9000EData.templateB.wheelManufacturer && { wheelManufacturer: ETO_9000EData.templateB.wheelManufacturer}),
                conveyorSpeed: ETO_9000EData.templateB.conveyorSpeed,
                conveyorSpeedUnit: ETO_9000EData.templateB.conveyorSpeedUnit,
                conveyorIndex: ETO_9000EData.templateB.conveyorIndex,
                ...(ETO_9000EData.templateB.travelDirection && { travelDirection: ETO_9000EData.templateB.travelDirection}),
                appEnviroment: ETO_9000EData.templateB.appEnviroment,
                ...(ETO_9000EData.templateB.otherAppEnviroment && { otherAppEnviroment: ETO_9000EData.templateB.otherAppEnviroment}),
                surroundingTemp: ETO_9000EData.templateB.surroundingTemp,
                orientationType: ETO_9000EData.templateB.orientationType,
                operatingVoltage: ETO_9000EData.templateB.operatingVoltage,
                controlVoltSingle: ETO_9000EData.templateB.controlVoltSingle,
                compressedAir: ETO_9000EData.templateB.compressedAir,
                ...(ETO_9000EData.templateB.airSupplyType && { airSupplyType: ETO_9000EData.templateB.airSupplyType}),

                templateA_BData: {
                    
                    existingMonitor: ETO_9000EData.templateA.existingMonitor,
                    newMonitor: ETO_9000EData.templateA.newMonitor,		
                    ...(ETO_9000EData.templateA.dcuStatus && { dcuStatus: ETO_9000EData.templateA.dcuStatus }),
                    ...(ETO_9000EData.templateA.dcuNum && { dcuNum: ETO_9000EData.templateA.dcuNum }),
                    ...(ETO_9000EData.templateA.existingWindows && { existingWindows: ETO_9000EData.templateA.existingWindows }),
                    ...(ETO_9000EData.templateA.existingHeadUnit && { existingHeadUnit: ETO_9000EData.templateA.existingHeadUnit }),
                    ...(ETO_9000EData.templateA.existingDCU && { existingDCU: ETO_9000EData.templateA.existingDCU }),
                    ...(ETO_9000EData.templateA.existingPowerInterface && { existingPowerInterface: ETO_9000EData.templateA.existingPowerInterface }),
                    ...(ETO_9000EData.templateA.newReservoir && { newReservoir: ETO_9000EData.templateA.newReservoir }),
                    ...(ETO_9000EData.templateA.reservoirSize && { reservoirSize: ETO_9000EData.templateA.reservoirSize }),
                    ...(ETO_9000EData.templateA.otherReservoirSize && { otherReservoirSize: ETO_9000EData.templateA.otherReservoirSize }),
                    ...(ETO_9000EData.templateA.newReservoirNum && { newReservoirNum: ETO_9000EData.templateA.newReservoirNum }),
                    ...(ETO_9000EData.templateA.typeMonitor && { typeMonitor: ETO_9000EData.templateA.typeMonitor }),
                    ...(ETO_9000EData.templateA.driveMotorAmp && { driveMotorAmp: ETO_9000EData.templateA.driveMotorAmp }),
                    ...(ETO_9000EData.templateA.driveMotorAmpNum && { driveMotorAmpNum: ETO_9000EData.templateA.driveMotorAmpNum }),
                    ...(ETO_9000EData.templateA.driveTakeUpAir && { driveTakeUpAir: ETO_9000EData.templateA.driveTakeUpAir }),
                    ...(ETO_9000EData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_9000EData.templateA.driveTakeUpAirNum }),
                    ...(ETO_9000EData.templateA.takeUpDistance && { takeUpDistance: ETO_9000EData.templateA.takeUpDistance }),
                    ...(ETO_9000EData.templateA.takeUpDistanceNum && { takeUpDistanceNum: ETO_9000EData.templateA.takeUpDistanceNum }),
                    ...(ETO_9000EData.templateA.driveTemp && { driveTemp: ETO_9000EData.templateA.driveTemp }),
                    ...(ETO_9000EData.templateA.driveTempNum && { driveTempNum: ETO_9000EData.templateA.driveTempNum }),
                    ...(ETO_9000EData.templateA.driveVibration && { driveVibration: ETO_9000EData.templateA.driveVibration }),
                    ...(ETO_9000EData.templateA.driveVibrationNum && { driveVibrationNum: ETO_9000EData.templateA.driveVibrationNum }),
                    ...(ETO_9000EData.templateA.dogPitch && { dogPitch: ETO_9000EData.templateA.dogPitch }),
                    ...(ETO_9000EData.templateA.dogPitchNum && { dogPitchNum: ETO_9000EData.templateA.dogPitchNum }),
                    ...(ETO_9000EData.templateA.paintMarker && { paintMarker: ETO_9000EData.templateA.paintMarker }),
                    ...(ETO_9000EData.templateA.paintMarkerNum && { paintMarkerNum: ETO_9000EData.templateA.paintMarkerNum }),
                    ...(ETO_9000EData.templateA.chainVision && { chainVision: ETO_9000EData.templateA.chainVision }),
                    ...(ETO_9000EData.templateA.lubeVision && { lubeVision: ETO_9000EData.templateA.lubeVision }),
                    ...(ETO_9000EData.templateA.trolleyVision && { trolleyVision: ETO_9000EData.templateA.trolleyVision }),
                    ...(ETO_9000EData.templateA.trolleyDetect && { trolleyDetect: ETO_9000EData.templateA.trolleyDetect }),
                    ...(ETO_9000EData.templateA.omniView && { omniView: ETO_9000EData.templateA.omniView }),
                    ...(ETO_9000EData.templateA.dcuUpgradeNum && { dcuUpgradeNum: ETO_9000EData.templateA.dcuUpgradeNum }),
                    ...(ETO_9000EData.templateA.piuDistance && { piuDistance: ETO_9000EData.templateA.piuDistance }),
                    ...(ETO_9000EData.templateA.switchDistance && { switchDistance: ETO_9000EData.templateA.switchDistance }),
                    ...(ETO_9000EData.templateA.ampPickup && { ampPickup: ETO_9000EData.templateA.ampPickup }),
                    ...(ETO_9000EData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_9000EData.templateA.fromAirTakeUpDistance }),
                    ...(ETO_9000EData.templateA.specialControllerOptions && { specialControllerOptions: ETO_9000EData.templateA.specialControllerOptions }),
                    ...(ETO_9000EData.templateA.operatingVoltage && { operatingVoltage: ETO_9000EData.templateA.operatingVoltage })

                },

                freeWheelStatus: ETO_9000EData.templateB.freeWheelStatus,
                actuatorStatus: ETO_9000EData.templateB.actuatorStatus,
                ...(ETO_9000EData.templateB.pivotStatus && { pivotStatus: ETO_9000EData.templateB.pivotStatus}),
                kingPinStatus: ETO_9000EData.templateB.kingPinStatus,
                lubeBrand: ETO_9000EData.templateB.lubeBrand,
                lubeViscosity: ETO_9000EData.templateB.lubeViscosity,
                ...(ETO_9000EData.templateB.lubeType && { lubeType: ETO_9000EData.templateB.lubeType}),
                currentGrease: ETO_9000EData.templateB.currentGrease,
                currentGreaseGrade: ETO_9000EData.templateB.currentGreaseGrade,
                zerkDirection: ETO_9000EData.templateB.zerkDirection,
                zerkLocationType: ETO_9000EData.templateB.zerkLocationType,
                wheelDiameter: ETO_9000EData.templateB.wheelDiameter,
                conveyorSwing: ETO_9000EData.templateB.conveyorSwing,
                ...(ETO_9000EData.templateB.chainMaster && { chainMaster: ETO_9000EData.templateB.chainMaster}),
                ...(ETO_9000EData.templateB.remoteStatus && { remoteStatus: ETO_9000EData.templateB.remoteStatus}),
                ...(ETO_9000EData.templateB.mountStatus && { mountStatus: ETO_9000EData.templateB.mountStatus}),
                ...(ETO_9000EData.templateB.otherUnitStatus && { otherUnitStatus: ETO_9000EData.templateB.otherUnitStatus}),
                ...(ETO_9000EData.templateB.timerStatus && { timerStatus: ETO_9000EData.templateB.timerStatus}),
                ...(ETO_9000EData.templateB.electricStatus && { electricStatus: ETO_9000EData.templateB.electricStatus}),
                ...(ETO_9000EData.templateB.mightyLubeMonitoring && { mightyLubeMonitoring: ETO_9000EData.templateB.mightyLubeMonitoring}),
                ...(ETO_9000EData.templateB.preMountType && { preMountType: ETO_9000EData.templateB.preMountType}),
                ...(ETO_9000EData.templateB.otherPreMountType && { otherPreMountType: ETO_9000EData.templateB.otherPreMountType}),
                ...(ETO_9000EData.templateB.plcConnection && { plcConnection: ETO_9000EData.templateB.plcConnection}),
                ...(ETO_9000EData.templateB.otherControllerNotes && { otherControllerNotes: ETO_9000EData.templateB.otherControllerNotes}),
                ...(ETO_9000EData.templateB.templateB_UnitType && { templateB_UnitType: ETO_9000EData.templateB.templateB_UnitType}),
                ...(ETO_9000EData.templateB.templateB_InvertedB && { templateB_InvertedB: ETO_9000EData.templateB.templateB_InvertedB}),
                ...(ETO_9000EData.templateB.templateB_InvertedE && { templateB_InvertedE: ETO_9000EData.templateB.templateB_InvertedE}),
                ...(ETO_9000EData.templateB.templateB_InvertedG && { templateB_InvertedG: ETO_9000EData.templateB.templateB_InvertedG}),
                ...(ETO_9000EData.templateB.templateB_InvertedH && { templateB_InvertedH: ETO_9000EData.templateB.templateB_InvertedH}),
                ...(ETO_9000EData.templateB.templateB_InvertedK && { templateB_InvertedK: ETO_9000EData.templateB.templateB_InvertedK}),
                ...(ETO_9000EData.templateB.templateB_InvertedT && { templateB_InvertedT: ETO_9000EData.templateB.templateB_InvertedT}),
                ...(ETO_9000EData.templateB.templateB_InvertedU && { templateB_InvertedU: ETO_9000EData.templateB.templateB_InvertedU}),
                ...(ETO_9000EData.templateB.templateB_InvertedV && { templateB_InvertedV: ETO_9000EData.templateB.templateB_InvertedV}),
                ...(ETO_9000EData.templateB.templateB_InvertedW && { templateB_InvertedW: ETO_9000EData.templateB.templateB_InvertedW}),

            },
            
            templateCData: 
            {
            conveyorName: ETO_9000EData.templateC.conveyorName,
            industrialChainManufacturer: ETO_9000EData.templateC.industrialChainManufacturer,
            ...(ETO_9000EData.templateC.otherChainManufacturer && { otherChainManufacturer: ETO_9000EData.templateC.otherChainManufacturer }),
            wheelManufacturer: ETO_9000EData.templateC.wheelManufacturer,
            ...(ETO_9000EData.templateC.wheelManufacturer && { wheelManufacturer: ETO_9000EData.templateC.wheelManufacturer}),
            conveyorSpeed: ETO_9000EData.templateC.conveyorSpeed,
            conveyorSpeedUnit: ETO_9000EData.templateC.conveyorSpeedUnit,
            conveyorIndex: ETO_9000EData.templateC.conveyorIndex,
            ...(ETO_9000EData.templateC.travelDirection && { travelDirection: ETO_9000EData.templateC.travelDirection}),
            appEnviroment: ETO_9000EData.templateC.appEnviroment,
            ...(ETO_9000EData.templateC.otherAppEnviroment && { otherAppEnviroment: ETO_9000EData.templateC.otherAppEnviroment}),
            surroundingTemp: ETO_9000EData.templateC.surroundingTemp,
            orientationType: ETO_9000EData.templateC.orientationType,
            guideWheelsEven: ETO_9000EData.templateC.guideWheelsEven,
            operatingVoltage: ETO_9000EData.templateC.operatingVoltage,
            controlVoltSingle: ETO_9000EData.templateC.controlVoltSingle,
            compressedAir: ETO_9000EData.templateC.compressedAir,
            ...(ETO_9000EData.templateC.airSupplyType && { airSupplyType: ETO_9000EData.templateC.airSupplyType}),

            templateA_CData: 
            {
                existingMonitor: ETO_9000EData.templateA.existingMonitor,
                newMonitor: ETO_9000EData.templateA.newMonitor,		
                ...(ETO_9000EData.templateA.dcuStatus && { dcuStatus: ETO_9000EData.templateA.dcuStatus }),
                ...(ETO_9000EData.templateA.dcuNum && { dcuNum: ETO_9000EData.templateA.dcuNum }),
                ...(ETO_9000EData.templateA.existingWindows && { existingWindows: ETO_9000EData.templateA.existingWindows }),
                ...(ETO_9000EData.templateA.existingHeadUnit && { existingHeadUnit: ETO_9000EData.templateA.existingHeadUnit }),
                ...(ETO_9000EData.templateA.existingDCU && { existingDCU: ETO_9000EData.templateA.existingDCU }),
                ...(ETO_9000EData.templateA.existingPowerInterface && { existingPowerInterface: ETO_9000EData.templateA.existingPowerInterface }),
                ...(ETO_9000EData.templateA.newReservoir && { newReservoir: ETO_9000EData.templateA.newReservoir }),
                ...(ETO_9000EData.templateA.reservoirSize && { reservoirSize: ETO_9000EData.templateA.reservoirSize }),
                ...(ETO_9000EData.templateA.otherReservoirSize && { otherReservoirSize: ETO_9000EData.templateA.otherReservoirSize }),
                ...(ETO_9000EData.templateA.newReservoirNum && { newReservoirNum: ETO_9000EData.templateA.newReservoirNum }),
                ...(ETO_9000EData.templateA.typeMonitor && { typeMonitor: ETO_9000EData.templateA.typeMonitor }),
                ...(ETO_9000EData.templateA.driveMotorAmp && { driveMotorAmp: ETO_9000EData.templateA.driveMotorAmp }),
                ...(ETO_9000EData.templateA.driveMotorAmpNum && { driveMotorAmpNum: ETO_9000EData.templateA.driveMotorAmpNum }),
                ...(ETO_9000EData.templateA.driveTakeUpAir && { driveTakeUpAir: ETO_9000EData.templateA.driveTakeUpAir }),
                ...(ETO_9000EData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_9000EData.templateA.driveTakeUpAirNum }),
                ...(ETO_9000EData.templateA.takeUpDistance && { takeUpDistance: ETO_9000EData.templateA.takeUpDistance }),
                ...(ETO_9000EData.templateA.takeUpDistanceNum && { takeUpDistanceNum: ETO_9000EData.templateA.takeUpDistanceNum }),
                ...(ETO_9000EData.templateA.driveTemp && { driveTemp: ETO_9000EData.templateA.driveTemp }),
                ...(ETO_9000EData.templateA.driveTempNum && { driveTempNum: ETO_9000EData.templateA.driveTempNum }),
                ...(ETO_9000EData.templateA.driveVibration && { driveVibration: ETO_9000EData.templateA.driveVibration }),
                ...(ETO_9000EData.templateA.driveVibrationNum && { driveVibrationNum: ETO_9000EData.templateA.driveVibrationNum }),
                ...(ETO_9000EData.templateA.dogPitch && { dogPitch: ETO_9000EData.templateA.dogPitch }),
                ...(ETO_9000EData.templateA.dogPitchNum && { dogPitchNum: ETO_9000EData.templateA.dogPitchNum }),
                ...(ETO_9000EData.templateA.paintMarker && { paintMarker: ETO_9000EData.templateA.paintMarker }),
                ...(ETO_9000EData.templateA.paintMarkerNum && { paintMarkerNum: ETO_9000EData.templateA.paintMarkerNum }),
                ...(ETO_9000EData.templateA.chainVision && { chainVision: ETO_9000EData.templateA.chainVision }),
                ...(ETO_9000EData.templateA.lubeVision && { lubeVision: ETO_9000EData.templateA.lubeVision }),
                ...(ETO_9000EData.templateA.trolleyVision && { trolleyVision: ETO_9000EData.templateA.trolleyVision }),
                ...(ETO_9000EData.templateA.trolleyDetect && { trolleyDetect: ETO_9000EData.templateA.trolleyDetect }),
                ...(ETO_9000EData.templateA.omniView && { omniView: ETO_9000EData.templateA.omniView }),
                ...(ETO_9000EData.templateA.dcuUpgradeNum && { dcuUpgradeNum: ETO_9000EData.templateA.dcuUpgradeNum }),
                ...(ETO_9000EData.templateA.piuDistance && { piuDistance: ETO_9000EData.templateA.piuDistance }),
                ...(ETO_9000EData.templateA.switchDistance && { switchDistance: ETO_9000EData.templateA.switchDistance }),
                ...(ETO_9000EData.templateA.ampPickup && { ampPickup: ETO_9000EData.templateA.ampPickup }),
                ...(ETO_9000EData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_9000EData.templateA.fromAirTakeUpDistance }),
                ...(ETO_9000EData.templateA.specialControllerOptions && { specialControllerOptions: ETO_9000EData.templateA.specialControllerOptions }),
                ...(ETO_9000EData.templateA.operatingVoltage && { operatingVoltage: ETO_9000EData.templateA.operatingVoltage })
            },
            
            freeWheelStatus: ETO_9000EData.templateC.freeWheelStatus,
            actuatorStatus: ETO_9000EData.templateC.actuatorStatus,
            ...(ETO_9000EData.templateC.pivotStatus && { pivotStatus: ETO_9000EData.templateC.pivotStatus}),
            kingPinStatus: ETO_9000EData.templateC.kingPinStatus,
            lubeBrand: ETO_9000EData.templateC.lubeBrand,
            lubeViscosity: ETO_9000EData.templateC.lubeViscosity,
            ...(ETO_9000EData.templateC.lubeType && { lubeType: ETO_9000EData.templateC.lubeType}),
            currentGrease: ETO_9000EData.templateC.currentGrease,
            currentGreaseGrade: ETO_9000EData.templateC.currentGreaseGrade,
            zerkDirection: ETO_9000EData.templateC.zerkDirection,
            zerkLocationType: ETO_9000EData.templateC.zerkLocationType,
            wheelDiameter: ETO_9000EData.templateC.wheelDiameter,
            conveyorSwing: ETO_9000EData.templateC.conveyorSwing,
            ...(ETO_9000EData.templateC.chainMaster && { lubeType: ETO_9000EData.templateC.chainMaster}),
            ...(ETO_9000EData.templateC.remoteStatus && { lubeType: ETO_9000EData.templateC.remoteStatus}),
            ...(ETO_9000EData.templateC.mountStatus && { lubeType: ETO_9000EData.templateC.mountStatus}),
            ...(ETO_9000EData.templateC.otherUnitStatus && { lubeType: ETO_9000EData.templateC.otherUnitStatus}),
            ...(ETO_9000EData.templateC.timerStatus && { lubeType: ETO_9000EData.templateC.timerStatus}),
            ...(ETO_9000EData.templateC.electricStatus && { lubeType: ETO_9000EData.templateC.electricStatus}),
            ...(ETO_9000EData.templateC.mightyLubeMonitoring && { lubeType: ETO_9000EData.templateC.mightyLubeMonitoring}),
            ...(ETO_9000EData.templateC.preMountType && { lubeType: ETO_9000EData.templateC.preMountType}),
            ...(ETO_9000EData.templateC.otherPreMountType && { lubeType: ETO_9000EData.templateC.otherPreMountType}),
            ...(ETO_9000EData.templateC.plcConnection && { lubeType: ETO_9000EData.templateC.plcConnection}),
            ...(ETO_9000EData.templateC.otherControllerNotes && { lubeType: ETO_9000EData.templateC.otherControllerNotes}),
            ...(ETO_9000EData.templateC.templateC_UnitType && { lubeType: ETO_9000EData.templateC.templateC_UnitType}),
            templateC_InvertedA: ETO_9000EData.templateC.templateC_InvertedA,
            templateC_InvertedB: ETO_9000EData.templateC.templateC_InvertedB,
            templateC_InvertedE: ETO_9000EData.templateC.templateC_InvertedE,
            templateC_InvertedS: ETO_9000EData.templateC.templateC_InvertedS,
        },
        

            catDriveStatus: ETO_9000EData.catDriveStatus,

            templateEData: 
            {
                conveyorName: ETO_9000EData.templateE.conveyorName,
                ...(ETO_9000EData.templateE.chainSize && { chainSize: ETO_9000EData.templateE.chainSize }),
                ...(ETO_9000EData.templateE.otherChainSize && { otherChainSize: ETO_9000EData.templateE.otherChainSize }),
                ...(ETO_9000EData.templateE.industrialChainManufacturer && { industrialChainManufacturer: ETO_9000EData.templateE.industrialChainManufacturer }),
                ...(ETO_9000EData.templateE.otherChainManufacturer && { otherChainManufacturer: ETO_9000EData.templateE.otherChainManufacturer }),
                ...(ETO_9000EData.templateE.conveyorLength && { conveyorLength: ETO_9000EData.templateE.conveyorLength }),
                ...(ETO_9000EData.templateE.conveyorLengthUnit && { conveyorLengthUnit: ETO_9000EData.templateE.conveyorLengthUnit }),
                ...(ETO_9000EData.templateE.appEnviroment && { appEnviroment: ETO_9000EData.templateE.appEnviroment }),
                ...(ETO_9000EData.templateE.otherAppEnviroment && { otherAppEnviroment: ETO_9000EData.templateE.otherAppEnviroment }),
                ...(ETO_9000EData.templateE.lubeBrand && { lubeBrand: ETO_9000EData.templateE.lubeBrand }),
                ...(ETO_9000EData.templateE.lubeType && { lubeType: ETO_9000EData.templateE.lubeType }),
                ...(ETO_9000EData.templateE.lubeViscosity && { lubeViscosity: ETO_9000EData.templateE.lubeViscosity }),
                ...(ETO_9000EData.templateE.specialControllerOptions && { specialControllerOptions: ETO_9000EData.templateE.specialControllerOptions }),
                ...(ETO_9000EData.templateE.wireMeasurementUnit && { wireMeasurementUnit: ETO_9000EData.templateE.wireMeasurementUnit }),
                ...(ETO_9000EData.templateE.conductor2 && { conductor2: ETO_9000EData.templateE.conductor2 }),
                ...(ETO_9000EData.templateE.conductor4 && { conductor4: ETO_9000EData.templateE.conductor4 }),
                ...(ETO_9000EData.templateE.conductor7 && { conductor7: ETO_9000EData.templateE.conductor7 }),
                ...(ETO_9000EData.templateE.conductor12 && { conductor12: ETO_9000EData.templateE.conductor12 }),
                ...(ETO_9000EData.templateE.junctionBoxNum && { junctionBoxNum: ETO_9000EData.templateE.junctionBoxNum }),

            },         
       
            ...(ETO_9000EData.catDriveNum && { catDriveNum: ETO_9000EData.catDriveNum }),
            ...(ETO_9000EData.externalLubeStatus && { externalLubeStatus: ETO_9000EData.externalLubeStatus }),
            ...(ETO_9000EData.lubeBrand && { lubeBrand: ETO_9000EData.lubeBrand }),
            ...(ETO_9000EData.lubeType && { lubeType: ETO_9000EData.lubeType }),
            ...(ETO_9000EData.lubeViscosity && { lubeViscosity: ETO_9000EData.lubeViscosity }),
            ...(ETO_9000EData.chainMaster && { chainMaster: ETO_9000EData.chainMaster }),
            ...(ETO_9000EData.timerStatus && { timerStatus: ETO_9000EData.timerStatus }),
            ...(ETO_9000EData.electricStatus && { electricStatus: ETO_9000EData.electricStatus }),
            ...(ETO_9000EData.pneumaticStatus && { pneumaticStatus: ETO_9000EData.pneumaticStatus }),
            ...(ETO_9000EData.mightyLubeMonitoring && { mightyLubeMonitoring: ETO_9000EData.mightyLubeMonitoring }),
            ...(ETO_9000EData.plcConnection && { plcConnection: ETO_9000EData.plcConnection }),
            ...(ETO_9000EData.otherControllerInfo && { otherControllerInfo: ETO_9000EData.otherControllerInfo }),
            ...(ETO_9000EData.wireMeasurementUnit && { wireMeasurementUnit: ETO_9000EData.wireMeasurementUnit }),
            ...(ETO_9000EData.conductor2 && { conductor2: ETO_9000EData.conductor2 }),
            ...(ETO_9000EData.conductor4 && { conductor4: ETO_9000EData.conductor4 }),
            ...(ETO_9000EData.conductor7 && { conductor7: ETO_9000EData.conductor7 }),
            ...(ETO_9000EData.conductor12 && { conductor12: ETO_9000EData.conductor12 }),
            ...(ETO_9000EData.junctionBoxNum && { junctionBoxNum: ETO_9000EData.junctionBoxNum }),
            ...(ETO_9000EData.enclosedUnitType && { enclosedUnitType: ETO_9000EData.enclosedUnitType }),
            ...(ETO_9000EData.enclosedTrackB && { enclosedTrackB: ETO_9000EData.enclosedTrackB }),
            ...(ETO_9000EData.enclosedTrackG && { enclosedTrackG: ETO_9000EData.enclosedTrackG }),
            ...(ETO_9000EData.enclosedTrackH && { enclosedTrackH: ETO_9000EData.enclosedTrackH }),
            ...(ETO_9000EData.enclosedTrackS && { enclosedTrackS: ETO_9000EData.enclosedTrackS }),
            ...(ETO_9000EData.enclosedTrackK2 && { enclosedTrackK2: ETO_9000EData.enclosedTrackK2 }),
            ...(ETO_9000EData.enclosedTrackL2 && { enclosedTrackL2: ETO_9000EData.enclosedTrackL2 }),
            ...(ETO_9000EData.enclosedTrackM2 && { enclosedTrackM2: ETO_9000EData.enclosedTrackM2 }),
            ...(ETO_9000EData.enclosedTrackN2 && { enclosedTrackN2: ETO_9000EData.enclosedTrackN2 }),
            ...(ETO_9000EData.enclosedTrackS2 && { enclosedTrackS2: ETO_9000EData.enclosedTrackS2 })
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "ETO_9000E"
        });
        await req.user.save();
        return res.status(200).json({ message: "ETO_9000E entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;