const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const ETO_OP48E = require("../models/ETO_OP48E");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");
const templateF= require("../models/templateF"); 
const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { ETO_OP48EData, numRequested } = req.body;
        const order = new ETO_OP48E({
            ...(ETO_OP48EData.chainSize && { chainSize: ETO_OP48EData.chainSize }),
            ...(ETO_OP48EData.otherChainSize && { otherChainSize: ETO_OP48EData.otherChainSize }),            
            industrialChainManufacturer: ETO_OP48EData.industrialChainManufacturer,
            ...(ETO_OP48EData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: ETO_OP48EData.otherIndustrialChainManufacturer }),
            ...(ETO_OP48EData.conveyorLength && { conveyorLength: ETO_OP48EData.conveyorLength }),
            ...(ETO_OP48EData.conveyorLengthUnit && { conveyorLengthUnit: ETO_OP48EData.conveyorLengthUnit }),
            ...(ETO_OP48EData.conveyorSpeed && { conveyorSpeed: ETO_OP48EData.conveyorSpeed }),
            ...(ETO_OP48EData.conveyorSpeedUnit && { conveyorSpeedUnit: ETO_OP48EData.conveyorSpeedUnit }),
            ...(ETO_OP48EData.conveyorIndex && { conveyorIndex: ETO_OP48EData.conveyorIndex }),
            ...(ETO_OP48EData.travelDirection && { travelDirection: ETO_OP48EData.travelDirection }),
            appEnviroment: ETO_OP48EData.appEnviroment,
            ...(ETO_OP48EData.ovenStatus && { ovenStatus: ETO_OP48EData.ovenStatus }),
            ...(ETO_OP48EData.ovenTemp && { ovenTemp: ETO_OP48EData.ovenTemp }),
            ...(ETO_OP48EData.otherAppEnviroment && { otherAppEnviroment: ETO_OP48EData.otherAppEnviroment }),
            ...(ETO_OP48EData.surroundingTemp && { surroundingTemp: ETO_OP48EData.surroundingTemp }),
            ...(ETO_OP48EData.conveyorLoaded && { conveyorLoaded: ETO_OP48EData.conveyorLoaded }),
            ...(ETO_OP48EData.conveyorSwing && { conveyorSwing: ETO_OP48EData.conveyorSwing }),

            operatingVoltage: ETO_OP48EData.operatingVoltage,
            controlVoltage: ETO_OP48EData.controlVoltage,


            existingMonitor: ETO_OP48EData.existingMonitor,
            newMonitor: ETO_OP48EData.newMonitor,
            monitorData: {
                ...(ETO_OP48EData.dcuStatus && { dcuStatus: ETO_OP48EData.dcuStatus }),
                ...(ETO_OP48EData.dcuNum && { dcuNum: ETO_OP48EData.dcuNum }),
                ...(ETO_OP48EData.existingWindows && { existingWindows: ETO_OP48EData.existingWindows }),
                ...(ETO_OP48EData.existingHeadUnit && { existingHeadUnit: ETO_OP48EData.existingHeadUnit }),
                ...(ETO_OP48EData.existingDCU && { existingDCU: ETO_OP48EData.existingDCU }),
                ...(ETO_OP48EData.existingPowerInterface && { existingPowerInterface: ETO_OP48EData.existingPowerInterface }),
                ...(ETO_OP48EData.newReservoir && { newReservoir: ETO_OP48EData.newReservoir }),
                ...(ETO_OP48EData.reservoirSize && { reservoirSize: ETO_OP48EData.reservoirSize }),
                ...(ETO_OP48EData.otherReservoirSize && { otherReservoirSize: ETO_OP48EData.otherReservoirSize }),
                ...(ETO_OP48EData.newReservoirNum && { newReservoirNum: ETO_OP48EData.newReservoirNum }),
                ...(ETO_OP48EData.typeMonitor && { typeMonitor: ETO_OP48EData.typeMonitor }),
                ...(ETO_OP48EData.driveMotorAmp && { driveMotorAmp: ETO_OP48EData.driveMotorAmp }),
                ...(ETO_OP48EData.driveMotorAmpNum && { driveMotorAmpNum: ETO_OP48EData.driveMotorAmpNum }),
                ...(ETO_OP48EData.driveTakeUpAir && { driveTakeUpAir: ETO_OP48EData.driveTakeUpAir }),
                ...(ETO_OP48EData.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_OP48EData.driveTakeUpAirNum }),
                ...(ETO_OP48EData.takeUpDistance && { takeUpDistance: ETO_OP48EData.takeUpDistance }),
                ...(ETO_OP48EData.takeUpDistanceNum && { takeUpDistanceNum: ETO_OP48EData.takeUpDistanceNum }),
                ...(ETO_OP48EData.driveTemp && { driveTemp: ETO_OP48EData.driveTemp }),
                ...(ETO_OP48EData.driveTempNum && { driveTempNum: ETO_OP48EData.driveTempNum }),
                ...(ETO_OP48EData.driveVibration && { driveVibration: ETO_OP48EData.driveVibration }),
                ...(ETO_OP48EData.driveVibrationNum && { driveVibrationNum: ETO_OP48EData.driveVibrationNum }),
                ...(ETO_OP48EData.dogPitch && { dogPitch: ETO_OP48EData.dogPitch }),
                ...(ETO_OP48EData.dogPitchNum && { dogPitchNum: ETO_OP48EData.dogPitchNum }),
                ...(ETO_OP48EData.paintMarker && { paintMarker: ETO_OP48EData.paintMarker }),
                ...(ETO_OP48EData.paintMarkerNum && { paintMarkerNum: ETO_OP48EData.paintMarkerNum }),
                ...(ETO_OP48EData.chainVision && { chainVision: ETO_OP48EData.chainVision }),
                ...(ETO_OP48EData.lubeVision && { lubeVision: ETO_OP48EData.lubeVision }),
                ...(ETO_OP48EData.trolleyVision && { trolleyVision: ETO_OP48EData.trolleyVision }),
                ...(ETO_OP48EData.trolleyDetect && { trolleyDetect: ETO_OP48EData.trolleyDetect }),
                ...(ETO_OP48EData.omniView && { omniView: ETO_OP48EData.omniView }),
                ...(ETO_OP48EData.dcuUpgradeNum && { dcuUpgradeNum: ETO_OP48EData.dcuUpgradeNum }),
                ...(ETO_OP48EData.itNameOne && { itNameOne: ETO_OP48EData.itNameOne }),
                ...(ETO_OP48EData.itIPOne && { itIPOne: ETO_OP48EData.itIPOne }),
                ...(ETO_OP48EData.itGatewayOne && { itGatewayOne: ETO_OP48EData.itGatewayOne }),
                ...(ETO_OP48EData.itSubnetOne && { itSubnetOne: ETO_OP48EData.itSubnetOne }),
                ...(ETO_OP48EData.itDNSOne && { itDNSOne: ETO_OP48EData.itDNSOne }),
                ...(ETO_OP48EData.itSMTPOne && { itSMTPOne: ETO_OP48EData.itSMTPOne }),
                ...(ETO_OP48EData.itNameTwo && { itNameTwo: ETO_OP48EData.itNameTwo }),
                ...(ETO_OP48EData.itIPTwo && { itIPTwo: ETO_OP48EData.itIPTwo }),
                ...(ETO_OP48EData.itGatewayTwo && { itGatewayTwo: ETO_OP48EData.itGatewayTwo }),
                ...(ETO_OP48EData.itSubnetTwo && { itSubnetTwo: ETO_OP48EData.itSubnetTwo }),
                ...(ETO_OP48EData.itDNSTwo && { itDNSTwo: ETO_OP48EData.itDNSTwo }),
                ...(ETO_OP48EData.itSMTPTwo && { itSMTPTwo: ETO_OP48EData.itSMTPTwo }),
                ...(ETO_OP48EData.itNameThree && { itNameThree: ETO_OP48EData.itNameThree }),
                ...(ETO_OP48EData.itIPThree && { itIPThree: ETO_OP48EData.itIPThree }),
                ...(ETO_OP48EData.itGatewayThree && { itGatewayThree: ETO_OP48EData.itGatewayThree }),
                ...(ETO_OP48EData.itSubnetThree && { itSubnetThree: ETO_OP48EData.itSubnetThree }),
                ...(ETO_OP48EData.itDNSThree && { itDNSThree: ETO_OP48EData.itDNSThree }),
                ...(ETO_OP48EData.itSMTPThree && { itSMTPThree: ETO_OP48EData.itSMTPThree }),
                ...(ETO_OP48EData.itAdditionalNotes && { itAdditionalNotes: ETO_OP48EData.itAdditionalNotes }),
                ...(ETO_OP48EData.piuDistance && { piuDistance: ETO_OP48EData.piuDistance }),
                ...(ETO_OP48EData.switchDistance && { switchDistance: ETO_OP48EData.switchDistance }),
                ...(ETO_OP48EData.ampPickup && { ampPickup: ETO_OP48EData.ampPickup }),
                ...(ETO_OP48EData.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_OP48EData.fromAirTakeUpDistance }),
                ...(ETO_OP48EData.specialControllerOptions && { specialControllerOptions: ETO_OP48EData.specialControllerOptions }),
                ...(ETO_OP48EData.operatingVoltage && { operatingVoltage: ETO_OP48EData.operatingVoltage })

            },

            addFreeCarrier: ETO_OP48EData.addFreeCarrier,

            templateBData: {
                conveyorName: ETO_OP48EData.conveyorName,
                industrialChainManufacturer: ETO_OP48EData.industrialChainManufacturer,
                ...(ETO_OP48EData.otherChainManufacturer && { otherChainManufacturer: ETO_OP48EData.otherChainManufacturer }),
                wheelManufacturer: ETO_OP48EData.wheelManufacturer,
                ...(ETO_OP48EData.wheelManufacturer && { wheelManufacturer: ETO_OP48EData.wheelManufacturer}),
                conveyorSpeed: ETO_OP48EData.conveyorSpeed,
                conveyorSpeedUnit: ETO_OP48EData.conveyorSpeedUnit,
                conveyorIndex: ETO_OP48EData.conveyorIndex,
                ...(ETO_OP48EData.travelDirection && { travelDirection: ETO_OP48EData.travelDirection}),
                appEnviroment: ETO_OP48EData.appEnviroment,
                ...(ETO_OP48EData.otherAppEnviroment && { otherAppEnviroment: ETO_OP48EData.otherAppEnviroment}),
                surroundingTemp: ETO_OP48EData.surroundingTemp,
                orientationType: ETO_OP48EData.orientationType,
                operatingVoltage: ETO_OP48EData.operatingVoltage,
                controlVoltSingle: ETO_OP48EData.controlVoltSingle,
                compressedAir: ETO_OP48EData.compressedAir,
                ...(ETO_OP48EData.airSupplyType && { airSupplyType: ETO_OP48EData.airSupplyType}),
            existingMonitor: ETO_OP48EData.existingMonitor,
            newMonitor: ETO_OP48EData.newMonitor,
            templateA_BData: {
                ...(ETO_OP48EData.dcuStatus && { dcuStatus: ETO_OP48EData.dcuStatus }),
                ...(ETO_OP48EData.dcuNum && { dcuNum: ETO_OP48EData.dcuNum }),
                ...(ETO_OP48EData.existingWindows && { existingWindows: ETO_OP48EData.existingWindows }),
                ...(ETO_OP48EData.existingHeadUnit && { existingHeadUnit: ETO_OP48EData.existingHeadUnit }),
                ...(ETO_OP48EData.existingDCU && { existingDCU: ETO_OP48EData.existingDCU }),
                ...(ETO_OP48EData.existingPowerInterface && { existingPowerInterface: ETO_OP48EData.existingPowerInterface }),
                ...(ETO_OP48EData.newReservoir && { newReservoir: ETO_OP48EData.newReservoir }),
                ...(ETO_OP48EData.reservoirSize && { reservoirSize: ETO_OP48EData.reservoirSize }),
                ...(ETO_OP48EData.otherReservoirSize && { otherReservoirSize: ETO_OP48EData.otherReservoirSize }),
                ...(ETO_OP48EData.newReservoirNum && { newReservoirNum: ETO_OP48EData.newReservoirNum }),
                ...(ETO_OP48EData.typeMonitor && { typeMonitor: ETO_OP48EData.typeMonitor }),
                ...(ETO_OP48EData.driveMotorAmp && { driveMotorAmp: ETO_OP48EData.driveMotorAmp }),
                ...(ETO_OP48EData.driveMotorAmpNum && { driveMotorAmpNum: ETO_OP48EData.driveMotorAmpNum }),
                ...(ETO_OP48EData.driveTakeUpAir && { driveTakeUpAir: ETO_OP48EData.driveTakeUpAir }),
                ...(ETO_OP48EData.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_OP48EData.driveTakeUpAirNum }),
                ...(ETO_OP48EData.takeUpDistance && { takeUpDistance: ETO_OP48EData.takeUpDistance }),
                ...(ETO_OP48EData.takeUpDistanceNum && { takeUpDistanceNum: ETO_OP48EData.takeUpDistanceNum }),
                ...(ETO_OP48EData.driveTemp && { driveTemp: ETO_OP48EData.driveTemp }),
                ...(ETO_OP48EData.driveTempNum && { driveTempNum: ETO_OP48EData.driveTempNum }),
                ...(ETO_OP48EData.driveVibration && { driveVibration: ETO_OP48EData.driveVibration }),
                ...(ETO_OP48EData.driveVibrationNum && { driveVibrationNum: ETO_OP48EData.driveVibrationNum }),
                ...(ETO_OP48EData.dogPitch && { dogPitch: ETO_OP48EData.dogPitch }),
                ...(ETO_OP48EData.dogPitchNum && { dogPitchNum: ETO_OP48EData.dogPitchNum }),
                ...(ETO_OP48EData.paintMarker && { paintMarker: ETO_OP48EData.paintMarker }),
                ...(ETO_OP48EData.paintMarkerNum && { paintMarkerNum: ETO_OP48EData.paintMarkerNum }),
                ...(ETO_OP48EData.chainVision && { chainVision: ETO_OP48EData.chainVision }),
                ...(ETO_OP48EData.lubeVision && { lubeVision: ETO_OP48EData.lubeVision }),
                ...(ETO_OP48EData.trolleyVision && { trolleyVision: ETO_OP48EData.trolleyVision }),
                ...(ETO_OP48EData.trolleyDetect && { trolleyDetect: ETO_OP48EData.trolleyDetect }),
                ...(ETO_OP48EData.omniView && { omniView: ETO_OP48EData.omniView }),
                ...(ETO_OP48EData.dcuUpgradeNum && { dcuUpgradeNum: ETO_OP48EData.dcuUpgradeNum }),
                ...(ETO_OP48EData.itNameOne && { itNameOne: ETO_OP48EData.itNameOne }),
                ...(ETO_OP48EData.itIPOne && { itIPOne: ETO_OP48EData.itIPOne }),
                ...(ETO_OP48EData.itGatewayOne && { itGatewayOne: ETO_OP48EData.itGatewayOne }),
                ...(ETO_OP48EData.itSubnetOne && { itSubnetOne: ETO_OP48EData.itSubnetOne }),
                ...(ETO_OP48EData.itDNSOne && { itDNSOne: ETO_OP48EData.itDNSOne }),
                ...(ETO_OP48EData.itSMTPOne && { itSMTPOne: ETO_OP48EData.itSMTPOne }),
                ...(ETO_OP48EData.itNameTwo && { itNameTwo: ETO_OP48EData.itNameTwo }),
                ...(ETO_OP48EData.itIPTwo && { itIPTwo: ETO_OP48EData.itIPTwo }),
                ...(ETO_OP48EData.itGatewayTwo && { itGatewayTwo: ETO_OP48EData.itGatewayTwo }),
                ...(ETO_OP48EData.itSubnetTwo && { itSubnetTwo: ETO_OP48EData.itSubnetTwo }),
                ...(ETO_OP48EData.itDNSTwo && { itDNSTwo: ETO_OP48EData.itDNSTwo }),
                ...(ETO_OP48EData.itSMTPTwo && { itSMTPTwo: ETO_OP48EData.itSMTPTwo }),
                ...(ETO_OP48EData.itNameThree && { itNameThree: ETO_OP48EData.itNameThree }),
                ...(ETO_OP48EData.itIPThree && { itIPThree: ETO_OP48EData.itIPThree }),
                ...(ETO_OP48EData.itGatewayThree && { itGatewayThree: ETO_OP48EData.itGatewayThree }),
                ...(ETO_OP48EData.itSubnetThree && { itSubnetThree: ETO_OP48EData.itSubnetThree }),
                ...(ETO_OP48EData.itDNSThree && { itDNSThree: ETO_OP48EData.itDNSThree }),
                ...(ETO_OP48EData.itSMTPThree && { itSMTPThree: ETO_OP48EData.itSMTPThree }),
                ...(ETO_OP48EData.itAdditionalNotes && { itAdditionalNotes: ETO_OP48EData.itAdditionalNotes }),
                ...(ETO_OP48EData.piuDistance && { piuDistance: ETO_OP48EData.piuDistance }),
                ...(ETO_OP48EData.switchDistance && { switchDistance: ETO_OP48EData.switchDistance }),
                ...(ETO_OP48EData.ampPickup && { ampPickup: ETO_OP48EData.ampPickup }),
                ...(ETO_OP48EData.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_OP48EData.fromAirTakeUpDistance }),
                ...(ETO_OP48EData.specialControllerOptions && { specialControllerOptions: ETO_OP48EData.specialControllerOptions }),
                ...(ETO_OP48EData.operatingVoltage && { operatingVoltage: ETO_OP48EData.operatingVoltage })

                },
                freeWheelStatus: ETO_OP48EData.freeWheelStatus,
                actuatorStatus: ETO_OP48EData.actuatorStatus,
                ...(ETO_OP48EData.pivotStatus && { pivotStatus: ETO_OP48EData.pivotStatus}),
                kingPinStatus: ETO_OP48EData.kingPinStatus,
                lubeBrand: ETO_OP48EData.lubeBrand,
                lubeViscosity: ETO_OP48EData.lubeViscosity,
                ...(ETO_OP48EData.lubeType && { lubeType: ETO_OP48EData.lubeType}),
                currentGrease: ETO_OP48EData.currentGrease,
                currentGreaseGrade: ETO_OP48EData.currentGreaseGrade,
                zerkDirection: ETO_OP48EData.zerkDirection,
                zerkLocationType: ETO_OP48EData.zerkLocationType,
                wheelDiameter: ETO_OP48EData.wheelDiameter,
                conveyorSwing: ETO_OP48EData.conveyorSwing,
                ...(ETO_OP48EData.chainMaster && { lubeType: ETO_OP48EData.chainMaster}),
                ...(ETO_OP48EData.remoteStatus && { lubeType: ETO_OP48EData.remoteStatus}),
                ...(ETO_OP48EData.mountStatus && { lubeType: ETO_OP48EData.mountStatus}),
                ...(ETO_OP48EData.otherUnitStatus && { lubeType: ETO_OP48EData.otherUnitStatus}),
                ...(ETO_OP48EData.timerStatus && { lubeType: ETO_OP48EData.timerStatus}),
                ...(ETO_OP48EData.electricStatus && { lubeType: ETO_OP48EData.electricStatus}),
                ...(ETO_OP48EData.mightyLubeMonitoring && { lubeType: ETO_OP48EData.mightyLubeMonitoring}),
                ...(ETO_OP48EData.preMountType && { lubeType: ETO_OP48EData.preMountType}),
                ...(ETO_OP48EData.otherPreMountType && { lubeType: ETO_OP48EData.otherPreMountType}),
                ...(ETO_OP48EData.plcConnection && { lubeType: ETO_OP48EData.plcConnection}),
                ...(ETO_OP48EData.otherControllerNotes && { lubeType: ETO_OP48EData.otherControllerNotes}),
                ...(ETO_OP48EData.templateB_UnitType && { lubeType: ETO_OP48EData.templateB_UnitType}),
                ...(ETO_OP48EData.templateB_InvertedB && { lubeType: ETO_OP48EData.templateB_InvertedB}),
                ...(ETO_OP48EData.templateB_InvertedE && { lubeType: ETO_OP48EData.templateB_InvertedE}),
                ...(ETO_OP48EData.templateB_InvertedG && { lubeType: ETO_OP48EData.templateB_InvertedG}),
                ...(ETO_OP48EData.templateB_InvertedH && { lubeType: ETO_OP48EData.templateB_InvertedH}),
                ...(ETO_OP48EData.templateB_InvertedK && { lubeType: ETO_OP48EData.templateB_InvertedK}),
                ...(ETO_OP48EData.templateB_InvertedT && { lubeType: ETO_OP48EData.templateB_InvertedT}),
                ...(ETO_OP48EData.templateB_InvertedU && { lubeType: ETO_OP48EData.templateB_InvertedU}),
                ...(ETO_OP48EData.templateB_InvertedV && { lubeType: ETO_OP48EData.templateB_InvertedV}),
                ...(ETO_OP48EData.templateB_InvertedW && { lubeType: ETO_OP48EData.templateB_InvertedW}),

            },

            templateCData: {
                conveyorName: ETO_OP48EData.conveyorName,
                industrialChainManufacturer: ETO_OP48EData.industrialChainManufacturer,
                ...(ETO_OP48EData.otherChainManufacturer && { otherChainManufacturer: ETO_OP48EData.otherChainManufacturer }),
                wheelManufacturer: ETO_OP48EData.wheelManufacturer,
                ...(ETO_OP48EData.wheelManufacturer && { wheelManufacturer: ETO_OP48EData.wheelManufacturer}),
                conveyorSpeed: ETO_OP48EData.conveyorSpeed,
                conveyorSpeedUnit: ETO_OP48EData.conveyorSpeedUnit,
                conveyorIndex: ETO_OP48EData.conveyorIndex,
                ...(ETO_OP48EData.travelDirection && { travelDirection: ETO_OP48EData.travelDirection}),
                appEnviroment: ETO_OP48EData.appEnviroment,
                ...(ETO_OP48EData.otherAppEnviroment && { otherAppEnviroment: ETO_OP48EData.otherAppEnviroment}),
                surroundingTemp: ETO_OP48EData.surroundingTemp,
                orientationType: ETO_OP48EData.orientationType,
                guideWheelsEven: ETO_OP48EData.guideWheelsEven,
                operatingVoltage: ETO_OP48EData.operatingVoltage,
                controlVoltSingle: ETO_OP48EData.controlVoltSingle,
                compressedAir: ETO_OP48EData.compressedAir,
                ...(ETO_OP48EData.airSupplyType && { airSupplyType: ETO_OP48EData.airSupplyType}),
                existingMonitor: ETO_OP48EData.existingMonitor,
                newMonitor: ETO_OP48EData.newMonitor,
                templateA_CData: {
                ...(ETO_OP48EData.dcuStatus && { dcuStatus: ETO_OP48EData.dcuStatus }),
                ...(ETO_OP48EData.dcuNum && { dcuNum: ETO_OP48EData.dcuNum }),
                ...(ETO_OP48EData.existingWindows && { existingWindows: ETO_OP48EData.existingWindows }),
                ...(ETO_OP48EData.existingHeadUnit && { existingHeadUnit: ETO_OP48EData.existingHeadUnit }),
                ...(ETO_OP48EData.existingDCU && { existingDCU: ETO_OP48EData.existingDCU }),
                ...(ETO_OP48EData.existingPowerInterface && { existingPowerInterface: ETO_OP48EData.existingPowerInterface }),
                ...(ETO_OP48EData.newReservoir && { newReservoir: ETO_OP48EData.newReservoir }),
                ...(ETO_OP48EData.reservoirSize && { reservoirSize: ETO_OP48EData.reservoirSize }),
                ...(ETO_OP48EData.otherReservoirSize && { otherReservoirSize: ETO_OP48EData.otherReservoirSize }),
                ...(ETO_OP48EData.newReservoirNum && { newReservoirNum: ETO_OP48EData.newReservoirNum }),
                ...(ETO_OP48EData.typeMonitor && { typeMonitor: ETO_OP48EData.typeMonitor }),
                ...(ETO_OP48EData.driveMotorAmp && { driveMotorAmp: ETO_OP48EData.driveMotorAmp }),
                ...(ETO_OP48EData.driveMotorAmpNum && { driveMotorAmpNum: ETO_OP48EData.driveMotorAmpNum }),
                ...(ETO_OP48EData.driveTakeUpAir && { driveTakeUpAir: ETO_OP48EData.driveTakeUpAir }),
                ...(ETO_OP48EData.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_OP48EData.driveTakeUpAirNum }),
                ...(ETO_OP48EData.takeUpDistance && { takeUpDistance: ETO_OP48EData.takeUpDistance }),
                ...(ETO_OP48EData.takeUpDistanceNum && { takeUpDistanceNum: ETO_OP48EData.takeUpDistanceNum }),
                ...(ETO_OP48EData.driveTemp && { driveTemp: ETO_OP48EData.driveTemp }),
                ...(ETO_OP48EData.driveTempNum && { driveTempNum: ETO_OP48EData.driveTempNum }),
                ...(ETO_OP48EData.driveVibration && { driveVibration: ETO_OP48EData.driveVibration }),
                ...(ETO_OP48EData.driveVibrationNum && { driveVibrationNum: ETO_OP48EData.driveVibrationNum }),
                ...(ETO_OP48EData.dogPitch && { dogPitch: ETO_OP48EData.dogPitch }),
                ...(ETO_OP48EData.dogPitchNum && { dogPitchNum: ETO_OP48EData.dogPitchNum }),
                ...(ETO_OP48EData.paintMarker && { paintMarker: ETO_OP48EData.paintMarker }),
                ...(ETO_OP48EData.paintMarkerNum && { paintMarkerNum: ETO_OP48EData.paintMarkerNum }),
                ...(ETO_OP48EData.chainVision && { chainVision: ETO_OP48EData.chainVision }),
                ...(ETO_OP48EData.lubeVision && { lubeVision: ETO_OP48EData.lubeVision }),
                ...(ETO_OP48EData.trolleyVision && { trolleyVision: ETO_OP48EData.trolleyVision }),
                ...(ETO_OP48EData.trolleyDetect && { trolleyDetect: ETO_OP48EData.trolleyDetect }),
                ...(ETO_OP48EData.omniView && { omniView: ETO_OP48EData.omniView }),
                ...(ETO_OP48EData.dcuUpgradeNum && { dcuUpgradeNum: ETO_OP48EData.dcuUpgradeNum }),
                ...(ETO_OP48EData.itNameOne && { itNameOne: ETO_OP48EData.itNameOne }),
                ...(ETO_OP48EData.itIPOne && { itIPOne: ETO_OP48EData.itIPOne }),
                ...(ETO_OP48EData.itGatewayOne && { itGatewayOne: ETO_OP48EData.itGatewayOne }),
                ...(ETO_OP48EData.itSubnetOne && { itSubnetOne: ETO_OP48EData.itSubnetOne }),
                ...(ETO_OP48EData.itDNSOne && { itDNSOne: ETO_OP48EData.itDNSOne }),
                ...(ETO_OP48EData.itSMTPOne && { itSMTPOne: ETO_OP48EData.itSMTPOne }),
                ...(ETO_OP48EData.itNameTwo && { itNameTwo: ETO_OP48EData.itNameTwo }),
                ...(ETO_OP48EData.itIPTwo && { itIPTwo: ETO_OP48EData.itIPTwo }),
                ...(ETO_OP48EData.itGatewayTwo && { itGatewayTwo: ETO_OP48EData.itGatewayTwo }),
                ...(ETO_OP48EData.itSubnetTwo && { itSubnetTwo: ETO_OP48EData.itSubnetTwo }),
                ...(ETO_OP48EData.itDNSTwo && { itDNSTwo: ETO_OP48EData.itDNSTwo }),
                ...(ETO_OP48EData.itSMTPTwo && { itSMTPTwo: ETO_OP48EData.itSMTPTwo }),
                ...(ETO_OP48EData.itNameThree && { itNameThree: ETO_OP48EData.itNameThree }),
                ...(ETO_OP48EData.itIPThree && { itIPThree: ETO_OP48EData.itIPThree }),
                ...(ETO_OP48EData.itGatewayThree && { itGatewayThree: ETO_OP48EData.itGatewayThree }),
                ...(ETO_OP48EData.itSubnetThree && { itSubnetThree: ETO_OP48EData.itSubnetThree }),
                ...(ETO_OP48EData.itDNSThree && { itDNSThree: ETO_OP48EData.itDNSThree }),
                ...(ETO_OP48EData.itSMTPThree && { itSMTPThree: ETO_OP48EData.itSMTPThree }),
                ...(ETO_OP48EData.itAdditionalNotes && { itAdditionalNotes: ETO_OP48EData.itAdditionalNotes }),
                ...(ETO_OP48EData.piuDistance && { piuDistance: ETO_OP48EData.piuDistance }),
                ...(ETO_OP48EData.switchDistance && { switchDistance: ETO_OP48EData.switchDistance }),
                ...(ETO_OP48EData.ampPickup && { ampPickup: ETO_OP48EData.ampPickup }),
                ...(ETO_OP48EData.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_OP48EData.fromAirTakeUpDistance }),
                ...(ETO_OP48EData.specialControllerOptions && { specialControllerOptions: ETO_OP48EData.specialControllerOptions }),
                ...(ETO_OP48EData.operatingVoltage && { operatingVoltage: ETO_OP48EData.operatingVoltage })

                },
                freeWheelStatus: ETO_OP48EData.freeWheelStatus,
                actuatorStatus: ETO_OP48EData.actuatorStatus,
                ...(ETO_OP48EData.pivotStatus && { pivotStatus: ETO_OP48EData.pivotStatus}),
                kingPinStatus: ETO_OP48EData.kingPinStatus,
                lubeBrand: ETO_OP48EData.lubeBrand,
                lubeViscosity: ETO_OP48EData.lubeViscosity,
                ...(ETO_OP48EData.lubeType && { lubeType: ETO_OP48EData.lubeType}),
                currentGrease: ETO_OP48EData.currentGrease,
                currentGreaseGrade: ETO_OP48EData.currentGreaseGrade,
                zerkDirection: ETO_OP48EData.zerkDirection,
                zerkLocationType: ETO_OP48EData.zerkLocationType,
                wheelDiameter: ETO_OP48EData.wheelDiameter,
                conveyorSwing: ETO_OP48EData.conveyorSwing,
                ...(ETO_OP48EData.chainMaster && { lubeType: ETO_OP48EData.chainMaster}),
                ...(ETO_OP48EData.remoteStatus && { lubeType: ETO_OP48EData.remoteStatus}),
                ...(ETO_OP48EData.mountStatus && { lubeType: ETO_OP48EData.mountStatus}),
                ...(ETO_OP48EData.otherUnitStatus && { lubeType: ETO_OP48EData.otherUnitStatus}),
                ...(ETO_OP48EData.timerStatus && { lubeType: ETO_OP48EData.timerStatus}),
                ...(ETO_OP48EData.electricStatus && { lubeType: ETO_OP48EData.electricStatus}),
                ...(ETO_OP48EData.mightyLubeMonitoring && { lubeType: ETO_OP48EData.mightyLubeMonitoring}),
                ...(ETO_OP48EData.preMountType && { lubeType: ETO_OP48EData.preMountType}),
                ...(ETO_OP48EData.otherPreMountType && { lubeType: ETO_OP48EData.otherPreMountType}),
                ...(ETO_OP48EData.plcConnection && { lubeType: ETO_OP48EData.plcConnection}),
                ...(ETO_OP48EData.otherControllerNotes && { lubeType: ETO_OP48EData.otherControllerNotes}),
                ...(ETO_OP48EData.templateC_UnitType && { lubeType: ETO_OP48EData.templateC_UnitType}),
                templateC_InvertedA: ETO_OP48EData.templateC_InvertedA,
                templateC_InvertedB: ETO_OP48EData.templateC_InvertedB,
                templateC_InvertedE: ETO_OP48EData.templateC_InvertedE,
                templateC_InvertedS: ETO_OP48EData.templateC_InvertedS,
            },

            catDriveStatus: ETO_OP48EData.catDriveStatus,

            templateFData: {
                conveyorName: ETO_OP48EData.conveyorName,
                chainSize: ETO_OP48EData.chainSize,
                ...(ETO_OP48EData.otherChainSize && { otherChainSize: ETO_OP48EData.otherChainSize }),
                industrialChainManufacturer: ETO_OP48EData.industrialChainManufacturer,
                ...(ETO_OP48EData.otherChainManufacturer && { otherChainManufacturer: ETO_OP48EData.otherChainManufacturer }),
                wheelManufacturer: ETO_OP48EData.wheelManufacturer,
                ...(ETO_OP48EData.otherWheelManufacturer && { otherWheelManufacturer: ETO_OP48EData.otherWheelManufacturer }),
                conveyorLength: ETO_OP48EData.conveyorLength,
                conveyorLengthUnit: ETO_OP48EData.conveyorLengthUnit,
                brushApplicators: ETO_OP48EData.brushApplicators,
                m12Plugs: ETO_OP48EData.m12Plugs,
                oilStatus: ETO_OP48EData.oilStatus,
                operatingVoltage: ETO_OP48EData.operatingVoltage,
                controlVoltSingle: ETO_OP48EData.controlVoltSingle,
            },

            ...(ETO_OP48EData.catDriveNum && { catDriveNum: ETO_OP48EData.catDriveNum }),            
            ...(ETO_OP48EData.lubeBrand && { lubeBrand: ETO_OP48EData.lubeBrand }),
            ...(ETO_OP48EData.lubeType && { lubeType: ETO_OP48EData.lubeType }),
            ...(ETO_OP48EData.lubeViscosity && { lubeViscosity: ETO_OP48EData.lubeViscosity }),
            ...(ETO_OP48EData.chainMaster && { chainMaster: ETO_OP48EData.chainMaster }),
            ...(ETO_OP48EData.timerStatus && { timerStatus: ETO_OP48EData.timerStatus }),
            ...(ETO_OP48EData.electricStatus && { electricStatus: ETO_OP48EData.electricStatus }),
            ...(ETO_OP48EData.pneumaticStatus && { pneumaticStatus: ETO_OP48EData.pneumaticStatus }),
            ...(ETO_OP48EData.mightyLubeMonitoring && { mightyLubeMonitoring: ETO_OP48EData.mightyLubeMonitoring }),
            ...(ETO_OP48EData.plcConnection && { plcConnection: ETO_OP48EData.plcConnection }),
            ...(ETO_OP48EData.otherControllerInfo && { otherControllerInfo: ETO_OP48EData.otherControllerInfo }),
            ...(ETO_OP48EData.etUnitType && { etUnitType: ETO_OP48EData.etUnitType }),
            ...(ETO_OP48EData.etOverheadB && { etOverheadB: ETO_OP48EData.etOverheadB }),
            ...(ETO_OP48EData.etOverheadG && { etOverheadG: ETO_OP48EData.etOverheadG }),
            ...(ETO_OP48EData.etOverheadH && { etOverheadH: ETO_OP48EData.etOverheadH }),
            ...(ETO_OP48EData.etOverheadS && { etOverheadS: ETO_OP48EData.etOverheadS }),
            ...(ETO_OP48EData.etOverheadK2 && { etOverheadK2: ETO_OP48EData.etOverheadK2 }),
            ...(ETO_OP48EData.etOverheadLS && { etOverheadLS: ETO_OP48EData.etOverheadLS }),
            ...(ETO_OP48EData.etOverheadM2 && { etOverheadM2: ETO_OP48EData.etOverheadM2 }),
            ...(ETO_OP48EData.etOverheadN2 && { etOverheadN2: ETO_OP48EData.etOverheadN2 }),
            ...(ETO_OP48EData.etOverheadS2 && { etOverheadS2: ETO_OP48EData.etOverheadS2 })
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "ETO_OP48E"
        });
        await req.user.save();
        return res.status(200).json({ message: "ETO_OP48E entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;