const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const ETO_9000E = require("../models/ETO_9000E");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");
const templateE= require("../models/templateE");
const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { ETO_9000EData, numRequested } = req.body;
        const order = new ETO_9000E({
            ...(ETO_9000EData.chainSize && { chainSize: ETO_9000EData.chainSize }),
            ...(ETO_9000EData.otherChainSize && { otherChainSize: ETO_9000EData.otherChainSize }),
            industrialChainManufacturer: ETO_9000EData.industrialChainManufacturer,
            ...(ETO_9000EData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: ETO_9000EData.otherIndustrialChainManufacturer }),
            ...(ETO_9000EData.conveyorLength && { conveyorLength: ETO_9000EData.conveyorLength }),
            ...(ETO_9000EData.conveyorLengthUnit && { conveyorLengthUnit: ETO_9000EData.conveyorLengthUnit }),
            ...(ETO_9000EData.conveyorSpeed && { conveyorSpeed: ETO_9000EData.conveyorSpeed }),
            ...(ETO_9000EData.conveyorSpeedUnit && { conveyorSpeedUnit: ETO_9000EData.conveyorSpeedUnit }),
            ...(ETO_9000EData.conveyorIndex && { conveyorIndex: ETO_9000EData.conveyorIndex }),
            ...(ETO_9000EData.travelDirection && { travelDirection: ETO_9000EData.travelDirection }),
            appEnviroment: ETO_9000EData.appEnviroment,
            ...(ETO_9000EData.ovenStatus && { ovenStatus: ETO_9000EData.ovenStatus }),
            ...(ETO_9000EData.ovenTemp && { ovenTemp: ETO_9000EData.ovenTemp }),
            ...(ETO_9000EData.otherAppEnviroment && { otherAppEnviroment: ETO_9000EData.otherAppEnviroment }),
            ...(ETO_9000EData.surroundingTemp && { surroundingTemp: ETO_9000EData.surroundingTemp }),
            ...(ETO_9000EData.conveyorLoaded && { conveyorLoaded: ETO_9000EData.conveyorLoaded }),
            ...(ETO_9000EData.conveyorSwing && { conveyorSwing: ETO_9000EData.conveyorSwing }),
            operatingVoltage: ETO_9000EData.operatingVoltage,
            existingMonitor: ETO_9000EData.existingMonitor,
            newMonitor: ETO_9000EData.newMonitor,
            monitorData: {
                ...(ETO_9000EData.dcuStatus && { dcuStatus: ETO_9000EData.dcuStatus }),
                ...(ETO_9000EData.dcuNum && { dcuNum: ETO_9000EData.dcuNum }),
                ...(ETO_9000EData.existingWindows && { existingWindows: ETO_9000EData.existingWindows }),
                ...(ETO_9000EData.existingHeadUnit && { existingHeadUnit: ETO_9000EData.existingHeadUnit }),
                ...(ETO_9000EData.existingDCU && { existingDCU: ETO_9000EData.existingDCU }),
                ...(ETO_9000EData.existingPowerInterface && { existingPowerInterface: ETO_9000EData.existingPowerInterface }),
                ...(ETO_9000EData.newReservoir && { newReservoir: ETO_9000EData.newReservoir }),
                ...(ETO_9000EData.reservoirSize && { reservoirSize: ETO_9000EData.reservoirSize }),
                ...(ETO_9000EData.otherReservoirSize && { otherReservoirSize: ETO_9000EData.otherReservoirSize }),
                ...(ETO_9000EData.newReservoirNum && { newReservoirNum: ETO_9000EData.newReservoirNum }),
                ...(ETO_9000EData.typeMonitor && { typeMonitor: ETO_9000EData.typeMonitor }),
                ...(ETO_9000EData.driveMotorAmp && { driveMotorAmp: ETO_9000EData.driveMotorAmp }),
                ...(ETO_9000EData.driveMotorAmpNum && { driveMotorAmpNum: ETO_9000EData.driveMotorAmpNum }),
                ...(ETO_9000EData.driveTakeUpAir && { driveTakeUpAir: ETO_9000EData.driveTakeUpAir }),
                ...(ETO_9000EData.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_9000EData.driveTakeUpAirNum }),
                ...(ETO_9000EData.takeUpDistance && { takeUpDistance: ETO_9000EData.takeUpDistance }),
                ...(ETO_9000EData.takeUpDistanceNum && { takeUpDistanceNum: ETO_9000EData.takeUpDistanceNum }),
                ...(ETO_9000EData.driveTemp && { driveTemp: ETO_9000EData.driveTemp }),
                ...(ETO_9000EData.driveTempNum && { driveTempNum: ETO_9000EData.driveTempNum }),
                ...(ETO_9000EData.driveVibration && { driveVibration: ETO_9000EData.driveVibration }),
                ...(ETO_9000EData.driveVibrationNum && { driveVibrationNum: ETO_9000EData.driveVibrationNum }),
                ...(ETO_9000EData.dogPitch && { dogPitch: ETO_9000EData.dogPitch }),
                ...(ETO_9000EData.dogPitchNum && { dogPitchNum: ETO_9000EData.dogPitchNum }),
                ...(ETO_9000EData.paintMarker && { paintMarker: ETO_9000EData.paintMarker }),
                ...(ETO_9000EData.paintMarkerNum && { paintMarkerNum: ETO_9000EData.paintMarkerNum }),
                ...(ETO_9000EData.chainVision && { chainVision: ETO_9000EData.chainVision }),
                ...(ETO_9000EData.lubeVision && { lubeVision: ETO_9000EData.lubeVision }),
                ...(ETO_9000EData.trolleyVision && { trolleyVision: ETO_9000EData.trolleyVision }),
                ...(ETO_9000EData.trolleyDetect && { trolleyDetect: ETO_9000EData.trolleyDetect }),
                ...(ETO_9000EData.omniView && { omniView: ETO_9000EData.omniView }),
                ...(ETO_9000EData.dcuUpgradeNum && { dcuUpgradeNum: ETO_9000EData.dcuUpgradeNum }),
                ...(ETO_9000EData.itNameOne && { itNameOne: ETO_9000EData.itNameOne }),
                ...(ETO_9000EData.itIPOne && { itIPOne: ETO_9000EData.itIPOne }),
                ...(ETO_9000EData.itGatewayOne && { itGatewayOne: ETO_9000EData.itGatewayOne }),
                ...(ETO_9000EData.itSubnetOne && { itSubnetOne: ETO_9000EData.itSubnetOne }),
                ...(ETO_9000EData.itDNSOne && { itDNSOne: ETO_9000EData.itDNSOne }),
                ...(ETO_9000EData.itSMTPOne && { itSMTPOne: ETO_9000EData.itSMTPOne }),
                ...(ETO_9000EData.itNameTwo && { itNameTwo: ETO_9000EData.itNameTwo }),
                ...(ETO_9000EData.itIPTwo && { itIPTwo: ETO_9000EData.itIPTwo }),
                ...(ETO_9000EData.itGatewayTwo && { itGatewayTwo: ETO_9000EData.itGatewayTwo }),
                ...(ETO_9000EData.itSubnetTwo && { itSubnetTwo: ETO_9000EData.itSubnetTwo }),
                ...(ETO_9000EData.itDNSTwo && { itDNSTwo: ETO_9000EData.itDNSTwo }),
                ...(ETO_9000EData.itSMTPTwo && { itSMTPTwo: ETO_9000EData.itSMTPTwo }),
                ...(ETO_9000EData.itNameThree && { itNameThree: ETO_9000EData.itNameThree }),
                ...(ETO_9000EData.itIPThree && { itIPThree: ETO_9000EData.itIPThree }),
                ...(ETO_9000EData.itGatewayThree && { itGatewayThree: ETO_9000EData.itGatewayThree }),
                ...(ETO_9000EData.itSubnetThree && { itSubnetThree: ETO_9000EData.itSubnetThree }),
                ...(ETO_9000EData.itDNSThree && { itDNSThree: ETO_9000EData.itDNSThree }),
                ...(ETO_9000EData.itSMTPThree && { itSMTPThree: ETO_9000EData.itSMTPThree }),
                ...(ETO_9000EData.itAdditionalNotes && { itAdditionalNotes: ETO_9000EData.itAdditionalNotes }),
                ...(ETO_9000EData.piuDistance && { piuDistance: ETO_9000EData.piuDistance }),
                ...(ETO_9000EData.switchDistance && { switchDistance: ETO_9000EData.switchDistance }),
                ...(ETO_9000EData.ampPickup && { ampPickup: ETO_9000EData.ampPickup }),
                ...(ETO_9000EData.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_9000EData.fromAirTakeUpDistance }),
                ...(ETO_9000EData.specialControllerOptions && { specialControllerOptions: ETO_9000EData.specialControllerOptions }),
                ...(ETO_9000EData.operatingVoltage && { operatingVoltage: ETO_9000EData.operatingVoltage })

            },

            addFreeCarrier: ETO_9000EData.addFreeCarrier,

            templateBData: {
                conveyorName: ETO_9000EData.conveyorName,
                industrialChainManufacturer: ETO_9000EData.industrialChainManufacturer,
                ...(ETO_9000EData.otherChainManufacturer && { otherChainManufacturer: ETO_9000EData.otherChainManufacturer }),
                wheelManufacturer: ETO_9000EData.wheelManufacturer,
                ...(ETO_9000EData.wheelManufacturer && { wheelManufacturer: ETO_9000EData.wheelManufacturer}),
                conveyorSpeed: ETO_9000EData.conveyorSpeed,
                conveyorSpeedUnit: ETO_9000EData.conveyorSpeedUnit,
                conveyorIndex: ETO_9000EData.conveyorIndex,
                ...(ETO_9000EData.travelDirection && { travelDirection: ETO_9000EData.travelDirection}),
                appEnviroment: ETO_9000EData.appEnviroment,
                ...(ETO_9000EData.otherAppEnviroment && { otherAppEnviroment: ETO_9000EData.otherAppEnviroment}),
                surroundingTemp: ETO_9000EData.surroundingTemp,
                orientationType: ETO_9000EData.orientationType,
                operatingVoltage: ETO_9000EData.operatingVoltage,
                controlVoltSingle: ETO_9000EData.controlVoltSingle,
                compressedAir: ETO_9000EData.compressedAir,
                ...(ETO_9000EData.airSupplyType && { airSupplyType: ETO_9000EData.airSupplyType}),
            existingMonitor: ETO_9000EData.existingMonitor,
            newMonitor: ETO_9000EData.newMonitor,
            templateA_BData: {
                ...(ETO_9000EData.dcuStatus && { dcuStatus: ETO_9000EData.dcuStatus }),
                ...(ETO_9000EData.dcuNum && { dcuNum: ETO_9000EData.dcuNum }),
                ...(ETO_9000EData.existingWindows && { existingWindows: ETO_9000EData.existingWindows }),
                ...(ETO_9000EData.existingHeadUnit && { existingHeadUnit: ETO_9000EData.existingHeadUnit }),
                ...(ETO_9000EData.existingDCU && { existingDCU: ETO_9000EData.existingDCU }),
                ...(ETO_9000EData.existingPowerInterface && { existingPowerInterface: ETO_9000EData.existingPowerInterface }),
                ...(ETO_9000EData.newReservoir && { newReservoir: ETO_9000EData.newReservoir }),
                ...(ETO_9000EData.reservoirSize && { reservoirSize: ETO_9000EData.reservoirSize }),
                ...(ETO_9000EData.otherReservoirSize && { otherReservoirSize: ETO_9000EData.otherReservoirSize }),
                ...(ETO_9000EData.newReservoirNum && { newReservoirNum: ETO_9000EData.newReservoirNum }),
                ...(ETO_9000EData.typeMonitor && { typeMonitor: ETO_9000EData.typeMonitor }),
                ...(ETO_9000EData.driveMotorAmp && { driveMotorAmp: ETO_9000EData.driveMotorAmp }),
                ...(ETO_9000EData.driveMotorAmpNum && { driveMotorAmpNum: ETO_9000EData.driveMotorAmpNum }),
                ...(ETO_9000EData.driveTakeUpAir && { driveTakeUpAir: ETO_9000EData.driveTakeUpAir }),
                ...(ETO_9000EData.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_9000EData.driveTakeUpAirNum }),
                ...(ETO_9000EData.takeUpDistance && { takeUpDistance: ETO_9000EData.takeUpDistance }),
                ...(ETO_9000EData.takeUpDistanceNum && { takeUpDistanceNum: ETO_9000EData.takeUpDistanceNum }),
                ...(ETO_9000EData.driveTemp && { driveTemp: ETO_9000EData.driveTemp }),
                ...(ETO_9000EData.driveTempNum && { driveTempNum: ETO_9000EData.driveTempNum }),
                ...(ETO_9000EData.driveVibration && { driveVibration: ETO_9000EData.driveVibration }),
                ...(ETO_9000EData.driveVibrationNum && { driveVibrationNum: ETO_9000EData.driveVibrationNum }),
                ...(ETO_9000EData.dogPitch && { dogPitch: ETO_9000EData.dogPitch }),
                ...(ETO_9000EData.dogPitchNum && { dogPitchNum: ETO_9000EData.dogPitchNum }),
                ...(ETO_9000EData.paintMarker && { paintMarker: ETO_9000EData.paintMarker }),
                ...(ETO_9000EData.paintMarkerNum && { paintMarkerNum: ETO_9000EData.paintMarkerNum }),
                ...(ETO_9000EData.chainVision && { chainVision: ETO_9000EData.chainVision }),
                ...(ETO_9000EData.lubeVision && { lubeVision: ETO_9000EData.lubeVision }),
                ...(ETO_9000EData.trolleyVision && { trolleyVision: ETO_9000EData.trolleyVision }),
                ...(ETO_9000EData.trolleyDetect && { trolleyDetect: ETO_9000EData.trolleyDetect }),
                ...(ETO_9000EData.omniView && { omniView: ETO_9000EData.omniView }),
                ...(ETO_9000EData.dcuUpgradeNum && { dcuUpgradeNum: ETO_9000EData.dcuUpgradeNum }),
                ...(ETO_9000EData.itNameOne && { itNameOne: ETO_9000EData.itNameOne }),
                ...(ETO_9000EData.itIPOne && { itIPOne: ETO_9000EData.itIPOne }),
                ...(ETO_9000EData.itGatewayOne && { itGatewayOne: ETO_9000EData.itGatewayOne }),
                ...(ETO_9000EData.itSubnetOne && { itSubnetOne: ETO_9000EData.itSubnetOne }),
                ...(ETO_9000EData.itDNSOne && { itDNSOne: ETO_9000EData.itDNSOne }),
                ...(ETO_9000EData.itSMTPOne && { itSMTPOne: ETO_9000EData.itSMTPOne }),
                ...(ETO_9000EData.itNameTwo && { itNameTwo: ETO_9000EData.itNameTwo }),
                ...(ETO_9000EData.itIPTwo && { itIPTwo: ETO_9000EData.itIPTwo }),
                ...(ETO_9000EData.itGatewayTwo && { itGatewayTwo: ETO_9000EData.itGatewayTwo }),
                ...(ETO_9000EData.itSubnetTwo && { itSubnetTwo: ETO_9000EData.itSubnetTwo }),
                ...(ETO_9000EData.itDNSTwo && { itDNSTwo: ETO_9000EData.itDNSTwo }),
                ...(ETO_9000EData.itSMTPTwo && { itSMTPTwo: ETO_9000EData.itSMTPTwo }),
                ...(ETO_9000EData.itNameThree && { itNameThree: ETO_9000EData.itNameThree }),
                ...(ETO_9000EData.itIPThree && { itIPThree: ETO_9000EData.itIPThree }),
                ...(ETO_9000EData.itGatewayThree && { itGatewayThree: ETO_9000EData.itGatewayThree }),
                ...(ETO_9000EData.itSubnetThree && { itSubnetThree: ETO_9000EData.itSubnetThree }),
                ...(ETO_9000EData.itDNSThree && { itDNSThree: ETO_9000EData.itDNSThree }),
                ...(ETO_9000EData.itSMTPThree && { itSMTPThree: ETO_9000EData.itSMTPThree }),
                ...(ETO_9000EData.itAdditionalNotes && { itAdditionalNotes: ETO_9000EData.itAdditionalNotes }),
                ...(ETO_9000EData.piuDistance && { piuDistance: ETO_9000EData.piuDistance }),
                ...(ETO_9000EData.switchDistance && { switchDistance: ETO_9000EData.switchDistance }),
                ...(ETO_9000EData.ampPickup && { ampPickup: ETO_9000EData.ampPickup }),
                ...(ETO_9000EData.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_9000EData.fromAirTakeUpDistance }),
                ...(ETO_9000EData.specialControllerOptions && { specialControllerOptions: ETO_9000EData.specialControllerOptions }),
                ...(ETO_9000EData.operatingVoltage && { operatingVoltage: ETO_9000EData.operatingVoltage })

                },
                freeWheelStatus: ETO_9000EData.freeWheelStatus,
                actuatorStatus: ETO_9000EData.actuatorStatus,
                ...(ETO_9000EData.pivotStatus && { pivotStatus: ETO_9000EData.pivotStatus}),
                kingPinStatus: ETO_9000EData.kingPinStatus,
                lubeBrand: ETO_9000EData.lubeBrand,
                lubeViscosity: ETO_9000EData.lubeViscosity,
                ...(ETO_9000EData.lubeType && { lubeType: ETO_9000EData.lubeType}),
                currentGrease: ETO_9000EData.currentGrease,
                currentGreaseGrade: ETO_9000EData.currentGreaseGrade,
                zerkDirection: ETO_9000EData.zerkDirection,
                zerkLocationType: ETO_9000EData.zerkLocationType,
                wheelDiameter: ETO_9000EData.wheelDiameter,
                conveyorSwing: ETO_9000EData.conveyorSwing,
                ...(ETO_9000EData.chainMaster && { lubeType: ETO_9000EData.chainMaster}),
                ...(ETO_9000EData.remoteStatus && { lubeType: ETO_9000EData.remoteStatus}),
                ...(ETO_9000EData.mountStatus && { lubeType: ETO_9000EData.mountStatus}),
                ...(ETO_9000EData.otherUnitStatus && { lubeType: ETO_9000EData.otherUnitStatus}),
                ...(ETO_9000EData.timerStatus && { lubeType: ETO_9000EData.timerStatus}),
                ...(ETO_9000EData.electricStatus && { lubeType: ETO_9000EData.electricStatus}),
                ...(ETO_9000EData.mightyLubeMonitoring && { lubeType: ETO_9000EData.mightyLubeMonitoring}),
                ...(ETO_9000EData.preMountType && { lubeType: ETO_9000EData.preMountType}),
                ...(ETO_9000EData.otherPreMountType && { lubeType: ETO_9000EData.otherPreMountType}),
                ...(ETO_9000EData.plcConnection && { lubeType: ETO_9000EData.plcConnection}),
                ...(ETO_9000EData.otherControllerNotes && { lubeType: ETO_9000EData.otherControllerNotes}),
                ...(ETO_9000EData.templateB_UnitType && { lubeType: ETO_9000EData.templateB_UnitType}),
                ...(ETO_9000EData.templateB_InvertedB && { lubeType: ETO_9000EData.templateB_InvertedB}),
                ...(ETO_9000EData.templateB_InvertedE && { lubeType: ETO_9000EData.templateB_InvertedE}),
                ...(ETO_9000EData.templateB_InvertedG && { lubeType: ETO_9000EData.templateB_InvertedG}),
                ...(ETO_9000EData.templateB_InvertedH && { lubeType: ETO_9000EData.templateB_InvertedH}),
                ...(ETO_9000EData.templateB_InvertedK && { lubeType: ETO_9000EData.templateB_InvertedK}),
                ...(ETO_9000EData.templateB_InvertedT && { lubeType: ETO_9000EData.templateB_InvertedT}),
                ...(ETO_9000EData.templateB_InvertedU && { lubeType: ETO_9000EData.templateB_InvertedU}),
                ...(ETO_9000EData.templateB_InvertedV && { lubeType: ETO_9000EData.templateB_InvertedV}),
                ...(ETO_9000EData.templateB_InvertedW && { lubeType: ETO_9000EData.templateB_InvertedW}),

            },

            templateCData: {
                conveyorName: ETO_9000EData.conveyorName,
                industrialChainManufacturer: ETO_9000EData.industrialChainManufacturer,
                ...(ETO_9000EData.otherChainManufacturer && { otherChainManufacturer: ETO_9000EData.otherChainManufacturer }),
                wheelManufacturer: ETO_9000EData.wheelManufacturer,
                ...(ETO_9000EData.wheelManufacturer && { wheelManufacturer: ETO_9000EData.wheelManufacturer}),
                conveyorSpeed: ETO_9000EData.conveyorSpeed,
                conveyorSpeedUnit: ETO_9000EData.conveyorSpeedUnit,
                conveyorIndex: ETO_9000EData.conveyorIndex,
                ...(ETO_9000EData.travelDirection && { travelDirection: ETO_9000EData.travelDirection}),
                appEnviroment: ETO_9000EData.appEnviroment,
                ...(ETO_9000EData.otherAppEnviroment && { otherAppEnviroment: ETO_9000EData.otherAppEnviroment}),
                surroundingTemp: ETO_9000EData.surroundingTemp,
                orientationType: ETO_9000EData.orientationType,
                guideWheelsEven: ETO_9000EData.guideWheelsEven,
                operatingVoltage: ETO_9000EData.operatingVoltage,
                controlVoltSingle: ETO_9000EData.controlVoltSingle,
                compressedAir: ETO_9000EData.compressedAir,
                ...(ETO_9000EData.airSupplyType && { airSupplyType: ETO_9000EData.airSupplyType}),
                existingMonitor: ETO_9000EData.existingMonitor,
                newMonitor: ETO_9000EData.newMonitor,
                templateA_CData: {
                ...(ETO_9000EData.dcuStatus && { dcuStatus: ETO_9000EData.dcuStatus }),
                ...(ETO_9000EData.dcuNum && { dcuNum: ETO_9000EData.dcuNum }),
                ...(ETO_9000EData.existingWindows && { existingWindows: ETO_9000EData.existingWindows }),
                ...(ETO_9000EData.existingHeadUnit && { existingHeadUnit: ETO_9000EData.existingHeadUnit }),
                ...(ETO_9000EData.existingDCU && { existingDCU: ETO_9000EData.existingDCU }),
                ...(ETO_9000EData.existingPowerInterface && { existingPowerInterface: ETO_9000EData.existingPowerInterface }),
                ...(ETO_9000EData.newReservoir && { newReservoir: ETO_9000EData.newReservoir }),
                ...(ETO_9000EData.reservoirSize && { reservoirSize: ETO_9000EData.reservoirSize }),
                ...(ETO_9000EData.otherReservoirSize && { otherReservoirSize: ETO_9000EData.otherReservoirSize }),
                ...(ETO_9000EData.newReservoirNum && { newReservoirNum: ETO_9000EData.newReservoirNum }),
                ...(ETO_9000EData.typeMonitor && { typeMonitor: ETO_9000EData.typeMonitor }),
                ...(ETO_9000EData.driveMotorAmp && { driveMotorAmp: ETO_9000EData.driveMotorAmp }),
                ...(ETO_9000EData.driveMotorAmpNum && { driveMotorAmpNum: ETO_9000EData.driveMotorAmpNum }),
                ...(ETO_9000EData.driveTakeUpAir && { driveTakeUpAir: ETO_9000EData.driveTakeUpAir }),
                ...(ETO_9000EData.driveTakeUpAirNum && { driveTakeUpAirNum: ETO_9000EData.driveTakeUpAirNum }),
                ...(ETO_9000EData.takeUpDistance && { takeUpDistance: ETO_9000EData.takeUpDistance }),
                ...(ETO_9000EData.takeUpDistanceNum && { takeUpDistanceNum: ETO_9000EData.takeUpDistanceNum }),
                ...(ETO_9000EData.driveTemp && { driveTemp: ETO_9000EData.driveTemp }),
                ...(ETO_9000EData.driveTempNum && { driveTempNum: ETO_9000EData.driveTempNum }),
                ...(ETO_9000EData.driveVibration && { driveVibration: ETO_9000EData.driveVibration }),
                ...(ETO_9000EData.driveVibrationNum && { driveVibrationNum: ETO_9000EData.driveVibrationNum }),
                ...(ETO_9000EData.dogPitch && { dogPitch: ETO_9000EData.dogPitch }),
                ...(ETO_9000EData.dogPitchNum && { dogPitchNum: ETO_9000EData.dogPitchNum }),
                ...(ETO_9000EData.paintMarker && { paintMarker: ETO_9000EData.paintMarker }),
                ...(ETO_9000EData.paintMarkerNum && { paintMarkerNum: ETO_9000EData.paintMarkerNum }),
                ...(ETO_9000EData.chainVision && { chainVision: ETO_9000EData.chainVision }),
                ...(ETO_9000EData.lubeVision && { lubeVision: ETO_9000EData.lubeVision }),
                ...(ETO_9000EData.trolleyVision && { trolleyVision: ETO_9000EData.trolleyVision }),
                ...(ETO_9000EData.trolleyDetect && { trolleyDetect: ETO_9000EData.trolleyDetect }),
                ...(ETO_9000EData.omniView && { omniView: ETO_9000EData.omniView }),
                ...(ETO_9000EData.dcuUpgradeNum && { dcuUpgradeNum: ETO_9000EData.dcuUpgradeNum }),
                ...(ETO_9000EData.itNameOne && { itNameOne: ETO_9000EData.itNameOne }),
                ...(ETO_9000EData.itIPOne && { itIPOne: ETO_9000EData.itIPOne }),
                ...(ETO_9000EData.itGatewayOne && { itGatewayOne: ETO_9000EData.itGatewayOne }),
                ...(ETO_9000EData.itSubnetOne && { itSubnetOne: ETO_9000EData.itSubnetOne }),
                ...(ETO_9000EData.itDNSOne && { itDNSOne: ETO_9000EData.itDNSOne }),
                ...(ETO_9000EData.itSMTPOne && { itSMTPOne: ETO_9000EData.itSMTPOne }),
                ...(ETO_9000EData.itNameTwo && { itNameTwo: ETO_9000EData.itNameTwo }),
                ...(ETO_9000EData.itIPTwo && { itIPTwo: ETO_9000EData.itIPTwo }),
                ...(ETO_9000EData.itGatewayTwo && { itGatewayTwo: ETO_9000EData.itGatewayTwo }),
                ...(ETO_9000EData.itSubnetTwo && { itSubnetTwo: ETO_9000EData.itSubnetTwo }),
                ...(ETO_9000EData.itDNSTwo && { itDNSTwo: ETO_9000EData.itDNSTwo }),
                ...(ETO_9000EData.itSMTPTwo && { itSMTPTwo: ETO_9000EData.itSMTPTwo }),
                ...(ETO_9000EData.itNameThree && { itNameThree: ETO_9000EData.itNameThree }),
                ...(ETO_9000EData.itIPThree && { itIPThree: ETO_9000EData.itIPThree }),
                ...(ETO_9000EData.itGatewayThree && { itGatewayThree: ETO_9000EData.itGatewayThree }),
                ...(ETO_9000EData.itSubnetThree && { itSubnetThree: ETO_9000EData.itSubnetThree }),
                ...(ETO_9000EData.itDNSThree && { itDNSThree: ETO_9000EData.itDNSThree }),
                ...(ETO_9000EData.itSMTPThree && { itSMTPThree: ETO_9000EData.itSMTPThree }),
                ...(ETO_9000EData.itAdditionalNotes && { itAdditionalNotes: ETO_9000EData.itAdditionalNotes }),
                ...(ETO_9000EData.piuDistance && { piuDistance: ETO_9000EData.piuDistance }),
                ...(ETO_9000EData.switchDistance && { switchDistance: ETO_9000EData.switchDistance }),
                ...(ETO_9000EData.ampPickup && { ampPickup: ETO_9000EData.ampPickup }),
                ...(ETO_9000EData.fromAirTakeUpDistance && { fromAirTakeUpDistance: ETO_9000EData.fromAirTakeUpDistance }),
                ...(ETO_9000EData.specialControllerOptions && { specialControllerOptions: ETO_9000EData.specialControllerOptions }),
                ...(ETO_9000EData.operatingVoltage && { operatingVoltage: ETO_9000EData.operatingVoltage })

                },
                freeWheelStatus: ETO_9000EData.freeWheelStatus,
                actuatorStatus: ETO_9000EData.actuatorStatus,
                ...(ETO_9000EData.pivotStatus && { pivotStatus: ETO_9000EData.pivotStatus}),
                kingPinStatus: ETO_9000EData.kingPinStatus,
                lubeBrand: ETO_9000EData.lubeBrand,
                lubeViscosity: ETO_9000EData.lubeViscosity,
                ...(ETO_9000EData.lubeType && { lubeType: ETO_9000EData.lubeType}),
                currentGrease: ETO_9000EData.currentGrease,
                currentGreaseGrade: ETO_9000EData.currentGreaseGrade,
                zerkDirection: ETO_9000EData.zerkDirection,
                zerkLocationType: ETO_9000EData.zerkLocationType,
                wheelDiameter: ETO_9000EData.wheelDiameter,
                conveyorSwing: ETO_9000EData.conveyorSwing,
                ...(ETO_9000EData.chainMaster && { lubeType: ETO_9000EData.chainMaster}),
                ...(ETO_9000EData.remoteStatus && { lubeType: ETO_9000EData.remoteStatus}),
                ...(ETO_9000EData.mountStatus && { lubeType: ETO_9000EData.mountStatus}),
                ...(ETO_9000EData.otherUnitStatus && { lubeType: ETO_9000EData.otherUnitStatus}),
                ...(ETO_9000EData.timerStatus && { lubeType: ETO_9000EData.timerStatus}),
                ...(ETO_9000EData.electricStatus && { lubeType: ETO_9000EData.electricStatus}),
                ...(ETO_9000EData.mightyLubeMonitoring && { lubeType: ETO_9000EData.mightyLubeMonitoring}),
                ...(ETO_9000EData.preMountType && { lubeType: ETO_9000EData.preMountType}),
                ...(ETO_9000EData.otherPreMountType && { lubeType: ETO_9000EData.otherPreMountType}),
                ...(ETO_9000EData.plcConnection && { lubeType: ETO_9000EData.plcConnection}),
                ...(ETO_9000EData.otherControllerNotes && { lubeType: ETO_9000EData.otherControllerNotes}),
                ...(ETO_9000EData.templateC_UnitType && { lubeType: ETO_9000EData.templateC_UnitType}),
                templateC_InvertedA: ETO_9000EData.templateC_InvertedA,
                templateC_InvertedB: ETO_9000EData.templateC_InvertedB,
                templateC_InvertedE: ETO_9000EData.templateC_InvertedE,
                templateC_InvertedS: ETO_9000EData.templateC_InvertedS,
            },

            catDriveStatus: ETO_9000EData.catDriveStatus,

                templateEData: {
                conveyorName: ETO_9000EData.conveyorName,
                chainSize: ETO_9000EData.chainSize,
                ...(ETO_9000EData.otherChainSize && { otherChainSize: ETO_9000EData.otherChainSize }),
                ...(ETO_9000EData.industrialChainManufacturer && { industrialChainManufacturer: ETO_9000EData.industrialChainManufacturer }),
                ...(ETO_9000EData.otherChainManufacturer && { otherChainManufacturer: ETO_9000EData.otherChainManufacturer }),
                ...(ETO_9000EData.conveyorLength && { conveyorLength: ETO_9000EData.conveyorLength }),
                ...(ETO_9000EData.conveyorLengthUnit && { conveyorLengthUnit: ETO_9000EData.conveyorLengthUnit }),
                ...(ETO_9000EData.appEnviroment && { appEnviroment: ETO_9000EData.appEnviroment }),
                ...(ETO_9000EData.otherAppEnviroment && { otherAppEnviroment: ETO_9000EData.otherAppEnviroment }),
                ...(ETO_9000EData.lubeBrand && { lubeBrand: ETO_9000EData.lubeBrand }),
                ...(ETO_9000EData.lubeType && { lubeType: ETO_9000EData.lubeType }),
                ...(ETO_9000EData.lubeViscosity && { lubeViscosity: ETO_9000EData.lubeViscosity }),
                ...(ETO_9000EData.specialControllerOptions && { specialControllerOptions: ETO_9000EData.specialControllerOptions }),
                ...(ETO_9000EData.wireMeasurementUnit && { wireMeasurementUnit: ETO_9000EData.wireMeasurementUnit }),
                ...(ETO_9000EData.conductor2 && { conductor2: ETO_9000EData.conductor2 }),
                ...(ETO_9000EData.conductor4 && { conductor4: ETO_9000EData.conductor4 }),
                ...(ETO_9000EData.conductor7 && { conductor7: ETO_9000EData.conductor7 }),
                ...(ETO_9000EData.conductor12 && { conductor12: ETO_9000EData.conductor12 }),
                ...(ETO_9000EData.junctionBoxNum && { junctionBoxNum: ETO_9000EData.junctionBoxNum }),

            },            
      
            ...(ETO_9000EData.catDriveNum && { catDriveNum: ETO_9000EData.catDriveNum }),
            ...(ETO_9000EData.externalLubeStatus && { externalLubeStatus: ETO_9000EData.externalLubeStatus }),
            ...(ETO_9000EData.lubeBrand && { lubeBrand: ETO_9000EData.lubeBrand }),
            ...(ETO_9000EData.lubeType && { lubeType: ETO_9000EData.lubeType }),
            ...(ETO_9000EData.lubeViscosity && { lubeViscosity: ETO_9000EData.lubeViscosity }),
            ...(ETO_9000EData.chainMaster && { chainMaster: ETO_9000EData.chainMaster }),
            ...(ETO_9000EData.timerStatus && { timerStatus: ETO_9000EData.timerStatus }),
            ...(ETO_9000EData.electricStatus && { electricStatus: ETO_9000EData.electricStatus }),
            ...(ETO_9000EData.pneumaticStatus && { pneumaticStatus: ETO_9000EData.pneumaticStatus }),
            ...(ETO_9000EData.mightyLubeMonitoring && { mightyLubeMonitoring: ETO_9000EData.mightyLubeMonitoring }),
            ...(ETO_9000EData.plcConnection && { plcConnection: ETO_9000EData.plcConnection }),
            ...(ETO_9000EData.otherControllerInfo && { otherControllerInfo: ETO_9000EData.otherControllerInfo }),
            ...(ETO_9000EData.wireMeasurementUnit && { wireMeasurementUnit: ETO_9000EData.wireMeasurementUnit }),
            ...(ETO_9000EData.conductor2 && { conductor2: ETO_9000EData.conductor2 }),
            ...(ETO_9000EData.conductor4 && { conductor4: ETO_9000EData.conductor4 }),
            ...(ETO_9000EData.conductor7 && { conductor7: ETO_9000EData.conductor7 }),
            ...(ETO_9000EData.conductor12 && { conductor12: ETO_9000EData.conductor12 }),
            ...(ETO_9000EData.junctionBoxNum && { junctionBoxNum: ETO_9000EData.junctionBoxNum }),
            ...(ETO_9000EData.enclosedUnitType && { enclosedUnitType: ETO_9000EData.enclosedUnitType }),
            ...(ETO_9000EData.enclosedTrackB && { enclosedTrackB: ETO_9000EData.enclosedTrackB }),
            ...(ETO_9000EData.enclosedTrackG && { enclosedTrackG: ETO_9000EData.enclosedTrackG }),
            ...(ETO_9000EData.enclosedTrackH && { enclosedTrackH: ETO_9000EData.enclosedTrackH }),
            ...(ETO_9000EData.enclosedTrackS && { enclosedTrackS: ETO_9000EData.enclosedTrackS }),
            ...(ETO_9000EData.enclosedTrackK2 && { enclosedTrackK2: ETO_9000EData.enclosedTrackK2 }),
            ...(ETO_9000EData.enclosedTrackL2 && { enclosedTrackL2: ETO_9000EData.enclosedTrackL2 }),
            ...(ETO_9000EData.enclosedTrackM2 && { enclosedTrackM2: ETO_9000EData.enclosedTrackM2 }),
            ...(ETO_9000EData.enclosedTrackN2 && { enclosedTrackN2: ETO_9000EData.enclosedTrackN2 }),
            ...(ETO_9000EData.enclosedTrackS2 && { enclosedTrackS2: ETO_9000EData.enclosedTrackS2 })
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "ETO_9000E"
        });
        await req.user.save();
        return res.status(200).json({ message: "ETO_9000E entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;