const express = require("express");
const { authenticate } = require("./sessions");
const FT_OP4OE = require("../models/FT_OP4OE");
const templateA = require("../models/templateA");
const templateE = require("../models/templateE");

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
  try {
    const { FT_OP4OEData, numRequested } = req.body;

    const order = new FT_OP4OE({
      conveyorName: FT_OP4OEData.conveyorName,
      chainSize: FT_OP4OEData.chainSize,
      ...(FT_OP4OEData.otherChainSize && { otherChainSize: FT_OP4OEData.otherChainSize }),
      industrialChainManufacturer: FT_OP4OEData.industrialChainManufacturer,
      ...(FT_OP4OEData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: FT_OP4OEData.otherIndustrialChainManufacturer }),
      wheelManufacturer: FT_OP4OEData.wheelManufacturer,
      ...(FT_OP4OEData.otherWheelManufacturer && { otherWheelManufacturer: FT_OP4OEData.otherWheelManufacturer }),
      conveyorLength: FT_OP4OEData.conveyorLength,
      conveyorLengthUnit: FT_OP4OEData.conveyorLengthUnit,
      conveyorSpeed: FT_OP4OEData.conveyorSpeed,
      conveyorSpeedUnit: FT_OP4OEData.conveyorSpeedUnit,
      conveyorIndex: FT_OP4OEData.conveyorIndex,
      ...(FT_OP4OEData.travelDirection && { travelDirection: FT_OP4OEData.travelDirection }),
      appEnviroment: FT_OP4OEData.appEnviroment,
      ...(FT_OP4OEData.ovenStatus && { ovenStatus: FT_OP4OEData.ovenStatus }),
      ...(FT_OP4OEData.ovenTemp && { ovenTemp: FT_OP4OEData.ovenTemp }),
      ...(FT_OP4OEData.otherAppEnviroment && { otherAppEnviroment: FT_OP4OEData.otherAppEnviroment }),
      ...(FT_OP4OEData.surroundingTemp && { surroundingTemp: FT_OP4OEData.surroundingTemp }),
      ...(FT_OP4OEData.conveyorLoaded && { conveyorLoaded: FT_OP4OEData.conveyorLoaded }),
      ...(FT_OP4OEData.conveyorSwing && { conveyorSwing: FT_OP4OEData.conveyorSwing }),
      strandStatus: FT_OP4OEData.strandStatus,
      ...(FT_OP4OEData.plantLayout && { plantLayout: FT_OP4OEData.plantLayout }),
      ...(FT_OP4OEData.requiredPics && { requiredPics: FT_OP4OEData.requiredPics }),
      operatingVoltage: FT_OP4OEData.operatingVoltage,
      controlVoltage: FT_OP4OEData.controlVoltage,
      existingMonitor: FT_OP4OEData.existingMonitor,
      newMonitor: FT_OP4OEData.newMonitor,
      monitorData: {
        ...(FT_FTLData.dcuStatus && { dcuStatus: FT_FTLData.dcuStatus }),
        ...(FT_FTLData.dcuNum && { dcuNum: FT_FTLData.dcuNum }),
        ...(FT_FTLData.existingWindows && { existingWindows: FT_FTLData.existingWindows }),
        ...(FT_FTLData.existingHeadUnit && { existingHeadUnit: FT_FTLData.existingHeadUnit }),
        ...(FT_FTLData.existingDCU && { existingDCU: FT_FTLData.existingDCU }),
        ...(FT_FTLData.existingPowerInterface && { existingPowerInterface: FT_FTLData.existingPowerInterface }),
        ...(FT_FTLData.newReservoir && { newReservoir: FT_FTLData.newReservoir }),
        ...(FT_FTLData.reservoirSize && { reservoirSize: FT_FTLData.reservoirSize }),
        ...(FT_FTLData.otherReservoirSize && { otherReservoirSize: FT_FTLData.otherReservoirSize }),
        ...(FT_FTLData.newReservoirNum && { newReservoirNum: FT_FTLData.newReservoirNum }),
        ...(FT_FTLData.typeMonitor && { typeMonitor: FT_FTLData.typeMonitor }),
        ...(FT_FTLData.driveMotorAmp && { driveMotorAmp: FT_FTLData.driveMotorAmp }),
        ...(FT_FTLData.driveMotorAmpNum && { driveMotorAmpNum: FT_FTLData.driveMotorAmpNum }),
        ...(FT_FTLData.driveTakeUpAir && { driveTakeUpAir: FT_FTLData.driveTakeUpAir }),
        ...(FT_FTLData.driveTakeUpAirNum && { driveTakeUpAirNum: FT_FTLData.driveTakeUpAirNum }),
        ...(FT_FTLData.takeUpDistance && { takeUpDistance: FT_FTLData.takeUpDistance }),
        ...(FT_FTLData.takeUpDistanceNum && { takeUpDistanceNum: FT_FTLData.takeUpDistanceNum }),
        ...(FT_FTLData.driveTemp && { driveTemp: FT_FTLData.driveTemp }),
        ...(FT_FTLData.driveTempNum && { driveTempNum: FT_FTLData.driveTempNum }),
        ...(FT_FTLData.driveVibration && { driveVibration: FT_FTLData.driveVibration }),
        ...(FT_FTLData.driveVibrationNum && { driveVibrationNum: FT_FTLData.driveVibrationNum }),
        ...(FT_FTLData.dogPitch && { dogPitch: FT_FTLData.dogPitch }),
        ...(FT_FTLData.dogPitchNum && { dogPitchNum: FT_FTLData.dogPitchNum }),
        ...(FT_FTLData.paintMarker && { paintMarker: FT_FTLData.paintMarker }),
        ...(FT_FTLData.paintMarkerNum && { paintMarkerNum: FT_FTLData.paintMarkerNum }),
        ...(FT_FTLData.chainVision && { chainVision: FT_FTLData.chainVision }),
        ...(FT_FTLData.lubeVision && { lubeVision: FT_FTLData.lubeVision }),
        ...(FT_FTLData.trolleyVision && { trolleyVision: FT_FTLData.trolleyVision }),
        ...(FT_FTLData.trolleyDetect && { trolleyDetect: FT_FTLData.trolleyDetect }),
        ...(FT_FTLData.omniView && { omniView: FT_FTLData.omniView }),
        ...(FT_FTLData.dcuUpgradeNum && { dcuUpgradeNum: FT_FTLData.dcuUpgradeNum }),
        ...(FT_FTLData.itNameOne && { itNameOne: FT_FTLData.itNameOne }),
        ...(FT_FTLData.itIPOne && { itIPOne: FT_FTLData.itIPOne }),
        ...(FT_FTLData.itGatewayOne && { itGatewayOne: FT_FTLData.itGatewayOne }),
        ...(FT_FTLData.itSubnetOne && { itSubnetOne: FT_FTLData.itSubnetOne }),
        ...(FT_FTLData.itDNSOne && { itDNSOne: FT_FTLData.itDNSOne }),
        ...(FT_FTLData.itSMTPOne && { itSMTPOne: FT_FTLData.itSMTPOne }),
        ...(FT_FTLData.itNameTwo && { itNameTwo: FT_FTLData.itNameTwo }),
        ...(FT_FTLData.itIPTwo && { itIPTwo: FT_FTLData.itIPTwo }),
        ...(FT_FTLData.itGatewayTwo && { itGatewayTwo: FT_FTLData.itGatewayTwo }),
        ...(FT_FTLData.itSubnetTwo && { itSubnetTwo: FT_FTLData.itSubnetTwo }),
        ...(FT_FTLData.itDNSTwo && { itDNSTwo: FT_FTLData.itDNSTwo }),
        ...(FT_FTLData.itSMTPTwo && { itSMTPTwo: FT_FTLData.itSMTPTwo }),
        ...(FT_FTLData.itNameThree && { itNameThree: FT_FTLData.itNameThree }),
        ...(FT_FTLData.itIPThree && { itIPThree: FT_FTLData.itIPThree }),
        ...(FT_FTLData.itGatewayThree && { itGatewayThree: FT_FTLData.itGatewayThree }),
        ...(FT_FTLData.itSubnetThree && { itSubnetThree: FT_FTLData.itSubnetThree }),
        ...(FT_FTLData.itDNSThree && { itDNSThree: FT_FTLData.itDNSThree }),
        ...(FT_FTLData.itSMTPThree && { itSMTPThree: FT_FTLData.itSMTPThree }),
        ...(FT_FTLData.itAdditionalNotes && { itAdditionalNotes: FT_FTLData.itAdditionalNotes }),
        ...(FT_FTLData.piuDistance && { piuDistance: FT_FTLData.piuDistance }),
        ...(FT_FTLData.switchDistance && { switchDistance: FT_FTLData.switchDistance }),
        ...(FT_FTLData.ampPickup && { ampPickup: FT_FTLData.ampPickup }),
        ...(FT_FTLData.fromAirTakeUpDistance && { fromAirTakeUpDistance: FT_FTLData.fromAirTakeUpDistance }),
        ...(FT_FTLData.specialControllerOptions && { specialControllerOptions: FT_FTLData.specialControllerOptions }),
        ...(FT_FTLData.operatingVoltage && { operatingVoltage: FT_FTLData.operatingVoltage })
      },
      wheelOpenType: FT_OP4OEData.wheelOpenType,
      ...(FT_OP4OEData.wheelClosedType && { wheelClosedType: FT_OP4OEData.wheelClosedType }),
      openStatus: FT_OP4OEData.openStatus,
      ...(FT_OP4OEData.freeWheelStatus && { freeWheelStatus: FT_OP4OEData.freeWheelStatus }),
      ...(FT_OP4OEData.guideRollerStatus && { guideRollerStatus: FT_OP4OEData.guideRollerStatus }),
      ...(FT_OP4OEData.openRaceStyleType && { openRaceStyleType: FT_OP4OEData.openRaceStyleType }),
      ...(FT_OP4OEData.closedRaceStyleType && { closedRaceStyleType: FT_OP4OEData.closedRaceStyleType }),
      ...(FT_OP4OEData.holeStatus && { holeStatus: FT_OP4OEData.holeStatus }),
      ...(FT_OP4OEData.actuatorStatus && { actuatorStatus: FT_OP4OEData.actuatorStatus }),
      ...(FT_OP4OEData.pivotStatus && { pivotStatus: FT_OP4OEData.pivotStatus }),
      ...(FT_OP4OEData.kingPinStatus && { kingPinStatus: FT_OP4OEData.kingPinStatus }),
      outboardStatus: FT_OP4OEData.outboardStatus,
      catDriveStatus: FT_OP4OEData.catDriveStatus,
      templateEData: {
          conveyorName: COE_CELData.conveyorName,
          chainSize: COE_CELData.chainSize,
          ...(COE_CELData.otherChainSize && { otherChainSize: COE_CELData.otherChainSize }),
          ...(COE_CELData.industrialChainManufacturer && { industrialChainManufacturer: COE_CELData.industrialChainManufacturer }),
          ...(COE_CELData.otherChainManufacturer && { otherChainManufacturer: COE_CELData.otherChainManufacturer }),
          ...(COE_CELData.conveyorLength && { conveyorLength: COE_CELData.conveyorLength }),
          ...(COE_CELData.conveyorLengthUnit && { conveyorLengthUnit: COE_CELData.conveyorLengthUnit }),
          ...(COE_CELData.appEnviroment && { appEnviroment: COE_CELData.appEnviroment }),
          ...(COE_CELData.otherAppEnviroment && { otherAppEnviroment: COE_CELData.otherAppEnviroment }),
          ...(COE_CELData.lubeBrand && { lubeBrand: COE_CELData.lubeBrand }),
          ...(COE_CELData.lubeType && { lubeType: COE_CELData.lubeType }),
          ...(COE_CELData.lubeViscosity && { lubeViscosity: COE_CELData.lubeViscosity }),
          ...(COE_CELData.specialControllerOptions && { specialControllerOptions: COE_CELData.specialControllerOptions }),
          ...(COE_CELData.wireMeasurementUnit && { wireMeasurementUnit: COE_CELData.wireMeasurementUnit }),
          ...(COE_CELData.conductor2 && { conductor2: COE_CELData.conductor2 }),
          ...(COE_CELData.conductor4 && { conductor4: COE_CELData.conductor4 }),
          ...(COE_CELData.conductor7 && { conductor7: COE_CELData.conductor7 }),
          ...(COE_CELData.conductor12 && { conductor12: COE_CELData.conductor12 }),
          ...(COE_CELData.junctionBoxNum && { junctionBoxNum: COE_CELData.junctionBoxNum }),
      },  
      ...(FT_OP4OEData.lubeBrand && { lubeBrand: FT_OP4OEData.lubeBrand }),
      ...(FT_OP4OEData.lubeType && { lubeType: FT_OP4OEData.lubeType }),
      ...(FT_OP4OEData.lubeViscosity && { lubeViscosity: FT_OP4OEData.lubeViscosity }),
      ...(FT_OP4OEData.chainMaster && { chainMaster: FT_OP4OEData.chainMaster }),
      ...(FT_OP4OEData.timerStatus && { timerStatus: FT_OP4OEData.timerStatus }),
      ...(FT_OP4OEData.electricStatus && { electricStatus: FT_OP4OEData.electricStatus }),
      ...(FT_OP4OEData.pneumaticStatus && { pneumaticStatus: FT_OP4OEData.pneumaticStatus }),
      ...(FT_OP4OEData.mightyLubeMonitoring && { mightyLubeMonitoring: FT_OP4OEData.mightyLubeMonitoring }),
      ...(FT_OP4OEData.plcConnection && { plcConnection: FT_OP4OEData.plcConnection }),
      ...(FT_OP4OEData.otherControllerInfo && { otherControllerInfo: FT_OP4OEData.otherControllerInfo }),
      ...(FT_OP4OEData.ftUnitType && { ftUnitType: FT_OP4OEData.ftUnitType }),
      ...(FT_OP4OEData.ftTopG && { ftTopG: FT_OP4OEData.ftTopG }),
      ...(FT_OP4OEData.ftTopH && { ftTopH: FT_OP4OEData.ftTopH }),
      ...(FT_OP4OEData.ftTopA1 && { ftTopA1: FT_OP4OEData.ftTopA1 }),
      ...(FT_OP4OEData.ftTopB1 && { ftTopB1: FT_OP4OEData.ftTopB1 }),
      ...(FT_OP4OEData.ftTopH1 && { ftTopH1: FT_OP4OEData.ftTopH1 }),
      ...(FT_OP4OEData.ftTopJ1 && { ftTopJ1: FT_OP4OEData.ftTopJ1 }),
      ...(FT_OP4OEData.ftTopL1 && { ftTopL1: FT_OP4OEData.ftTopL1 }),
      ...(FT_OP4OEData.ftTopM1 && { ftTopM1: FT_OP4OEData.ftTopM1 }),
      ...(FT_OP4OEData.ftTopN1 && { ftTopN1: FT_OP4OEData.ftTopN1 }),
      ...(FT_OP4OEData.ftTopP1 && { ftTopP1: FT_OP4OEData.ftTopP1 }),
      ...(FT_OP4OEData.ftTopR1 && { ftTopR1: FT_OP4OEData.ftTopR1 }),
    });

    req.user.cart.push({
      numRequested,
      productConfigurationInfo: order,
      productType: "FT_OP4OE"
    });

    await req.user.save();
    return res.status(200).json({ message: "FT_OP4OE entry added" });

  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: "Internal server error" });
  }
});

module.exports = router;
