const express = require("express");
const { authenticate } = require("./sessions");
const FT_OPCO = require("../models/FT_OPCO");
const templateA = require("../models/templateA");

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
  try {
    const { FT_OPCOData, numRequested } = req.body;

    const order = new FT_OPCO({
      conveyorName: FT_OPCOData.conveyorName,
      chainSize: FT_OPCOData.chainSize,
      ...(FT_OPCOData.otherChainSize && { otherChainSize: FT_OPCOData.otherChainSize }),
      industrialChainManufacturer: FT_OPCOData.industrialChainManufacturer,
      ...(FT_OPCOData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: FT_OPCOData.otherIndustrialChainManufacturer }),
      wheelManufacturer: FT_OPCOData.wheelManufacturer,
      ...(FT_OPCOData.otherWheelManufacturer && { otherWheelManufacturer: FT_OPCOData.otherWheelManufacturer }),
      conveyorLength: FT_OPCOData.conveyorLength,
      conveyorLengthUnit: FT_OPCOData.conveyorLengthUnit,
      conveyorSpeed: FT_OPCOData.conveyorSpeed,
      conveyorSpeedUnit: FT_OPCOData.conveyorSpeedUnit,
      ...(FT_OPCOData.conveyorIndex && { conveyorIndex: FT_OPCOData.conveyorIndex }),
      ...(FT_OPCOData.travelDirection && { travelDirection: FT_OPCOData.travelDirection }),
      appEnviroment: FT_OPCOData.appEnviroment,
      ...(FT_OPCOData.ovenStatus && { ovenStatus: FT_OPCOData.ovenStatus }),
      ...(FT_OPCOData.ovenTemp && { ovenTemp: FT_OPCOData.ovenTemp }),
      ...(FT_OPCOData.otherAppEnviroment && { otherAppEnviroment: FT_OPCOData.otherAppEnviroment }),
      ...(FT_OPCOData.surroundingTemp && { surroundingTemp: FT_OPCOData.surroundingTemp }),
      ...(FT_OPCOData.conveyorLoaded && { conveyorLoaded: FT_OPCOData.conveyorLoaded }),
      strandStatus: FT_OPCOData.strandStatus,
      conveyorSwing: FT_OPCOData.conveyorSwing,
      ...(FT_OPCOData.wearStrips && { wearStrips: FT_OPCOData.wearStrips }),
      ...(FT_OPCOData.skiBars && { skiBars: FT_OPCOData.skiBars }),
      ...(FT_OPCOData.relayStatus && { relayStatus: FT_OPCOData.relayStatus }),
      ...(FT_OPCOData.plantLayout && { plantLayout: FT_OPCOData.plantLayout }),
      ...(FT_OPCOData.requiredPics && { requiredPics: FT_OPCOData.requiredPics }),
      operatingVoltage: FT_OPCOData.operatingVoltage,
      controlVoltage: FT_OPCOData.controlVoltage,
      compressedAir: FT_OPCOData.compressedAir,
      existingMonitor: FT_OPCOData.existingMonitor,
      newMonitor: FT_OPCOData.newMonitor,
      monitorData: new templateA({
        ...(FT_FTLData.templateA.dcuStatus && { dcuStatus: FT_FTLData.templateA.dcuStatus }),
        ...(FT_FTLData.templateA.dcuNum && { dcuNum: FT_FTLData.templateA.dcuNum }),
        ...(FT_FTLData.templateA.existingWindows && { existingWindows: FT_FTLData.templateA.existingWindows }),
        ...(FT_FTLData.templateA.existingHeadUnit && { existingHeadUnit: FT_FTLData.templateA.existingHeadUnit }),
        ...(FT_FTLData.templateA.existingDCU && { existingDCU: FT_FTLData.templateA.existingDCU }),
        ...(FT_FTLData.templateA.existingPowerInterface && { existingPowerInterface: FT_FTLData.templateA.existingPowerInterface }),
        ...(FT_FTLData.templateA.newReservoir && { newReservoir: FT_FTLData.templateA.newReservoir }),
        ...(FT_FTLData.templateA.reservoirSize && { reservoirSize: FT_FTLData.templateA.reservoirSize }),
        ...(FT_FTLData.templateA.otherReservoirSize && { otherReservoirSize: FT_FTLData.templateA.otherReservoirSize }),
        ...(FT_FTLData.templateA.newReservoirNum && { newReservoirNum: FT_FTLData.templateA.newReservoirNum }),
        ...(FT_FTLData.templateA.typeMonitor && { typeMonitor: FT_FTLData.templateA.typeMonitor }),
        ...(FT_FTLData.templateA.driveMotorAmp && { driveMotorAmp: FT_FTLData.templateA.driveMotorAmp }),
        ...(FT_FTLData.templateA.driveMotorAmpNum && { driveMotorAmpNum: FT_FTLData.templateA.driveMotorAmpNum }),
        ...(FT_FTLData.templateA.driveTakeUpAir && { driveTakeUpAir: FT_FTLData.templateA.driveTakeUpAir }),
        ...(FT_FTLData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: FT_FTLData.templateA.driveTakeUpAirNum }),
        ...(FT_FTLData.templateA.takeUpDistance && { takeUpDistance: FT_FTLData.templateA.takeUpDistance }),
        ...(FT_FTLData.templateA.takeUpDistanceNum && { takeUpDistanceNum: FT_FTLData.templateA.takeUpDistanceNum }),
        ...(FT_FTLData.templateA.driveTemp && { driveTemp: FT_FTLData.templateA.driveTemp }),
        ...(FT_FTLData.templateA.driveTempNum && { driveTempNum: FT_FTLData.templateA.driveTempNum }),
        ...(FT_FTLData.templateA.driveVibration && { driveVibration: FT_FTLData.templateA.driveVibration }),
        ...(FT_FTLData.templateA.driveVibrationNum && { driveVibrationNum: FT_FTLData.templateA.driveVibrationNum }),
        ...(FT_FTLData.templateA.dogPitch && { dogPitch: FT_FTLData.templateA.dogPitch }),
        ...(FT_FTLData.templateA.dogPitchNum && { dogPitchNum: FT_FTLData.templateA.dogPitchNum }),
        ...(FT_FTLData.templateA.paintMarker && { paintMarker: FT_FTLData.templateA.paintMarker }),
        ...(FT_FTLData.templateA.paintMarkerNum && { paintMarkerNum: FT_FTLData.templateA.paintMarkerNum }),
        ...(FT_FTLData.templateA.chainVision && { chainVision: FT_FTLData.templateA.chainVision }),
        ...(FT_FTLData.templateA.lubeVision && { lubeVision: FT_FTLData.templateA.lubeVision }),
        ...(FT_FTLData.templateA.trolleyVision && { trolleyVision: FT_FTLData.templateA.trolleyVision }),
        ...(FT_FTLData.templateA.trolleyDetect && { trolleyDetect: FT_FTLData.templateA.trolleyDetect }),
        ...(FT_FTLData.templateA.omniView && { omniView: FT_FTLData.templateA.omniView }),
        ...(FT_FTLData.templateA.dcuUpgradeNum && { dcuUpgradeNum: FT_FTLData.templateA.dcuUpgradeNum }),
        ...(FT_FTLData.templateA.itNameOne && { itNameOne: FT_FTLData.templateA.itNameOne }),
        ...(FT_FTLData.templateA.itIPOne && { itIPOne: FT_FTLData.templateA.itIPOne }),
        ...(FT_FTLData.templateA.itGatewayOne && { itGatewayOne: FT_FTLData.templateA.itGatewayOne }),
        ...(FT_FTLData.templateA.itSubnetOne && { itSubnetOne: FT_FTLData.templateA.itSubnetOne }),
        ...(FT_FTLData.templateA.itDNSOne && { itDNSOne: FT_FTLData.templateA.itDNSOne }),
        ...(FT_FTLData.templateA.itSMTPOne && { itSMTPOne: FT_FTLData.templateA.itSMTPOne }),
        ...(FT_FTLData.templateA.itNameTwo && { itNameTwo: FT_FTLData.templateA.itNameTwo }),
        ...(FT_FTLData.templateA.itIPTwo && { itIPTwo: FT_FTLData.templateA.itIPTwo }),
        ...(FT_FTLData.templateA.itGatewayTwo && { itGatewayTwo: FT_FTLData.templateA.itGatewayTwo }),
        ...(FT_FTLData.templateA.itSubnetTwo && { itSubnetTwo: FT_FTLData.templateA.itSubnetTwo }),
        ...(FT_FTLData.templateA.itDNSTwo && { itDNSTwo: FT_FTLData.templateA.itDNSTwo }),
        ...(FT_FTLData.templateA.itSMTPTwo && { itSMTPTwo: FT_FTLData.templateA.itSMTPTwo }),
        ...(FT_FTLData.templateA.itNameThree && { itNameThree: FT_FTLData.templateA.itNameThree }),
        ...(FT_FTLData.templateA.itIPThree && { itIPThree: FT_FTLData.templateA.itIPThree }),
        ...(FT_FTLData.templateA.itGatewayThree && { itGatewayThree: FT_FTLData.templateA.itGatewayThree }),
        ...(FT_FTLData.templateA.itSubnetThree && { itSubnetThree: FT_FTLData.templateA.itSubnetThree }),
        ...(FT_FTLData.templateA.itDNSThree && { itDNSThree: FT_FTLData.templateA.itDNSThree }),
        ...(FT_FTLData.templateA.itSMTPThree && { itSMTPThree: FT_FTLData.templateA.itSMTPThree }),
        ...(FT_FTLData.templateA.itAdditionalNotes && { itAdditionalNotes: FT_FTLData.templateA.itAdditionalNotes }),
        ...(FT_FTLData.templateA.piuDistance && { piuDistance: FT_FTLData.templateA.piuDistance }),
        ...(FT_FTLData.templateA.switchDistance && { switchDistance: FT_FTLData.templateA.switchDistance }),
        ...(FT_FTLData.templateA.ampPickup && { ampPickup: FT_FTLData.templateA.ampPickup }),
        ...(FT_FTLData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: FT_FTLData.templateA.fromAirTakeUpDistance }),
        ...(FT_FTLData.templateA.specialControllerOptions && { specialControllerOptions: FT_FTLData.templateA.specialControllerOptions }),
        ...(FT_FTLData.templateA.operatingVoltage && { operatingVoltage: FT_FTLData.templateA.operatingVoltage })
      }),
      ...(FT_OPCOData.wheelOpenType && { wheelOpenType: FT_OPCOData.wheelOpenType }),
      ...(FT_OPCOData.wheelClosedType && { wheelClosedType: FT_OPCOData.wheelClosedType }),
      ...(FT_OPCOData.openStatus && { openStatus: FT_OPCOData.openStatus }),
      freeWheelStatus: FT_OPCOData.freeWheelStatus,
      actuatorStatus: FT_OPCOData.actuatorStatus,
      ...(FT_OPCOData.kingPinStatus && { kingPinStatus: FT_OPCOData.kingPinStatus }),
      ...(FT_OPCOData.guideRollerStatus && { guideRollerStatus: FT_OPCOData.guideRollerStatus }),
      ...(FT_OPCOData.openRaceStyleType && { openRaceStyleType: FT_OPCOData.openRaceStyleType }),
      ...(FT_OPCOData.closedRaceStyleType && { closedRaceStyleType: FT_OPCOData.closedRaceStyleType }),
      ...(FT_OPCOData.holeStatus && { holeStatus: FT_OPCOData.holeStatus }),
      ...(FT_OPCOData.rollerChainStatus && { rollerChainStatus: FT_OPCOData.rollerChainStatus }),
      ...(FT_OPCOData.brushStatus && { brushStatus: FT_OPCOData.brushStatus }),
      ...(FT_OPCOData.outboardStatus && { outboardStatus: FT_OPCOData.outboardStatus }),
      lubeBrand: FT_OPCOData.lubeBrand,
      lubeViscosity: FT_OPCOData.lubeViscosity,
      currentGrease: FT_OPCOData.currentGrease,
      currentLube: FT_OPCOData.currentLube,
      oilOrGrease: FT_OPCOData.oilOrGrease,
      ...(FT_OPCOData.oilViscosity && { oilViscosity: FT_OPCOData.oilViscosity }),
      ...(FT_OPCOData.greaseNGLIGrade && { greaseNGLIGrade: FT_OPCOData.greaseNGLIGrade }),
      zerkDirection: FT_OPCOData.zerkDirection,
      zerkLocationType: FT_OPCOData.zerkLocationType,
      swingStatusAgain: FT_OPCOData.swingStatusAgain,
      wheelDiameter: FT_OPCOData.wheelDiameter,
      ...(FT_OPCOData.chainMaster && { chainMaster: FT_OPCOData.chainMaster }),
      ...(FT_OPCOData.remoteStatus && { remoteStatus: FT_OPCOData.remoteStatus }),
      ...(FT_OPCOData.mountStatus && { mountStatus: FT_OPCOData.mountStatus }),
      ...(FT_OPCOData.otherUnitStatus && { otherUnitStatus: FT_OPCOData.otherUnitStatus }),
      ...(FT_OPCOData.timerStatus && { timerStatus: FT_OPCOData.timerStatus }),
      ...(FT_OPCOData.electricStatus && { electricStatus: FT_OPCOData.electricStatus }),
      ...(FT_OPCOData.mightyLubeMonitoring && { mightyLubeMonitoring: FT_OPCOData.mightyLubeMonitoring }),
      ...(FT_OPCOData.preMountType && { preMountType: FT_OPCOData.preMountType }),
      ...(FT_OPCOData.otherPreMountType && { otherPreMountType: FT_OPCOData.otherPreMountType }),
      ...(FT_OPCOData.plcConnection && { plcConnection: FT_OPCOData.plcConnection }),
      ...(FT_OPCOData.otherControllerNotes && { otherControllerNotes: FT_OPCOData.otherControllerNotes }),
      ...(FT_OPCOData.ftUnitType && { ftUnitType: FT_OPCOData.ftUnitType }),
      ...(FT_OPCOData.ftTopF && { ftTopF: FT_OPCOData.ftTopF }),
      ...(FT_OPCOData.ftTopG && { ftTopG: FT_OPCOData.ftTopG }),
      ...(FT_OPCOData.ftTopH && { ftTopH: FT_OPCOData.ftTopH }),
      ...(FT_OPCOData.ftTopA1 && { ftTopA1: FT_OPCOData.ftTopA1 }),
      ...(FT_OPCOData.ftTopB1 && { ftTopB1: FT_OPCOData.ftTopB1 }),
      ...(FT_OPCOData.ftTopH1 && { ftTopH1: FT_OPCOData.ftTopH1 }),
      ...(FT_OPCOData.ftTopJ1 && { ftTopJ1: FT_OPCOData.ftTopJ1 }),
      ...(FT_OPCOData.ftTopK1 && { ftTopK1: FT_OPCOData.ftTopK1 }),
      ...(FT_OPCOData.ftTopL1 && { ftTopL1: FT_OPCOData.ftTopL1 }),
      ...(FT_OPCOData.ftTopM1 && { ftTopM1: FT_OPCOData.ftTopM1 }),
      ...(FT_OPCOData.ftTopN1 && { ftTopN1: FT_OPCOData.ftTopN1 }),
      ...(FT_OPCOData.ftTopP1 && { ftTopP1: FT_OPCOData.ftTopP1 }),
      ...(FT_OPCOData.ftTopR1 && { ftTopR1: FT_OPCOData.ftTopR1 })
    });

    req.user.cart.push({
      numRequested,
      productConfigurationInfo: order,
      productType: "FT_OPCO"
    });

    await req.user.save();
    return res.status(200).json({ message: "FT_OPCO entry added" });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: "Internal server error" });
  }
});

module.exports = router;
