const express = require("express");
const { authenticate } = require("./sessions");
const FT_OP4OE = require("../models/FT_OP4OE");
const templateA = require("../models/templateA");
const templateE = require("../models/templateE");

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
  try {
    const { FT_OP4OEData, numRequested } = req.body;

    const order = new FT_OP4OE({
      conveyorName: FT_OP4OEData.conveyorName,
      chainSize: FT_OP4OEData.chainSize,
      ...(FT_OP4OEData.otherChainSize && { otherChainSize: FT_OP4OEData.otherChainSize }),
      industrialChainManufacturer: FT_OP4OEData.industrialChainManufacturer,
      ...(FT_OP4OEData.otherIndustrialChainManufacturer && { otherIndustrialChainManufacturer: FT_OP4OEData.otherIndustrialChainManufacturer }),
      wheelManufacturer: FT_OP4OEData.wheelManufacturer,
      ...(FT_OP4OEData.otherWheelManufacturer && { otherWheelManufacturer: FT_OP4OEData.otherWheelManufacturer }),
      conveyorLength: FT_OP4OEData.conveyorLength,
      conveyorLengthUnit: FT_OP4OEData.conveyorLengthUnit,
      conveyorSpeed: FT_OP4OEData.conveyorSpeed,
      conveyorSpeedUnit: FT_OP4OEData.conveyorSpeedUnit,
      conveyorIndex: FT_OP4OEData.conveyorIndex,
      ...(FT_OP4OEData.travelDirection && { travelDirection: FT_OP4OEData.travelDirection }),
      appEnviroment: FT_OP4OEData.appEnviroment,
      ...(FT_OP4OEData.ovenStatus && { ovenStatus: FT_OP4OEData.ovenStatus }),
      ...(FT_OP4OEData.ovenTemp && { ovenTemp: FT_OP4OEData.ovenTemp }),
      ...(FT_OP4OEData.otherAppEnviroment && { otherAppEnviroment: FT_OP4OEData.otherAppEnviroment }),
      ...(FT_OP4OEData.surroundingTemp && { surroundingTemp: FT_OP4OEData.surroundingTemp }),
      ...(FT_OP4OEData.conveyorLoaded && { conveyorLoaded: FT_OP4OEData.conveyorLoaded }),
      ...(FT_OP4OEData.conveyorSwing && { conveyorSwing: FT_OP4OEData.conveyorSwing }),
      strandStatus: FT_OP4OEData.strandStatus,
      ...(FT_OP4OEData.plantLayout && { plantLayout: FT_OP4OEData.plantLayout }),
      ...(FT_OP4OEData.requiredPics && { requiredPics: FT_OP4OEData.requiredPics }),
      operatingVoltage: FT_OP4OEData.operatingVoltage,
      controlVoltage: FT_OP4OEData.controlVoltage,
      existingMonitor: FT_OP4OEData.existingMonitor,
      newMonitor: FT_OP4OEData.newMonitor,
      monitorData: new templateA({
        ...(FT_FTLData.templateA.dcuStatus && { dcuStatus: FT_FTLData.templateA.dcuStatus }),
        ...(FT_FTLData.templateA.dcuNum && { dcuNum: FT_FTLData.templateA.dcuNum }),
        ...(FT_FTLData.templateA.existingWindows && { existingWindows: FT_FTLData.templateA.existingWindows }),
        ...(FT_FTLData.templateA.existingHeadUnit && { existingHeadUnit: FT_FTLData.templateA.existingHeadUnit }),
        ...(FT_FTLData.templateA.existingDCU && { existingDCU: FT_FTLData.templateA.existingDCU }),
        ...(FT_FTLData.templateA.existingPowerInterface && { existingPowerInterface: FT_FTLData.templateA.existingPowerInterface }),
        ...(FT_FTLData.templateA.newReservoir && { newReservoir: FT_FTLData.templateA.newReservoir }),
        ...(FT_FTLData.templateA.reservoirSize && { reservoirSize: FT_FTLData.templateA.reservoirSize }),
        ...(FT_FTLData.templateA.otherReservoirSize && { otherReservoirSize: FT_FTLData.templateA.otherReservoirSize }),
        ...(FT_FTLData.templateA.newReservoirNum && { newReservoirNum: FT_FTLData.templateA.newReservoirNum }),
        ...(FT_FTLData.templateA.typeMonitor && { typeMonitor: FT_FTLData.templateA.typeMonitor }),
        ...(FT_FTLData.templateA.driveMotorAmp && { driveMotorAmp: FT_FTLData.templateA.driveMotorAmp }),
        ...(FT_FTLData.templateA.driveMotorAmpNum && { driveMotorAmpNum: FT_FTLData.templateA.driveMotorAmpNum }),
        ...(FT_FTLData.templateA.driveTakeUpAir && { driveTakeUpAir: FT_FTLData.templateA.driveTakeUpAir }),
        ...(FT_FTLData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: FT_FTLData.templateA.driveTakeUpAirNum }),
        ...(FT_FTLData.templateA.takeUpDistance && { takeUpDistance: FT_FTLData.templateA.takeUpDistance }),
        ...(FT_FTLData.templateA.takeUpDistanceNum && { takeUpDistanceNum: FT_FTLData.templateA.takeUpDistanceNum }),
        ...(FT_FTLData.templateA.driveTemp && { driveTemp: FT_FTLData.templateA.driveTemp }),
        ...(FT_FTLData.templateA.driveTempNum && { driveTempNum: FT_FTLData.templateA.driveTempNum }),
        ...(FT_FTLData.templateA.driveVibration && { driveVibration: FT_FTLData.templateA.driveVibration }),
        ...(FT_FTLData.templateA.driveVibrationNum && { driveVibrationNum: FT_FTLData.templateA.driveVibrationNum }),
        ...(FT_FTLData.templateA.dogPitch && { dogPitch: FT_FTLData.templateA.dogPitch }),
        ...(FT_FTLData.templateA.dogPitchNum && { dogPitchNum: FT_FTLData.templateA.dogPitchNum }),
        ...(FT_FTLData.templateA.paintMarker && { paintMarker: FT_FTLData.templateA.paintMarker }),
        ...(FT_FTLData.templateA.paintMarkerNum && { paintMarkerNum: FT_FTLData.templateA.paintMarkerNum }),
        ...(FT_FTLData.templateA.chainVision && { chainVision: FT_FTLData.templateA.chainVision }),
        ...(FT_FTLData.templateA.lubeVision && { lubeVision: FT_FTLData.templateA.lubeVision }),
        ...(FT_FTLData.templateA.trolleyVision && { trolleyVision: FT_FTLData.templateA.trolleyVision }),
        ...(FT_FTLData.templateA.trolleyDetect && { trolleyDetect: FT_FTLData.templateA.trolleyDetect }),
        ...(FT_FTLData.templateA.omniView && { omniView: FT_FTLData.templateA.omniView }),
        ...(FT_FTLData.templateA.dcuUpgradeNum && { dcuUpgradeNum: FT_FTLData.templateA.dcuUpgradeNum }),
        ...(FT_FTLData.templateA.itNameOne && { itNameOne: FT_FTLData.templateA.itNameOne }),
        ...(FT_FTLData.templateA.itIPOne && { itIPOne: FT_FTLData.templateA.itIPOne }),
        ...(FT_FTLData.templateA.itGatewayOne && { itGatewayOne: FT_FTLData.templateA.itGatewayOne }),
        ...(FT_FTLData.templateA.itSubnetOne && { itSubnetOne: FT_FTLData.templateA.itSubnetOne }),
        ...(FT_FTLData.templateA.itDNSOne && { itDNSOne: FT_FTLData.templateA.itDNSOne }),
        ...(FT_FTLData.templateA.itSMTPOne && { itSMTPOne: FT_FTLData.templateA.itSMTPOne }),
        ...(FT_FTLData.templateA.itNameTwo && { itNameTwo: FT_FTLData.templateA.itNameTwo }),
        ...(FT_FTLData.templateA.itIPTwo && { itIPTwo: FT_FTLData.templateA.itIPTwo }),
        ...(FT_FTLData.templateA.itGatewayTwo && { itGatewayTwo: FT_FTLData.templateA.itGatewayTwo }),
        ...(FT_FTLData.templateA.itSubnetTwo && { itSubnetTwo: FT_FTLData.templateA.itSubnetTwo }),
        ...(FT_FTLData.templateA.itDNSTwo && { itDNSTwo: FT_FTLData.templateA.itDNSTwo }),
        ...(FT_FTLData.templateA.itSMTPTwo && { itSMTPTwo: FT_FTLData.templateA.itSMTPTwo }),
        ...(FT_FTLData.templateA.itNameThree && { itNameThree: FT_FTLData.templateA.itNameThree }),
        ...(FT_FTLData.templateA.itIPThree && { itIPThree: FT_FTLData.templateA.itIPThree }),
        ...(FT_FTLData.templateA.itGatewayThree && { itGatewayThree: FT_FTLData.templateA.itGatewayThree }),
        ...(FT_FTLData.templateA.itSubnetThree && { itSubnetThree: FT_FTLData.templateA.itSubnetThree }),
        ...(FT_FTLData.templateA.itDNSThree && { itDNSThree: FT_FTLData.templateA.itDNSThree }),
        ...(FT_FTLData.templateA.itSMTPThree && { itSMTPThree: FT_FTLData.templateA.itSMTPThree }),
        ...(FT_FTLData.templateA.itAdditionalNotes && { itAdditionalNotes: FT_FTLData.templateA.itAdditionalNotes }),
        ...(FT_FTLData.templateA.piuDistance && { piuDistance: FT_FTLData.templateA.piuDistance }),
        ...(FT_FTLData.templateA.switchDistance && { switchDistance: FT_FTLData.templateA.switchDistance }),
        ...(FT_FTLData.templateA.ampPickup && { ampPickup: FT_FTLData.templateA.ampPickup }),
        ...(FT_FTLData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: FT_FTLData.templateA.fromAirTakeUpDistance }),
        ...(FT_FTLData.templateA.specialControllerOptions && { specialControllerOptions: FT_FTLData.templateA.specialControllerOptions }),
        ...(FT_FTLData.templateA.operatingVoltage && { operatingVoltage: FT_FTLData.templateA.operatingVoltage })
      }),
      wheelOpenType: FT_OP4OEData.wheelOpenType,
      ...(FT_OP4OEData.wheelClosedType && { wheelClosedType: FT_OP4OEData.wheelClosedType }),
      openStatus: FT_OP4OEData.openStatus,
      ...(FT_OP4OEData.freeWheelStatus && { freeWheelStatus: FT_OP4OEData.freeWheelStatus }),
      ...(FT_OP4OEData.guideRollerStatus && { guideRollerStatus: FT_OP4OEData.guideRollerStatus }),
      ...(FT_OP4OEData.openRaceStyleType && { openRaceStyleType: FT_OP4OEData.openRaceStyleType }),
      ...(FT_OP4OEData.closedRaceStyleType && { closedRaceStyleType: FT_OP4OEData.closedRaceStyleType }),
      ...(FT_OP4OEData.holeStatus && { holeStatus: FT_OP4OEData.holeStatus }),
      ...(FT_OP4OEData.actuatorStatus && { actuatorStatus: FT_OP4OEData.actuatorStatus }),
      ...(FT_OP4OEData.pivotStatus && { pivotStatus: FT_OP4OEData.pivotStatus }),
      ...(FT_OP4OEData.kingPinStatus && { kingPinStatus: FT_OP4OEData.kingPinStatus }),
      outboardStatus: FT_OP4OEData.outboardStatus,
      catDriveStatus: FT_OP4OEData.catDriveStatus,
      templateEData: new templateE ({
          conveyorName: COE_CELData.templateE.conveyorName,
          chainSize: COE_CELData.templateE.chainSize,
          ...(COE_CELData.templateE.otherChainSize && { otherChainSize: COE_CELData.templateE.otherChainSize }),
          ...(COE_CELData.templateE.industrialChainManufacturer && { industrialChainManufacturer: COE_CELData.templateE.industrialChainManufacturer }),
          ...(COE_CELData.templateE.otherChainManufacturer && { otherChainManufacturer: COE_CELData.templateE.otherChainManufacturer }),
          ...(COE_CELData.templateE.conveyorLength && { conveyorLength: COE_CELData.templateE.conveyorLength }),
          ...(COE_CELData.templateE.conveyorLengthUnit && { conveyorLengthUnit: COE_CELData.templateE.conveyorLengthUnit }),
          ...(COE_CELData.templateE.appEnviroment && { appEnviroment: COE_CELData.templateE.appEnviroment }),
          ...(COE_CELData.templateE.otherAppEnviroment && { otherAppEnviroment: COE_CELData.templateE.otherAppEnviroment }),
          ...(COE_CELData.templateE.lubeBrand && { lubeBrand: COE_CELData.templateE.lubeBrand }),
          ...(COE_CELData.templateE.lubeType && { lubeType: COE_CELData.templateE.lubeType }),
          ...(COE_CELData.templateE.lubeViscosity && { lubeViscosity: COE_CELData.templateE.lubeViscosity }),
          ...(COE_CELData.templateE.specialControllerOptions && { specialControllerOptions: COE_CELData.templateE.specialControllerOptions }),
          ...(COE_CELData.templateE.wireMeasurementUnit && { wireMeasurementUnit: COE_CELData.templateE.wireMeasurementUnit }),
          ...(COE_CELData.templateE.conductor2 && { conductor2: COE_CELData.templateE.conductor2 }),
          ...(COE_CELData.templateE.conductor4 && { conductor4: COE_CELData.templateE.conductor4 }),
          ...(COE_CELData.templateE.conductor7 && { conductor7: COE_CELData.templateE.conductor7 }),
          ...(COE_CELData.templateE.conductor12 && { conductor12: COE_CELData.templateE.conductor12 }),
          ...(COE_CELData.templateE.junctionBoxNum && { junctionBoxNum: COE_CELData.templateE.junctionBoxNum }),
      }),  
      ...(FT_OP4OEData.lubeBrand && { lubeBrand: FT_OP4OEData.lubeBrand }),
      ...(FT_OP4OEData.lubeType && { lubeType: FT_OP4OEData.lubeType }),
      ...(FT_OP4OEData.lubeViscosity && { lubeViscosity: FT_OP4OEData.lubeViscosity }),
      ...(FT_OP4OEData.chainMaster && { chainMaster: FT_OP4OEData.chainMaster }),
      ...(FT_OP4OEData.timerStatus && { timerStatus: FT_OP4OEData.timerStatus }),
      ...(FT_OP4OEData.electricStatus && { electricStatus: FT_OP4OEData.electricStatus }),
      ...(FT_OP4OEData.pneumaticStatus && { pneumaticStatus: FT_OP4OEData.pneumaticStatus }),
      ...(FT_OP4OEData.mightyLubeMonitoring && { mightyLubeMonitoring: FT_OP4OEData.mightyLubeMonitoring }),
      ...(FT_OP4OEData.plcConnection && { plcConnection: FT_OP4OEData.plcConnection }),
      ...(FT_OP4OEData.otherControllerInfo && { otherControllerInfo: FT_OP4OEData.otherControllerInfo }),
      ...(FT_OP4OEData.ftUnitType && { ftUnitType: FT_OP4OEData.ftUnitType }),
      ...(FT_OP4OEData.ftTopG && { ftTopG: FT_OP4OEData.ftTopG }),
      ...(FT_OP4OEData.ftTopH && { ftTopH: FT_OP4OEData.ftTopH }),
      ...(FT_OP4OEData.ftTopA1 && { ftTopA1: FT_OP4OEData.ftTopA1 }),
      ...(FT_OP4OEData.ftTopB1 && { ftTopB1: FT_OP4OEData.ftTopB1 }),
      ...(FT_OP4OEData.ftTopH1 && { ftTopH1: FT_OP4OEData.ftTopH1 }),
      ...(FT_OP4OEData.ftTopJ1 && { ftTopJ1: FT_OP4OEData.ftTopJ1 }),
      ...(FT_OP4OEData.ftTopL1 && { ftTopL1: FT_OP4OEData.ftTopL1 }),
      ...(FT_OP4OEData.ftTopM1 && { ftTopM1: FT_OP4OEData.ftTopM1 }),
      ...(FT_OP4OEData.ftTopN1 && { ftTopN1: FT_OP4OEData.ftTopN1 }),
      ...(FT_OP4OEData.ftTopP1 && { ftTopP1: FT_OP4OEData.ftTopP1 }),
      ...(FT_OP4OEData.ftTopR1 && { ftTopR1: FT_OP4OEData.ftTopR1 }),
    });

    req.user.cart.push({
      numRequested,
      productConfigurationInfo: order,
      productType: "FT_OP4OE"
    });

    await req.user.save();
    return res.status(200).json({ message: "FT_OP4OE entry added" });

  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: "Internal server error" });
  }
});

module.exports = router;
