const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const OHP_OP139A = require("../models/OHP_OP139A");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { OHP_OP139AData, numRequested } = req.body;
        const order = new OHP_OP139A({
            conveyorName: OHP_OP139AData.conveyorName,
            chainSize: OHP_OP139AData.chainSize,
            ...(OHP_OP139AData.otherChainSize && { otherChainSize: OHP_OP139AData.otherChainSize }),
            industrialChainManufacturer: OHP_OP139AData.industrialChainManufacturer,
            ...(OHP_OP139AData.otherChainManufacturer && { otherChainManufacturer: OHP_OP139AData.otherChainManufacturer }),
            wheelManufacturer: OHP_OP139AData.wheelManufacturer,
            ...(OHP_OP139AData.otherWheelManufacturer && { otherWheelManufacturer: OHP_OP139AData.otherWheelManufacturer }),
            conveyorLength: OHP_OP139AData.conveyorLength,
            conveyorLengthUnit: OHP_OP139AData.conveyorLengthUnit,
            conveyorSpeed: OHP_OP139AData.conveyorSpeed,
            conveyorSpeedUnit: OHP_OP139AData.conveyorSpeedUnit,
            conveyorIndex: OHP_OP139AData.conveyorIndex,
            ...(OHP_OP139AData.travelDirection && { travelDirection: OHP_OP139AData.travelDirection }),
            appEnviroment: OHP_OP139AData.appEnviroment,
            ...(OHP_OP139AData.ovenStatus && { ovenStatus: OHP_OP139AData.ovenStatus }),
            ...(OHP_OP139AData.ovenTemp && { ovenTemp: OHP_OP139AData.ovenTemp }),
            ...(OHP_OP139AData.otherAppEnviroment && { otherAppEnviroment: OHP_OP139AData.otherAppEnviroment }),
            strandStatus: OHP_OP139AData.strandStatus,
            pointsOfLube: OHP_OP139AData.pointsOfLube,
            sensingMethod: OHP_OP139AData.sensingMethod,
            ...(OHP_OP139AData.surroundingTemp && { surroundingTemp: OHP_OP139AData.surroundingTemp }),
            ...(OHP_OP139AData.conveyorLoaded && { conveyorLoaded: OHP_OP139AData.conveyorLoaded }),
            ...(OHP_OP139AData.conveyorSwing && { conveyorSwing: OHP_OP139AData.conveyorSwing }),
            ...(OHP_OP139AData.compressedAir && { compressedAir: OHP_OP139AData.compressedAir }),
            ...(OHP_OP139AData.airSupplyType && { airSupplyType: OHP_OP139AData.airSupplyType }),
            operatingVoltSingle: OHP_OP139AData.operatingVoltSingle,
            controlVoltSingle: OHP_OP139AData.controlVoltSingle,
            existingMonitor: OHP_OP139AData.existingMonitor,
            newMonitor: OHP_OP139AData.newMonitor,
            monitorData: {
                ...(OHP_OP139AData.dcuStatus && { dcuStatus: OHP_OP139AData.dcuStatus }),
                ...(OHP_OP139AData.dcuNum && { dcuNum: OHP_OP139AData.dcuNum }),
                ...(OHP_OP139AData.existingWindows && { existingWindows: OHP_OP139AData.existingWindows }),
                ...(OHP_OP139AData.existingHeadUnit && { existingHeadUnit: OHP_OP139AData.existingHeadUnit }),
                ...(OHP_OP139AData.existingDCU && { existingDCU: OHP_OP139AData.existingDCU }),
                ...(OHP_OP139AData.existingPowerInterface && { existingPowerInterface: OHP_OP139AData.existingPowerInterface }),
                ...(OHP_OP139AData.newReservoir && { newReservoir: OHP_OP139AData.newReservoir }),
                ...(OHP_OP139AData.reservoirSize && { reservoirSize: OHP_OP139AData.reservoirSize }),
                ...(OHP_OP139AData.otherReservoirSize && { otherReservoirSize: OHP_OP139AData.otherReservoirSize }),
                ...(OHP_OP139AData.newReservoirNum && { newReservoirNum: OHP_OP139AData.newReservoirNum }),
                ...(OHP_OP139AData.typeMonitor && { typeMonitor: OHP_OP139AData.typeMonitor }),
                ...(OHP_OP139AData.driveMotorAmp && { driveMotorAmp: OHP_OP139AData.driveMotorAmp }),
                ...(OHP_OP139AData.driveMotorAmpNum && { driveMotorAmpNum: OHP_OP139AData.driveMotorAmpNum }),
                ...(OHP_OP139AData.driveTakeUpAir && { driveTakeUpAir: OHP_OP139AData.driveTakeUpAir }),
                ...(OHP_OP139AData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_OP139AData.driveTakeUpAirNum }),
                ...(OHP_OP139AData.takeUpDistance && { takeUpDistance: OHP_OP139AData.takeUpDistance }),
                ...(OHP_OP139AData.takeUpDistanceNum && { takeUpDistanceNum: OHP_OP139AData.takeUpDistanceNum }),
                ...(OHP_OP139AData.driveTemp && { driveTemp: OHP_OP139AData.driveTemp }),
                ...(OHP_OP139AData.driveTempNum && { driveTempNum: OHP_OP139AData.driveTempNum }),
                ...(OHP_OP139AData.driveVibration && { driveVibration: OHP_OP139AData.driveVibration }),
                ...(OHP_OP139AData.driveVibrationNum && { driveVibrationNum: OHP_OP139AData.driveVibrationNum }),
                ...(OHP_OP139AData.dogPitch && { dogPitch: OHP_OP139AData.dogPitch }), 
                ...(OHP_OP139AData.dogPitchNum && { dogPitchNum: OHP_OP139AData.dogPitchNum }),
                ...(OHP_OP139AData.paintMarker && { paintMarker: OHP_OP139AData.paintMarker }),
                ...(OHP_OP139AData.paintMarkerNum && { paintMarkerNum: OHP_OP139AData.paintMarkerNum }),
                ...(OHP_OP139AData.chainVision && { chainVision: OHP_OP139AData.chainVision }),
                ...(OHP_OP139AData.lubeVision && { lubeVision: OHP_OP139AData.lubeVision }),
                ...(OHP_OP139AData.trolleyVision && { trolleyVision: OHP_OP139AData.trolleyVision }),
                ...(OHP_OP139AData.trolleyDetect && { trolleyDetect: OHP_OP139AData.trolleyDetect }),
                ...(OHP_OP139AData.omniView && { omniView: OHP_OP139AData.omniView }),
                ...(OHP_OP139AData.dcuUpgradeNum && { dcuUpgradeNum: OHP_OP139AData.dcuUpgradeNum }),
                ...(OHP_OP139AData.itNameOne && { itNameOne: OHP_OP139AData.itNameOne }),
                ...(OHP_OP139AData.itIPOne && { itIPOne: OHP_OP139AData.itIPOne }),
                ...(OHP_OP139AData.itGatewayOne && { itGatewayOne: OHP_OP139AData.itGatewayOne }),
                ...(OHP_OP139AData.itSubnetOne && { itSubnetOne: OHP_OP139AData.itSubnetOne }),
                ...(OHP_OP139AData.itDNSOne && { itDNSOne: OHP_OP139AData.itDNSOne }),
                ...(OHP_OP139AData.itSMTPOne && { itSMTPOne: OHP_OP139AData.itSMTPOne }),
                ...(OHP_OP139AData.itNameTwo && { itNameTwo: OHP_OP139AData.itNameTwo }),
                ...(OHP_OP139AData.itIPTwo && { itIPTwo: OHP_OP139AData.itIPTwo }),
                ...(OHP_OP139AData.itGatewayTwo && { itGatewayTwo: OHP_OP139AData.itGatewayTwo }),
                ...(OHP_OP139AData.itSubnetTwo && { itSubnetTwo: OHP_OP139AData.itSubnetTwo }),
                ...(OHP_OP139AData.itDNSTwo && { itDNSTwo: OHP_OP139AData.itDNSTwo }),
                ...(OHP_OP139AData.itSMTPTwo && { itSMTPTwo: OHP_OP139AData.itSMTPTwo }),
                ...(OHP_OP139AData.itNameThree && { itNameThree: OHP_OP139AData.itNameThree }),
                ...(OHP_OP139AData.itIPThree && { itIPThree: OHP_OP139AData.itIPThree }),
                ...(OHP_OP139AData.itGatewayThree && { itGatewayThree: OHP_OP139AData.itGatewayThree }),
                ...(OHP_OP139AData.itSubnetThree && { itSubnetThree: OHP_OP139AData.itSubnetThree }),
                ...(OHP_OP139AData.itDNSThree && { itDNSThree: OHP_OP139AData.itDNSThree }),
                ...(OHP_OP139AData.itSMTPThree && { itSMTPThree: OHP_OP139AData.itSMTPThree }),
                ...(OHP_OP139AData.itAdditionalNotes && { itAdditionalNotes: OHP_OP139AData.itAdditionalNotes }),
                ...(OHP_OP139AData.piuDistance && { piuDistance: OHP_OP139AData.piuDistance }),
                ...(OHP_OP139AData.switchDistance && { switchDistance: OHP_OP139AData.switchDistance }),
                ...(OHP_OP139AData.ampPickup && { ampPickup: OHP_OP139AData.ampPickup }),
                ...(OHP_OP139AData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_OP139AData.fromAirTakeUpDistance }),
                ...(OHP_OP139AData.specialControllerOptions && { specialControllerOptions: OHP_OP139AData.specialControllerOptions })
            },

            addFreeCarrier: OHP_OP139AData.addFreeCarrier,

            templateBData: {
                conveyorName: OHP_OP139AData.conveyorName,
                industrialChainManufacturer: OHP_OP139AData.industrialChainManufacturer,
                ...(OHP_OP139AData.otherChainManufacturer && { otherChainManufacturer: OHP_OP139AData.otherChainManufacturer }),
                wheelManufacturer: OHP_OP139AData.wheelManufacturer,
                ...(OHP_OP139AData.wheelManufacturer && { wheelManufacturer: OHP_OP139AData.wheelManufacturer}),
                conveyorSpeed: OHP_OP139AData.conveyorSpeed,
                conveyorSpeedUnit: OHP_OP139AData.conveyorSpeedUnit,
                conveyorIndex: OHP_OP139AData.conveyorIndex,
                ...(OHP_OP139AData.travelDirection && { travelDirection: OHP_OP139AData.travelDirection}),
                appEnviroment: OHP_OP139AData.appEnviroment,
                ...(OHP_OP139AData.otherAppEnviroment && { otherAppEnviroment: OHP_OP139AData.otherAppEnviroment}),
                surroundingTemp: OHP_OP139AData.surroundingTemp,
                orientationType: OHP_OP139AData.orientationType,
                operatingVoltage: OHP_OP139AData.operatingVoltage,
                controlVoltSingle: OHP_OP139AData.controlVoltSingle,
                compressedAir: OHP_OP139AData.compressedAir,
                ...(OHP_OP139AData.airSupplyType && { airSupplyType: OHP_OP139AData.airSupplyType}),
            existingMonitor: OHP_OP139AData.existingMonitor,
            newMonitor: OHP_OP139AData.newMonitor,
            templateA_BData: {
                ...(OHP_OP139AData.dcuStatus && { dcuStatus: OHP_OP139AData.dcuStatus }),
                ...(OHP_OP139AData.dcuNum && { dcuNum: OHP_OP139AData.dcuNum }),
                ...(OHP_OP139AData.existingWindows && { existingWindows: OHP_OP139AData.existingWindows }),
                ...(OHP_OP139AData.existingHeadUnit && { existingHeadUnit: OHP_OP139AData.existingHeadUnit }),
                ...(OHP_OP139AData.existingDCU && { existingDCU: OHP_OP139AData.existingDCU }),
                ...(OHP_OP139AData.existingPowerInterface && { existingPowerInterface: OHP_OP139AData.existingPowerInterface }),
                ...(OHP_OP139AData.newReservoir && { newReservoir: OHP_OP139AData.newReservoir }),
                ...(OHP_OP139AData.reservoirSize && { reservoirSize: OHP_OP139AData.reservoirSize }),
                ...(OHP_OP139AData.otherReservoirSize && { otherReservoirSize: OHP_OP139AData.otherReservoirSize }),
                ...(OHP_OP139AData.newReservoirNum && { newReservoirNum: OHP_OP139AData.newReservoirNum }),
                ...(OHP_OP139AData.typeMonitor && { typeMonitor: OHP_OP139AData.typeMonitor }),
                ...(OHP_OP139AData.driveMotorAmp && { driveMotorAmp: OHP_OP139AData.driveMotorAmp }),
                ...(OHP_OP139AData.driveMotorAmpNum && { driveMotorAmpNum: OHP_OP139AData.driveMotorAmpNum }),
                ...(OHP_OP139AData.driveTakeUpAir && { driveTakeUpAir: OHP_OP139AData.driveTakeUpAir }),
                ...(OHP_OP139AData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_OP139AData.driveTakeUpAirNum }),
                ...(OHP_OP139AData.takeUpDistance && { takeUpDistance: OHP_OP139AData.takeUpDistance }),
                ...(OHP_OP139AData.takeUpDistanceNum && { takeUpDistanceNum: OHP_OP139AData.takeUpDistanceNum }),
                ...(OHP_OP139AData.driveTemp && { driveTemp: OHP_OP139AData.driveTemp }),
                ...(OHP_OP139AData.driveTempNum && { driveTempNum: OHP_OP139AData.driveTempNum }),
                ...(OHP_OP139AData.driveVibration && { driveVibration: OHP_OP139AData.driveVibration }),
                ...(OHP_OP139AData.driveVibrationNum && { driveVibrationNum: OHP_OP139AData.driveVibrationNum }),
                ...(OHP_OP139AData.dogPitch && { dogPitch: OHP_OP139AData.dogPitch }),
                ...(OHP_OP139AData.dogPitchNum && { dogPitchNum: OHP_OP139AData.dogPitchNum }),
                ...(OHP_OP139AData.paintMarker && { paintMarker: OHP_OP139AData.paintMarker }),
                ...(OHP_OP139AData.paintMarkerNum && { paintMarkerNum: OHP_OP139AData.paintMarkerNum }),
                ...(OHP_OP139AData.chainVision && { chainVision: OHP_OP139AData.chainVision }),
                ...(OHP_OP139AData.lubeVision && { lubeVision: OHP_OP139AData.lubeVision }),
                ...(OHP_OP139AData.trolleyVision && { trolleyVision: OHP_OP139AData.trolleyVision }),
                ...(OHP_OP139AData.trolleyDetect && { trolleyDetect: OHP_OP139AData.trolleyDetect }),
                ...(OHP_OP139AData.omniView && { omniView: OHP_OP139AData.omniView }),
                ...(OHP_OP139AData.dcuUpgradeNum && { dcuUpgradeNum: OHP_OP139AData.dcuUpgradeNum }),
                ...(OHP_OP139AData.itNameOne && { itNameOne: OHP_OP139AData.itNameOne }),
                ...(OHP_OP139AData.itIPOne && { itIPOne: OHP_OP139AData.itIPOne }),
                ...(OHP_OP139AData.itGatewayOne && { itGatewayOne: OHP_OP139AData.itGatewayOne }),
                ...(OHP_OP139AData.itSubnetOne && { itSubnetOne: OHP_OP139AData.itSubnetOne }),
                ...(OHP_OP139AData.itDNSOne && { itDNSOne: OHP_OP139AData.itDNSOne }),
                ...(OHP_OP139AData.itSMTPOne && { itSMTPOne: OHP_OP139AData.itSMTPOne }),
                ...(OHP_OP139AData.itNameTwo && { itNameTwo: OHP_OP139AData.itNameTwo }),
                ...(OHP_OP139AData.itIPTwo && { itIPTwo: OHP_OP139AData.itIPTwo }),
                ...(OHP_OP139AData.itGatewayTwo && { itGatewayTwo: OHP_OP139AData.itGatewayTwo }),
                ...(OHP_OP139AData.itSubnetTwo && { itSubnetTwo: OHP_OP139AData.itSubnetTwo }),
                ...(OHP_OP139AData.itDNSTwo && { itDNSTwo: OHP_OP139AData.itDNSTwo }),
                ...(OHP_OP139AData.itSMTPTwo && { itSMTPTwo: OHP_OP139AData.itSMTPTwo }),
                ...(OHP_OP139AData.itNameThree && { itNameThree: OHP_OP139AData.itNameThree }),
                ...(OHP_OP139AData.itIPThree && { itIPThree: OHP_OP139AData.itIPThree }),
                ...(OHP_OP139AData.itGatewayThree && { itGatewayThree: OHP_OP139AData.itGatewayThree }),
                ...(OHP_OP139AData.itSubnetThree && { itSubnetThree: OHP_OP139AData.itSubnetThree }),
                ...(OHP_OP139AData.itDNSThree && { itDNSThree: OHP_OP139AData.itDNSThree }),
                ...(OHP_OP139AData.itSMTPThree && { itSMTPThree: OHP_OP139AData.itSMTPThree }),
                ...(OHP_OP139AData.itAdditionalNotes && { itAdditionalNotes: OHP_OP139AData.itAdditionalNotes }),
                ...(OHP_OP139AData.piuDistance && { piuDistance: OHP_OP139AData.piuDistance }),
                ...(OHP_OP139AData.switchDistance && { switchDistance: OHP_OP139AData.switchDistance }),
                ...(OHP_OP139AData.ampPickup && { ampPickup: OHP_OP139AData.ampPickup }),
                ...(OHP_OP139AData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_OP139AData.fromAirTakeUpDistance }),
                ...(OHP_OP139AData.specialControllerOptions && { specialControllerOptions: OHP_OP139AData.specialControllerOptions }),
                ...(OHP_OP139AData.operatingVoltage && { operatingVoltage: OHP_OP139AData.operatingVoltage })

                },


                freeWheelStatus: OHP_OP139AData.freeWheelStatus,
                actuatorStatus: OHP_OP139AData.actuatorStatus,
                ...(OHP_OP139AData.pivotStatus && { pivotStatus: OHP_OP139AData.pivotStatus}),
                kingPinStatus: OHP_OP139AData.kingPinStatus,
                lubeBrand: OHP_OP139AData.lubeBrand,
                lubeViscosity: OHP_OP139AData.lubeViscosity,
                ...(OHP_OP139AData.lubeType && { lubeType: OHP_OP139AData.lubeType}),
                currentGrease: OHP_OP139AData.currentGrease,
                currentGreaseGrade: OHP_OP139AData.currentGreaseGrade,
                zerkDirection: OHP_OP139AData.zerkDirection,
                zerkLocationType: OHP_OP139AData.zerkLocationType,
                wheelDiameter: OHP_OP139AData.wheelDiameter,
                conveyorSwing: OHP_OP139AData.conveyorSwing,
                ...(OHP_OP139AData.chainMaster && { lubeType: OHP_OP139AData.chainMaster}),
                ...(OHP_OP139AData.remoteStatus && { lubeType: OHP_OP139AData.remoteStatus}),
                ...(OHP_OP139AData.mountStatus && { lubeType: OHP_OP139AData.mountStatus}),
                ...(OHP_OP139AData.otherUnitStatus && { lubeType: OHP_OP139AData.otherUnitStatus}),
                ...(OHP_OP139AData.timerStatus && { lubeType: OHP_OP139AData.timerStatus}),
                ...(OHP_OP139AData.electricStatus && { lubeType: OHP_OP139AData.electricStatus}),
                ...(OHP_OP139AData.mightyLubeMonitoring && { lubeType: OHP_OP139AData.mightyLubeMonitoring}),
                ...(OHP_OP139AData.preMountType && { lubeType: OHP_OP139AData.preMountType}),
                ...(OHP_OP139AData.otherPreMountType && { lubeType: OHP_OP139AData.otherPreMountType}),
                ...(OHP_OP139AData.plcConnection && { lubeType: OHP_OP139AData.plcConnection}),
                ...(OHP_OP139AData.otherControllerNotes && { lubeType: OHP_OP139AData.otherControllerNotes}),
                ...(OHP_OP139AData.templateB_UnitType && { lubeType: OHP_OP139AData.templateB_UnitType}),
                ...(OHP_OP139AData.templateB_InvertedB && { lubeType: OHP_OP139AData.templateB_InvertedB}),
                ...(OHP_OP139AData.templateB_InvertedE && { lubeType: OHP_OP139AData.templateB_InvertedE}),
                ...(OHP_OP139AData.templateB_InvertedG && { lubeType: OHP_OP139AData.templateB_InvertedG}),
                ...(OHP_OP139AData.templateB_InvertedH && { lubeType: OHP_OP139AData.templateB_InvertedH}),
                ...(OHP_OP139AData.templateB_InvertedK && { lubeType: OHP_OP139AData.templateB_InvertedK}),
                ...(OHP_OP139AData.templateB_InvertedT && { lubeType: OHP_OP139AData.templateB_InvertedT}),
                ...(OHP_OP139AData.templateB_InvertedU && { lubeType: OHP_OP139AData.templateB_InvertedU}),
                ...(OHP_OP139AData.templateB_InvertedV && { lubeType: OHP_OP139AData.templateB_InvertedV}),
                ...(OHP_OP139AData.templateB_InvertedW && { lubeType: OHP_OP139AData.templateB_InvertedW}),

            },



            templateCData: {
                conveyorName: OHP_OP139AData.conveyorName,
                industrialChainManufacturer: OHP_OP139AData.industrialChainManufacturer,
                ...(OHP_OP139AData.otherChainManufacturer && { otherChainManufacturer: OHP_OP139AData.otherChainManufacturer }),
                wheelManufacturer: OHP_OP139AData.wheelManufacturer,
                ...(OHP_OP139AData.wheelManufacturer && { wheelManufacturer: OHP_OP139AData.wheelManufacturer}),
                conveyorSpeed: OHP_OP139AData.conveyorSpeed,
                conveyorSpeedUnit: OHP_OP139AData.conveyorSpeedUnit,
                conveyorIndex: OHP_OP139AData.conveyorIndex,
                ...(OHP_OP139AData.travelDirection && { travelDirection: OHP_OP139AData.travelDirection}),
                appEnviroment: OHP_OP139AData.appEnviroment,
                ...(OHP_OP139AData.otherAppEnviroment && { otherAppEnviroment: OHP_OP139AData.otherAppEnviroment}),
                surroundingTemp: OHP_OP139AData.surroundingTemp,
                orientationType: OHP_OP139AData.orientationType,
                guideWheelsEven: OHP_OP139AData.guideWheelsEven,
                operatingVoltage: OHP_OP139AData.operatingVoltage,
                controlVoltSingle: OHP_OP139AData.controlVoltSingle,
                compressedAir: OHP_OP139AData.compressedAir,
                ...(OHP_OP139AData.airSupplyType && { airSupplyType: OHP_OP139AData.airSupplyType}),
                existingMonitor: OHP_OP139AData.existingMonitor,
                newMonitor: OHP_OP139AData.newMonitor,
                templateA_CData: {
                ...(OHP_OP139AData.dcuStatus && { dcuStatus: OHP_OP139AData.dcuStatus }),
                ...(OHP_OP139AData.dcuNum && { dcuNum: OHP_OP139AData.dcuNum }),
                ...(OHP_OP139AData.existingWindows && { existingWindows: OHP_OP139AData.existingWindows }),
                ...(OHP_OP139AData.existingHeadUnit && { existingHeadUnit: OHP_OP139AData.existingHeadUnit }),
                ...(OHP_OP139AData.existingDCU && { existingDCU: OHP_OP139AData.existingDCU }),
                ...(OHP_OP139AData.existingPowerInterface && { existingPowerInterface: OHP_OP139AData.existingPowerInterface }),
                ...(OHP_OP139AData.newReservoir && { newReservoir: OHP_OP139AData.newReservoir }),
                ...(OHP_OP139AData.reservoirSize && { reservoirSize: OHP_OP139AData.reservoirSize }),
                ...(OHP_OP139AData.otherReservoirSize && { otherReservoirSize: OHP_OP139AData.otherReservoirSize }),
                ...(OHP_OP139AData.newReservoirNum && { newReservoirNum: OHP_OP139AData.newReservoirNum }),
                ...(OHP_OP139AData.typeMonitor && { typeMonitor: OHP_OP139AData.typeMonitor }),
                ...(OHP_OP139AData.driveMotorAmp && { driveMotorAmp: OHP_OP139AData.driveMotorAmp }),
                ...(OHP_OP139AData.driveMotorAmpNum && { driveMotorAmpNum: OHP_OP139AData.driveMotorAmpNum }),
                ...(OHP_OP139AData.driveTakeUpAir && { driveTakeUpAir: OHP_OP139AData.driveTakeUpAir }),
                ...(OHP_OP139AData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_OP139AData.driveTakeUpAirNum }),
                ...(OHP_OP139AData.takeUpDistance && { takeUpDistance: OHP_OP139AData.takeUpDistance }),
                ...(OHP_OP139AData.takeUpDistanceNum && { takeUpDistanceNum: OHP_OP139AData.takeUpDistanceNum }),
                ...(OHP_OP139AData.driveTemp && { driveTemp: OHP_OP139AData.driveTemp }),
                ...(OHP_OP139AData.driveTempNum && { driveTempNum: OHP_OP139AData.driveTempNum }),
                ...(OHP_OP139AData.driveVibration && { driveVibration: OHP_OP139AData.driveVibration }),
                ...(OHP_OP139AData.driveVibrationNum && { driveVibrationNum: OHP_OP139AData.driveVibrationNum }),
                ...(OHP_OP139AData.dogPitch && { dogPitch: OHP_OP139AData.dogPitch }),
                ...(OHP_OP139AData.dogPitchNum && { dogPitchNum: OHP_OP139AData.dogPitchNum }),
                ...(OHP_OP139AData.paintMarker && { paintMarker: OHP_OP139AData.paintMarker }),
                ...(OHP_OP139AData.paintMarkerNum && { paintMarkerNum: OHP_OP139AData.paintMarkerNum }),
                ...(OHP_OP139AData.chainVision && { chainVision: OHP_OP139AData.chainVision }),
                ...(OHP_OP139AData.lubeVision && { lubeVision: OHP_OP139AData.lubeVision }),
                ...(OHP_OP139AData.trolleyVision && { trolleyVision: OHP_OP139AData.trolleyVision }),
                ...(OHP_OP139AData.trolleyDetect && { trolleyDetect: OHP_OP139AData.trolleyDetect }),
                ...(OHP_OP139AData.omniView && { omniView: OHP_OP139AData.omniView }),
                ...(OHP_OP139AData.dcuUpgradeNum && { dcuUpgradeNum: OHP_OP139AData.dcuUpgradeNum }),
                ...(OHP_OP139AData.itNameOne && { itNameOne: OHP_OP139AData.itNameOne }),
                ...(OHP_OP139AData.itIPOne && { itIPOne: OHP_OP139AData.itIPOne }),
                ...(OHP_OP139AData.itGatewayOne && { itGatewayOne: OHP_OP139AData.itGatewayOne }),
                ...(OHP_OP139AData.itSubnetOne && { itSubnetOne: OHP_OP139AData.itSubnetOne }),
                ...(OHP_OP139AData.itDNSOne && { itDNSOne: OHP_OP139AData.itDNSOne }),
                ...(OHP_OP139AData.itSMTPOne && { itSMTPOne: OHP_OP139AData.itSMTPOne }),
                ...(OHP_OP139AData.itNameTwo && { itNameTwo: OHP_OP139AData.itNameTwo }),
                ...(OHP_OP139AData.itIPTwo && { itIPTwo: OHP_OP139AData.itIPTwo }),
                ...(OHP_OP139AData.itGatewayTwo && { itGatewayTwo: OHP_OP139AData.itGatewayTwo }),
                ...(OHP_OP139AData.itSubnetTwo && { itSubnetTwo: OHP_OP139AData.itSubnetTwo }),
                ...(OHP_OP139AData.itDNSTwo && { itDNSTwo: OHP_OP139AData.itDNSTwo }),
                ...(OHP_OP139AData.itSMTPTwo && { itSMTPTwo: OHP_OP139AData.itSMTPTwo }),
                ...(OHP_OP139AData.itNameThree && { itNameThree: OHP_OP139AData.itNameThree }),
                ...(OHP_OP139AData.itIPThree && { itIPThree: OHP_OP139AData.itIPThree }),
                ...(OHP_OP139AData.itGatewayThree && { itGatewayThree: OHP_OP139AData.itGatewayThree }),
                ...(OHP_OP139AData.itSubnetThree && { itSubnetThree: OHP_OP139AData.itSubnetThree }),
                ...(OHP_OP139AData.itDNSThree && { itDNSThree: OHP_OP139AData.itDNSThree }),
                ...(OHP_OP139AData.itSMTPThree && { itSMTPThree: OHP_OP139AData.itSMTPThree }),
                ...(OHP_OP139AData.itAdditionalNotes && { itAdditionalNotes: OHP_OP139AData.itAdditionalNotes }),
                ...(OHP_OP139AData.piuDistance && { piuDistance: OHP_OP139AData.piuDistance }),
                ...(OHP_OP139AData.switchDistance && { switchDistance: OHP_OP139AData.switchDistance }),
                ...(OHP_OP139AData.ampPickup && { ampPickup: OHP_OP139AData.ampPickup }),
                ...(OHP_OP139AData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_OP139AData.fromAirTakeUpDistance }),
                ...(OHP_OP139AData.specialControllerOptions && { specialControllerOptions: OHP_OP139AData.specialControllerOptions }),
                ...(OHP_OP139AData.operatingVoltage && { operatingVoltage: OHP_OP139AData.operatingVoltage })

                },
                freeWheelStatus: OHP_OP139AData.freeWheelStatus,
                actuatorStatus: OHP_OP139AData.actuatorStatus,
                ...(OHP_OP139AData.pivotStatus && { pivotStatus: OHP_OP139AData.pivotStatus}),
                kingPinStatus: OHP_OP139AData.kingPinStatus,
                lubeBrand: OHP_OP139AData.lubeBrand,
                lubeViscosity: OHP_OP139AData.lubeViscosity,
                ...(OHP_OP139AData.lubeType && { lubeType: OHP_OP139AData.lubeType}),
                currentGrease: OHP_OP139AData.currentGrease,
                currentGreaseGrade: OHP_OP139AData.currentGreaseGrade,
                zerkDirection: OHP_OP139AData.zerkDirection,
                zerkLocationType: OHP_OP139AData.zerkLocationType,
                wheelDiameter: OHP_OP139AData.wheelDiameter,
                conveyorSwing: OHP_OP139AData.conveyorSwing,
                ...(OHP_OP139AData.chainMaster && { lubeType: OHP_OP139AData.chainMaster}),
                ...(OHP_OP139AData.remoteStatus && { lubeType: OHP_OP139AData.remoteStatus}),
                ...(OHP_OP139AData.mountStatus && { lubeType: OHP_OP139AData.mountStatus}),
                ...(OHP_OP139AData.otherUnitStatus && { lubeType: OHP_OP139AData.otherUnitStatus}),
                ...(OHP_OP139AData.timerStatus && { lubeType: OHP_OP139AData.timerStatus}),
                ...(OHP_OP139AData.electricStatus && { lubeType: OHP_OP139AData.electricStatus}),
                ...(OHP_OP139AData.mightyLubeMonitoring && { lubeType: OHP_OP139AData.mightyLubeMonitoring}),
                ...(OHP_OP139AData.preMountType && { lubeType: OHP_OP139AData.preMountType}),
                ...(OHP_OP139AData.otherPreMountType && { lubeType: OHP_OP139AData.otherPreMountType}),
                ...(OHP_OP139AData.plcConnection && { lubeType: OHP_OP139AData.plcConnection}),
                ...(OHP_OP139AData.otherControllerNotes && { lubeType: OHP_OP139AData.otherControllerNotes}),
                ...(OHP_OP139AData.templateC_UnitType && { lubeType: OHP_OP139AData.templateC_UnitType}),
                templateC_InvertedA: OHP_OP139AData.templateC_InvertedA,
                templateC_InvertedB: OHP_OP139AData.templateC_InvertedB,
                templateC_InvertedE: OHP_OP139AData.templateC_InvertedE,
                templateC_InvertedS: OHP_OP139AData.templateC_InvertedS,
            },
            ...(OHP_OP139AData.railLubeStatus && { railLubeStatus: OHP_OP139AData.railLubeStatus }),
            ...(OHP_OP139AData.lubeBrand && { lubeBrand: OHP_OP139AData.lubeBrand }),
            ...(OHP_OP139AData.lubeType && { lubeType: OHP_OP139AData.lubeType }),
            ...(OHP_OP139AData.lubeViscosity && { lubeViscosity: OHP_OP139AData.lubeViscosity }),
            ...(OHP_OP139AData.sideLubeStatus && { sideLubeStatus: OHP_OP139AData.sideLubeStatus }),
            ...(OHP_OP139AData.topLubeStatus && { topLubeStatus: OHP_OP139AData.topLubeStatus }),
            ...(OHP_OP139AData.chainCleanStatus && { chainCleanStatus: OHP_OP139AData.chainCleanStatus }),
            ...(OHP_OP139AData.chainMaster && { chainMaster: OHP_OP139AData.chainMaster }),
            ...(OHP_OP139AData.otherUnitStatus && { otherUnitStatus: OHP_OP139AData.otherUnitStatus }),
            ...(OHP_OP139AData.timerStatus && { timerStatus: OHP_OP139AData.timerStatus }),
                electricStatus: OHP_OP139AData.electricStatus,
            ...(OHP_OP139AData.pneumaticStatus && { pneumaticStatus: OHP_OP139AData.pneumaticStatus }),
            ...(OHP_OP139AData.mightyLubeMonitoring && { mightyLubeMonitoring: OHP_OP139AData.mightyLubeMonitoring }),
            ...(OHP_OP139AData.plcConnection && { plcConnection: OHP_OP139AData.plcConnection }),
            ...(OHP_OP139AData.otherControllerNotes && { otherControllerNotes: OHP_OP139AData.otherControllerNotes }),
            ...(OHP_OP139AData.ohpUnitType && { ohpUnitType: OHP_OP139AData.ohpUnitType }),
            ...(OHP_OP139AData.chainDrop && { chainDrop: OHP_OP139AData.chainDrop }),
            ...(OHP_OP139AData.ohpDiameter && { ohpDiameter: OHP_OP139AData.ohpDiameter }),
            ...(OHP_OP139AData.ohpWidth && { ohpWidth: OHP_OP139AData.ohpWidth }),
            ...(OHP_OP139AData.ohpHeight && { ohpHeight: OHP_OP139AData.ohpHeight }),
            ...(OHP_OP139AData.radioButtonType && { radioButtonType: OHP_OP139AData.radioButtonType })
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "OHP_OP139A"
        });
        await req.user.save();
        return res.status(200).json({ message: "OHP_OP139A entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;