const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const OHP_OP139A = require("../models/OHP_OP139A");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { OHP_OP139AData, numRequested } = req.body;
        const order = new OHP_OP139A({
            conveyorName: OHP_OP139AData.conveyorName,
            chainSize: OHP_OP139AData.chainSize,
            ...(OHP_OP139AData.otherChainSize && { otherChainSize: OHP_OP139AData.otherChainSize }),
            industrialChainManufacturer: OHP_OP139AData.industrialChainManufacturer,
            ...(OHP_OP139AData.otherChainManufacturer && { otherChainManufacturer: OHP_OP139AData.otherChainManufacturer }),
            wheelManufacturer: OHP_OP139AData.wheelManufacturer,
            ...(OHP_OP139AData.otherWheelManufacturer && { otherWheelManufacturer: OHP_OP139AData.otherWheelManufacturer }),
            conveyorLength: OHP_OP139AData.conveyorLength,
            conveyorLengthUnit: OHP_OP139AData.conveyorLengthUnit,
            conveyorSpeed: OHP_OP139AData.conveyorSpeed,
            conveyorSpeedUnit: OHP_OP139AData.conveyorSpeedUnit,
            conveyorIndex: OHP_OP139AData.conveyorIndex,
            ...(OHP_OP139AData.travelDirection && { travelDirection: OHP_OP139AData.travelDirection }),
            appEnviroment: OHP_OP139AData.appEnviroment,
            ...(OHP_OP139AData.ovenStatus && { ovenStatus: OHP_OP139AData.ovenStatus }),
            ...(OHP_OP139AData.ovenTemp && { ovenTemp: OHP_OP139AData.ovenTemp }),
            ...(OHP_OP139AData.otherAppEnviroment && { otherAppEnviroment: OHP_OP139AData.otherAppEnviroment }),
            strandStatus: OHP_OP139AData.strandStatus,
            pointsOfLube: OHP_OP139AData.pointsOfLube,
            sensingMethod: OHP_OP139AData.sensingMethod,
            ...(OHP_OP139AData.surroundingTemp && { surroundingTemp: OHP_OP139AData.surroundingTemp }),
            ...(OHP_OP139AData.conveyorLoaded && { conveyorLoaded: OHP_OP139AData.conveyorLoaded }),
            ...(OHP_OP139AData.conveyorSwing && { conveyorSwing: OHP_OP139AData.conveyorSwing }),
            ...(OHP_OP139AData.compressedAir && { compressedAir: OHP_OP139AData.compressedAir }),
            ...(OHP_OP139AData.airSupplyType && { airSupplyType: OHP_OP139AData.airSupplyType }),
            operatingVoltSingle: OHP_OP139AData.operatingVoltSingle,
            controlVoltSingle: OHP_OP139AData.controlVoltSingle,
        monitorData: 
        {
                existingMonitor: OHP_OP139AData.templateA.existingMonitor,
                newMonitor: OHP_OP139AData.templateA.newMonitor,		
                ...(OHP_OP139AData.templateA.dcuStatus && { dcuStatus: OHP_OP139AData.templateA.dcuStatus }),
                ...(OHP_OP139AData.templateA.dcuNum && { dcuNum: OHP_OP139AData.templateA.dcuNum }),
                ...(OHP_OP139AData.templateA.existingWindows && { existingWindows: OHP_OP139AData.templateA.existingWindows }),
                ...(OHP_OP139AData.templateA.existingHeadUnit && { existingHeadUnit: OHP_OP139AData.templateA.existingHeadUnit }),
                ...(OHP_OP139AData.templateA.existingDCU && { existingDCU: OHP_OP139AData.templateA.existingDCU }),
                ...(OHP_OP139AData.templateA.existingPowerInterface && { existingPowerInterface: OHP_OP139AData.templateA.existingPowerInterface }),
                ...(OHP_OP139AData.templateA.newReservoir && { newReservoir: OHP_OP139AData.templateA.newReservoir }),
                ...(OHP_OP139AData.templateA.reservoirSize && { reservoirSize: OHP_OP139AData.templateA.reservoirSize }),
                ...(OHP_OP139AData.templateA.otherReservoirSize && { otherReservoirSize: OHP_OP139AData.templateA.otherReservoirSize }),
                ...(OHP_OP139AData.templateA.newReservoirNum && { newReservoirNum: OHP_OP139AData.templateA.newReservoirNum }),
                ...(OHP_OP139AData.templateA.typeMonitor && { typeMonitor: OHP_OP139AData.templateA.typeMonitor }),
                ...(OHP_OP139AData.templateA.driveMotorAmp && { driveMotorAmp: OHP_OP139AData.templateA.driveMotorAmp }),
                ...(OHP_OP139AData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_OP139AData.templateA.driveMotorAmpNum }),
                ...(OHP_OP139AData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_OP139AData.templateA.driveTakeUpAir }),
                ...(OHP_OP139AData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_OP139AData.templateA.driveTakeUpAirNum }),
                ...(OHP_OP139AData.templateA.takeUpDistance && { takeUpDistance: OHP_OP139AData.templateA.takeUpDistance }),
                ...(OHP_OP139AData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_OP139AData.templateA.takeUpDistanceNum }),
                ...(OHP_OP139AData.templateA.driveTemp && { driveTemp: OHP_OP139AData.templateA.driveTemp }),
                ...(OHP_OP139AData.templateA.driveTempNum && { driveTempNum: OHP_OP139AData.templateA.driveTempNum }),
                ...(OHP_OP139AData.templateA.driveVibration && { driveVibration: OHP_OP139AData.templateA.driveVibration }),
                ...(OHP_OP139AData.templateA.driveVibrationNum && { driveVibrationNum: OHP_OP139AData.templateA.driveVibrationNum }),
                ...(OHP_OP139AData.templateA.dogPitch && { dogPitch: OHP_OP139AData.templateA.dogPitch }),
                ...(OHP_OP139AData.templateA.dogPitchNum && { dogPitchNum: OHP_OP139AData.templateA.dogPitchNum }),
                ...(OHP_OP139AData.templateA.paintMarker && { paintMarker: OHP_OP139AData.templateA.paintMarker }),
                ...(OHP_OP139AData.templateA.paintMarkerNum && { paintMarkerNum: OHP_OP139AData.templateA.paintMarkerNum }),
                ...(OHP_OP139AData.templateA.chainVision && { chainVision: OHP_OP139AData.templateA.chainVision }),
                ...(OHP_OP139AData.templateA.lubeVision && { lubeVision: OHP_OP139AData.templateA.lubeVision }),
                ...(OHP_OP139AData.templateA.trolleyVision && { trolleyVision: OHP_OP139AData.templateA.trolleyVision }),
                ...(OHP_OP139AData.templateA.trolleyDetect && { trolleyDetect: OHP_OP139AData.templateA.trolleyDetect }),
                ...(OHP_OP139AData.templateA.omniView && { omniView: OHP_OP139AData.templateA.omniView }),
                ...(OHP_OP139AData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_OP139AData.templateA.dcuUpgradeNum }),
                ...(OHP_OP139AData.templateA.piuDistance && { piuDistance: OHP_OP139AData.templateA.piuDistance }),
                ...(OHP_OP139AData.templateA.switchDistance && { switchDistance: OHP_OP139AData.templateA.switchDistance }),
                ...(OHP_OP139AData.templateA.ampPickup && { ampPickup: OHP_OP139AData.templateA.ampPickup }),
                ...(OHP_OP139AData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_OP139AData.templateA.fromAirTakeUpDistance }),
                ...(OHP_OP139AData.templateA.specialControllerOptions && { specialControllerOptions: OHP_OP139AData.templateA.specialControllerOptions }),
                ...(OHP_OP139AData.templateA.operatingVoltage && { operatingVoltage: OHP_OP139AData.templateA.operatingVoltage })
            },

            addFreeCarrier: OHP_OP139AData.addFreeCarrier,

            templateBData: 
            {
                
                conveyorName: OHP_OP139AData.templateB.conveyorName,
                industrialChainManufacturer: OHP_OP139AData.templateB.industrialChainManufacturer,
                ...(OHP_OP139AData.templateB.otherChainManufacturer && { otherChainManufacturer: OHP_OP139AData.templateB.otherChainManufacturer }),
                wheelManufacturer: OHP_OP139AData.templateB.wheelManufacturer,
                ...(OHP_OP139AData.templateB.wheelManufacturer && { wheelManufacturer: OHP_OP139AData.templateB.wheelManufacturer}),
                conveyorSpeed: OHP_OP139AData.templateB.conveyorSpeed,
                conveyorSpeedUnit: OHP_OP139AData.templateB.conveyorSpeedUnit,
                conveyorIndex: OHP_OP139AData.templateB.conveyorIndex,
                ...(OHP_OP139AData.templateB.travelDirection && { travelDirection: OHP_OP139AData.templateB.travelDirection}),
                appEnviroment: OHP_OP139AData.templateB.appEnviroment,
                ...(OHP_OP139AData.templateB.otherAppEnviroment && { otherAppEnviroment: OHP_OP139AData.templateB.otherAppEnviroment}),
                surroundingTemp: OHP_OP139AData.templateB.surroundingTemp,
                orientationType: OHP_OP139AData.templateB.orientationType,
                operatingVoltage: OHP_OP139AData.templateB.operatingVoltage,
                controlVoltSingle: OHP_OP139AData.templateB.controlVoltSingle,
                compressedAir: OHP_OP139AData.templateB.compressedAir,
                ...(OHP_OP139AData.templateB.airSupplyType && { airSupplyType: OHP_OP139AData.templateB.airSupplyType}),

                templateA_BData: {
                    
                    existingMonitor: OHP_OP139AData.templateA.existingMonitor,
                    newMonitor: OHP_OP139AData.templateA.newMonitor,		
                    ...(OHP_OP139AData.templateA.dcuStatus && { dcuStatus: OHP_OP139AData.templateA.dcuStatus }),
                    ...(OHP_OP139AData.templateA.dcuNum && { dcuNum: OHP_OP139AData.templateA.dcuNum }),
                    ...(OHP_OP139AData.templateA.existingWindows && { existingWindows: OHP_OP139AData.templateA.existingWindows }),
                    ...(OHP_OP139AData.templateA.existingHeadUnit && { existingHeadUnit: OHP_OP139AData.templateA.existingHeadUnit }),
                    ...(OHP_OP139AData.templateA.existingDCU && { existingDCU: OHP_OP139AData.templateA.existingDCU }),
                    ...(OHP_OP139AData.templateA.existingPowerInterface && { existingPowerInterface: OHP_OP139AData.templateA.existingPowerInterface }),
                    ...(OHP_OP139AData.templateA.newReservoir && { newReservoir: OHP_OP139AData.templateA.newReservoir }),
                    ...(OHP_OP139AData.templateA.reservoirSize && { reservoirSize: OHP_OP139AData.templateA.reservoirSize }),
                    ...(OHP_OP139AData.templateA.otherReservoirSize && { otherReservoirSize: OHP_OP139AData.templateA.otherReservoirSize }),
                    ...(OHP_OP139AData.templateA.newReservoirNum && { newReservoirNum: OHP_OP139AData.templateA.newReservoirNum }),
                    ...(OHP_OP139AData.templateA.typeMonitor && { typeMonitor: OHP_OP139AData.templateA.typeMonitor }),
                    ...(OHP_OP139AData.templateA.driveMotorAmp && { driveMotorAmp: OHP_OP139AData.templateA.driveMotorAmp }),
                    ...(OHP_OP139AData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_OP139AData.templateA.driveMotorAmpNum }),
                    ...(OHP_OP139AData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_OP139AData.templateA.driveTakeUpAir }),
                    ...(OHP_OP139AData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_OP139AData.templateA.driveTakeUpAirNum }),
                    ...(OHP_OP139AData.templateA.takeUpDistance && { takeUpDistance: OHP_OP139AData.templateA.takeUpDistance }),
                    ...(OHP_OP139AData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_OP139AData.templateA.takeUpDistanceNum }),
                    ...(OHP_OP139AData.templateA.driveTemp && { driveTemp: OHP_OP139AData.templateA.driveTemp }),
                    ...(OHP_OP139AData.templateA.driveTempNum && { driveTempNum: OHP_OP139AData.templateA.driveTempNum }),
                    ...(OHP_OP139AData.templateA.driveVibration && { driveVibration: OHP_OP139AData.templateA.driveVibration }),
                    ...(OHP_OP139AData.templateA.driveVibrationNum && { driveVibrationNum: OHP_OP139AData.templateA.driveVibrationNum }),
                    ...(OHP_OP139AData.templateA.dogPitch && { dogPitch: OHP_OP139AData.templateA.dogPitch }),
                    ...(OHP_OP139AData.templateA.dogPitchNum && { dogPitchNum: OHP_OP139AData.templateA.dogPitchNum }),
                    ...(OHP_OP139AData.templateA.paintMarker && { paintMarker: OHP_OP139AData.templateA.paintMarker }),
                    ...(OHP_OP139AData.templateA.paintMarkerNum && { paintMarkerNum: OHP_OP139AData.templateA.paintMarkerNum }),
                    ...(OHP_OP139AData.templateA.chainVision && { chainVision: OHP_OP139AData.templateA.chainVision }),
                    ...(OHP_OP139AData.templateA.lubeVision && { lubeVision: OHP_OP139AData.templateA.lubeVision }),
                    ...(OHP_OP139AData.templateA.trolleyVision && { trolleyVision: OHP_OP139AData.templateA.trolleyVision }),
                    ...(OHP_OP139AData.templateA.trolleyDetect && { trolleyDetect: OHP_OP139AData.templateA.trolleyDetect }),
                    ...(OHP_OP139AData.templateA.omniView && { omniView: OHP_OP139AData.templateA.omniView }),
                    ...(OHP_OP139AData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_OP139AData.templateA.dcuUpgradeNum }),
                    ...(OHP_OP139AData.templateA.piuDistance && { piuDistance: OHP_OP139AData.templateA.piuDistance }),
                    ...(OHP_OP139AData.templateA.switchDistance && { switchDistance: OHP_OP139AData.templateA.switchDistance }),
                    ...(OHP_OP139AData.templateA.ampPickup && { ampPickup: OHP_OP139AData.templateA.ampPickup }),
                    ...(OHP_OP139AData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_OP139AData.templateA.fromAirTakeUpDistance }),
                    ...(OHP_OP139AData.templateA.specialControllerOptions && { specialControllerOptions: OHP_OP139AData.templateA.specialControllerOptions }),
                    ...(OHP_OP139AData.templateA.operatingVoltage && { operatingVoltage: OHP_OP139AData.templateA.operatingVoltage })

                },

                freeWheelStatus: OHP_OP139AData.templateB.freeWheelStatus,
                actuatorStatus: OHP_OP139AData.templateB.actuatorStatus,
                ...(OHP_OP139AData.templateB.pivotStatus && { pivotStatus: OHP_OP139AData.templateB.pivotStatus}),
                kingPinStatus: OHP_OP139AData.templateB.kingPinStatus,
                lubeBrand: OHP_OP139AData.templateB.lubeBrand,
                lubeViscosity: OHP_OP139AData.templateB.lubeViscosity,
                ...(OHP_OP139AData.templateB.lubeType && { lubeType: OHP_OP139AData.templateB.lubeType}),
                currentGrease: OHP_OP139AData.templateB.currentGrease,
                currentGreaseGrade: OHP_OP139AData.templateB.currentGreaseGrade,
                zerkDirection: OHP_OP139AData.templateB.zerkDirection,
                zerkLocationType: OHP_OP139AData.templateB.zerkLocationType,
                wheelDiameter: OHP_OP139AData.templateB.wheelDiameter,
                conveyorSwing: OHP_OP139AData.templateB.conveyorSwing,
                ...(OHP_OP139AData.templateB.chainMaster && { lubeType: OHP_OP139AData.templateB.chainMaster}),
                ...(OHP_OP139AData.templateB.remoteStatus && { lubeType: OHP_OP139AData.templateB.remoteStatus}),
                ...(OHP_OP139AData.templateB.mountStatus && { lubeType: OHP_OP139AData.templateB.mountStatus}),
                ...(OHP_OP139AData.templateB.otherUnitStatus && { lubeType: OHP_OP139AData.templateB.otherUnitStatus}),
                ...(OHP_OP139AData.templateB.timerStatus && { lubeType: OHP_OP139AData.templateB.timerStatus}),
                ...(OHP_OP139AData.templateB.electricStatus && { lubeType: OHP_OP139AData.templateB.electricStatus}),
                ...(OHP_OP139AData.templateB.mightyLubeMonitoring && { lubeType: OHP_OP139AData.templateB.mightyLubeMonitoring}),
                ...(OHP_OP139AData.templateB.preMountType && { lubeType: OHP_OP139AData.templateB.preMountType}),
                ...(OHP_OP139AData.templateB.otherPreMountType && { lubeType: OHP_OP139AData.templateB.otherPreMountType}),
                ...(OHP_OP139AData.templateB.plcConnection && { lubeType: OHP_OP139AData.templateB.plcConnection}),
                ...(OHP_OP139AData.templateB.otherControllerNotes && { lubeType: OHP_OP139AData.templateB.otherControllerNotes}),
                ...(OHP_OP139AData.templateB.templateB_UnitType && { lubeType: OHP_OP139AData_UnitType}),
                ...(OHP_OP139AData.templateB.templateB_InvertedB && { lubeType: OHP_OP139AData_InvertedB}),
                ...(OHP_OP139AData.templateB.templateB_InvertedE && { lubeType: OHP_OP139AData_InvertedE}),
                ...(OHP_OP139AData.templateB.templateB_InvertedG && { lubeType: OHP_OP139AData_InvertedG}),
                ...(OHP_OP139AData.templateB.templateB_InvertedH && { lubeType: OHP_OP139AData_InvertedH}),
                ...(OHP_OP139AData.templateB.templateB_InvertedK && { lubeType: OHP_OP139AData_InvertedK}),
                ...(OHP_OP139AData.templateB.templateB_InvertedT && { lubeType: OHP_OP139AData_InvertedT}),
                ...(OHP_OP139AData.templateB.templateB_InvertedU && { lubeType: OHP_OP139AData_InvertedU}),
                ...(OHP_OP139AData.templateB.templateB_InvertedV && { lubeType: OHP_OP139AData_InvertedV}),
                ...(OHP_OP139AData.templateB.templateB_InvertedW && { lubeType: OHP_OP139AData_InvertedW}),

            },


            templateCData: 
            {
            conveyorName: OHP_OP139AData.templateC.conveyorName,
            industrialChainManufacturer: OHP_OP139AData.templateC.industrialChainManufacturer,
            ...(OHP_OP139AData.templateC.otherChainManufacturer && { otherChainManufacturer: OHP_OP139AData.templateC.otherChainManufacturer }),
            wheelManufacturer: OHP_OP139AData.templateC.wheelManufacturer,
            ...(OHP_OP139AData.templateC.wheelManufacturer && { wheelManufacturer: OHP_OP139AData.templateC.wheelManufacturer}),
            conveyorSpeed: OHP_OP139AData.templateC.conveyorSpeed,
            conveyorSpeedUnit: OHP_OP139AData.templateC.conveyorSpeedUnit,
            conveyorIndex: OHP_OP139AData.templateC.conveyorIndex,
            ...(OHP_OP139AData.templateC.travelDirection && { travelDirection: OHP_OP139AData.templateC.travelDirection}),
            appEnviroment: OHP_OP139AData.templateC.appEnviroment,
            ...(OHP_OP139AData.templateC.otherAppEnviroment && { otherAppEnviroment: OHP_OP139AData.templateC.otherAppEnviroment}),
            surroundingTemp: OHP_OP139AData.templateC.surroundingTemp,
            orientationType: OHP_OP139AData.templateC.orientationType,
            guideWheelsEven: OHP_OP139AData.templateC.guideWheelsEven,
            operatingVoltage: OHP_OP139AData.templateC.operatingVoltage,
            controlVoltSingle: OHP_OP139AData.templateC.controlVoltSingle,
            compressedAir: OHP_OP139AData.templateC.compressedAir,
            ...(OHP_OP139AData.templateC.airSupplyType && { airSupplyType: OHP_OP139AData.templateC.airSupplyType}),

            templateA_CData: 
            {
                existingMonitor: OHP_OP139AData.templateA.existingMonitor,
                newMonitor: OHP_OP139AData.templateA.newMonitor,		
                ...(OHP_OP139AData.templateA.dcuStatus && { dcuStatus: OHP_OP139AData.templateA.dcuStatus }),
                ...(OHP_OP139AData.templateA.dcuNum && { dcuNum: OHP_OP139AData.templateA.dcuNum }),
                ...(OHP_OP139AData.templateA.existingWindows && { existingWindows: OHP_OP139AData.templateA.existingWindows }),
                ...(OHP_OP139AData.templateA.existingHeadUnit && { existingHeadUnit: OHP_OP139AData.templateA.existingHeadUnit }),
                ...(OHP_OP139AData.templateA.existingDCU && { existingDCU: OHP_OP139AData.templateA.existingDCU }),
                ...(OHP_OP139AData.templateA.existingPowerInterface && { existingPowerInterface: OHP_OP139AData.templateA.existingPowerInterface }),
                ...(OHP_OP139AData.templateA.newReservoir && { newReservoir: OHP_OP139AData.templateA.newReservoir }),
                ...(OHP_OP139AData.templateA.reservoirSize && { reservoirSize: OHP_OP139AData.templateA.reservoirSize }),
                ...(OHP_OP139AData.templateA.otherReservoirSize && { otherReservoirSize: OHP_OP139AData.templateA.otherReservoirSize }),
                ...(OHP_OP139AData.templateA.newReservoirNum && { newReservoirNum: OHP_OP139AData.templateA.newReservoirNum }),
                ...(OHP_OP139AData.templateA.typeMonitor && { typeMonitor: OHP_OP139AData.templateA.typeMonitor }),
                ...(OHP_OP139AData.templateA.driveMotorAmp && { driveMotorAmp: OHP_OP139AData.templateA.driveMotorAmp }),
                ...(OHP_OP139AData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_OP139AData.templateA.driveMotorAmpNum }),
                ...(OHP_OP139AData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_OP139AData.templateA.driveTakeUpAir }),
                ...(OHP_OP139AData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_OP139AData.templateA.driveTakeUpAirNum }),
                ...(OHP_OP139AData.templateA.takeUpDistance && { takeUpDistance: OHP_OP139AData.templateA.takeUpDistance }),
                ...(OHP_OP139AData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_OP139AData.templateA.takeUpDistanceNum }),
                ...(OHP_OP139AData.templateA.driveTemp && { driveTemp: OHP_OP139AData.templateA.driveTemp }),
                ...(OHP_OP139AData.templateA.driveTempNum && { driveTempNum: OHP_OP139AData.templateA.driveTempNum }),
                ...(OHP_OP139AData.templateA.driveVibration && { driveVibration: OHP_OP139AData.templateA.driveVibration }),
                ...(OHP_OP139AData.templateA.driveVibrationNum && { driveVibrationNum: OHP_OP139AData.templateA.driveVibrationNum }),
                ...(OHP_OP139AData.templateA.dogPitch && { dogPitch: OHP_OP139AData.templateA.dogPitch }),
                ...(OHP_OP139AData.templateA.dogPitchNum && { dogPitchNum: OHP_OP139AData.templateA.dogPitchNum }),
                ...(OHP_OP139AData.templateA.paintMarker && { paintMarker: OHP_OP139AData.templateA.paintMarker }),
                ...(OHP_OP139AData.templateA.paintMarkerNum && { paintMarkerNum: OHP_OP139AData.templateA.paintMarkerNum }),
                ...(OHP_OP139AData.templateA.chainVision && { chainVision: OHP_OP139AData.templateA.chainVision }),
                ...(OHP_OP139AData.templateA.lubeVision && { lubeVision: OHP_OP139AData.templateA.lubeVision }),
                ...(OHP_OP139AData.templateA.trolleyVision && { trolleyVision: OHP_OP139AData.templateA.trolleyVision }),
                ...(OHP_OP139AData.templateA.trolleyDetect && { trolleyDetect: OHP_OP139AData.templateA.trolleyDetect }),
                ...(OHP_OP139AData.templateA.omniView && { omniView: OHP_OP139AData.templateA.omniView }),
                ...(OHP_OP139AData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_OP139AData.templateA.dcuUpgradeNum }),
                ...(OHP_OP139AData.templateA.piuDistance && { piuDistance: OHP_OP139AData.templateA.piuDistance }),
                ...(OHP_OP139AData.templateA.switchDistance && { switchDistance: OHP_OP139AData.templateA.switchDistance }),
                ...(OHP_OP139AData.templateA.ampPickup && { ampPickup: OHP_OP139AData.templateA.ampPickup }),
                ...(OHP_OP139AData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_OP139AData.templateA.fromAirTakeUpDistance }),
                ...(OHP_OP139AData.templateA.specialControllerOptions && { specialControllerOptions: OHP_OP139AData.templateA.specialControllerOptions }),
                ...(OHP_OP139AData.templateA.operatingVoltage && { operatingVoltage: OHP_OP139AData.templateA.operatingVoltage })
            },
            
            freeWheelStatus: OHP_OP139AData.templateC.freeWheelStatus,
            actuatorStatus: OHP_OP139AData.templateC.actuatorStatus,
            ...(OHP_OP139AData.templateC.pivotStatus && { pivotStatus: OHP_OP139AData.templateC.pivotStatus}),
            kingPinStatus: OHP_OP139AData.templateC.kingPinStatus,
            lubeBrand: OHP_OP139AData.templateC.lubeBrand,
            lubeViscosity: OHP_OP139AData.templateC.lubeViscosity,
            ...(OHP_OP139AData.templateC.lubeType && { lubeType: OHP_OP139AData.templateC.lubeType}),
            currentGrease: OHP_OP139AData.templateC.currentGrease,
            currentGreaseGrade: OHP_OP139AData.templateC.currentGreaseGrade,
            zerkDirection: OHP_OP139AData.templateC.zerkDirection,
            zerkLocationType: OHP_OP139AData.templateC.zerkLocationType,
            wheelDiameter: OHP_OP139AData.templateC.wheelDiameter,
            conveyorSwing: OHP_OP139AData.templateC.conveyorSwing,
            ...(OHP_OP139AData.templateC.chainMaster && { lubeType: OHP_OP139AData.templateC.chainMaster}),
            ...(OHP_OP139AData.templateC.remoteStatus && { lubeType: OHP_OP139AData.templateC.remoteStatus}),
            ...(OHP_OP139AData.templateC.mountStatus && { lubeType: OHP_OP139AData.templateC.mountStatus}),
            ...(OHP_OP139AData.templateC.otherUnitStatus && { lubeType: OHP_OP139AData.templateC.otherUnitStatus}),
            ...(OHP_OP139AData.templateC.timerStatus && { lubeType: OHP_OP139AData.templateC.timerStatus}),
            ...(OHP_OP139AData.templateC.electricStatus && { lubeType: OHP_OP139AData.templateC.electricStatus}),
            ...(OHP_OP139AData.templateC.mightyLubeMonitoring && { lubeType: OHP_OP139AData.templateC.mightyLubeMonitoring}),
            ...(OHP_OP139AData.templateC.preMountType && { lubeType: OHP_OP139AData.templateC.preMountType}),
            ...(OHP_OP139AData.templateC.otherPreMountType && { lubeType: OHP_OP139AData.templateC.otherPreMountType}),
            ...(OHP_OP139AData.templateC.plcConnection && { lubeType: OHP_OP139AData.templateC.plcConnection}),
            ...(OHP_OP139AData.templateC.otherControllerNotes && { lubeType: OHP_OP139AData.templateC.otherControllerNotes}),
            ...(OHP_OP139AData.templateC.templateC_UnitType && { lubeType: OHP_OP139AData.templateC.templateC_UnitType}),
            templateC_InvertedA: OHP_OP139AData.templateC.templateC_InvertedA,
            templateC_InvertedB: OHP_OP139AData.templateC.templateC_InvertedB,
            templateC_InvertedE: OHP_OP139AData.templateC.templateC_InvertedE,
            templateC_InvertedS: OHP_OP139AData.templateC.templateC_InvertedS,
        },
        
            ...(OHP_OP139AData.railLubeStatus && { railLubeStatus: OHP_OP139AData.railLubeStatus }),
            ...(OHP_OP139AData.lubeBrand && { lubeBrand: OHP_OP139AData.lubeBrand }),
            ...(OHP_OP139AData.lubeType && { lubeType: OHP_OP139AData.lubeType }),
            ...(OHP_OP139AData.lubeViscosity && { lubeViscosity: OHP_OP139AData.lubeViscosity }),
            ...(OHP_OP139AData.sideLubeStatus && { sideLubeStatus: OHP_OP139AData.sideLubeStatus }),
            ...(OHP_OP139AData.topLubeStatus && { topLubeStatus: OHP_OP139AData.topLubeStatus }),
            ...(OHP_OP139AData.chainCleanStatus && { chainCleanStatus: OHP_OP139AData.chainCleanStatus }),
            ...(OHP_OP139AData.chainMaster && { chainMaster: OHP_OP139AData.chainMaster }),
            ...(OHP_OP139AData.otherUnitStatus && { otherUnitStatus: OHP_OP139AData.otherUnitStatus }),
            ...(OHP_OP139AData.timerStatus && { timerStatus: OHP_OP139AData.timerStatus }),
                electricStatus: OHP_OP139AData.electricStatus,
            ...(OHP_OP139AData.pneumaticStatus && { pneumaticStatus: OHP_OP139AData.pneumaticStatus }),
            ...(OHP_OP139AData.mightyLubeMonitoring && { mightyLubeMonitoring: OHP_OP139AData.mightyLubeMonitoring }),
            ...(OHP_OP139AData.plcConnection && { plcConnection: OHP_OP139AData.plcConnection }),
            ...(OHP_OP139AData.otherControllerNotes && { otherControllerNotes: OHP_OP139AData.otherControllerNotes }),
            ...(OHP_OP139AData.ohpUnitType && { ohpUnitType: OHP_OP139AData.ohpUnitType }),
            ...(OHP_OP139AData.chainDrop && { chainDrop: OHP_OP139AData.chainDrop }),
            ...(OHP_OP139AData.ohpDiameter && { ohpDiameter: OHP_OP139AData.ohpDiameter }),
            ...(OHP_OP139AData.ohpWidth && { ohpWidth: OHP_OP139AData.ohpWidth }),
            ...(OHP_OP139AData.ohpHeight && { ohpHeight: OHP_OP139AData.ohpHeight }),
            ...(OHP_OP139AData.radioButtonType && { radioButtonType: OHP_OP139AData.radioButtonType })
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "OHP_OP139A"
        });
        await req.user.save();
        return res.status(200).json({ message: "OHP_OP139A entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;