const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const OHP_9000I = require("../models/OHP_9000I");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");


const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { OHP_9000IData, numRequested } = req.body;
        const order = new OHP_9000I({
            conveyorName: OHP_9000IData.conveyorName,
            chainSize: OHP_9000IData.chainSize,
            ...(OHP_9000IData.otherChainSize && { otherChainSize: OHP_9000IData.otherChainSize }),
            industrialChainManufacturer: OHP_9000IData.industrialChainManufacturer,
            ...(OHP_9000IData.otherChainManufacturer && { otherChainManufacturer: OHP_9000IData.otherChainManufacturer }),
            ...(OHP_9000IData.conveyorLength && { conveyorLength: OHP_9000IData.conveyorLength }),
            ...(OHP_9000IData.conveyorLengthUnit && { conveyorLengthUnit: OHP_9000IData.conveyorLengthUnit }),
            ...(OHP_9000IData.conveyorSpeed && { conveyorSpeed: OHP_9000IData.conveyorSpeed }),
            ...(OHP_9000IData.conveyorSpeedUnit && { conveyorSpeedUnit: OHP_9000IData.conveyorSpeedUnit }),
            ...(OHP_9000IData.conveyorIndex && { conveyorIndex: OHP_9000IData.conveyorIndex }),
            ...(OHP_9000IData.travelDirection && { travelDirection: OHP_9000IData.travelDirection }),
            appEnviroment: OHP_9000IData.appEnviroment,
            ...(OHP_9000IData.ovenStatus && { ovenStatus: OHP_9000IData.ovenStatus }),
            ...(OHP_9000IData.ovenTemp && { ovenTemp: OHP_9000IData.ovenTemp }),
            ...(OHP_9000IData.otherAppEnviroment && { otherAppEnviroment: OHP_9000IData.otherAppEnviroment }),
            ...(OHP_9000IData.surroundingTemp && { surroundingTemp: OHP_9000IData.surroundingTemp }),
            ...(OHP_9000IData.conveyorLoaded && { conveyorLoaded: OHP_9000IData.conveyorLoaded }),
            ...(OHP_9000IData.swingStatus && { swingStatus: OHP_9000IData.swingStatus }),
            ...(OHP_9000IData.operatingVoltSingle && { operatingVoltSingle: OHP_9000IData.operatingVoltSingle }),
            ...(OHP_9000IData.controlVoltSingle && { controlVoltSingle: OHP_9000IData.controlVoltSingle }),
            existingMonitor: OHP_9000IData.existingMonitor,
            newMonitor: OHP_9000IData.newMonitor,
            monitorData: new templateA({
                ...(OHP_9000IData.templateA.dcuStatus && { dcuStatus: OHP_9000IData.templateA.dcuStatus }),
                ...(OHP_9000IData.templateA.dcuNum && { dcuNum: OHP_9000IData.templateA.dcuNum }),
                ...(OHP_9000IData.templateA.existingWindows && { existingWindows: OHP_9000IData.templateA.existingWindows }),
                ...(OHP_9000IData.templateA.existingHeadUnit && { existingHeadUnit: OHP_9000IData.templateA.existingHeadUnit }),
                ...(OHP_9000IData.templateA.existingDCU && { existingDCU: OHP_9000IData.templateA.existingDCU }),
                ...(OHP_9000IData.templateA.existingPowerInterface && { existingPowerInterface: OHP_9000IData.templateA.existingPowerInterface }),
                ...(OHP_9000IData.templateA.newReservoir && { newReservoir: OHP_9000IData.templateA.newReservoir }),
                ...(OHP_9000IData.templateA.reservoirSize && { reservoirSize: OHP_9000IData.templateA.reservoirSize }),
                ...(OHP_9000IData.templateA.otherReservoirSize && { otherReservoirSize: OHP_9000IData.templateA.otherReservoirSize }),
                ...(OHP_9000IData.templateA.newReservoirNum && { newReservoirNum: OHP_9000IData.templateA.newReservoirNum }),
                ...(OHP_9000IData.templateA.typeMonitor && { typeMonitor: OHP_9000IData.templateA.typeMonitor }),
                ...(OHP_9000IData.templateA.driveMotorAmp && { driveMotorAmp: OHP_9000IData.templateA.driveMotorAmp }),
                ...(OHP_9000IData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_9000IData.templateA.driveMotorAmpNum }),
                ...(OHP_9000IData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_9000IData.templateA.driveTakeUpAir }),
                ...(OHP_9000IData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_9000IData.templateA.driveTakeUpAirNum }),
                ...(OHP_9000IData.templateA.takeUpDistance && { takeUpDistance: OHP_9000IData.templateA.takeUpDistance }),
                ...(OHP_9000IData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_9000IData.templateA.takeUpDistanceNum }),
                ...(OHP_9000IData.templateA.driveTemp && { driveTemp: OHP_9000IData.templateA.driveTemp }),
                ...(OHP_9000IData.templateA.driveTempNum && { driveTempNum: OHP_9000IData.templateA.driveTempNum }),
                ...(OHP_9000IData.templateA.driveVibration && { driveVibration: OHP_9000IData.templateA.driveVibration }),
                ...(OHP_9000IData.templateA.driveVibrationNum && { driveVibrationNum: OHP_9000IData.templateA.driveVibrationNum }),
                ...(OHP_9000IData.templateA.dogPitch && { dogPitch: OHP_9000IData.templateA.dogPitch }),
                ...(OHP_9000IData.templateA.dogPitchNum && { dogPitchNum: OHP_9000IData.templateA.dogPitchNum }),
                ...(OHP_9000IData.templateA.paintMarker && { paintMarker: OHP_9000IData.templateA.paintMarker }),
                ...(OHP_9000IData.templateA.paintMarkerNum && { paintMarkerNum: OHP_9000IData.templateA.paintMarkerNum }),
                ...(OHP_9000IData.templateA.chainVision && { chainVision: OHP_9000IData.templateA.chainVision }),
                ...(OHP_9000IData.templateA.lubeVision && { lubeVision: OHP_9000IData.templateA.lubeVision }),
                ...(OHP_9000IData.templateA.trolleyVision && { trolleyVision: OHP_9000IData.templateA.trolleyVision }),
                ...(OHP_9000IData.templateA.trolleyDetect && { trolleyDetect: OHP_9000IData.templateA.trolleyDetect }),
                ...(OHP_9000IData.templateA.omniView && { omniView: OHP_9000IData.templateA.omniView }),
                ...(OHP_9000IData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_9000IData.templateA.dcuUpgradeNum }),
                ...(OHP_9000IData.templateA.itNameOne && { itNameOne: OHP_9000IData.templateA.itNameOne }),
                ...(OHP_9000IData.templateA.itIPOne && { itIPOne: OHP_9000IData.templateA.itIPOne }),
                ...(OHP_9000IData.templateA.itGatewayOne && { itGatewayOne: OHP_9000IData.templateA.itGatewayOne }),
                ...(OHP_9000IData.templateA.itSubnetOne && { itSubnetOne: OHP_9000IData.templateA.itSubnetOne }),
                ...(OHP_9000IData.templateA.itDNSOne && { itDNSOne: OHP_9000IData.templateA.itDNSOne }),
                ...(OHP_9000IData.templateA.itSMTPOne && { itSMTPOne: OHP_9000IData.templateA.itSMTPOne }),
                ...(OHP_9000IData.templateA.itNameTwo && { itNameTwo: OHP_9000IData.templateA.itNameTwo }),
                ...(OHP_9000IData.templateA.itIPTwo && { itIPTwo: OHP_9000IData.templateA.itIPTwo }),
                ...(OHP_9000IData.templateA.itGatewayTwo && { itGatewayTwo: OHP_9000IData.templateA.itGatewayTwo }),
                ...(OHP_9000IData.templateA.itSubnetTwo && { itSubnetTwo: OHP_9000IData.templateA.itSubnetTwo }),
                ...(OHP_9000IData.templateA.itDNSTwo && { itDNSTwo: OHP_9000IData.templateA.itDNSTwo }),
                ...(OHP_9000IData.templateA.itSMTPTwo && { itSMTPTwo: OHP_9000IData.templateA.itSMTPTwo }),
                ...(OHP_9000IData.templateA.itNameThree && { itNameThree: OHP_9000IData.templateA.itNameThree }),
                ...(OHP_9000IData.templateA.itIPThree && { itIPThree: OHP_9000IData.templateA.itIPThree }),
                ...(OHP_9000IData.templateA.itGatewayThree && { itGatewayThree: OHP_9000IData.templateA.itGatewayThree }),
                ...(OHP_9000IData.templateA.itSubnetThree && { itSubnetThree: OHP_9000IData.templateA.itSubnetThree }),
                ...(OHP_9000IData.templateA.itDNSThree && { itDNSThree: OHP_9000IData.templateA.itDNSThree }),
                ...(OHP_9000IData.templateA.itSMTPThree && { itSMTPThree: OHP_9000IData.templateA.itSMTPThree }),
                ...(OHP_9000IData.templateA.itAdditionalNotes && { itAdditionalNotes: OHP_9000IData.templateA.itAdditionalNotes }),
                ...(OHP_9000IData.templateA.piuDistance && { piuDistance: OHP_9000IData.templateA.piuDistance }),
                ...(OHP_9000IData.templateA.switchDistance && { switchDistance: OHP_9000IData.templateA.switchDistance }),
                ...(OHP_9000IData.templateA.ampPickup && { ampPickup: OHP_9000IData.templateA.ampPickup }),
                ...(OHP_9000IData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_9000IData.templateA.fromAirTakeUpDistance }),
                ...(OHP_9000IData.templateA.specialControllerOptions && { specialControllerOptions: OHP_9000IData.templateA.specialControllerOptions }),
                ...(OHP_9000IData.templateA.operatingVoltage && { operatingVoltage: OHP_9000IData.templateA.operatingVoltage })

            }),
            
            addFreeCarrier: OHP_9000IData.addFreeCarrier,

            templateBData: new templateB({
                conveyorName: OHP_9000IData.templateB.conveyorName,
                industrialChainManufacturer: OHP_9000IData.templateB.industrialChainManufacturer,
                ...(OHP_9000IData.templateB.otherChainManufacturer && { otherChainManufacturer: OHP_9000IData.templateB.otherChainManufacturer }),
                wheelManufacturer: OHP_9000IData.templateB.wheelManufacturer,
                ...(OHP_9000IData.templateB.wheelManufacturer && { wheelManufacturer: OHP_9000IData.templateB.wheelManufacturer}),
                conveyorSpeed: OHP_9000IData.templateB.conveyorSpeed,
                conveyorSpeedUnit: OHP_9000IData.templateB.conveyorSpeedUnit,
                conveyorIndex: OHP_9000IData.templateB.conveyorIndex,
                ...(OHP_9000IData.templateB.travelDirection && { travelDirection: OHP_9000IData.templateB.travelDirection}),
                appEnviroment: OHP_9000IData.templateB.appEnviroment,
                ...(OHP_9000IData.templateB.otherAppEnviroment && { otherAppEnviroment: OHP_9000IData.templateB.otherAppEnviroment}),
                surroundingTemp: OHP_9000IData.templateB.surroundingTemp,
                orientationType: OHP_9000IData.templateB.orientationType,
                operatingVoltage: OHP_9000IData.templateB.operatingVoltage,
                controlVoltSingle: OHP_9000IData.templateB.controlVoltSingle,
                compressedAir: OHP_9000IData.templateB.compressedAir,
                ...(OHP_9000IData.templateB.airSupplyType && { airSupplyType: OHP_9000IData.templateB.airSupplyType}),
            existingMonitor: OHP_9000IData.templateB.existingMonitor,
            newMonitor: OHP_9000IData.templateB.newMonitor,
            templateA_BData: new templateA({
                ...(OHP_9000IData.templateA.dcuStatus && { dcuStatus: OHP_9000IData.templateA.dcuStatus }),
                ...(OHP_9000IData.templateA.dcuNum && { dcuNum: OHP_9000IData.templateA.dcuNum }),
                ...(OHP_9000IData.templateA.existingWindows && { existingWindows: OHP_9000IData.templateA.existingWindows }),
                ...(OHP_9000IData.templateA.existingHeadUnit && { existingHeadUnit: OHP_9000IData.templateA.existingHeadUnit }),
                ...(OHP_9000IData.templateA.existingDCU && { existingDCU: OHP_9000IData.templateA.existingDCU }),
                ...(OHP_9000IData.templateA.existingPowerInterface && { existingPowerInterface: OHP_9000IData.templateA.existingPowerInterface }),
                ...(OHP_9000IData.templateA.newReservoir && { newReservoir: OHP_9000IData.templateA.newReservoir }),
                ...(OHP_9000IData.templateA.reservoirSize && { reservoirSize: OHP_9000IData.templateA.reservoirSize }),
                ...(OHP_9000IData.templateA.otherReservoirSize && { otherReservoirSize: OHP_9000IData.templateA.otherReservoirSize }),
                ...(OHP_9000IData.templateA.newReservoirNum && { newReservoirNum: OHP_9000IData.templateA.newReservoirNum }),
                ...(OHP_9000IData.templateA.typeMonitor && { typeMonitor: OHP_9000IData.templateA.typeMonitor }),
                ...(OHP_9000IData.templateA.driveMotorAmp && { driveMotorAmp: OHP_9000IData.templateA.driveMotorAmp }),
                ...(OHP_9000IData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_9000IData.templateA.driveMotorAmpNum }),
                ...(OHP_9000IData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_9000IData.templateA.driveTakeUpAir }),
                ...(OHP_9000IData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_9000IData.templateA.driveTakeUpAirNum }),
                ...(OHP_9000IData.templateA.takeUpDistance && { takeUpDistance: OHP_9000IData.templateA.takeUpDistance }),
                ...(OHP_9000IData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_9000IData.templateA.takeUpDistanceNum }),
                ...(OHP_9000IData.templateA.driveTemp && { driveTemp: OHP_9000IData.templateA.driveTemp }),
                ...(OHP_9000IData.templateA.driveTempNum && { driveTempNum: OHP_9000IData.templateA.driveTempNum }),
                ...(OHP_9000IData.templateA.driveVibration && { driveVibration: OHP_9000IData.templateA.driveVibration }),
                ...(OHP_9000IData.templateA.driveVibrationNum && { driveVibrationNum: OHP_9000IData.templateA.driveVibrationNum }),
                ...(OHP_9000IData.templateA.dogPitch && { dogPitch: OHP_9000IData.templateA.dogPitch }),
                ...(OHP_9000IData.templateA.dogPitchNum && { dogPitchNum: OHP_9000IData.templateA.dogPitchNum }),
                ...(OHP_9000IData.templateA.paintMarker && { paintMarker: OHP_9000IData.templateA.paintMarker }),
                ...(OHP_9000IData.templateA.paintMarkerNum && { paintMarkerNum: OHP_9000IData.templateA.paintMarkerNum }),
                ...(OHP_9000IData.templateA.chainVision && { chainVision: OHP_9000IData.templateA.chainVision }),
                ...(OHP_9000IData.templateA.lubeVision && { lubeVision: OHP_9000IData.templateA.lubeVision }),
                ...(OHP_9000IData.templateA.trolleyVision && { trolleyVision: OHP_9000IData.templateA.trolleyVision }),
                ...(OHP_9000IData.templateA.trolleyDetect && { trolleyDetect: OHP_9000IData.templateA.trolleyDetect }),
                ...(OHP_9000IData.templateA.omniView && { omniView: OHP_9000IData.templateA.omniView }),
                ...(OHP_9000IData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_9000IData.templateA.dcuUpgradeNum }),
                ...(OHP_9000IData.templateA.itNameOne && { itNameOne: OHP_9000IData.templateA.itNameOne }),
                ...(OHP_9000IData.templateA.itIPOne && { itIPOne: OHP_9000IData.templateA.itIPOne }),
                ...(OHP_9000IData.templateA.itGatewayOne && { itGatewayOne: OHP_9000IData.templateA.itGatewayOne }),
                ...(OHP_9000IData.templateA.itSubnetOne && { itSubnetOne: OHP_9000IData.templateA.itSubnetOne }),
                ...(OHP_9000IData.templateA.itDNSOne && { itDNSOne: OHP_9000IData.templateA.itDNSOne }),
                ...(OHP_9000IData.templateA.itSMTPOne && { itSMTPOne: OHP_9000IData.templateA.itSMTPOne }),
                ...(OHP_9000IData.templateA.itNameTwo && { itNameTwo: OHP_9000IData.templateA.itNameTwo }),
                ...(OHP_9000IData.templateA.itIPTwo && { itIPTwo: OHP_9000IData.templateA.itIPTwo }),
                ...(OHP_9000IData.templateA.itGatewayTwo && { itGatewayTwo: OHP_9000IData.templateA.itGatewayTwo }),
                ...(OHP_9000IData.templateA.itSubnetTwo && { itSubnetTwo: OHP_9000IData.templateA.itSubnetTwo }),
                ...(OHP_9000IData.templateA.itDNSTwo && { itDNSTwo: OHP_9000IData.templateA.itDNSTwo }),
                ...(OHP_9000IData.templateA.itSMTPTwo && { itSMTPTwo: OHP_9000IData.templateA.itSMTPTwo }),
                ...(OHP_9000IData.templateA.itNameThree && { itNameThree: OHP_9000IData.templateA.itNameThree }),
                ...(OHP_9000IData.templateA.itIPThree && { itIPThree: OHP_9000IData.templateA.itIPThree }),
                ...(OHP_9000IData.templateA.itGatewayThree && { itGatewayThree: OHP_9000IData.templateA.itGatewayThree }),
                ...(OHP_9000IData.templateA.itSubnetThree && { itSubnetThree: OHP_9000IData.templateA.itSubnetThree }),
                ...(OHP_9000IData.templateA.itDNSThree && { itDNSThree: OHP_9000IData.templateA.itDNSThree }),
                ...(OHP_9000IData.templateA.itSMTPThree && { itSMTPThree: OHP_9000IData.templateA.itSMTPThree }),
                ...(OHP_9000IData.templateA.itAdditionalNotes && { itAdditionalNotes: OHP_9000IData.templateA.itAdditionalNotes }),
                ...(OHP_9000IData.templateA.piuDistance && { piuDistance: OHP_9000IData.templateA.piuDistance }),
                ...(OHP_9000IData.templateA.switchDistance && { switchDistance: OHP_9000IData.templateA.switchDistance }),
                ...(OHP_9000IData.templateA.ampPickup && { ampPickup: OHP_9000IData.templateA.ampPickup }),
                ...(OHP_9000IData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_9000IData.templateA.fromAirTakeUpDistance }),
                ...(OHP_9000IData.templateA.specialControllerOptions && { specialControllerOptions: OHP_9000IData.templateA.specialControllerOptions }),
                ...(OHP_9000IData.templateA.operatingVoltage && { operatingVoltage: OHP_9000IData.templateA.operatingVoltage })

                }),
                freeWheelStatus: OHP_9000IData.templateB.freeWheelStatus,
                actuatorStatus: OHP_9000IData.templateB.actuatorStatus,
                ...(OHP_9000IData.templateB.pivotStatus && { pivotStatus: OHP_9000IData.templateB.pivotStatus}),
                kingPinStatus: OHP_9000IData.templateB.kingPinStatus,
                lubeBrand: OHP_9000IData.templateB.lubeBrand,
                lubeViscosity: OHP_9000IData.templateB.lubeViscosity,
                ...(OHP_9000IData.templateB.lubeType && { lubeType: OHP_9000IData.templateB.lubeType}),
                currentGrease: OHP_9000IData.templateB.currentGrease,
                currentGreaseGrade: OHP_9000IData.templateB.currentGreaseGrade,
                zerkDirection: OHP_9000IData.templateB.zerkDirection,
                zerkLocationType: OHP_9000IData.templateB.zerkLocationType,
                wheelDiameter: OHP_9000IData.templateB.wheelDiameter,
                conveyorSwing: OHP_9000IData.templateB.conveyorSwing,
                ...(OHP_9000IData.templateB.chainMaster && { lubeType: OHP_9000IData.templateB.chainMaster}),
                ...(OHP_9000IData.templateB.remoteStatus && { lubeType: OHP_9000IData.templateB.remoteStatus}),
                ...(OHP_9000IData.templateB.mountStatus && { lubeType: OHP_9000IData.templateB.mountStatus}),
                ...(OHP_9000IData.templateB.otherUnitStatus && { lubeType: OHP_9000IData.templateB.otherUnitStatus}),
                ...(OHP_9000IData.templateB.timerStatus && { lubeType: OHP_9000IData.templateB.timerStatus}),
                ...(OHP_9000IData.templateB.electricStatus && { lubeType: OHP_9000IData.templateB.electricStatus}),
                ...(OHP_9000IData.templateB.mightyLubeMonitoring && { lubeType: OHP_9000IData.templateB.mightyLubeMonitoring}),
                ...(OHP_9000IData.templateB.preMountType && { lubeType: OHP_9000IData.templateB.preMountType}),
                ...(OHP_9000IData.templateB.otherPreMountType && { lubeType: OHP_9000IData.templateB.otherPreMountType}),
                ...(OHP_9000IData.templateB.plcConnection && { lubeType: OHP_9000IData.templateB.plcConnection}),
                ...(OHP_9000IData.templateB.otherControllerNotes && { lubeType: OHP_9000IData.templateB.otherControllerNotes}),
                ...(OHP_9000IData.templateB.templateB_UnitType && { lubeType: OHP_9000IData.templateB.templateB_UnitType}),
                ...(OHP_9000IData.templateB.templateB_InvertedB && { lubeType: OHP_9000IData.templateB.templateB_InvertedB}),
                ...(OHP_9000IData.templateB.templateB_InvertedE && { lubeType: OHP_9000IData.templateB.templateB_InvertedE}),
                ...(OHP_9000IData.templateB.templateB_InvertedG && { lubeType: OHP_9000IData.templateB.templateB_InvertedG}),
                ...(OHP_9000IData.templateB.templateB_InvertedH && { lubeType: OHP_9000IData.templateB.templateB_InvertedH}),
                ...(OHP_9000IData.templateB.templateB_InvertedK && { lubeType: OHP_9000IData.templateB.templateB_InvertedK}),
                ...(OHP_9000IData.templateB.templateB_InvertedT && { lubeType: OHP_9000IData.templateB.templateB_InvertedT}),
                ...(OHP_9000IData.templateB.templateB_InvertedU && { lubeType: OHP_9000IData.templateB.templateB_InvertedU}),
                ...(OHP_9000IData.templateB.templateB_InvertedV && { lubeType: OHP_9000IData.templateB.templateB_InvertedV}),
                ...(OHP_9000IData.templateB.templateB_InvertedW && { lubeType: OHP_9000IData.templateB.templateB_InvertedW}),

            }),



            templateCData: new templateC({
                conveyorName: OHP_9000IData.templateC.conveyorName,
                industrialChainManufacturer: OHP_9000IData.templateC.industrialChainManufacturer,
                ...(OHP_9000IData.templateC.otherChainManufacturer && { otherChainManufacturer: OHP_9000IData.templateC.otherChainManufacturer }),
                wheelManufacturer: OHP_9000IData.templateC.wheelManufacturer,
                ...(OHP_9000IData.templateC.wheelManufacturer && { wheelManufacturer: OHP_9000IData.templateC.wheelManufacturer}),
                conveyorSpeed: OHP_9000IData.templateC.conveyorSpeed,
                conveyorSpeedUnit: OHP_9000IData.templateC.conveyorSpeedUnit,
                conveyorIndex: OHP_9000IData.templateC.conveyorIndex,
                ...(OHP_9000IData.templateC.travelDirection && { travelDirection: OHP_9000IData.templateC.travelDirection}),
                appEnviroment: OHP_9000IData.templateC.appEnviroment,
                ...(OHP_9000IData.templateC.otherAppEnviroment && { otherAppEnviroment: OHP_9000IData.templateC.otherAppEnviroment}),
                surroundingTemp: OHP_9000IData.templateC.surroundingTemp,
                orientationType: OHP_9000IData.templateC.orientationType,
                guideWheelsEven: OHP_9000IData.templateC.guideWheelsEven,
                operatingVoltage: OHP_9000IData.templateC.operatingVoltage,
                controlVoltSingle: OHP_9000IData.templateC.controlVoltSingle,
                compressedAir: OHP_9000IData.templateC.compressedAir,
                ...(OHP_9000IData.templateC.airSupplyType && { airSupplyType: OHP_9000IData.templateC.airSupplyType}),
                existingMonitor: OHP_9000IData.templateC.existingMonitor,
                newMonitor: OHP_9000IData.templateC.newMonitor,
                templateA_CData: new templateA({
                ...(OHP_9000IData.templateA.dcuStatus && { dcuStatus: OHP_9000IData.templateA.dcuStatus }),
                ...(OHP_9000IData.templateA.dcuNum && { dcuNum: OHP_9000IData.templateA.dcuNum }),
                ...(OHP_9000IData.templateA.existingWindows && { existingWindows: OHP_9000IData.templateA.existingWindows }),
                ...(OHP_9000IData.templateA.existingHeadUnit && { existingHeadUnit: OHP_9000IData.templateA.existingHeadUnit }),
                ...(OHP_9000IData.templateA.existingDCU && { existingDCU: OHP_9000IData.templateA.existingDCU }),
                ...(OHP_9000IData.templateA.existingPowerInterface && { existingPowerInterface: OHP_9000IData.templateA.existingPowerInterface }),
                ...(OHP_9000IData.templateA.newReservoir && { newReservoir: OHP_9000IData.templateA.newReservoir }),
                ...(OHP_9000IData.templateA.reservoirSize && { reservoirSize: OHP_9000IData.templateA.reservoirSize }),
                ...(OHP_9000IData.templateA.otherReservoirSize && { otherReservoirSize: OHP_9000IData.templateA.otherReservoirSize }),
                ...(OHP_9000IData.templateA.newReservoirNum && { newReservoirNum: OHP_9000IData.templateA.newReservoirNum }),
                ...(OHP_9000IData.templateA.typeMonitor && { typeMonitor: OHP_9000IData.templateA.typeMonitor }),
                ...(OHP_9000IData.templateA.driveMotorAmp && { driveMotorAmp: OHP_9000IData.templateA.driveMotorAmp }),
                ...(OHP_9000IData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_9000IData.templateA.driveMotorAmpNum }),
                ...(OHP_9000IData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_9000IData.templateA.driveTakeUpAir }),
                ...(OHP_9000IData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_9000IData.templateA.driveTakeUpAirNum }),
                ...(OHP_9000IData.templateA.takeUpDistance && { takeUpDistance: OHP_9000IData.templateA.takeUpDistance }),
                ...(OHP_9000IData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_9000IData.templateA.takeUpDistanceNum }),
                ...(OHP_9000IData.templateA.driveTemp && { driveTemp: OHP_9000IData.templateA.driveTemp }),
                ...(OHP_9000IData.templateA.driveTempNum && { driveTempNum: OHP_9000IData.templateA.driveTempNum }),
                ...(OHP_9000IData.templateA.driveVibration && { driveVibration: OHP_9000IData.templateA.driveVibration }),
                ...(OHP_9000IData.templateA.driveVibrationNum && { driveVibrationNum: OHP_9000IData.templateA.driveVibrationNum }),
                ...(OHP_9000IData.templateA.dogPitch && { dogPitch: OHP_9000IData.templateA.dogPitch }),
                ...(OHP_9000IData.templateA.dogPitchNum && { dogPitchNum: OHP_9000IData.templateA.dogPitchNum }),
                ...(OHP_9000IData.templateA.paintMarker && { paintMarker: OHP_9000IData.templateA.paintMarker }),
                ...(OHP_9000IData.templateA.paintMarkerNum && { paintMarkerNum: OHP_9000IData.templateA.paintMarkerNum }),
                ...(OHP_9000IData.templateA.chainVision && { chainVision: OHP_9000IData.templateA.chainVision }),
                ...(OHP_9000IData.templateA.lubeVision && { lubeVision: OHP_9000IData.templateA.lubeVision }),
                ...(OHP_9000IData.templateA.trolleyVision && { trolleyVision: OHP_9000IData.templateA.trolleyVision }),
                ...(OHP_9000IData.templateA.trolleyDetect && { trolleyDetect: OHP_9000IData.templateA.trolleyDetect }),
                ...(OHP_9000IData.templateA.omniView && { omniView: OHP_9000IData.templateA.omniView }),
                ...(OHP_9000IData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_9000IData.templateA.dcuUpgradeNum }),
                ...(OHP_9000IData.templateA.itNameOne && { itNameOne: OHP_9000IData.templateA.itNameOne }),
                ...(OHP_9000IData.templateA.itIPOne && { itIPOne: OHP_9000IData.templateA.itIPOne }),
                ...(OHP_9000IData.templateA.itGatewayOne && { itGatewayOne: OHP_9000IData.templateA.itGatewayOne }),
                ...(OHP_9000IData.templateA.itSubnetOne && { itSubnetOne: OHP_9000IData.templateA.itSubnetOne }),
                ...(OHP_9000IData.templateA.itDNSOne && { itDNSOne: OHP_9000IData.templateA.itDNSOne }),
                ...(OHP_9000IData.templateA.itSMTPOne && { itSMTPOne: OHP_9000IData.templateA.itSMTPOne }),
                ...(OHP_9000IData.templateA.itNameTwo && { itNameTwo: OHP_9000IData.templateA.itNameTwo }),
                ...(OHP_9000IData.templateA.itIPTwo && { itIPTwo: OHP_9000IData.templateA.itIPTwo }),
                ...(OHP_9000IData.templateA.itGatewayTwo && { itGatewayTwo: OHP_9000IData.templateA.itGatewayTwo }),
                ...(OHP_9000IData.templateA.itSubnetTwo && { itSubnetTwo: OHP_9000IData.templateA.itSubnetTwo }),
                ...(OHP_9000IData.templateA.itDNSTwo && { itDNSTwo: OHP_9000IData.templateA.itDNSTwo }),
                ...(OHP_9000IData.templateA.itSMTPTwo && { itSMTPTwo: OHP_9000IData.templateA.itSMTPTwo }),
                ...(OHP_9000IData.templateA.itNameThree && { itNameThree: OHP_9000IData.templateA.itNameThree }),
                ...(OHP_9000IData.templateA.itIPThree && { itIPThree: OHP_9000IData.templateA.itIPThree }),
                ...(OHP_9000IData.templateA.itGatewayThree && { itGatewayThree: OHP_9000IData.templateA.itGatewayThree }),
                ...(OHP_9000IData.templateA.itSubnetThree && { itSubnetThree: OHP_9000IData.templateA.itSubnetThree }),
                ...(OHP_9000IData.templateA.itDNSThree && { itDNSThree: OHP_9000IData.templateA.itDNSThree }),
                ...(OHP_9000IData.templateA.itSMTPThree && { itSMTPThree: OHP_9000IData.templateA.itSMTPThree }),
                ...(OHP_9000IData.templateA.itAdditionalNotes && { itAdditionalNotes: OHP_9000IData.templateA.itAdditionalNotes }),
                ...(OHP_9000IData.templateA.piuDistance && { piuDistance: OHP_9000IData.templateA.piuDistance }),
                ...(OHP_9000IData.templateA.switchDistance && { switchDistance: OHP_9000IData.templateA.switchDistance }),
                ...(OHP_9000IData.templateA.ampPickup && { ampPickup: OHP_9000IData.templateA.ampPickup }),
                ...(OHP_9000IData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_9000IData.templateA.fromAirTakeUpDistance }),
                ...(OHP_9000IData.templateA.specialControllerOptions && { specialControllerOptions: OHP_9000IData.templateA.specialControllerOptions }),
                ...(OHP_9000IData.templateA.operatingVoltage && { operatingVoltage: OHP_9000IData.templateA.operatingVoltage })

                }),
                freeWheelStatus: OHP_9000IData.templateC.freeWheelStatus,
                actuatorStatus: OHP_9000IData.templateC.actuatorStatus,
                ...(OHP_9000IData.templateC.pivotStatus && { pivotStatus: OHP_9000IData.templateC.pivotStatus}),
                kingPinStatus: OHP_9000IData.templateC.kingPinStatus,
                lubeBrand: OHP_9000IData.templateC.lubeBrand,
                lubeViscosity: OHP_9000IData.templateC.lubeViscosity,
                ...(OHP_9000IData.templateC.lubeType && { lubeType: OHP_9000IData.templateC.lubeType}),
                currentGrease: OHP_9000IData.templateC.currentGrease,
                currentGreaseGrade: OHP_9000IData.templateC.currentGreaseGrade,
                zerkDirection: OHP_9000IData.templateC.zerkDirection,
                zerkLocationType: OHP_9000IData.templateC.zerkLocationType,
                wheelDiameter: OHP_9000IData.templateC.wheelDiameter,
                conveyorSwing: OHP_9000IData.templateC.conveyorSwing,
                ...(OHP_9000IData.templateC.chainMaster && { lubeType: OHP_9000IData.templateC.chainMaster}),
                ...(OHP_9000IData.templateC.remoteStatus && { lubeType: OHP_9000IData.templateC.remoteStatus}),
                ...(OHP_9000IData.templateC.mountStatus && { lubeType: OHP_9000IData.templateC.mountStatus}),
                ...(OHP_9000IData.templateC.otherUnitStatus && { lubeType: OHP_9000IData.templateC.otherUnitStatus}),
                ...(OHP_9000IData.templateC.timerStatus && { lubeType: OHP_9000IData.templateC.timerStatus}),
                ...(OHP_9000IData.templateC.electricStatus && { lubeType: OHP_9000IData.templateC.electricStatus}),
                ...(OHP_9000IData.templateC.mightyLubeMonitoring && { lubeType: OHP_9000IData.templateC.mightyLubeMonitoring}),
                ...(OHP_9000IData.templateC.preMountType && { lubeType: OHP_9000IData.templateC.preMountType}),
                ...(OHP_9000IData.templateC.otherPreMountType && { lubeType: OHP_9000IData.templateC.otherPreMountType}),
                ...(OHP_9000IData.templateC.plcConnection && { lubeType: OHP_9000IData.templateC.plcConnection}),
                ...(OHP_9000IData.templateC.otherControllerNotes && { lubeType: OHP_9000IData.templateC.otherControllerNotes}),
                ...(OHP_9000IData.templateC.templateC_UnitType && { lubeType: OHP_9000IData.templateC.templateC_UnitType}),
                templateC_InvertedA: OHP_9000IData.templateC.templateC_InvertedA,
                templateC_InvertedB: OHP_9000IData.templateC.templateC_InvertedB,
                templateC_InvertedE: OHP_9000IData.templateC.templateC_InvertedE,
                templateC_InvertedS: OHP_9000IData.templateC.templateC_InvertedS,
            }),
            ...(OHP_9000IData.wheelOpenType && { wheelOpenType: OHP_9000IData.wheelOpenType }),
            ...(OHP_9000IData.wheelClosedType && { wheelClosedType: OHP_9000IData.wheelClosedType }),
            ...(OHP_9000IData.powerChainStatus && { powerChainStatus: OHP_9000IData.powerChainStatus }),
            ...(OHP_9000IData.chainPinStatus && { chainPinStatus: OHP_9000IData.chainPinStatus }),
            ...(OHP_9000IData.catDriveStatus && { catDriveStatus: OHP_9000IData.catDriveStatus }),
            ...(OHP_9000IData.catDriveNum && { catDriveNum: OHP_9000IData.catDriveNum }),
            ...(OHP_9000IData.railLubeStatus && { railLubeStatus: OHP_9000IData.railLubeStatus }),
            ...(OHP_9000IData.externalLubeStatus && { externalLubeStatus: OHP_9000IData.externalLubeStatus }),
            ...(OHP_9000IData.lubeBrand && { lubeBrand: OHP_9000IData.lubeBrand }),
            ...(OHP_9000IData.lubeType && { lubeType: OHP_9000IData.lubeType }),
            ...(OHP_9000IData.lubeViscosity && { lubeViscosity: OHP_9000IData.lubeViscosity }),
            ...(OHP_9000IData.sideLubeStatus && { sideLubeStatus: OHP_9000IData.sideLubeStatus }),
            ...(OHP_9000IData.topLubeStatus && { topLubeStatus: OHP_9000IData.topLubeStatus }),
            ...(OHP_9000IData.chainCleanStatus && { chainCleanStatus: OHP_9000IData.chainCleanStatus }),
            ...(OHP_9000IData.wireMeasurementUnit && { wireMeasurementUnit: OHP_9000IData.wireMeasurementUnit }),
            ...(OHP_9000IData.twoConductor && { twoConductor: OHP_9000IData.twoConductor }),
            ...(OHP_9000IData.fourConductor && { fourConductor: OHP_9000IData.fourConductor }),
            ...(OHP_9000IData.sevenConductor && { sevenConductor: OHP_9000IData.sevenConductor }),
            ...(OHP_9000IData.twelveConductor && { twelveConductor: OHP_9000IData.twelveConductor }),
            ...(OHP_9000IData.junctionBoxNum && { junctionBoxNum: OHP_9000IData.junctionBoxNum }),
            ...(OHP_9000IData.ohpUnitType && { ohpUnitType: OHP_9000IData.ohpUnitType }),
            ...(OHP_9000IData.ohpDiameter && { ohpDiameter: OHP_9000IData.ohpDiameter }),
            ...(OHP_9000IData.ohpWidth && { ohpWidth: OHP_9000IData.ohpWidth }),
            ...(OHP_9000IData.ohpHeight && { ohpHeight: OHP_9000IData.ohpHeight })
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "OHP_9000I"
        });
        await req.user.save();
        return res.status(200).json({ message: "OHP_9000I entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;