const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const OHP_9000I = require("../models/OHP_9000I");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");


const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { OHP_9000IData, numRequested } = req.body;
        const order = new OHP_9000I({
            conveyorName: OHP_9000IData.conveyorName,
            chainSize: OHP_9000IData.chainSize,
            ...(OHP_9000IData.otherChainSize && { otherChainSize: OHP_9000IData.otherChainSize }),
            industrialChainManufacturer: OHP_9000IData.industrialChainManufacturer,
            ...(OHP_9000IData.otherChainManufacturer && { otherChainManufacturer: OHP_9000IData.otherChainManufacturer }),
            ...(OHP_9000IData.conveyorLength && { conveyorLength: OHP_9000IData.conveyorLength }),
            ...(OHP_9000IData.conveyorLengthUnit && { conveyorLengthUnit: OHP_9000IData.conveyorLengthUnit }),
            ...(OHP_9000IData.conveyorSpeed && { conveyorSpeed: OHP_9000IData.conveyorSpeed }),
            ...(OHP_9000IData.conveyorSpeedUnit && { conveyorSpeedUnit: OHP_9000IData.conveyorSpeedUnit }),
            ...(OHP_9000IData.conveyorIndex && { conveyorIndex: OHP_9000IData.conveyorIndex }),
            ...(OHP_9000IData.travelDirection && { travelDirection: OHP_9000IData.travelDirection }),
            appEnviroment: OHP_9000IData.appEnviroment,
            ...(OHP_9000IData.ovenStatus && { ovenStatus: OHP_9000IData.ovenStatus }),
            ...(OHP_9000IData.ovenTemp && { ovenTemp: OHP_9000IData.ovenTemp }),
            ...(OHP_9000IData.otherAppEnviroment && { otherAppEnviroment: OHP_9000IData.otherAppEnviroment }),
            ...(OHP_9000IData.surroundingTemp && { surroundingTemp: OHP_9000IData.surroundingTemp }),
            ...(OHP_9000IData.conveyorLoaded && { conveyorLoaded: OHP_9000IData.conveyorLoaded }),
            ...(OHP_9000IData.swingStatus && { swingStatus: OHP_9000IData.swingStatus }),
            ...(OHP_9000IData.operatingVoltSingle && { operatingVoltSingle: OHP_9000IData.operatingVoltSingle }),
            ...(OHP_9000IData.controlVoltSingle && { controlVoltSingle: OHP_9000IData.controlVoltSingle }),
            existingMonitor: OHP_9000IData.existingMonitor,
            newMonitor: OHP_9000IData.newMonitor,
            monitorData: {
                ...(OHP_9000IData.dcuStatus && { dcuStatus: OHP_9000IData.dcuStatus }),
                ...(OHP_9000IData.dcuNum && { dcuNum: OHP_9000IData.dcuNum }),
                ...(OHP_9000IData.existingWindows && { existingWindows: OHP_9000IData.existingWindows }),
                ...(OHP_9000IData.existingHeadUnit && { existingHeadUnit: OHP_9000IData.existingHeadUnit }),
                ...(OHP_9000IData.existingDCU && { existingDCU: OHP_9000IData.existingDCU }),
                ...(OHP_9000IData.existingPowerInterface && { existingPowerInterface: OHP_9000IData.existingPowerInterface }),
                ...(OHP_9000IData.newReservoir && { newReservoir: OHP_9000IData.newReservoir }),
                ...(OHP_9000IData.reservoirSize && { reservoirSize: OHP_9000IData.reservoirSize }),
                ...(OHP_9000IData.otherReservoirSize && { otherReservoirSize: OHP_9000IData.otherReservoirSize }),
                ...(OHP_9000IData.newReservoirNum && { newReservoirNum: OHP_9000IData.newReservoirNum }),
                ...(OHP_9000IData.typeMonitor && { typeMonitor: OHP_9000IData.typeMonitor }),
                ...(OHP_9000IData.driveMotorAmp && { driveMotorAmp: OHP_9000IData.driveMotorAmp }),
                ...(OHP_9000IData.driveMotorAmpNum && { driveMotorAmpNum: OHP_9000IData.driveMotorAmpNum }),
                ...(OHP_9000IData.driveTakeUpAir && { driveTakeUpAir: OHP_9000IData.driveTakeUpAir }),
                ...(OHP_9000IData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_9000IData.driveTakeUpAirNum }),
                ...(OHP_9000IData.takeUpDistance && { takeUpDistance: OHP_9000IData.takeUpDistance }),
                ...(OHP_9000IData.takeUpDistanceNum && { takeUpDistanceNum: OHP_9000IData.takeUpDistanceNum }),
                ...(OHP_9000IData.driveTemp && { driveTemp: OHP_9000IData.driveTemp }),
                ...(OHP_9000IData.driveTempNum && { driveTempNum: OHP_9000IData.driveTempNum }),
                ...(OHP_9000IData.driveVibration && { driveVibration: OHP_9000IData.driveVibration }),
                ...(OHP_9000IData.driveVibrationNum && { driveVibrationNum: OHP_9000IData.driveVibrationNum }),
                ...(OHP_9000IData.dogPitch && { dogPitch: OHP_9000IData.dogPitch }),
                ...(OHP_9000IData.dogPitchNum && { dogPitchNum: OHP_9000IData.dogPitchNum }),
                ...(OHP_9000IData.paintMarker && { paintMarker: OHP_9000IData.paintMarker }),
                ...(OHP_9000IData.paintMarkerNum && { paintMarkerNum: OHP_9000IData.paintMarkerNum }),
                ...(OHP_9000IData.chainVision && { chainVision: OHP_9000IData.chainVision }),
                ...(OHP_9000IData.lubeVision && { lubeVision: OHP_9000IData.lubeVision }),
                ...(OHP_9000IData.trolleyVision && { trolleyVision: OHP_9000IData.trolleyVision }),
                ...(OHP_9000IData.trolleyDetect && { trolleyDetect: OHP_9000IData.trolleyDetect }),
                ...(OHP_9000IData.omniView && { omniView: OHP_9000IData.omniView }),
                ...(OHP_9000IData.dcuUpgradeNum && { dcuUpgradeNum: OHP_9000IData.dcuUpgradeNum }),
                ...(OHP_9000IData.itNameOne && { itNameOne: OHP_9000IData.itNameOne }),
                ...(OHP_9000IData.itIPOne && { itIPOne: OHP_9000IData.itIPOne }),
                ...(OHP_9000IData.itGatewayOne && { itGatewayOne: OHP_9000IData.itGatewayOne }),
                ...(OHP_9000IData.itSubnetOne && { itSubnetOne: OHP_9000IData.itSubnetOne }),
                ...(OHP_9000IData.itDNSOne && { itDNSOne: OHP_9000IData.itDNSOne }),
                ...(OHP_9000IData.itSMTPOne && { itSMTPOne: OHP_9000IData.itSMTPOne }),
                ...(OHP_9000IData.itNameTwo && { itNameTwo: OHP_9000IData.itNameTwo }),
                ...(OHP_9000IData.itIPTwo && { itIPTwo: OHP_9000IData.itIPTwo }),
                ...(OHP_9000IData.itGatewayTwo && { itGatewayTwo: OHP_9000IData.itGatewayTwo }),
                ...(OHP_9000IData.itSubnetTwo && { itSubnetTwo: OHP_9000IData.itSubnetTwo }),
                ...(OHP_9000IData.itDNSTwo && { itDNSTwo: OHP_9000IData.itDNSTwo }),
                ...(OHP_9000IData.itSMTPTwo && { itSMTPTwo: OHP_9000IData.itSMTPTwo }),
                ...(OHP_9000IData.itNameThree && { itNameThree: OHP_9000IData.itNameThree }),
                ...(OHP_9000IData.itIPThree && { itIPThree: OHP_9000IData.itIPThree }),
                ...(OHP_9000IData.itGatewayThree && { itGatewayThree: OHP_9000IData.itGatewayThree }),
                ...(OHP_9000IData.itSubnetThree && { itSubnetThree: OHP_9000IData.itSubnetThree }),
                ...(OHP_9000IData.itDNSThree && { itDNSThree: OHP_9000IData.itDNSThree }),
                ...(OHP_9000IData.itSMTPThree && { itSMTPThree: OHP_9000IData.itSMTPThree }),
                ...(OHP_9000IData.itAdditionalNotes && { itAdditionalNotes: OHP_9000IData.itAdditionalNotes }),
                ...(OHP_9000IData.piuDistance && { piuDistance: OHP_9000IData.piuDistance }),
                ...(OHP_9000IData.switchDistance && { switchDistance: OHP_9000IData.switchDistance }),
                ...(OHP_9000IData.ampPickup && { ampPickup: OHP_9000IData.ampPickup }),
                ...(OHP_9000IData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_9000IData.fromAirTakeUpDistance }),
                ...(OHP_9000IData.specialControllerOptions && { specialControllerOptions: OHP_9000IData.specialControllerOptions }),
                ...(OHP_9000IData.operatingVoltage && { operatingVoltage: OHP_9000IData.operatingVoltage })

            },
            
            addFreeCarrier: OHP_9000IData.addFreeCarrier,

            templateBData: {
                conveyorName: OHP_9000IData.conveyorName,
                industrialChainManufacturer: OHP_9000IData.industrialChainManufacturer,
                ...(OHP_9000IData.otherChainManufacturer && { otherChainManufacturer: OHP_9000IData.otherChainManufacturer }),
                wheelManufacturer: OHP_9000IData.wheelManufacturer,
                ...(OHP_9000IData.wheelManufacturer && { wheelManufacturer: OHP_9000IData.wheelManufacturer}),
                conveyorSpeed: OHP_9000IData.conveyorSpeed,
                conveyorSpeedUnit: OHP_9000IData.conveyorSpeedUnit,
                conveyorIndex: OHP_9000IData.conveyorIndex,
                ...(OHP_9000IData.travelDirection && { travelDirection: OHP_9000IData.travelDirection}),
                appEnviroment: OHP_9000IData.appEnviroment,
                ...(OHP_9000IData.otherAppEnviroment && { otherAppEnviroment: OHP_9000IData.otherAppEnviroment}),
                surroundingTemp: OHP_9000IData.surroundingTemp,
                orientationType: OHP_9000IData.orientationType,
                operatingVoltage: OHP_9000IData.operatingVoltage,
                controlVoltSingle: OHP_9000IData.controlVoltSingle,
                compressedAir: OHP_9000IData.compressedAir,
                ...(OHP_9000IData.airSupplyType && { airSupplyType: OHP_9000IData.airSupplyType}),
            existingMonitor: OHP_9000IData.existingMonitor,
            newMonitor: OHP_9000IData.newMonitor,
            templateA_BData: {
                ...(OHP_9000IData.dcuStatus && { dcuStatus: OHP_9000IData.dcuStatus }),
                ...(OHP_9000IData.dcuNum && { dcuNum: OHP_9000IData.dcuNum }),
                ...(OHP_9000IData.existingWindows && { existingWindows: OHP_9000IData.existingWindows }),
                ...(OHP_9000IData.existingHeadUnit && { existingHeadUnit: OHP_9000IData.existingHeadUnit }),
                ...(OHP_9000IData.existingDCU && { existingDCU: OHP_9000IData.existingDCU }),
                ...(OHP_9000IData.existingPowerInterface && { existingPowerInterface: OHP_9000IData.existingPowerInterface }),
                ...(OHP_9000IData.newReservoir && { newReservoir: OHP_9000IData.newReservoir }),
                ...(OHP_9000IData.reservoirSize && { reservoirSize: OHP_9000IData.reservoirSize }),
                ...(OHP_9000IData.otherReservoirSize && { otherReservoirSize: OHP_9000IData.otherReservoirSize }),
                ...(OHP_9000IData.newReservoirNum && { newReservoirNum: OHP_9000IData.newReservoirNum }),
                ...(OHP_9000IData.typeMonitor && { typeMonitor: OHP_9000IData.typeMonitor }),
                ...(OHP_9000IData.driveMotorAmp && { driveMotorAmp: OHP_9000IData.driveMotorAmp }),
                ...(OHP_9000IData.driveMotorAmpNum && { driveMotorAmpNum: OHP_9000IData.driveMotorAmpNum }),
                ...(OHP_9000IData.driveTakeUpAir && { driveTakeUpAir: OHP_9000IData.driveTakeUpAir }),
                ...(OHP_9000IData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_9000IData.driveTakeUpAirNum }),
                ...(OHP_9000IData.takeUpDistance && { takeUpDistance: OHP_9000IData.takeUpDistance }),
                ...(OHP_9000IData.takeUpDistanceNum && { takeUpDistanceNum: OHP_9000IData.takeUpDistanceNum }),
                ...(OHP_9000IData.driveTemp && { driveTemp: OHP_9000IData.driveTemp }),
                ...(OHP_9000IData.driveTempNum && { driveTempNum: OHP_9000IData.driveTempNum }),
                ...(OHP_9000IData.driveVibration && { driveVibration: OHP_9000IData.driveVibration }),
                ...(OHP_9000IData.driveVibrationNum && { driveVibrationNum: OHP_9000IData.driveVibrationNum }),
                ...(OHP_9000IData.dogPitch && { dogPitch: OHP_9000IData.dogPitch }),
                ...(OHP_9000IData.dogPitchNum && { dogPitchNum: OHP_9000IData.dogPitchNum }),
                ...(OHP_9000IData.paintMarker && { paintMarker: OHP_9000IData.paintMarker }),
                ...(OHP_9000IData.paintMarkerNum && { paintMarkerNum: OHP_9000IData.paintMarkerNum }),
                ...(OHP_9000IData.chainVision && { chainVision: OHP_9000IData.chainVision }),
                ...(OHP_9000IData.lubeVision && { lubeVision: OHP_9000IData.lubeVision }),
                ...(OHP_9000IData.trolleyVision && { trolleyVision: OHP_9000IData.trolleyVision }),
                ...(OHP_9000IData.trolleyDetect && { trolleyDetect: OHP_9000IData.trolleyDetect }),
                ...(OHP_9000IData.omniView && { omniView: OHP_9000IData.omniView }),
                ...(OHP_9000IData.dcuUpgradeNum && { dcuUpgradeNum: OHP_9000IData.dcuUpgradeNum }),
                ...(OHP_9000IData.itNameOne && { itNameOne: OHP_9000IData.itNameOne }),
                ...(OHP_9000IData.itIPOne && { itIPOne: OHP_9000IData.itIPOne }),
                ...(OHP_9000IData.itGatewayOne && { itGatewayOne: OHP_9000IData.itGatewayOne }),
                ...(OHP_9000IData.itSubnetOne && { itSubnetOne: OHP_9000IData.itSubnetOne }),
                ...(OHP_9000IData.itDNSOne && { itDNSOne: OHP_9000IData.itDNSOne }),
                ...(OHP_9000IData.itSMTPOne && { itSMTPOne: OHP_9000IData.itSMTPOne }),
                ...(OHP_9000IData.itNameTwo && { itNameTwo: OHP_9000IData.itNameTwo }),
                ...(OHP_9000IData.itIPTwo && { itIPTwo: OHP_9000IData.itIPTwo }),
                ...(OHP_9000IData.itGatewayTwo && { itGatewayTwo: OHP_9000IData.itGatewayTwo }),
                ...(OHP_9000IData.itSubnetTwo && { itSubnetTwo: OHP_9000IData.itSubnetTwo }),
                ...(OHP_9000IData.itDNSTwo && { itDNSTwo: OHP_9000IData.itDNSTwo }),
                ...(OHP_9000IData.itSMTPTwo && { itSMTPTwo: OHP_9000IData.itSMTPTwo }),
                ...(OHP_9000IData.itNameThree && { itNameThree: OHP_9000IData.itNameThree }),
                ...(OHP_9000IData.itIPThree && { itIPThree: OHP_9000IData.itIPThree }),
                ...(OHP_9000IData.itGatewayThree && { itGatewayThree: OHP_9000IData.itGatewayThree }),
                ...(OHP_9000IData.itSubnetThree && { itSubnetThree: OHP_9000IData.itSubnetThree }),
                ...(OHP_9000IData.itDNSThree && { itDNSThree: OHP_9000IData.itDNSThree }),
                ...(OHP_9000IData.itSMTPThree && { itSMTPThree: OHP_9000IData.itSMTPThree }),
                ...(OHP_9000IData.itAdditionalNotes && { itAdditionalNotes: OHP_9000IData.itAdditionalNotes }),
                ...(OHP_9000IData.piuDistance && { piuDistance: OHP_9000IData.piuDistance }),
                ...(OHP_9000IData.switchDistance && { switchDistance: OHP_9000IData.switchDistance }),
                ...(OHP_9000IData.ampPickup && { ampPickup: OHP_9000IData.ampPickup }),
                ...(OHP_9000IData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_9000IData.fromAirTakeUpDistance }),
                ...(OHP_9000IData.specialControllerOptions && { specialControllerOptions: OHP_9000IData.specialControllerOptions }),
                ...(OHP_9000IData.operatingVoltage && { operatingVoltage: OHP_9000IData.operatingVoltage })

                },
                freeWheelStatus: OHP_9000IData.freeWheelStatus,
                actuatorStatus: OHP_9000IData.actuatorStatus,
                ...(OHP_9000IData.pivotStatus && { pivotStatus: OHP_9000IData.pivotStatus}),
                kingPinStatus: OHP_9000IData.kingPinStatus,
                lubeBrand: OHP_9000IData.lubeBrand,
                lubeViscosity: OHP_9000IData.lubeViscosity,
                ...(OHP_9000IData.lubeType && { lubeType: OHP_9000IData.lubeType}),
                currentGrease: OHP_9000IData.currentGrease,
                currentGreaseGrade: OHP_9000IData.currentGreaseGrade,
                zerkDirection: OHP_9000IData.zerkDirection,
                zerkLocationType: OHP_9000IData.zerkLocationType,
                wheelDiameter: OHP_9000IData.wheelDiameter,
                conveyorSwing: OHP_9000IData.conveyorSwing,
                ...(OHP_9000IData.chainMaster && { lubeType: OHP_9000IData.chainMaster}),
                ...(OHP_9000IData.remoteStatus && { lubeType: OHP_9000IData.remoteStatus}),
                ...(OHP_9000IData.mountStatus && { lubeType: OHP_9000IData.mountStatus}),
                ...(OHP_9000IData.otherUnitStatus && { lubeType: OHP_9000IData.otherUnitStatus}),
                ...(OHP_9000IData.timerStatus && { lubeType: OHP_9000IData.timerStatus}),
                ...(OHP_9000IData.electricStatus && { lubeType: OHP_9000IData.electricStatus}),
                ...(OHP_9000IData.mightyLubeMonitoring && { lubeType: OHP_9000IData.mightyLubeMonitoring}),
                ...(OHP_9000IData.preMountType && { lubeType: OHP_9000IData.preMountType}),
                ...(OHP_9000IData.otherPreMountType && { lubeType: OHP_9000IData.otherPreMountType}),
                ...(OHP_9000IData.plcConnection && { lubeType: OHP_9000IData.plcConnection}),
                ...(OHP_9000IData.otherControllerNotes && { lubeType: OHP_9000IData.otherControllerNotes}),
                ...(OHP_9000IData.templateB_UnitType && { lubeType: OHP_9000IData.templateB_UnitType}),
                ...(OHP_9000IData.templateB_InvertedB && { lubeType: OHP_9000IData.templateB_InvertedB}),
                ...(OHP_9000IData.templateB_InvertedE && { lubeType: OHP_9000IData.templateB_InvertedE}),
                ...(OHP_9000IData.templateB_InvertedG && { lubeType: OHP_9000IData.templateB_InvertedG}),
                ...(OHP_9000IData.templateB_InvertedH && { lubeType: OHP_9000IData.templateB_InvertedH}),
                ...(OHP_9000IData.templateB_InvertedK && { lubeType: OHP_9000IData.templateB_InvertedK}),
                ...(OHP_9000IData.templateB_InvertedT && { lubeType: OHP_9000IData.templateB_InvertedT}),
                ...(OHP_9000IData.templateB_InvertedU && { lubeType: OHP_9000IData.templateB_InvertedU}),
                ...(OHP_9000IData.templateB_InvertedV && { lubeType: OHP_9000IData.templateB_InvertedV}),
                ...(OHP_9000IData.templateB_InvertedW && { lubeType: OHP_9000IData.templateB_InvertedW}),

            },

            templateCData: {
                conveyorName: OHP_9000IData.conveyorName,
                industrialChainManufacturer: OHP_9000IData.industrialChainManufacturer,
                ...(OHP_9000IData.otherChainManufacturer && { otherChainManufacturer: OHP_9000IData.otherChainManufacturer }),
                wheelManufacturer: OHP_9000IData.wheelManufacturer,
                ...(OHP_9000IData.wheelManufacturer && { wheelManufacturer: OHP_9000IData.wheelManufacturer}),
                conveyorSpeed: OHP_9000IData.conveyorSpeed,
                conveyorSpeedUnit: OHP_9000IData.conveyorSpeedUnit,
                conveyorIndex: OHP_9000IData.conveyorIndex,
                ...(OHP_9000IData.travelDirection && { travelDirection: OHP_9000IData.travelDirection}),
                appEnviroment: OHP_9000IData.appEnviroment,
                ...(OHP_9000IData.otherAppEnviroment && { otherAppEnviroment: OHP_9000IData.otherAppEnviroment}),
                surroundingTemp: OHP_9000IData.surroundingTemp,
                orientationType: OHP_9000IData.orientationType,
                guideWheelsEven: OHP_9000IData.guideWheelsEven,
                operatingVoltage: OHP_9000IData.operatingVoltage,
                controlVoltSingle: OHP_9000IData.controlVoltSingle,
                compressedAir: OHP_9000IData.compressedAir,
                ...(OHP_9000IData.airSupplyType && { airSupplyType: OHP_9000IData.airSupplyType}),
                existingMonitor: OHP_9000IData.existingMonitor,
                newMonitor: OHP_9000IData.newMonitor,
                templateA_CData: {
                ...(OHP_9000IData.dcuStatus && { dcuStatus: OHP_9000IData.dcuStatus }),
                ...(OHP_9000IData.dcuNum && { dcuNum: OHP_9000IData.dcuNum }),
                ...(OHP_9000IData.existingWindows && { existingWindows: OHP_9000IData.existingWindows }),
                ...(OHP_9000IData.existingHeadUnit && { existingHeadUnit: OHP_9000IData.existingHeadUnit }),
                ...(OHP_9000IData.existingDCU && { existingDCU: OHP_9000IData.existingDCU }),
                ...(OHP_9000IData.existingPowerInterface && { existingPowerInterface: OHP_9000IData.existingPowerInterface }),
                ...(OHP_9000IData.newReservoir && { newReservoir: OHP_9000IData.newReservoir }),
                ...(OHP_9000IData.reservoirSize && { reservoirSize: OHP_9000IData.reservoirSize }),
                ...(OHP_9000IData.otherReservoirSize && { otherReservoirSize: OHP_9000IData.otherReservoirSize }),
                ...(OHP_9000IData.newReservoirNum && { newReservoirNum: OHP_9000IData.newReservoirNum }),
                ...(OHP_9000IData.typeMonitor && { typeMonitor: OHP_9000IData.typeMonitor }),
                ...(OHP_9000IData.driveMotorAmp && { driveMotorAmp: OHP_9000IData.driveMotorAmp }),
                ...(OHP_9000IData.driveMotorAmpNum && { driveMotorAmpNum: OHP_9000IData.driveMotorAmpNum }),
                ...(OHP_9000IData.driveTakeUpAir && { driveTakeUpAir: OHP_9000IData.driveTakeUpAir }),
                ...(OHP_9000IData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_9000IData.driveTakeUpAirNum }),
                ...(OHP_9000IData.takeUpDistance && { takeUpDistance: OHP_9000IData.takeUpDistance }),
                ...(OHP_9000IData.takeUpDistanceNum && { takeUpDistanceNum: OHP_9000IData.takeUpDistanceNum }),
                ...(OHP_9000IData.driveTemp && { driveTemp: OHP_9000IData.driveTemp }),
                ...(OHP_9000IData.driveTempNum && { driveTempNum: OHP_9000IData.driveTempNum }),
                ...(OHP_9000IData.driveVibration && { driveVibration: OHP_9000IData.driveVibration }),
                ...(OHP_9000IData.driveVibrationNum && { driveVibrationNum: OHP_9000IData.driveVibrationNum }),
                ...(OHP_9000IData.dogPitch && { dogPitch: OHP_9000IData.dogPitch }),
                ...(OHP_9000IData.dogPitchNum && { dogPitchNum: OHP_9000IData.dogPitchNum }),
                ...(OHP_9000IData.paintMarker && { paintMarker: OHP_9000IData.paintMarker }),
                ...(OHP_9000IData.paintMarkerNum && { paintMarkerNum: OHP_9000IData.paintMarkerNum }),
                ...(OHP_9000IData.chainVision && { chainVision: OHP_9000IData.chainVision }),
                ...(OHP_9000IData.lubeVision && { lubeVision: OHP_9000IData.lubeVision }),
                ...(OHP_9000IData.trolleyVision && { trolleyVision: OHP_9000IData.trolleyVision }),
                ...(OHP_9000IData.trolleyDetect && { trolleyDetect: OHP_9000IData.trolleyDetect }),
                ...(OHP_9000IData.omniView && { omniView: OHP_9000IData.omniView }),
                ...(OHP_9000IData.dcuUpgradeNum && { dcuUpgradeNum: OHP_9000IData.dcuUpgradeNum }),
                ...(OHP_9000IData.itNameOne && { itNameOne: OHP_9000IData.itNameOne }),
                ...(OHP_9000IData.itIPOne && { itIPOne: OHP_9000IData.itIPOne }),
                ...(OHP_9000IData.itGatewayOne && { itGatewayOne: OHP_9000IData.itGatewayOne }),
                ...(OHP_9000IData.itSubnetOne && { itSubnetOne: OHP_9000IData.itSubnetOne }),
                ...(OHP_9000IData.itDNSOne && { itDNSOne: OHP_9000IData.itDNSOne }),
                ...(OHP_9000IData.itSMTPOne && { itSMTPOne: OHP_9000IData.itSMTPOne }),
                ...(OHP_9000IData.itNameTwo && { itNameTwo: OHP_9000IData.itNameTwo }),
                ...(OHP_9000IData.itIPTwo && { itIPTwo: OHP_9000IData.itIPTwo }),
                ...(OHP_9000IData.itGatewayTwo && { itGatewayTwo: OHP_9000IData.itGatewayTwo }),
                ...(OHP_9000IData.itSubnetTwo && { itSubnetTwo: OHP_9000IData.itSubnetTwo }),
                ...(OHP_9000IData.itDNSTwo && { itDNSTwo: OHP_9000IData.itDNSTwo }),
                ...(OHP_9000IData.itSMTPTwo && { itSMTPTwo: OHP_9000IData.itSMTPTwo }),
                ...(OHP_9000IData.itNameThree && { itNameThree: OHP_9000IData.itNameThree }),
                ...(OHP_9000IData.itIPThree && { itIPThree: OHP_9000IData.itIPThree }),
                ...(OHP_9000IData.itGatewayThree && { itGatewayThree: OHP_9000IData.itGatewayThree }),
                ...(OHP_9000IData.itSubnetThree && { itSubnetThree: OHP_9000IData.itSubnetThree }),
                ...(OHP_9000IData.itDNSThree && { itDNSThree: OHP_9000IData.itDNSThree }),
                ...(OHP_9000IData.itSMTPThree && { itSMTPThree: OHP_9000IData.itSMTPThree }),
                ...(OHP_9000IData.itAdditionalNotes && { itAdditionalNotes: OHP_9000IData.itAdditionalNotes }),
                ...(OHP_9000IData.piuDistance && { piuDistance: OHP_9000IData.piuDistance }),
                ...(OHP_9000IData.switchDistance && { switchDistance: OHP_9000IData.switchDistance }),
                ...(OHP_9000IData.ampPickup && { ampPickup: OHP_9000IData.ampPickup }),
                ...(OHP_9000IData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_9000IData.fromAirTakeUpDistance }),
                ...(OHP_9000IData.specialControllerOptions && { specialControllerOptions: OHP_9000IData.specialControllerOptions }),
                ...(OHP_9000IData.operatingVoltage && { operatingVoltage: OHP_9000IData.operatingVoltage })

                },
                freeWheelStatus: OHP_9000IData.freeWheelStatus,
                actuatorStatus: OHP_9000IData.actuatorStatus,
                ...(OHP_9000IData.pivotStatus && { pivotStatus: OHP_9000IData.pivotStatus}),
                kingPinStatus: OHP_9000IData.kingPinStatus,
                lubeBrand: OHP_9000IData.lubeBrand,
                lubeViscosity: OHP_9000IData.lubeViscosity,
                ...(OHP_9000IData.lubeType && { lubeType: OHP_9000IData.lubeType}),
                currentGrease: OHP_9000IData.currentGrease,
                currentGreaseGrade: OHP_9000IData.currentGreaseGrade,
                zerkDirection: OHP_9000IData.zerkDirection,
                zerkLocationType: OHP_9000IData.zerkLocationType,
                wheelDiameter: OHP_9000IData.wheelDiameter,
                conveyorSwing: OHP_9000IData.conveyorSwing,
                ...(OHP_9000IData.chainMaster && { lubeType: OHP_9000IData.chainMaster}),
                ...(OHP_9000IData.remoteStatus && { lubeType: OHP_9000IData.remoteStatus}),
                ...(OHP_9000IData.mountStatus && { lubeType: OHP_9000IData.mountStatus}),
                ...(OHP_9000IData.otherUnitStatus && { lubeType: OHP_9000IData.otherUnitStatus}),
                ...(OHP_9000IData.timerStatus && { lubeType: OHP_9000IData.timerStatus}),
                ...(OHP_9000IData.electricStatus && { lubeType: OHP_9000IData.electricStatus}),
                ...(OHP_9000IData.mightyLubeMonitoring && { lubeType: OHP_9000IData.mightyLubeMonitoring}),
                ...(OHP_9000IData.preMountType && { lubeType: OHP_9000IData.preMountType}),
                ...(OHP_9000IData.otherPreMountType && { lubeType: OHP_9000IData.otherPreMountType}),
                ...(OHP_9000IData.plcConnection && { lubeType: OHP_9000IData.plcConnection}),
                ...(OHP_9000IData.otherControllerNotes && { lubeType: OHP_9000IData.otherControllerNotes}),
                ...(OHP_9000IData.templateC_UnitType && { lubeType: OHP_9000IData.templateC_UnitType}),
                templateC_InvertedA: OHP_9000IData.templateC_InvertedA,
                templateC_InvertedB: OHP_9000IData.templateC_InvertedB,
                templateC_InvertedE: OHP_9000IData.templateC_InvertedE,
                templateC_InvertedS: OHP_9000IData.templateC_InvertedS,
            },
            ...(OHP_9000IData.wheelOpenType && { wheelOpenType: OHP_9000IData.wheelOpenType }),
            ...(OHP_9000IData.wheelClosedType && { wheelClosedType: OHP_9000IData.wheelClosedType }),
            ...(OHP_9000IData.powerChainStatus && { powerChainStatus: OHP_9000IData.powerChainStatus }),
            ...(OHP_9000IData.chainPinStatus && { chainPinStatus: OHP_9000IData.chainPinStatus }),
            ...(OHP_9000IData.catDriveStatus && { catDriveStatus: OHP_9000IData.catDriveStatus }),
            ...(OHP_9000IData.catDriveNum && { catDriveNum: OHP_9000IData.catDriveNum }),
            ...(OHP_9000IData.railLubeStatus && { railLubeStatus: OHP_9000IData.railLubeStatus }),
            ...(OHP_9000IData.externalLubeStatus && { externalLubeStatus: OHP_9000IData.externalLubeStatus }),
            ...(OHP_9000IData.lubeBrand && { lubeBrand: OHP_9000IData.lubeBrand }),
            ...(OHP_9000IData.lubeType && { lubeType: OHP_9000IData.lubeType }),
            ...(OHP_9000IData.lubeViscosity && { lubeViscosity: OHP_9000IData.lubeViscosity }),
            ...(OHP_9000IData.sideLubeStatus && { sideLubeStatus: OHP_9000IData.sideLubeStatus }),
            ...(OHP_9000IData.topLubeStatus && { topLubeStatus: OHP_9000IData.topLubeStatus }),
            ...(OHP_9000IData.chainCleanStatus && { chainCleanStatus: OHP_9000IData.chainCleanStatus }),
            ...(OHP_9000IData.wireMeasurementUnit && { wireMeasurementUnit: OHP_9000IData.wireMeasurementUnit }),
            ...(OHP_9000IData.twoConductor && { twoConductor: OHP_9000IData.twoConductor }),
            ...(OHP_9000IData.fourConductor && { fourConductor: OHP_9000IData.fourConductor }),
            ...(OHP_9000IData.sevenConductor && { sevenConductor: OHP_9000IData.sevenConductor }),
            ...(OHP_9000IData.twelveConductor && { twelveConductor: OHP_9000IData.twelveConductor }),
            ...(OHP_9000IData.junctionBoxNum && { junctionBoxNum: OHP_9000IData.junctionBoxNum }),
            ...(OHP_9000IData.ohpUnitType && { ohpUnitType: OHP_9000IData.ohpUnitType }),
            ...(OHP_9000IData.ohpDiameter && { ohpDiameter: OHP_9000IData.ohpDiameter }),
            ...(OHP_9000IData.ohpWidth && { ohpWidth: OHP_9000IData.ohpWidth }),
            ...(OHP_9000IData.ohpHeight && { ohpHeight: OHP_9000IData.ohpHeight })
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "OHP_9000I"
        });
        await req.user.save();
        return res.status(200).json({ message: "OHP_9000I entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;