const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const OHP_2100I = require("../models/OHP_2100I");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");

 
const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { OHP_2100IData, numRequested } = req.body;
        const order = new OHP_2100I({
            conveyorName: OHP_2100IData.conveyorName,
            chainSize: OHP_2100IData.chainSize,
            ...(OHP_2100IData.otherChainSize && { otherChainSize: OHP_2100IData.otherChainSize }),
            industrialChainManufacturer: OHP_2100IData.industrialChainManufacturer,
            ...(OHP_2100IData.otherChainManufacturer && { otherChainManufacturer: OHP_2100IData.otherChainManufacturer }),
            ...(OHP_2100IData.conveyorLength && { conveyorLength: OHP_2100IData.conveyorLength }),
            ...(OHP_2100IData.conveyorLengthUnit && { conveyorLengthUnit: OHP_2100IData.conveyorLengthUnit }),
            ...(OHP_2100IData.conveyorSpeed && { conveyorSpeed: OHP_2100IData.conveyorSpeed }),
            ...(OHP_2100IData.conveyorSpeedUnit && { conveyorSpeedUnit: OHP_2100IData.conveyorSpeedUnit }),
            ...(OHP_2100IData.conveyorIndex && { conveyorIndex: OHP_2100IData.conveyorIndex }),
            ...(OHP_2100IData.travelDirection && { travelDirection: OHP_2100IData.travelDirection }),
            appEnviroment: OHP_2100IData.appEnviroment,
            ...(OHP_2100IData.ovenStatus && { ovenStatus: OHP_2100IData.ovenStatus }),
            ...(OHP_2100IData.ovenTemp && { ovenTemp: OHP_2100IData.ovenTemp }),
            ...(OHP_2100IData.otherAppEnviroment && { otherAppEnviroment: OHP_2100IData.otherAppEnviroment }),


            pointsOfLube: OHP_2100IData.pointsOfLube,
            conveyorOrientation: OHP_2100IData.conveyorOrientation,
            freeCarrierLube: OHP_2100IData.freeCarrierLube,
            freeCarrierLubePoints: OHP_2100IData.freeCarrierLubePoints,

            ...(OHP_2100IData.surroundingTemp && { surroundingTemp: OHP_2100IData.surroundingTemp }),
            ...(OHP_2100IData.conveyorLoaded && { conveyorLoaded: OHP_2100IData.conveyorLoaded }),
            ...(OHP_2100IData.swingStatus && { swingStatus: OHP_2100IData.swingStatus }),
            ...(OHP_2100IData.operatingVoltSingle && { operatingVoltSingle: OHP_2100IData.operatingVoltSingle }),
            ...(OHP_2100IData.controlVoltSingle && { controlVoltSingle: OHP_2100IData.controlVoltSingle }),
            existingMonitor: OHP_2100IData.existingMonitor,
            newMonitor: OHP_2100IData.newMonitor,
            monitorData: {
                ...(OHP_2100IData.dcuStatus && { dcuStatus: OHP_2100IData.dcuStatus }),
                ...(OHP_2100IData.dcuNum && { dcuNum: OHP_2100IData.dcuNum }),
                ...(OHP_2100IData.existingWindows && { existingWindows: OHP_2100IData.existingWindows }),
                ...(OHP_2100IData.existingHeadUnit && { existingHeadUnit: OHP_2100IData.existingHeadUnit }),
                ...(OHP_2100IData.existingDCU && { existingDCU: OHP_2100IData.existingDCU }),
                ...(OHP_2100IData.existingPowerInterface && { existingPowerInterface: OHP_2100IData.existingPowerInterface }),
                ...(OHP_2100IData.newReservoir && { newReservoir: OHP_2100IData.newReservoir }),
                ...(OHP_2100IData.reservoirSize && { reservoirSize: OHP_2100IData.reservoirSize }),
                ...(OHP_2100IData.otherReservoirSize && { otherReservoirSize: OHP_2100IData.otherReservoirSize }),
                ...(OHP_2100IData.newReservoirNum && { newReservoirNum: OHP_2100IData.newReservoirNum }),
                ...(OHP_2100IData.typeMonitor && { typeMonitor: OHP_2100IData.typeMonitor }),
                ...(OHP_2100IData.driveMotorAmp && { driveMotorAmp: OHP_2100IData.driveMotorAmp }),
                ...(OHP_2100IData.driveMotorAmpNum && { driveMotorAmpNum: OHP_2100IData.driveMotorAmpNum }),
                ...(OHP_2100IData.driveTakeUpAir && { driveTakeUpAir: OHP_2100IData.driveTakeUpAir }),
                ...(OHP_2100IData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_2100IData.driveTakeUpAirNum }),
                ...(OHP_2100IData.takeUpDistance && { takeUpDistance: OHP_2100IData.takeUpDistance }),
                ...(OHP_2100IData.takeUpDistanceNum && { takeUpDistanceNum: OHP_2100IData.takeUpDistanceNum }),
                ...(OHP_2100IData.driveTemp && { driveTemp: OHP_2100IData.driveTemp }),
                ...(OHP_2100IData.driveTempNum && { driveTempNum: OHP_2100IData.driveTempNum }),
                ...(OHP_2100IData.driveVibration && { driveVibration: OHP_2100IData.driveVibration }),
                ...(OHP_2100IData.driveVibrationNum && { driveVibrationNum: OHP_2100IData.driveVibrationNum }),
                ...(OHP_2100IData.dogPitch && { dogPitch: OHP_2100IData.dogPitch }),
                ...(OHP_2100IData.dogPitchNum && { dogPitchNum: OHP_2100IData.dogPitchNum }),
                ...(OHP_2100IData.paintMarker && { paintMarker: OHP_2100IData.paintMarker }),
                ...(OHP_2100IData.paintMarkerNum && { paintMarkerNum: OHP_2100IData.paintMarkerNum }),
                ...(OHP_2100IData.chainVision && { chainVision: OHP_2100IData.chainVision }),
                ...(OHP_2100IData.lubeVision && { lubeVision: OHP_2100IData.lubeVision }),
                ...(OHP_2100IData.trolleyVision && { trolleyVision: OHP_2100IData.trolleyVision }),
                ...(OHP_2100IData.trolleyDetect && { trolleyDetect: OHP_2100IData.trolleyDetect }),
                ...(OHP_2100IData.omniView && { omniView: OHP_2100IData.omniView }),
                ...(OHP_2100IData.dcuUpgradeNum && { dcuUpgradeNum: OHP_2100IData.dcuUpgradeNum }),
                ...(OHP_2100IData.itNameOne && { itNameOne: OHP_2100IData.itNameOne }),
                ...(OHP_2100IData.itIPOne && { itIPOne: OHP_2100IData.itIPOne }),
                ...(OHP_2100IData.itGatewayOne && { itGatewayOne: OHP_2100IData.itGatewayOne }),
                ...(OHP_2100IData.itSubnetOne && { itSubnetOne: OHP_2100IData.itSubnetOne }),
                ...(OHP_2100IData.itDNSOne && { itDNSOne: OHP_2100IData.itDNSOne }),
                ...(OHP_2100IData.itSMTPOne && { itSMTPOne: OHP_2100IData.itSMTPOne }),
                ...(OHP_2100IData.itNameTwo && { itNameTwo: OHP_2100IData.itNameTwo }),
                ...(OHP_2100IData.itIPTwo && { itIPTwo: OHP_2100IData.itIPTwo }),
                ...(OHP_2100IData.itGatewayTwo && { itGatewayTwo: OHP_2100IData.itGatewayTwo }),
                ...(OHP_2100IData.itSubnetTwo && { itSubnetTwo: OHP_2100IData.itSubnetTwo }),
                ...(OHP_2100IData.itDNSTwo && { itDNSTwo: OHP_2100IData.itDNSTwo }),
                ...(OHP_2100IData.itSMTPTwo && { itSMTPTwo: OHP_2100IData.itSMTPTwo }),
                ...(OHP_2100IData.itNameThree && { itNameThree: OHP_2100IData.itNameThree }),
                ...(OHP_2100IData.itIPThree && { itIPThree: OHP_2100IData.itIPThree }),
                ...(OHP_2100IData.itGatewayThree && { itGatewayThree: OHP_2100IData.itGatewayThree }),
                ...(OHP_2100IData.itSubnetThree && { itSubnetThree: OHP_2100IData.itSubnetThree }),
                ...(OHP_2100IData.itDNSThree && { itDNSThree: OHP_2100IData.itDNSThree }),
                ...(OHP_2100IData.itSMTPThree && { itSMTPThree: OHP_2100IData.itSMTPThree }),
                ...(OHP_2100IData.itAdditionalNotes && { itAdditionalNotes: OHP_2100IData.itAdditionalNotes }),
                ...(OHP_2100IData.piuDistance && { piuDistance: OHP_2100IData.piuDistance }),
                ...(OHP_2100IData.switchDistance && { switchDistance: OHP_2100IData.switchDistance }),
                ...(OHP_2100IData.ampPickup && { ampPickup: OHP_2100IData.ampPickup }),
                ...(OHP_2100IData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_2100IData.fromAirTakeUpDistance }),
                ...(OHP_2100IData.specialControllerOptions && { specialControllerOptions: OHP_2100IData.specialControllerOptions }),
                ...(OHP_2100IData.operatingVoltage && { operatingVoltage: OHP_2100IData.operatingVoltage })

            },
            
            addFreeCarrier: OHP_2100IData.addFreeCarrier,

            templateBData: {
                conveyorName: OHP_2100IData.conveyorName,
                industrialChainManufacturer: OHP_2100IData.industrialChainManufacturer,
                ...(OHP_2100IData.otherChainManufacturer && { otherChainManufacturer: OHP_2100IData.otherChainManufacturer }),
                wheelManufacturer: OHP_2100IData.wheelManufacturer,
                ...(OHP_2100IData.wheelManufacturer && { wheelManufacturer: OHP_2100IData.wheelManufacturer}),
                conveyorSpeed: OHP_2100IData.conveyorSpeed,
                conveyorSpeedUnit: OHP_2100IData.conveyorSpeedUnit,
                conveyorIndex: OHP_2100IData.conveyorIndex,
                ...(OHP_2100IData.travelDirection && { travelDirection: OHP_2100IData.travelDirection}),
                appEnviroment: OHP_2100IData.appEnviroment,
                ...(OHP_2100IData.otherAppEnviroment && { otherAppEnviroment: OHP_2100IData.otherAppEnviroment}),
                surroundingTemp: OHP_2100IData.surroundingTemp,
                orientationType: OHP_2100IData.orientationType,
                operatingVoltage: OHP_2100IData.operatingVoltage,
                controlVoltSingle: OHP_2100IData.controlVoltSingle,
                compressedAir: OHP_2100IData.compressedAir,
                ...(OHP_2100IData.airSupplyType && { airSupplyType: OHP_2100IData.airSupplyType}),
            existingMonitor: OHP_2100IData.existingMonitor,
            newMonitor: OHP_2100IData.newMonitor,
            templateA_BData: {
                ...(OHP_2100IData.dcuStatus && { dcuStatus: OHP_2100IData.dcuStatus }),
                ...(OHP_2100IData.dcuNum && { dcuNum: OHP_2100IData.dcuNum }),
                ...(OHP_2100IData.existingWindows && { existingWindows: OHP_2100IData.existingWindows }),
                ...(OHP_2100IData.existingHeadUnit && { existingHeadUnit: OHP_2100IData.existingHeadUnit }),
                ...(OHP_2100IData.existingDCU && { existingDCU: OHP_2100IData.existingDCU }),
                ...(OHP_2100IData.existingPowerInterface && { existingPowerInterface: OHP_2100IData.existingPowerInterface }),
                ...(OHP_2100IData.newReservoir && { newReservoir: OHP_2100IData.newReservoir }),
                ...(OHP_2100IData.reservoirSize && { reservoirSize: OHP_2100IData.reservoirSize }),
                ...(OHP_2100IData.otherReservoirSize && { otherReservoirSize: OHP_2100IData.otherReservoirSize }),
                ...(OHP_2100IData.newReservoirNum && { newReservoirNum: OHP_2100IData.newReservoirNum }),
                ...(OHP_2100IData.typeMonitor && { typeMonitor: OHP_2100IData.typeMonitor }),
                ...(OHP_2100IData.driveMotorAmp && { driveMotorAmp: OHP_2100IData.driveMotorAmp }),
                ...(OHP_2100IData.driveMotorAmpNum && { driveMotorAmpNum: OHP_2100IData.driveMotorAmpNum }),
                ...(OHP_2100IData.driveTakeUpAir && { driveTakeUpAir: OHP_2100IData.driveTakeUpAir }),
                ...(OHP_2100IData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_2100IData.driveTakeUpAirNum }),
                ...(OHP_2100IData.takeUpDistance && { takeUpDistance: OHP_2100IData.takeUpDistance }),
                ...(OHP_2100IData.takeUpDistanceNum && { takeUpDistanceNum: OHP_2100IData.takeUpDistanceNum }),
                ...(OHP_2100IData.driveTemp && { driveTemp: OHP_2100IData.driveTemp }),
                ...(OHP_2100IData.driveTempNum && { driveTempNum: OHP_2100IData.driveTempNum }),
                ...(OHP_2100IData.driveVibration && { driveVibration: OHP_2100IData.driveVibration }),
                ...(OHP_2100IData.driveVibrationNum && { driveVibrationNum: OHP_2100IData.driveVibrationNum }),
                ...(OHP_2100IData.dogPitch && { dogPitch: OHP_2100IData.dogPitch }),
                ...(OHP_2100IData.dogPitchNum && { dogPitchNum: OHP_2100IData.dogPitchNum }),
                ...(OHP_2100IData.paintMarker && { paintMarker: OHP_2100IData.paintMarker }),
                ...(OHP_2100IData.paintMarkerNum && { paintMarkerNum: OHP_2100IData.paintMarkerNum }),
                ...(OHP_2100IData.chainVision && { chainVision: OHP_2100IData.chainVision }),
                ...(OHP_2100IData.lubeVision && { lubeVision: OHP_2100IData.lubeVision }),
                ...(OHP_2100IData.trolleyVision && { trolleyVision: OHP_2100IData.trolleyVision }),
                ...(OHP_2100IData.trolleyDetect && { trolleyDetect: OHP_2100IData.trolleyDetect }),
                ...(OHP_2100IData.omniView && { omniView: OHP_2100IData.omniView }),
                ...(OHP_2100IData.dcuUpgradeNum && { dcuUpgradeNum: OHP_2100IData.dcuUpgradeNum }),
                ...(OHP_2100IData.itNameOne && { itNameOne: OHP_2100IData.itNameOne }),
                ...(OHP_2100IData.itIPOne && { itIPOne: OHP_2100IData.itIPOne }),
                ...(OHP_2100IData.itGatewayOne && { itGatewayOne: OHP_2100IData.itGatewayOne }),
                ...(OHP_2100IData.itSubnetOne && { itSubnetOne: OHP_2100IData.itSubnetOne }),
                ...(OHP_2100IData.itDNSOne && { itDNSOne: OHP_2100IData.itDNSOne }),
                ...(OHP_2100IData.itSMTPOne && { itSMTPOne: OHP_2100IData.itSMTPOne }),
                ...(OHP_2100IData.itNameTwo && { itNameTwo: OHP_2100IData.itNameTwo }),
                ...(OHP_2100IData.itIPTwo && { itIPTwo: OHP_2100IData.itIPTwo }),
                ...(OHP_2100IData.itGatewayTwo && { itGatewayTwo: OHP_2100IData.itGatewayTwo }),
                ...(OHP_2100IData.itSubnetTwo && { itSubnetTwo: OHP_2100IData.itSubnetTwo }),
                ...(OHP_2100IData.itDNSTwo && { itDNSTwo: OHP_2100IData.itDNSTwo }),
                ...(OHP_2100IData.itSMTPTwo && { itSMTPTwo: OHP_2100IData.itSMTPTwo }),
                ...(OHP_2100IData.itNameThree && { itNameThree: OHP_2100IData.itNameThree }),
                ...(OHP_2100IData.itIPThree && { itIPThree: OHP_2100IData.itIPThree }),
                ...(OHP_2100IData.itGatewayThree && { itGatewayThree: OHP_2100IData.itGatewayThree }),
                ...(OHP_2100IData.itSubnetThree && { itSubnetThree: OHP_2100IData.itSubnetThree }),
                ...(OHP_2100IData.itDNSThree && { itDNSThree: OHP_2100IData.itDNSThree }),
                ...(OHP_2100IData.itSMTPThree && { itSMTPThree: OHP_2100IData.itSMTPThree }),
                ...(OHP_2100IData.itAdditionalNotes && { itAdditionalNotes: OHP_2100IData.itAdditionalNotes }),
                ...(OHP_2100IData.piuDistance && { piuDistance: OHP_2100IData.piuDistance }),
                ...(OHP_2100IData.switchDistance && { switchDistance: OHP_2100IData.switchDistance }),
                ...(OHP_2100IData.ampPickup && { ampPickup: OHP_2100IData.ampPickup }),
                ...(OHP_2100IData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_2100IData.fromAirTakeUpDistance }),
                ...(OHP_2100IData.specialControllerOptions && { specialControllerOptions: OHP_2100IData.specialControllerOptions }),
                ...(OHP_2100IData.operatingVoltage && { operatingVoltage: OHP_2100IData.operatingVoltage })

                },
                freeWheelStatus: OHP_2100IData.freeWheelStatus,
                actuatorStatus: OHP_2100IData.actuatorStatus,
                ...(OHP_2100IData.pivotStatus && { pivotStatus: OHP_2100IData.pivotStatus}),
                kingPinStatus: OHP_2100IData.kingPinStatus,
                lubeBrand: OHP_2100IData.lubeBrand,
                lubeViscosity: OHP_2100IData.lubeViscosity,
                ...(OHP_2100IData.lubeType && { lubeType: OHP_2100IData.lubeType}),
                currentGrease: OHP_2100IData.currentGrease,
                currentGreaseGrade: OHP_2100IData.currentGreaseGrade,
                zerkDirection: OHP_2100IData.zerkDirection,
                zerkLocationType: OHP_2100IData.zerkLocationType,
                wheelDiameter: OHP_2100IData.wheelDiameter,
                conveyorSwing: OHP_2100IData.conveyorSwing,
                ...(OHP_2100IData.chainMaster && { lubeType: OHP_2100IData.chainMaster}),
                ...(OHP_2100IData.remoteStatus && { lubeType: OHP_2100IData.remoteStatus}),
                ...(OHP_2100IData.mountStatus && { lubeType: OHP_2100IData.mountStatus}),
                ...(OHP_2100IData.otherUnitStatus && { lubeType: OHP_2100IData.otherUnitStatus}),
                ...(OHP_2100IData.timerStatus && { lubeType: OHP_2100IData.timerStatus}),
                ...(OHP_2100IData.electricStatus && { lubeType: OHP_2100IData.electricStatus}),
                ...(OHP_2100IData.mightyLubeMonitoring && { lubeType: OHP_2100IData.mightyLubeMonitoring}),
                ...(OHP_2100IData.preMountType && { lubeType: OHP_2100IData.preMountType}),
                ...(OHP_2100IData.otherPreMountType && { lubeType: OHP_2100IData.otherPreMountType}),
                ...(OHP_2100IData.plcConnection && { lubeType: OHP_2100IData.plcConnection}),
                ...(OHP_2100IData.otherControllerNotes && { lubeType: OHP_2100IData.otherControllerNotes}),
                ...(OHP_2100IData.templateB_UnitType && { lubeType: OHP_2100IData.templateB_UnitType}),
                ...(OHP_2100IData.templateB_InvertedB && { lubeType: OHP_2100IData.templateB_InvertedB}),
                ...(OHP_2100IData.templateB_InvertedE && { lubeType: OHP_2100IData.templateB_InvertedE}),
                ...(OHP_2100IData.templateB_InvertedG && { lubeType: OHP_2100IData.templateB_InvertedG}),
                ...(OHP_2100IData.templateB_InvertedH && { lubeType: OHP_2100IData.templateB_InvertedH}),
                ...(OHP_2100IData.templateB_InvertedK && { lubeType: OHP_2100IData.templateB_InvertedK}),
                ...(OHP_2100IData.templateB_InvertedT && { lubeType: OHP_2100IData.templateB_InvertedT}),
                ...(OHP_2100IData.templateB_InvertedU && { lubeType: OHP_2100IData.templateB_InvertedU}),
                ...(OHP_2100IData.templateB_InvertedV && { lubeType: OHP_2100IData.templateB_InvertedV}),
                ...(OHP_2100IData.templateB_InvertedW && { lubeType: OHP_2100IData.templateB_InvertedW}),

            },



            templateCData: {
                conveyorName: OHP_2100IData.conveyorName,
                industrialChainManufacturer: OHP_2100IData.industrialChainManufacturer,
                ...(OHP_2100IData.otherChainManufacturer && { otherChainManufacturer: OHP_2100IData.otherChainManufacturer }),
                wheelManufacturer: OHP_2100IData.wheelManufacturer,
                ...(OHP_2100IData.wheelManufacturer && { wheelManufacturer: OHP_2100IData.wheelManufacturer}),
                conveyorSpeed: OHP_2100IData.conveyorSpeed,
                conveyorSpeedUnit: OHP_2100IData.conveyorSpeedUnit,
                conveyorIndex: OHP_2100IData.conveyorIndex,
                ...(OHP_2100IData.travelDirection && { travelDirection: OHP_2100IData.travelDirection}),
                appEnviroment: OHP_2100IData.appEnviroment,
                ...(OHP_2100IData.otherAppEnviroment && { otherAppEnviroment: OHP_2100IData.otherAppEnviroment}),
                surroundingTemp: OHP_2100IData.surroundingTemp,
                orientationType: OHP_2100IData.orientationType,
                guideWheelsEven: OHP_2100IData.guideWheelsEven,
                operatingVoltage: OHP_2100IData.operatingVoltage,
                controlVoltSingle: OHP_2100IData.controlVoltSingle,
                compressedAir: OHP_2100IData.compressedAir,
                ...(OHP_2100IData.airSupplyType && { airSupplyType: OHP_2100IData.airSupplyType}),
                existingMonitor: OHP_2100IData.existingMonitor,
                newMonitor: OHP_2100IData.newMonitor,
                templateA_CData: {
                ...(OHP_2100IData.dcuStatus && { dcuStatus: OHP_2100IData.dcuStatus }),
                ...(OHP_2100IData.dcuNum && { dcuNum: OHP_2100IData.dcuNum }),
                ...(OHP_2100IData.existingWindows && { existingWindows: OHP_2100IData.existingWindows }),
                ...(OHP_2100IData.existingHeadUnit && { existingHeadUnit: OHP_2100IData.existingHeadUnit }),
                ...(OHP_2100IData.existingDCU && { existingDCU: OHP_2100IData.existingDCU }),
                ...(OHP_2100IData.existingPowerInterface && { existingPowerInterface: OHP_2100IData.existingPowerInterface }),
                ...(OHP_2100IData.newReservoir && { newReservoir: OHP_2100IData.newReservoir }),
                ...(OHP_2100IData.reservoirSize && { reservoirSize: OHP_2100IData.reservoirSize }),
                ...(OHP_2100IData.otherReservoirSize && { otherReservoirSize: OHP_2100IData.otherReservoirSize }),
                ...(OHP_2100IData.newReservoirNum && { newReservoirNum: OHP_2100IData.newReservoirNum }),
                ...(OHP_2100IData.typeMonitor && { typeMonitor: OHP_2100IData.typeMonitor }),
                ...(OHP_2100IData.driveMotorAmp && { driveMotorAmp: OHP_2100IData.driveMotorAmp }),
                ...(OHP_2100IData.driveMotorAmpNum && { driveMotorAmpNum: OHP_2100IData.driveMotorAmpNum }),
                ...(OHP_2100IData.driveTakeUpAir && { driveTakeUpAir: OHP_2100IData.driveTakeUpAir }),
                ...(OHP_2100IData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_2100IData.driveTakeUpAirNum }),
                ...(OHP_2100IData.takeUpDistance && { takeUpDistance: OHP_2100IData.takeUpDistance }),
                ...(OHP_2100IData.takeUpDistanceNum && { takeUpDistanceNum: OHP_2100IData.takeUpDistanceNum }),
                ...(OHP_2100IData.driveTemp && { driveTemp: OHP_2100IData.driveTemp }),
                ...(OHP_2100IData.driveTempNum && { driveTempNum: OHP_2100IData.driveTempNum }),
                ...(OHP_2100IData.driveVibration && { driveVibration: OHP_2100IData.driveVibration }),
                ...(OHP_2100IData.driveVibrationNum && { driveVibrationNum: OHP_2100IData.driveVibrationNum }),
                ...(OHP_2100IData.dogPitch && { dogPitch: OHP_2100IData.dogPitch }),
                ...(OHP_2100IData.dogPitchNum && { dogPitchNum: OHP_2100IData.dogPitchNum }),
                ...(OHP_2100IData.paintMarker && { paintMarker: OHP_2100IData.paintMarker }),
                ...(OHP_2100IData.paintMarkerNum && { paintMarkerNum: OHP_2100IData.paintMarkerNum }),
                ...(OHP_2100IData.chainVision && { chainVision: OHP_2100IData.chainVision }),
                ...(OHP_2100IData.lubeVision && { lubeVision: OHP_2100IData.lubeVision }),
                ...(OHP_2100IData.trolleyVision && { trolleyVision: OHP_2100IData.trolleyVision }),
                ...(OHP_2100IData.trolleyDetect && { trolleyDetect: OHP_2100IData.trolleyDetect }),
                ...(OHP_2100IData.omniView && { omniView: OHP_2100IData.omniView }),
                ...(OHP_2100IData.dcuUpgradeNum && { dcuUpgradeNum: OHP_2100IData.dcuUpgradeNum }),
                ...(OHP_2100IData.itNameOne && { itNameOne: OHP_2100IData.itNameOne }),
                ...(OHP_2100IData.itIPOne && { itIPOne: OHP_2100IData.itIPOne }),
                ...(OHP_2100IData.itGatewayOne && { itGatewayOne: OHP_2100IData.itGatewayOne }),
                ...(OHP_2100IData.itSubnetOne && { itSubnetOne: OHP_2100IData.itSubnetOne }),
                ...(OHP_2100IData.itDNSOne && { itDNSOne: OHP_2100IData.itDNSOne }),
                ...(OHP_2100IData.itSMTPOne && { itSMTPOne: OHP_2100IData.itSMTPOne }),
                ...(OHP_2100IData.itNameTwo && { itNameTwo: OHP_2100IData.itNameTwo }),
                ...(OHP_2100IData.itIPTwo && { itIPTwo: OHP_2100IData.itIPTwo }),
                ...(OHP_2100IData.itGatewayTwo && { itGatewayTwo: OHP_2100IData.itGatewayTwo }),
                ...(OHP_2100IData.itSubnetTwo && { itSubnetTwo: OHP_2100IData.itSubnetTwo }),
                ...(OHP_2100IData.itDNSTwo && { itDNSTwo: OHP_2100IData.itDNSTwo }),
                ...(OHP_2100IData.itSMTPTwo && { itSMTPTwo: OHP_2100IData.itSMTPTwo }),
                ...(OHP_2100IData.itNameThree && { itNameThree: OHP_2100IData.itNameThree }),
                ...(OHP_2100IData.itIPThree && { itIPThree: OHP_2100IData.itIPThree }),
                ...(OHP_2100IData.itGatewayThree && { itGatewayThree: OHP_2100IData.itGatewayThree }),
                ...(OHP_2100IData.itSubnetThree && { itSubnetThree: OHP_2100IData.itSubnetThree }),
                ...(OHP_2100IData.itDNSThree && { itDNSThree: OHP_2100IData.itDNSThree }),
                ...(OHP_2100IData.itSMTPThree && { itSMTPThree: OHP_2100IData.itSMTPThree }),
                ...(OHP_2100IData.itAdditionalNotes && { itAdditionalNotes: OHP_2100IData.itAdditionalNotes }),
                ...(OHP_2100IData.piuDistance && { piuDistance: OHP_2100IData.piuDistance }),
                ...(OHP_2100IData.switchDistance && { switchDistance: OHP_2100IData.switchDistance }),
                ...(OHP_2100IData.ampPickup && { ampPickup: OHP_2100IData.ampPickup }),
                ...(OHP_2100IData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_2100IData.fromAirTakeUpDistance }),
                ...(OHP_2100IData.specialControllerOptions && { specialControllerOptions: OHP_2100IData.specialControllerOptions }),
                ...(OHP_2100IData.operatingVoltage && { operatingVoltage: OHP_2100IData.operatingVoltage })

                },
                freeWheelStatus: OHP_2100IData.freeWheelStatus,
                actuatorStatus: OHP_2100IData.actuatorStatus,
                ...(OHP_2100IData.pivotStatus && { pivotStatus: OHP_2100IData.pivotStatus}),
                kingPinStatus: OHP_2100IData.kingPinStatus,
                lubeBrand: OHP_2100IData.lubeBrand,
                lubeViscosity: OHP_2100IData.lubeViscosity,
                ...(OHP_2100IData.lubeType && { lubeType: OHP_2100IData.lubeType}),
                currentGrease: OHP_2100IData.currentGrease,
                currentGreaseGrade: OHP_2100IData.currentGreaseGrade,
                zerkDirection: OHP_2100IData.zerkDirection,
                zerkLocationType: OHP_2100IData.zerkLocationType,
                wheelDiameter: OHP_2100IData.wheelDiameter,
                conveyorSwing: OHP_2100IData.conveyorSwing,
                ...(OHP_2100IData.chainMaster && { lubeType: OHP_2100IData.chainMaster}),
                ...(OHP_2100IData.remoteStatus && { lubeType: OHP_2100IData.remoteStatus}),
                ...(OHP_2100IData.mountStatus && { lubeType: OHP_2100IData.mountStatus}),
                ...(OHP_2100IData.otherUnitStatus && { lubeType: OHP_2100IData.otherUnitStatus}),
                ...(OHP_2100IData.timerStatus && { lubeType: OHP_2100IData.timerStatus}),
                ...(OHP_2100IData.electricStatus && { lubeType: OHP_2100IData.electricStatus}),
                ...(OHP_2100IData.mightyLubeMonitoring && { lubeType: OHP_2100IData.mightyLubeMonitoring}),
                ...(OHP_2100IData.preMountType && { lubeType: OHP_2100IData.preMountType}),
                ...(OHP_2100IData.otherPreMountType && { lubeType: OHP_2100IData.otherPreMountType}),
                ...(OHP_2100IData.plcConnection && { lubeType: OHP_2100IData.plcConnection}),
                ...(OHP_2100IData.otherControllerNotes && { lubeType: OHP_2100IData.otherControllerNotes}),
                ...(OHP_2100IData.templateC_UnitType && { lubeType: OHP_2100IData.templateC_UnitType}),
                templateC_InvertedA: OHP_2100IData.templateC_InvertedA,
                templateC_InvertedB: OHP_2100IData.templateC_InvertedB,
                templateC_InvertedE: OHP_2100IData.templateC_InvertedE,
                templateC_InvertedS: OHP_2100IData.templateC_InvertedS,
            },
            ...(OHP_2100IData.wheelClosedType && { wheelClosedType: OHP_2100IData.wheelClosedType }),
            ...(OHP_2100IData.catDriveStatus && { catDriveStatus: OHP_2100IData.catDriveStatus }),
            ...(OHP_2100IData.catDriveNum && { catDriveNum: OHP_2100IData.catDriveNum }),
            ...(OHP_2100IData.railLubeStatus && { railLubeStatus: OHP_2100IData.railLubeStatus }),
            ...(OHP_2100IData.externalLubeStatus && { externalLubeStatus: OHP_2100IData.externalLubeStatus }),
            ...(OHP_2100IData.lubeBrand && { lubeBrand: OHP_2100IData.lubeBrand }),
            ...(OHP_2100IData.lubeType && { lubeType: OHP_2100IData.lubeType }),
            ...(OHP_2100IData.lubeViscosity && { lubeViscosity: OHP_2100IData.lubeViscosity }),
            ...(OHP_2100IData.sideLubeStatus && { sideLubeStatus: OHP_2100IData.sideLubeStatus }),
            ...(OHP_2100IData.topLubeStatus && { topLubeStatus: OHP_2100IData.topLubeStatus }),
            ...(OHP_2100IData.chainCleanStatus && { chainCleanStatus: OHP_2100IData.chainCleanStatus }),
            ...(OHP_2100IData.wireMeasurementUnit && { wireMeasurementUnit: OHP_2100IData.wireMeasurementUnit }),
            ...(OHP_2100IData.twoConductor && { twoConductor: OHP_2100IData.twoConductor }),
            ...(OHP_2100IData.fourConductor && { fourConductor: OHP_2100IData.fourConductor }),
            ...(OHP_2100IData.sevenConductor && { sevenConductor: OHP_2100IData.sevenConductor }),
            ...(OHP_2100IData.twelveConductor && { twelveConductor: OHP_2100IData.twelveConductor }),
            ...(OHP_2100IData.junctionBoxNum && { junctionBoxNum: OHP_2100IData.junctionBoxNum }),
            ...(OHP_2100IData.ohpUnitType && { ohpUnitType: OHP_2100IData.ohpUnitType }),
            ...(OHP_2100IData.ohpDiameter && { ohpDiameter: OHP_2100IData.ohpDiameter }),
            ...(OHP_2100IData.ohpWidth && { ohpWidth: OHP_2100IData.ohpWidth }),
            ...(OHP_2100IData.ohpHeight && { ohpHeight: OHP_2100IData.ohpHeight })
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "OHP_2100I"
        });
        await req.user.save();
        return res.status(200).json({ message: "OHP_2100I entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;