const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const OHP_2100I = require("../models/OHP_2100I");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");

 
const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { OHP_2100IData, numRequested } = req.body;
        const order = new OHP_2100I({
            conveyorName: OHP_2100IData.conveyorName,
            chainSize: OHP_2100IData.chainSize,
            ...(OHP_2100IData.otherChainSize && { otherChainSize: OHP_2100IData.otherChainSize }),
            industrialChainManufacturer: OHP_2100IData.industrialChainManufacturer,
            ...(OHP_2100IData.otherChainManufacturer && { otherChainManufacturer: OHP_2100IData.otherChainManufacturer }),
            ...(OHP_2100IData.conveyorLength && { conveyorLength: OHP_2100IData.conveyorLength }),
            ...(OHP_2100IData.conveyorLengthUnit && { conveyorLengthUnit: OHP_2100IData.conveyorLengthUnit }),
            ...(OHP_2100IData.conveyorSpeed && { conveyorSpeed: OHP_2100IData.conveyorSpeed }),
            ...(OHP_2100IData.conveyorSpeedUnit && { conveyorSpeedUnit: OHP_2100IData.conveyorSpeedUnit }),
            ...(OHP_2100IData.conveyorIndex && { conveyorIndex: OHP_2100IData.conveyorIndex }),
            ...(OHP_2100IData.travelDirection && { travelDirection: OHP_2100IData.travelDirection }),
            appEnviroment: OHP_2100IData.appEnviroment,
            ...(OHP_2100IData.ovenStatus && { ovenStatus: OHP_2100IData.ovenStatus }),
            ...(OHP_2100IData.ovenTemp && { ovenTemp: OHP_2100IData.ovenTemp }),
            ...(OHP_2100IData.otherAppEnviroment && { otherAppEnviroment: OHP_2100IData.otherAppEnviroment }),


            pointsOfLube: OHP_2100IData.pointsOfLube,
            conveyorOrientation: OHP_2100IData.conveyorOrientation,
            freeCarrierLube: OHP_2100IData.freeCarrierLube,
            freeCarrierLubePoints: OHP_2100IData.freeCarrierLubePoints,

            ...(OHP_2100IData.surroundingTemp && { surroundingTemp: OHP_2100IData.surroundingTemp }),
            ...(OHP_2100IData.conveyorLoaded && { conveyorLoaded: OHP_2100IData.conveyorLoaded }),
            ...(OHP_2100IData.swingStatus && { swingStatus: OHP_2100IData.swingStatus }),
            ...(OHP_2100IData.operatingVoltSingle && { operatingVoltSingle: OHP_2100IData.operatingVoltSingle }),
            ...(OHP_2100IData.controlVoltSingle && { controlVoltSingle: OHP_2100IData.controlVoltSingle }),
            monitorData: 
            {
                existingMonitor: OHP_2100IData.templateA.existingMonitor,
                newMonitor: OHP_2100IData.templateA.newMonitor,		
                ...(OHP_2100IData.templateA.dcuStatus && { dcuStatus: OHP_2100IData.templateA.dcuStatus }),
                ...(OHP_2100IData.templateA.dcuNum && { dcuNum: OHP_2100IData.templateA.dcuNum }),
                ...(OHP_2100IData.templateA.existingWindows && { existingWindows: OHP_2100IData.templateA.existingWindows }),
                ...(OHP_2100IData.templateA.existingHeadUnit && { existingHeadUnit: OHP_2100IData.templateA.existingHeadUnit }),
                ...(OHP_2100IData.templateA.existingDCU && { existingDCU: OHP_2100IData.templateA.existingDCU }),
                ...(OHP_2100IData.templateA.existingPowerInterface && { existingPowerInterface: OHP_2100IData.templateA.existingPowerInterface }),
                ...(OHP_2100IData.templateA.newReservoir && { newReservoir: OHP_2100IData.templateA.newReservoir }),
                ...(OHP_2100IData.templateA.reservoirSize && { reservoirSize: OHP_2100IData.templateA.reservoirSize }),
                ...(OHP_2100IData.templateA.otherReservoirSize && { otherReservoirSize: OHP_2100IData.templateA.otherReservoirSize }),
                ...(OHP_2100IData.templateA.newReservoirNum && { newReservoirNum: OHP_2100IData.templateA.newReservoirNum }),
                ...(OHP_2100IData.templateA.typeMonitor && { typeMonitor: OHP_2100IData.templateA.typeMonitor }),
                ...(OHP_2100IData.templateA.driveMotorAmp && { driveMotorAmp: OHP_2100IData.templateA.driveMotorAmp }),
                ...(OHP_2100IData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_2100IData.templateA.driveMotorAmpNum }),
                ...(OHP_2100IData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_2100IData.templateA.driveTakeUpAir }),
                ...(OHP_2100IData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_2100IData.templateA.driveTakeUpAirNum }),
                ...(OHP_2100IData.templateA.takeUpDistance && { takeUpDistance: OHP_2100IData.templateA.takeUpDistance }),
                ...(OHP_2100IData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_2100IData.templateA.takeUpDistanceNum }),
                ...(OHP_2100IData.templateA.driveTemp && { driveTemp: OHP_2100IData.templateA.driveTemp }),
                ...(OHP_2100IData.templateA.driveTempNum && { driveTempNum: OHP_2100IData.templateA.driveTempNum }),
                ...(OHP_2100IData.templateA.driveVibration && { driveVibration: OHP_2100IData.templateA.driveVibration }),
                ...(OHP_2100IData.templateA.driveVibrationNum && { driveVibrationNum: OHP_2100IData.templateA.driveVibrationNum }),
                ...(OHP_2100IData.templateA.dogPitch && { dogPitch: OHP_2100IData.templateA.dogPitch }),
                ...(OHP_2100IData.templateA.dogPitchNum && { dogPitchNum: OHP_2100IData.templateA.dogPitchNum }),
                ...(OHP_2100IData.templateA.paintMarker && { paintMarker: OHP_2100IData.templateA.paintMarker }),
                ...(OHP_2100IData.templateA.paintMarkerNum && { paintMarkerNum: OHP_2100IData.templateA.paintMarkerNum }),
                ...(OHP_2100IData.templateA.chainVision && { chainVision: OHP_2100IData.templateA.chainVision }),
                ...(OHP_2100IData.templateA.lubeVision && { lubeVision: OHP_2100IData.templateA.lubeVision }),
                ...(OHP_2100IData.templateA.trolleyVision && { trolleyVision: OHP_2100IData.templateA.trolleyVision }),
                ...(OHP_2100IData.templateA.trolleyDetect && { trolleyDetect: OHP_2100IData.templateA.trolleyDetect }),
                ...(OHP_2100IData.templateA.omniView && { omniView: OHP_2100IData.templateA.omniView }),
                ...(OHP_2100IData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_2100IData.templateA.dcuUpgradeNum }),
                ...(OHP_2100IData.templateA.piuDistance && { piuDistance: OHP_2100IData.templateA.piuDistance }),
                ...(OHP_2100IData.templateA.switchDistance && { switchDistance: OHP_2100IData.templateA.switchDistance }),
                ...(OHP_2100IData.templateA.ampPickup && { ampPickup: OHP_2100IData.templateA.ampPickup }),
                ...(OHP_2100IData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_2100IData.templateA.fromAirTakeUpDistance }),
                ...(OHP_2100IData.templateA.specialControllerOptions && { specialControllerOptions: OHP_2100IData.templateA.specialControllerOptions }),
                ...(OHP_2100IData.templateA.operatingVoltage && { operatingVoltage: OHP_2100IData.templateA.operatingVoltage })
            },          
            
            addFreeCarrier: OHP_2100IData.addFreeCarrier,

            templateBData: 
            {
                
                conveyorName: OHP_2100IData.templateB.conveyorName,
                industrialChainManufacturer: OHP_2100IData.templateB.industrialChainManufacturer,
                ...(OHP_2100IData.templateB.otherChainManufacturer && { otherChainManufacturer: OHP_2100IData.templateB.otherChainManufacturer }),
                wheelManufacturer: OHP_2100IData.templateB.wheelManufacturer,
                ...(OHP_2100IData.templateB.wheelManufacturer && { wheelManufacturer: OHP_2100IData.templateB.wheelManufacturer}),
                conveyorSpeed: OHP_2100IData.templateB.conveyorSpeed,
                conveyorSpeedUnit: OHP_2100IData.templateB.conveyorSpeedUnit,
                conveyorIndex: OHP_2100IData.templateB.conveyorIndex,
                ...(OHP_2100IData.templateB.travelDirection && { travelDirection: OHP_2100IData.templateB.travelDirection}),
                appEnviroment: OHP_2100IData.templateB.appEnviroment,
                ...(OHP_2100IData.templateB.otherAppEnviroment && { otherAppEnviroment: OHP_2100IData.templateB.otherAppEnviroment}),
                surroundingTemp: OHP_2100IData.templateB.surroundingTemp,
                orientationType: OHP_2100IData.templateB.orientationType,
                operatingVoltage: OHP_2100IData.templateB.operatingVoltage,
                controlVoltSingle: OHP_2100IData.templateB.controlVoltSingle,
                compressedAir: OHP_2100IData.templateB.compressedAir,
                ...(OHP_2100IData.templateB.airSupplyType && { airSupplyType: OHP_2100IData.templateB.airSupplyType}),

                templateA_BData: {
                    
                    existingMonitor: OHP_2100IData.templateA.existingMonitor,
                    newMonitor: OHP_2100IData.templateA.newMonitor,		
                    ...(OHP_2100IData.templateA.dcuStatus && { dcuStatus: OHP_2100IData.templateA.dcuStatus }),
                    ...(OHP_2100IData.templateA.dcuNum && { dcuNum: OHP_2100IData.templateA.dcuNum }),
                    ...(OHP_2100IData.templateA.existingWindows && { existingWindows: OHP_2100IData.templateA.existingWindows }),
                    ...(OHP_2100IData.templateA.existingHeadUnit && { existingHeadUnit: OHP_2100IData.templateA.existingHeadUnit }),
                    ...(OHP_2100IData.templateA.existingDCU && { existingDCU: OHP_2100IData.templateA.existingDCU }),
                    ...(OHP_2100IData.templateA.existingPowerInterface && { existingPowerInterface: OHP_2100IData.templateA.existingPowerInterface }),
                    ...(OHP_2100IData.templateA.newReservoir && { newReservoir: OHP_2100IData.templateA.newReservoir }),
                    ...(OHP_2100IData.templateA.reservoirSize && { reservoirSize: OHP_2100IData.templateA.reservoirSize }),
                    ...(OHP_2100IData.templateA.otherReservoirSize && { otherReservoirSize: OHP_2100IData.templateA.otherReservoirSize }),
                    ...(OHP_2100IData.templateA.newReservoirNum && { newReservoirNum: OHP_2100IData.templateA.newReservoirNum }),
                    ...(OHP_2100IData.templateA.typeMonitor && { typeMonitor: OHP_2100IData.templateA.typeMonitor }),
                    ...(OHP_2100IData.templateA.driveMotorAmp && { driveMotorAmp: OHP_2100IData.templateA.driveMotorAmp }),
                    ...(OHP_2100IData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_2100IData.templateA.driveMotorAmpNum }),
                    ...(OHP_2100IData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_2100IData.templateA.driveTakeUpAir }),
                    ...(OHP_2100IData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_2100IData.templateA.driveTakeUpAirNum }),
                    ...(OHP_2100IData.templateA.takeUpDistance && { takeUpDistance: OHP_2100IData.templateA.takeUpDistance }),
                    ...(OHP_2100IData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_2100IData.templateA.takeUpDistanceNum }),
                    ...(OHP_2100IData.templateA.driveTemp && { driveTemp: OHP_2100IData.templateA.driveTemp }),
                    ...(OHP_2100IData.templateA.driveTempNum && { driveTempNum: OHP_2100IData.templateA.driveTempNum }),
                    ...(OHP_2100IData.templateA.driveVibration && { driveVibration: OHP_2100IData.templateA.driveVibration }),
                    ...(OHP_2100IData.templateA.driveVibrationNum && { driveVibrationNum: OHP_2100IData.templateA.driveVibrationNum }),
                    ...(OHP_2100IData.templateA.dogPitch && { dogPitch: OHP_2100IData.templateA.dogPitch }),
                    ...(OHP_2100IData.templateA.dogPitchNum && { dogPitchNum: OHP_2100IData.templateA.dogPitchNum }),
                    ...(OHP_2100IData.templateA.paintMarker && { paintMarker: OHP_2100IData.templateA.paintMarker }),
                    ...(OHP_2100IData.templateA.paintMarkerNum && { paintMarkerNum: OHP_2100IData.templateA.paintMarkerNum }),
                    ...(OHP_2100IData.templateA.chainVision && { chainVision: OHP_2100IData.templateA.chainVision }),
                    ...(OHP_2100IData.templateA.lubeVision && { lubeVision: OHP_2100IData.templateA.lubeVision }),
                    ...(OHP_2100IData.templateA.trolleyVision && { trolleyVision: OHP_2100IData.templateA.trolleyVision }),
                    ...(OHP_2100IData.templateA.trolleyDetect && { trolleyDetect: OHP_2100IData.templateA.trolleyDetect }),
                    ...(OHP_2100IData.templateA.omniView && { omniView: OHP_2100IData.templateA.omniView }),
                    ...(OHP_2100IData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_2100IData.templateA.dcuUpgradeNum }),
                    ...(OHP_2100IData.templateA.piuDistance && { piuDistance: OHP_2100IData.templateA.piuDistance }),
                    ...(OHP_2100IData.templateA.switchDistance && { switchDistance: OHP_2100IData.templateA.switchDistance }),
                    ...(OHP_2100IData.templateA.ampPickup && { ampPickup: OHP_2100IData.templateA.ampPickup }),
                    ...(OHP_2100IData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_2100IData.templateA.fromAirTakeUpDistance }),
                    ...(OHP_2100IData.templateA.specialControllerOptions && { specialControllerOptions: OHP_2100IData.templateA.specialControllerOptions }),
                    ...(OHP_2100IData.templateA.operatingVoltage && { operatingVoltage: OHP_2100IData.templateA.operatingVoltage })

                },

                freeWheelStatus: OHP_2100IData.templateB.freeWheelStatus,
                actuatorStatus: OHP_2100IData.templateB.actuatorStatus,
                ...(OHP_2100IData.templateB.pivotStatus && { pivotStatus: OHP_2100IData.templateB.pivotStatus}),
                kingPinStatus: OHP_2100IData.templateB.kingPinStatus,
                lubeBrand: OHP_2100IData.templateB.lubeBrand,
                lubeViscosity: OHP_2100IData.templateB.lubeViscosity,
                ...(OHP_2100IData.templateB.lubeType && { lubeType: OHP_2100IData.templateB.lubeType}),
                currentGrease: OHP_2100IData.templateB.currentGrease,
                currentGreaseGrade: OHP_2100IData.templateB.currentGreaseGrade,
                zerkDirection: OHP_2100IData.templateB.zerkDirection,
                zerkLocationType: OHP_2100IData.templateB.zerkLocationType,
                wheelDiameter: OHP_2100IData.templateB.wheelDiameter,
                conveyorSwing: OHP_2100IData.templateB.conveyorSwing,
                ...(OHP_2100IData.templateB.chainMaster && { chainMaster: OHP_2100IData.templateB.chainMaster}),
                ...(OHP_2100IData.templateB.remoteStatus && { remoteStatus: OHP_2100IData.templateB.remoteStatus}),
                ...(OHP_2100IData.templateB.mountStatus && { mountStatus: OHP_2100IData.templateB.mountStatus}),
                ...(OHP_2100IData.templateB.otherUnitStatus && { otherUnitStatus: OHP_2100IData.templateB.otherUnitStatus}),
                ...(OHP_2100IData.templateB.timerStatus && { timerStatus: OHP_2100IData.templateB.timerStatus}),
                ...(OHP_2100IData.templateB.electricStatus && { electricStatus: OHP_2100IData.templateB.electricStatus}),
                ...(OHP_2100IData.templateB.mightyLubeMonitoring && { mightyLubeMonitoring: OHP_2100IData.templateB.mightyLubeMonitoring}),
                ...(OHP_2100IData.templateB.preMountType && { preMountType: OHP_2100IData.templateB.preMountType}),
                ...(OHP_2100IData.templateB.otherPreMountType && { otherPreMountType: OHP_2100IData.templateB.otherPreMountType}),
                ...(OHP_2100IData.templateB.plcConnection && { plcConnection: OHP_2100IData.templateB.plcConnection}),
                ...(OHP_2100IData.templateB.otherControllerNotes && { otherControllerNotes: OHP_2100IData.templateB.otherControllerNotes}),
                ...(OHP_2100IData.templateB.templateB_UnitType && { templateB_UnitType: OHP_2100IData.templateB.templateB_UnitType}),
                ...(OHP_2100IData.templateB.templateB_InvertedB && { templateB_InvertedB: OHP_2100IData.templateB.templateB_InvertedB}),
                ...(OHP_2100IData.templateB.templateB_InvertedE && { templateB_InvertedE: OHP_2100IData.templateB.templateB_InvertedE}),
                ...(OHP_2100IData.templateB.templateB_InvertedG && { templateB_InvertedG: OHP_2100IData.templateB.templateB_InvertedG}),
                ...(OHP_2100IData.templateB.templateB_InvertedH && { templateB_InvertedH: OHP_2100IData.templateB.templateB_InvertedH}),
                ...(OHP_2100IData.templateB.templateB_InvertedK && { templateB_InvertedK: OHP_2100IData.templateB.templateB_InvertedK}),
                ...(OHP_2100IData.templateB.templateB_InvertedT && { templateB_InvertedT: OHP_2100IData.templateB.templateB_InvertedT}),
                ...(OHP_2100IData.templateB.templateB_InvertedU && { templateB_InvertedU: OHP_2100IData.templateB.templateB_InvertedU}),
                ...(OHP_2100IData.templateB.templateB_InvertedV && { templateB_InvertedV: OHP_2100IData.templateB.templateB_InvertedV}),
                ...(OHP_2100IData.templateB.templateB_InvertedW && { templateB_InvertedW: OHP_2100IData.templateB.templateB_InvertedW}),

            },


            templateCData: 
            {
            conveyorName: OHP_2100IData.templateC.conveyorName,
            industrialChainManufacturer: OHP_2100IData.templateC.industrialChainManufacturer,
            ...(OHP_2100IData.templateC.otherChainManufacturer && { otherChainManufacturer: OHP_2100IData.templateC.otherChainManufacturer }),
            wheelManufacturer: OHP_2100IData.templateC.wheelManufacturer,
            ...(OHP_2100IData.templateC.wheelManufacturer && { wheelManufacturer: OHP_2100IData.templateC.wheelManufacturer}),
            conveyorSpeed: OHP_2100IData.templateC.conveyorSpeed,
            conveyorSpeedUnit: OHP_2100IData.templateC.conveyorSpeedUnit,
            conveyorIndex: OHP_2100IData.templateC.conveyorIndex,
            ...(OHP_2100IData.templateC.travelDirection && { travelDirection: OHP_2100IData.templateC.travelDirection}),
            appEnviroment: OHP_2100IData.templateC.appEnviroment,
            ...(OHP_2100IData.templateC.otherAppEnviroment && { otherAppEnviroment: OHP_2100IData.templateC.otherAppEnviroment}),
            surroundingTemp: OHP_2100IData.templateC.surroundingTemp,
            orientationType: OHP_2100IData.templateC.orientationType,
            guideWheelsEven: OHP_2100IData.templateC.guideWheelsEven,
            operatingVoltage: OHP_2100IData.templateC.operatingVoltage,
            controlVoltSingle: OHP_2100IData.templateC.controlVoltSingle,
            compressedAir: OHP_2100IData.templateC.compressedAir,
            ...(OHP_2100IData.templateC.airSupplyType && { airSupplyType: OHP_2100IData.templateC.airSupplyType}),

            templateA_CData: 
            {
                existingMonitor: OHP_2100IData.templateA.existingMonitor,
                newMonitor: OHP_2100IData.templateA.newMonitor,		
                ...(OHP_2100IData.templateA.dcuStatus && { dcuStatus: OHP_2100IData.templateA.dcuStatus }),
                ...(OHP_2100IData.templateA.dcuNum && { dcuNum: OHP_2100IData.templateA.dcuNum }),
                ...(OHP_2100IData.templateA.existingWindows && { existingWindows: OHP_2100IData.templateA.existingWindows }),
                ...(OHP_2100IData.templateA.existingHeadUnit && { existingHeadUnit: OHP_2100IData.templateA.existingHeadUnit }),
                ...(OHP_2100IData.templateA.existingDCU && { existingDCU: OHP_2100IData.templateA.existingDCU }),
                ...(OHP_2100IData.templateA.existingPowerInterface && { existingPowerInterface: OHP_2100IData.templateA.existingPowerInterface }),
                ...(OHP_2100IData.templateA.newReservoir && { newReservoir: OHP_2100IData.templateA.newReservoir }),
                ...(OHP_2100IData.templateA.reservoirSize && { reservoirSize: OHP_2100IData.templateA.reservoirSize }),
                ...(OHP_2100IData.templateA.otherReservoirSize && { otherReservoirSize: OHP_2100IData.templateA.otherReservoirSize }),
                ...(OHP_2100IData.templateA.newReservoirNum && { newReservoirNum: OHP_2100IData.templateA.newReservoirNum }),
                ...(OHP_2100IData.templateA.typeMonitor && { typeMonitor: OHP_2100IData.templateA.typeMonitor }),
                ...(OHP_2100IData.templateA.driveMotorAmp && { driveMotorAmp: OHP_2100IData.templateA.driveMotorAmp }),
                ...(OHP_2100IData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_2100IData.templateA.driveMotorAmpNum }),
                ...(OHP_2100IData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_2100IData.templateA.driveTakeUpAir }),
                ...(OHP_2100IData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_2100IData.templateA.driveTakeUpAirNum }),
                ...(OHP_2100IData.templateA.takeUpDistance && { takeUpDistance: OHP_2100IData.templateA.takeUpDistance }),
                ...(OHP_2100IData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_2100IData.templateA.takeUpDistanceNum }),
                ...(OHP_2100IData.templateA.driveTemp && { driveTemp: OHP_2100IData.templateA.driveTemp }),
                ...(OHP_2100IData.templateA.driveTempNum && { driveTempNum: OHP_2100IData.templateA.driveTempNum }),
                ...(OHP_2100IData.templateA.driveVibration && { driveVibration: OHP_2100IData.templateA.driveVibration }),
                ...(OHP_2100IData.templateA.driveVibrationNum && { driveVibrationNum: OHP_2100IData.templateA.driveVibrationNum }),
                ...(OHP_2100IData.templateA.dogPitch && { dogPitch: OHP_2100IData.templateA.dogPitch }),
                ...(OHP_2100IData.templateA.dogPitchNum && { dogPitchNum: OHP_2100IData.templateA.dogPitchNum }),
                ...(OHP_2100IData.templateA.paintMarker && { paintMarker: OHP_2100IData.templateA.paintMarker }),
                ...(OHP_2100IData.templateA.paintMarkerNum && { paintMarkerNum: OHP_2100IData.templateA.paintMarkerNum }),
                ...(OHP_2100IData.templateA.chainVision && { chainVision: OHP_2100IData.templateA.chainVision }),
                ...(OHP_2100IData.templateA.lubeVision && { lubeVision: OHP_2100IData.templateA.lubeVision }),
                ...(OHP_2100IData.templateA.trolleyVision && { trolleyVision: OHP_2100IData.templateA.trolleyVision }),
                ...(OHP_2100IData.templateA.trolleyDetect && { trolleyDetect: OHP_2100IData.templateA.trolleyDetect }),
                ...(OHP_2100IData.templateA.omniView && { omniView: OHP_2100IData.templateA.omniView }),
                ...(OHP_2100IData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_2100IData.templateA.dcuUpgradeNum }),
                ...(OHP_2100IData.templateA.piuDistance && { piuDistance: OHP_2100IData.templateA.piuDistance }),
                ...(OHP_2100IData.templateA.switchDistance && { switchDistance: OHP_2100IData.templateA.switchDistance }),
                ...(OHP_2100IData.templateA.ampPickup && { ampPickup: OHP_2100IData.templateA.ampPickup }),
                ...(OHP_2100IData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_2100IData.templateA.fromAirTakeUpDistance }),
                ...(OHP_2100IData.templateA.specialControllerOptions && { specialControllerOptions: OHP_2100IData.templateA.specialControllerOptions }),
                ...(OHP_2100IData.templateA.operatingVoltage && { operatingVoltage: OHP_2100IData.templateA.operatingVoltage })
            },
            
            freeWheelStatus: OHP_2100IData.templateC.freeWheelStatus,
            actuatorStatus: OHP_2100IData.templateC.actuatorStatus,
            ...(OHP_2100IData.templateC.pivotStatus && { pivotStatus: OHP_2100IData.templateC.pivotStatus}),
            kingPinStatus: OHP_2100IData.templateC.kingPinStatus,
            lubeBrand: OHP_2100IData.templateC.lubeBrand,
            lubeViscosity: OHP_2100IData.templateC.lubeViscosity,
            ...(OHP_2100IData.templateC.lubeType && { lubeType: OHP_2100IData.templateC.lubeType}),
            currentGrease: OHP_2100IData.templateC.currentGrease,
            currentGreaseGrade: OHP_2100IData.templateC.currentGreaseGrade,
            zerkDirection: OHP_2100IData.templateC.zerkDirection,
            zerkLocationType: OHP_2100IData.templateC.zerkLocationType,
            wheelDiameter: OHP_2100IData.templateC.wheelDiameter,
            conveyorSwing: OHP_2100IData.templateC.conveyorSwing,
            ...(OHP_2100IData.templateC.chainMaster && { lubeType: OHP_2100IData.templateC.chainMaster}),
            ...(OHP_2100IData.templateC.remoteStatus && { lubeType: OHP_2100IData.templateC.remoteStatus}),
            ...(OHP_2100IData.templateC.mountStatus && { lubeType: OHP_2100IData.templateC.mountStatus}),
            ...(OHP_2100IData.templateC.otherUnitStatus && { lubeType: OHP_2100IData.templateC.otherUnitStatus}),
            ...(OHP_2100IData.templateC.timerStatus && { lubeType: OHP_2100IData.templateC.timerStatus}),
            ...(OHP_2100IData.templateC.electricStatus && { lubeType: OHP_2100IData.templateC.electricStatus}),
            ...(OHP_2100IData.templateC.mightyLubeMonitoring && { lubeType: OHP_2100IData.templateC.mightyLubeMonitoring}),
            ...(OHP_2100IData.templateC.preMountType && { lubeType: OHP_2100IData.templateC.preMountType}),
            ...(OHP_2100IData.templateC.otherPreMountType && { lubeType: OHP_2100IData.templateC.otherPreMountType}),
            ...(OHP_2100IData.templateC.plcConnection && { lubeType: OHP_2100IData.templateC.plcConnection}),
            ...(OHP_2100IData.templateC.otherControllerNotes && { lubeType: OHP_2100IData.templateC.otherControllerNotes}),
            ...(OHP_2100IData.templateC.templateC_UnitType && { lubeType: OHP_2100IData.templateC.templateC_UnitType}),
            templateC_InvertedA: OHP_2100IData.templateC.templateC_InvertedA,
            templateC_InvertedB: OHP_2100IData.templateC.templateC_InvertedB,
            templateC_InvertedE: OHP_2100IData.templateC.templateC_InvertedE,
            templateC_InvertedS: OHP_2100IData.templateC.templateC_InvertedS,
        },
         
            ...(OHP_2100IData.wheelClosedType && { wheelClosedType: OHP_2100IData.wheelClosedType }),
            ...(OHP_2100IData.catDriveStatus && { catDriveStatus: OHP_2100IData.catDriveStatus }),
            ...(OHP_2100IData.catDriveNum && { catDriveNum: OHP_2100IData.catDriveNum }),
            ...(OHP_2100IData.railLubeStatus && { railLubeStatus: OHP_2100IData.railLubeStatus }),
            ...(OHP_2100IData.externalLubeStatus && { externalLubeStatus: OHP_2100IData.externalLubeStatus }),
            ...(OHP_2100IData.lubeBrand && { lubeBrand: OHP_2100IData.lubeBrand }),
            ...(OHP_2100IData.lubeType && { lubeType: OHP_2100IData.lubeType }),
            ...(OHP_2100IData.lubeViscosity && { lubeViscosity: OHP_2100IData.lubeViscosity }),
            ...(OHP_2100IData.sideLubeStatus && { sideLubeStatus: OHP_2100IData.sideLubeStatus }),
            ...(OHP_2100IData.topLubeStatus && { topLubeStatus: OHP_2100IData.topLubeStatus }),
            ...(OHP_2100IData.chainCleanStatus && { chainCleanStatus: OHP_2100IData.chainCleanStatus }),
            ...(OHP_2100IData.wireMeasurementUnit && { wireMeasurementUnit: OHP_2100IData.wireMeasurementUnit }),
            ...(OHP_2100IData.twoConductor && { twoConductor: OHP_2100IData.twoConductor }),
            ...(OHP_2100IData.fourConductor && { fourConductor: OHP_2100IData.fourConductor }),
            ...(OHP_2100IData.sevenConductor && { sevenConductor: OHP_2100IData.sevenConductor }),
            ...(OHP_2100IData.twelveConductor && { twelveConductor: OHP_2100IData.twelveConductor }),
            ...(OHP_2100IData.junctionBoxNum && { junctionBoxNum: OHP_2100IData.junctionBoxNum }),
            ...(OHP_2100IData.ohpUnitType && { ohpUnitType: OHP_2100IData.ohpUnitType }),
            ...(OHP_2100IData.ohpDiameter && { ohpDiameter: OHP_2100IData.ohpDiameter }),
            ...(OHP_2100IData.ohpWidth && { ohpWidth: OHP_2100IData.ohpWidth }),
            ...(OHP_2100IData.ohpHeight && { ohpHeight: OHP_2100IData.ohpHeight })
        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "OHP_2100I"
        });
        await req.user.save();
        return res.status(200).json({ message: "OHP_2100I entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;