const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const OHP_ES = require("../models/OHP_ES");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { OHP_ESData, numRequested } = req.body;
        const order = new OHP_ES({
            conveyorName: OHP_ESData.conveyorName,
            chainSize: OHP_ESData.chainSize,
            ...(OHP_ESData.otherChainSize && { otherChainSize: OHP_ESData.otherChainSize }),
            industrialChainManufacturer: OHP_ESData.industrialChainManufacturer,
            ...(OHP_ESData.otherChainManufacturer && { otherChainManufacturer: OHP_ESData.otherChainManufacturer }),
            wheelManufacturer: OHP_ESData.wheelManufacturer,
            ...(OHP_ESData.otherWheelManufacturer && { otherWheelManufacturer: OHP_ESData.otherWheelManufacturer }),
            conveyorLength: OHP_ESData.conveyorLength,
            conveyorLengthUnit: OHP_ESData.conveyorLengthUnit,
            conveyorSpeed: OHP_ESData.conveyorSpeed,
            conveyorSpeedUnit: OHP_ESData.conveyorSpeedUnit,
            conveyorIndex: OHP_ESData.conveyorIndex,
            ...(OHP_ESData.travelDirection && { travelDirection: OHP_ESData.travelDirection }),
            appEnviroment: OHP_ESData.appEnviroment,
            ...(OHP_ESData.ovenStatus && { ovenStatus: OHP_ESData.ovenStatus }),
            ...(OHP_ESData.ovenTemp && { ovenTemp: OHP_ESData.ovenTemp }),
            ...(OHP_ESData.otherAppEnviroment && { otherAppEnviroment: OHP_ESData.otherAppEnviroment }),
            ...(OHP_ESData.newMonitorStatus && { newMonitorStatus: OHP_ESData.newMonitorStatus }),
            ...(OHP_ESData.conveyorLoaded && { conveyorLoaded: OHP_ESData.conveyorLoaded }),
            ...(OHP_ESData.conveyorSwing && { conveyorSwing: OHP_ESData.conveyorSwing }),
            strandStatus: OHP_ESData.strandStatus,
            openBearings: OHP_ESData.openBearings,
            lubeStatus: OHP_ESData.lubeStatus,
            pointsOfLube: OHP_ESData.pointsOfLube,
            m12Plugs: OHP_ESData.m12Plugs,
            op201Controller: OHP_ESData.op201Controller,
            op201Order: OHP_ESData.op201Order,
            operatingVoltSingle: OHP_ESData.operatingVoltSingle,
            controlVoltSingle: OHP_ESData.controlVoltSingle,
            existingMonitor: OHP_ESData.existingMonitor,
            newMonitor: OHP_ESData.newMonitor,
            monitorData: {
                ...(OHP_ESData.dcuStatus && { dcuStatus: OHP_ESData.dcuStatus }),
                ...(OHP_ESData.dcuNum && { dcuNum: OHP_ESData.dcuNum }),
                ...(OHP_ESData.existingWindows && { existingWindows: OHP_ESData.existingWindows }),
                ...(OHP_ESData.existingHeadUnit && { existingHeadUnit: OHP_ESData.existingHeadUnit }),
                ...(OHP_ESData.existingDCU && { existingDCU: OHP_ESData.existingDCU }),
                ...(OHP_ESData.existingPowerInterface && { existingPowerInterface: OHP_ESData.existingPowerInterface }),
                ...(OHP_ESData.newReservoir && { newReservoir: OHP_ESData.newReservoir }),
                ...(OHP_ESData.reservoirSize && { reservoirSize: OHP_ESData.reservoirSize }),
                ...(OHP_ESData.otherReservoirSize && { otherReservoirSize: OHP_ESData.otherReservoirSize }),
                ...(OHP_ESData.newReservoirNum && { newReservoirNum: OHP_ESData.newReservoirNum }),
                ...(OHP_ESData.typeMonitor && { typeMonitor: OHP_ESData.typeMonitor }),
                ...(OHP_ESData.driveMotorAmp && { driveMotorAmp: OHP_ESData.driveMotorAmp }),
                ...(OHP_ESData.driveMotorAmpNum && { driveMotorAmpNum: OHP_ESData.driveMotorAmpNum }),
                ...(OHP_ESData.driveTakeUpAir && { driveTakeUpAir: OHP_ESData.driveTakeUpAir }),
                ...(OHP_ESData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_ESData.driveTakeUpAirNum }),
                ...(OHP_ESData.takeUpDistance && { takeUpDistance: OHP_ESData.takeUpDistance }),
                ...(OHP_ESData.takeUpDistanceNum && { takeUpDistanceNum: OHP_ESData.takeUpDistanceNum }),
                ...(OHP_ESData.driveTemp && { driveTemp: OHP_ESData.driveTemp }),
                ...(OHP_ESData.driveTempNum && { driveTempNum: OHP_ESData.driveTempNum }),
                ...(OHP_ESData.driveVibration && { driveVibration: OHP_ESData.driveVibration }),
                ...(OHP_ESData.driveVibrationNum && { driveVibrationNum: OHP_ESData.driveVibrationNum }),
                ...(OHP_ESData.dogPitch && { dogPitch: OHP_ESData.dogPitch }), 
                ...(OHP_ESData.dogPitchNum && { dogPitchNum: OHP_ESData.dogPitchNum }),
                ...(OHP_ESData.paintMarker && { paintMarker: OHP_ESData.paintMarker }),
                ...(OHP_ESData.paintMarkerNum && { paintMarkerNum: OHP_ESData.paintMarkerNum }),
                ...(OHP_ESData.chainVision && { chainVision: OHP_ESData.chainVision }),
                ...(OHP_ESData.lubeVision && { lubeVision: OHP_ESData.lubeVision }),
                ...(OHP_ESData.trolleyVision && { trolleyVision: OHP_ESData.trolleyVision }),
                ...(OHP_ESData.trolleyDetect && { trolleyDetect: OHP_ESData.trolleyDetect }),
                ...(OHP_ESData.omniView && { omniView: OHP_ESData.omniView }),
                ...(OHP_ESData.dcuUpgradeNum && { dcuUpgradeNum: OHP_ESData.dcuUpgradeNum }),
                ...(OHP_ESData.itNameOne && { itNameOne: OHP_ESData.itNameOne }),
                ...(OHP_ESData.itIPOne && { itIPOne: OHP_ESData.itIPOne }),
                ...(OHP_ESData.itGatewayOne && { itGatewayOne: OHP_ESData.itGatewayOne }),
                ...(OHP_ESData.itSubnetOne && { itSubnetOne: OHP_ESData.itSubnetOne }),
                ...(OHP_ESData.itDNSOne && { itDNSOne: OHP_ESData.itDNSOne }),
                ...(OHP_ESData.itSMTPOne && { itSMTPOne: OHP_ESData.itSMTPOne }),
                ...(OHP_ESData.itNameTwo && { itNameTwo: OHP_ESData.itNameTwo }),
                ...(OHP_ESData.itIPTwo && { itIPTwo: OHP_ESData.itIPTwo }),
                ...(OHP_ESData.itGatewayTwo && { itGatewayTwo: OHP_ESData.itGatewayTwo }),
                ...(OHP_ESData.itSubnetTwo && { itSubnetTwo: OHP_ESData.itSubnetTwo }),
                ...(OHP_ESData.itDNSTwo && { itDNSTwo: OHP_ESData.itDNSTwo }),
                ...(OHP_ESData.itSMTPTwo && { itSMTPTwo: OHP_ESData.itSMTPTwo }),
                ...(OHP_ESData.itNameThree && { itNameThree: OHP_ESData.itNameThree }),
                ...(OHP_ESData.itIPThree && { itIPThree: OHP_ESData.itIPThree }),
                ...(OHP_ESData.itGatewayThree && { itGatewayThree: OHP_ESData.itGatewayThree }),
                ...(OHP_ESData.itSubnetThree && { itSubnetThree: OHP_ESData.itSubnetThree }),
                ...(OHP_ESData.itDNSThree && { itDNSThree: OHP_ESData.itDNSThree }),
                ...(OHP_ESData.itSMTPThree && { itSMTPThree: OHP_ESData.itSMTPThree }),
                ...(OHP_ESData.itAdditionalNotes && { itAdditionalNotes: OHP_ESData.itAdditionalNotes }),
                ...(OHP_ESData.piuDistance && { piuDistance: OHP_ESData.piuDistance }),
                ...(OHP_ESData.switchDistance && { switchDistance: OHP_ESData.switchDistance }),
                ...(OHP_ESData.ampPickup && { ampPickup: OHP_ESData.ampPickup }),
                ...(OHP_ESData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_ESData.fromAirTakeUpDistance }),
                ...(OHP_ESData.specialControllerOptions && { specialControllerOptions: OHP_ESData.specialControllerOptions })
            },

            addFreeCarrier: OHP_ESData.addFreeCarrier,

            templateBData: {
                conveyorName: OHP_ESData.conveyorName,
                industrialChainManufacturer: OHP_ESData.industrialChainManufacturer,
                ...(OHP_ESData.otherChainManufacturer && { otherChainManufacturer: OHP_ESData.otherChainManufacturer }),
                wheelManufacturer: OHP_ESData.wheelManufacturer,
                ...(OHP_ESData.wheelManufacturer && { wheelManufacturer: OHP_ESData.wheelManufacturer}),
                conveyorSpeed: OHP_ESData.conveyorSpeed,
                conveyorSpeedUnit: OHP_ESData.conveyorSpeedUnit,
                conveyorIndex: OHP_ESData.conveyorIndex,
                ...(OHP_ESData.travelDirection && { travelDirection: OHP_ESData.travelDirection}),
                appEnviroment: OHP_ESData.appEnviroment,
                ...(OHP_ESData.otherAppEnviroment && { otherAppEnviroment: OHP_ESData.otherAppEnviroment}),
                surroundingTemp: OHP_ESData.surroundingTemp,
                orientationType: OHP_ESData.orientationType,
                operatingVoltage: OHP_ESData.operatingVoltage,
                controlVoltSingle: OHP_ESData.controlVoltSingle,
                compressedAir: OHP_ESData.compressedAir,
                ...(OHP_ESData.airSupplyType && { airSupplyType: OHP_ESData.airSupplyType}),
            existingMonitor: OHP_ESData.existingMonitor,
            newMonitor: OHP_ESData.newMonitor,
            templateA_BData: {
                ...(OHP_ESData.dcuStatus && { dcuStatus: OHP_ESData.dcuStatus }),
                ...(OHP_ESData.dcuNum && { dcuNum: OHP_ESData.dcuNum }),
                ...(OHP_ESData.existingWindows && { existingWindows: OHP_ESData.existingWindows }),
                ...(OHP_ESData.existingHeadUnit && { existingHeadUnit: OHP_ESData.existingHeadUnit }),
                ...(OHP_ESData.existingDCU && { existingDCU: OHP_ESData.existingDCU }),
                ...(OHP_ESData.existingPowerInterface && { existingPowerInterface: OHP_ESData.existingPowerInterface }),
                ...(OHP_ESData.newReservoir && { newReservoir: OHP_ESData.newReservoir }),
                ...(OHP_ESData.reservoirSize && { reservoirSize: OHP_ESData.reservoirSize }),
                ...(OHP_ESData.otherReservoirSize && { otherReservoirSize: OHP_ESData.otherReservoirSize }),
                ...(OHP_ESData.newReservoirNum && { newReservoirNum: OHP_ESData.newReservoirNum }),
                ...(OHP_ESData.typeMonitor && { typeMonitor: OHP_ESData.typeMonitor }),
                ...(OHP_ESData.driveMotorAmp && { driveMotorAmp: OHP_ESData.driveMotorAmp }),
                ...(OHP_ESData.driveMotorAmpNum && { driveMotorAmpNum: OHP_ESData.driveMotorAmpNum }),
                ...(OHP_ESData.driveTakeUpAir && { driveTakeUpAir: OHP_ESData.driveTakeUpAir }),
                ...(OHP_ESData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_ESData.driveTakeUpAirNum }),
                ...(OHP_ESData.takeUpDistance && { takeUpDistance: OHP_ESData.takeUpDistance }),
                ...(OHP_ESData.takeUpDistanceNum && { takeUpDistanceNum: OHP_ESData.takeUpDistanceNum }),
                ...(OHP_ESData.driveTemp && { driveTemp: OHP_ESData.driveTemp }),
                ...(OHP_ESData.driveTempNum && { driveTempNum: OHP_ESData.driveTempNum }),
                ...(OHP_ESData.driveVibration && { driveVibration: OHP_ESData.driveVibration }),
                ...(OHP_ESData.driveVibrationNum && { driveVibrationNum: OHP_ESData.driveVibrationNum }),
                ...(OHP_ESData.dogPitch && { dogPitch: OHP_ESData.dogPitch }),
                ...(OHP_ESData.dogPitchNum && { dogPitchNum: OHP_ESData.dogPitchNum }),
                ...(OHP_ESData.paintMarker && { paintMarker: OHP_ESData.paintMarker }),
                ...(OHP_ESData.paintMarkerNum && { paintMarkerNum: OHP_ESData.paintMarkerNum }),
                ...(OHP_ESData.chainVision && { chainVision: OHP_ESData.chainVision }),
                ...(OHP_ESData.lubeVision && { lubeVision: OHP_ESData.lubeVision }),
                ...(OHP_ESData.trolleyVision && { trolleyVision: OHP_ESData.trolleyVision }),
                ...(OHP_ESData.trolleyDetect && { trolleyDetect: OHP_ESData.trolleyDetect }),
                ...(OHP_ESData.omniView && { omniView: OHP_ESData.omniView }),
                ...(OHP_ESData.dcuUpgradeNum && { dcuUpgradeNum: OHP_ESData.dcuUpgradeNum }),
                ...(OHP_ESData.itNameOne && { itNameOne: OHP_ESData.itNameOne }),
                ...(OHP_ESData.itIPOne && { itIPOne: OHP_ESData.itIPOne }),
                ...(OHP_ESData.itGatewayOne && { itGatewayOne: OHP_ESData.itGatewayOne }),
                ...(OHP_ESData.itSubnetOne && { itSubnetOne: OHP_ESData.itSubnetOne }),
                ...(OHP_ESData.itDNSOne && { itDNSOne: OHP_ESData.itDNSOne }),
                ...(OHP_ESData.itSMTPOne && { itSMTPOne: OHP_ESData.itSMTPOne }),
                ...(OHP_ESData.itNameTwo && { itNameTwo: OHP_ESData.itNameTwo }),
                ...(OHP_ESData.itIPTwo && { itIPTwo: OHP_ESData.itIPTwo }),
                ...(OHP_ESData.itGatewayTwo && { itGatewayTwo: OHP_ESData.itGatewayTwo }),
                ...(OHP_ESData.itSubnetTwo && { itSubnetTwo: OHP_ESData.itSubnetTwo }),
                ...(OHP_ESData.itDNSTwo && { itDNSTwo: OHP_ESData.itDNSTwo }),
                ...(OHP_ESData.itSMTPTwo && { itSMTPTwo: OHP_ESData.itSMTPTwo }),
                ...(OHP_ESData.itNameThree && { itNameThree: OHP_ESData.itNameThree }),
                ...(OHP_ESData.itIPThree && { itIPThree: OHP_ESData.itIPThree }),
                ...(OHP_ESData.itGatewayThree && { itGatewayThree: OHP_ESData.itGatewayThree }),
                ...(OHP_ESData.itSubnetThree && { itSubnetThree: OHP_ESData.itSubnetThree }),
                ...(OHP_ESData.itDNSThree && { itDNSThree: OHP_ESData.itDNSThree }),
                ...(OHP_ESData.itSMTPThree && { itSMTPThree: OHP_ESData.itSMTPThree }),
                ...(OHP_ESData.itAdditionalNotes && { itAdditionalNotes: OHP_ESData.itAdditionalNotes }),
                ...(OHP_ESData.piuDistance && { piuDistance: OHP_ESData.piuDistance }),
                ...(OHP_ESData.switchDistance && { switchDistance: OHP_ESData.switchDistance }),
                ...(OHP_ESData.ampPickup && { ampPickup: OHP_ESData.ampPickup }),
                ...(OHP_ESData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_ESData.fromAirTakeUpDistance }),
                ...(OHP_ESData.specialControllerOptions && { specialControllerOptions: OHP_ESData.specialControllerOptions }),
                ...(OHP_ESData.operatingVoltage && { operatingVoltage: OHP_ESData.operatingVoltage })

                },


                freeWheelStatus: OHP_ESData.freeWheelStatus,
                actuatorStatus: OHP_ESData.actuatorStatus,
                ...(OHP_ESData.pivotStatus && { pivotStatus: OHP_ESData.pivotStatus}),
                kingPinStatus: OHP_ESData.kingPinStatus,
                lubeBrand: OHP_ESData.lubeBrand,
                lubeViscosity: OHP_ESData.lubeViscosity,
                ...(OHP_ESData.lubeType && { lubeType: OHP_ESData.lubeType}),
                currentGrease: OHP_ESData.currentGrease,
                currentGreaseGrade: OHP_ESData.currentGreaseGrade,
                zerkDirection: OHP_ESData.zerkDirection,
                zerkLocationType: OHP_ESData.zerkLocationType,
                wheelDiameter: OHP_ESData.wheelDiameter,
                conveyorSwing: OHP_ESData.conveyorSwing,
                ...(OHP_ESData.chainMaster && { lubeType: OHP_ESData.chainMaster}),
                ...(OHP_ESData.remoteStatus && { lubeType: OHP_ESData.remoteStatus}),
                ...(OHP_ESData.mountStatus && { lubeType: OHP_ESData.mountStatus}),
                ...(OHP_ESData.otherUnitStatus && { lubeType: OHP_ESData.otherUnitStatus}),
                ...(OHP_ESData.timerStatus && { lubeType: OHP_ESData.timerStatus}),
                ...(OHP_ESData.electricStatus && { lubeType: OHP_ESData.electricStatus}),
                ...(OHP_ESData.mightyLubeMonitoring && { lubeType: OHP_ESData.mightyLubeMonitoring}),
                ...(OHP_ESData.preMountType && { lubeType: OHP_ESData.preMountType}),
                ...(OHP_ESData.otherPreMountType && { lubeType: OHP_ESData.otherPreMountType}),
                ...(OHP_ESData.plcConnection && { lubeType: OHP_ESData.plcConnection}),
                ...(OHP_ESData.otherControllerNotes && { lubeType: OHP_ESData.otherControllerNotes}),
                ...(OHP_ESData.templateB_UnitType && { lubeType: OHP_ESData.templateB_UnitType}),
                ...(OHP_ESData.templateB_InvertedB && { lubeType: OHP_ESData.templateB_InvertedB}),
                ...(OHP_ESData.templateB_InvertedE && { lubeType: OHP_ESData.templateB_InvertedE}),
                ...(OHP_ESData.templateB_InvertedG && { lubeType: OHP_ESData.templateB_InvertedG}),
                ...(OHP_ESData.templateB_InvertedH && { lubeType: OHP_ESData.templateB_InvertedH}),
                ...(OHP_ESData.templateB_InvertedK && { lubeType: OHP_ESData.templateB_InvertedK}),
                ...(OHP_ESData.templateB_InvertedT && { lubeType: OHP_ESData.templateB_InvertedT}),
                ...(OHP_ESData.templateB_InvertedU && { lubeType: OHP_ESData.templateB_InvertedU}),
                ...(OHP_ESData.templateB_InvertedV && { lubeType: OHP_ESData.templateB_InvertedV}),
                ...(OHP_ESData.templateB_InvertedW && { lubeType: OHP_ESData.templateB_InvertedW}),

            },



            templateCData: {
                conveyorName: OHP_ESData.conveyorName,
                industrialChainManufacturer: OHP_ESData.industrialChainManufacturer,
                ...(OHP_ESData.otherChainManufacturer && { otherChainManufacturer: OHP_ESData.otherChainManufacturer }),
                wheelManufacturer: OHP_ESData.wheelManufacturer,
                ...(OHP_ESData.wheelManufacturer && { wheelManufacturer: OHP_ESData.wheelManufacturer}),
                conveyorSpeed: OHP_ESData.conveyorSpeed,
                conveyorSpeedUnit: OHP_ESData.conveyorSpeedUnit,
                conveyorIndex: OHP_ESData.conveyorIndex,
                ...(OHP_ESData.travelDirection && { travelDirection: OHP_ESData.travelDirection}),
                appEnviroment: OHP_ESData.appEnviroment,
                ...(OHP_ESData.otherAppEnviroment && { otherAppEnviroment: OHP_ESData.otherAppEnviroment}),
                surroundingTemp: OHP_ESData.surroundingTemp,
                orientationType: OHP_ESData.orientationType,
                guideWheelsEven: OHP_ESData.guideWheelsEven,
                operatingVoltage: OHP_ESData.operatingVoltage,
                controlVoltSingle: OHP_ESData.controlVoltSingle,
                compressedAir: OHP_ESData.compressedAir,
                ...(OHP_ESData.airSupplyType && { airSupplyType: OHP_ESData.airSupplyType}),
                existingMonitor: OHP_ESData.existingMonitor,
                newMonitor: OHP_ESData.newMonitor,
                templateA_CData: {
                ...(OHP_ESData.dcuStatus && { dcuStatus: OHP_ESData.dcuStatus }),
                ...(OHP_ESData.dcuNum && { dcuNum: OHP_ESData.dcuNum }),
                ...(OHP_ESData.existingWindows && { existingWindows: OHP_ESData.existingWindows }),
                ...(OHP_ESData.existingHeadUnit && { existingHeadUnit: OHP_ESData.existingHeadUnit }),
                ...(OHP_ESData.existingDCU && { existingDCU: OHP_ESData.existingDCU }),
                ...(OHP_ESData.existingPowerInterface && { existingPowerInterface: OHP_ESData.existingPowerInterface }),
                ...(OHP_ESData.newReservoir && { newReservoir: OHP_ESData.newReservoir }),
                ...(OHP_ESData.reservoirSize && { reservoirSize: OHP_ESData.reservoirSize }),
                ...(OHP_ESData.otherReservoirSize && { otherReservoirSize: OHP_ESData.otherReservoirSize }),
                ...(OHP_ESData.newReservoirNum && { newReservoirNum: OHP_ESData.newReservoirNum }),
                ...(OHP_ESData.typeMonitor && { typeMonitor: OHP_ESData.typeMonitor }),
                ...(OHP_ESData.driveMotorAmp && { driveMotorAmp: OHP_ESData.driveMotorAmp }),
                ...(OHP_ESData.driveMotorAmpNum && { driveMotorAmpNum: OHP_ESData.driveMotorAmpNum }),
                ...(OHP_ESData.driveTakeUpAir && { driveTakeUpAir: OHP_ESData.driveTakeUpAir }),
                ...(OHP_ESData.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_ESData.driveTakeUpAirNum }),
                ...(OHP_ESData.takeUpDistance && { takeUpDistance: OHP_ESData.takeUpDistance }),
                ...(OHP_ESData.takeUpDistanceNum && { takeUpDistanceNum: OHP_ESData.takeUpDistanceNum }),
                ...(OHP_ESData.driveTemp && { driveTemp: OHP_ESData.driveTemp }),
                ...(OHP_ESData.driveTempNum && { driveTempNum: OHP_ESData.driveTempNum }),
                ...(OHP_ESData.driveVibration && { driveVibration: OHP_ESData.driveVibration }),
                ...(OHP_ESData.driveVibrationNum && { driveVibrationNum: OHP_ESData.driveVibrationNum }),
                ...(OHP_ESData.dogPitch && { dogPitch: OHP_ESData.dogPitch }),
                ...(OHP_ESData.dogPitchNum && { dogPitchNum: OHP_ESData.dogPitchNum }),
                ...(OHP_ESData.paintMarker && { paintMarker: OHP_ESData.paintMarker }),
                ...(OHP_ESData.paintMarkerNum && { paintMarkerNum: OHP_ESData.paintMarkerNum }),
                ...(OHP_ESData.chainVision && { chainVision: OHP_ESData.chainVision }),
                ...(OHP_ESData.lubeVision && { lubeVision: OHP_ESData.lubeVision }),
                ...(OHP_ESData.trolleyVision && { trolleyVision: OHP_ESData.trolleyVision }),
                ...(OHP_ESData.trolleyDetect && { trolleyDetect: OHP_ESData.trolleyDetect }),
                ...(OHP_ESData.omniView && { omniView: OHP_ESData.omniView }),
                ...(OHP_ESData.dcuUpgradeNum && { dcuUpgradeNum: OHP_ESData.dcuUpgradeNum }),
                ...(OHP_ESData.itNameOne && { itNameOne: OHP_ESData.itNameOne }),
                ...(OHP_ESData.itIPOne && { itIPOne: OHP_ESData.itIPOne }),
                ...(OHP_ESData.itGatewayOne && { itGatewayOne: OHP_ESData.itGatewayOne }),
                ...(OHP_ESData.itSubnetOne && { itSubnetOne: OHP_ESData.itSubnetOne }),
                ...(OHP_ESData.itDNSOne && { itDNSOne: OHP_ESData.itDNSOne }),
                ...(OHP_ESData.itSMTPOne && { itSMTPOne: OHP_ESData.itSMTPOne }),
                ...(OHP_ESData.itNameTwo && { itNameTwo: OHP_ESData.itNameTwo }),
                ...(OHP_ESData.itIPTwo && { itIPTwo: OHP_ESData.itIPTwo }),
                ...(OHP_ESData.itGatewayTwo && { itGatewayTwo: OHP_ESData.itGatewayTwo }),
                ...(OHP_ESData.itSubnetTwo && { itSubnetTwo: OHP_ESData.itSubnetTwo }),
                ...(OHP_ESData.itDNSTwo && { itDNSTwo: OHP_ESData.itDNSTwo }),
                ...(OHP_ESData.itSMTPTwo && { itSMTPTwo: OHP_ESData.itSMTPTwo }),
                ...(OHP_ESData.itNameThree && { itNameThree: OHP_ESData.itNameThree }),
                ...(OHP_ESData.itIPThree && { itIPThree: OHP_ESData.itIPThree }),
                ...(OHP_ESData.itGatewayThree && { itGatewayThree: OHP_ESData.itGatewayThree }),
                ...(OHP_ESData.itSubnetThree && { itSubnetThree: OHP_ESData.itSubnetThree }),
                ...(OHP_ESData.itDNSThree && { itDNSThree: OHP_ESData.itDNSThree }),
                ...(OHP_ESData.itSMTPThree && { itSMTPThree: OHP_ESData.itSMTPThree }),
                ...(OHP_ESData.itAdditionalNotes && { itAdditionalNotes: OHP_ESData.itAdditionalNotes }),
                ...(OHP_ESData.piuDistance && { piuDistance: OHP_ESData.piuDistance }),
                ...(OHP_ESData.switchDistance && { switchDistance: OHP_ESData.switchDistance }),
                ...(OHP_ESData.ampPickup && { ampPickup: OHP_ESData.ampPickup }),
                ...(OHP_ESData.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_ESData.fromAirTakeUpDistance }),
                ...(OHP_ESData.specialControllerOptions && { specialControllerOptions: OHP_ESData.specialControllerOptions }),
                ...(OHP_ESData.operatingVoltage && { operatingVoltage: OHP_ESData.operatingVoltage })

                },
                freeWheelStatus: OHP_ESData.freeWheelStatus,
                actuatorStatus: OHP_ESData.actuatorStatus,
                ...(OHP_ESData.pivotStatus && { pivotStatus: OHP_ESData.pivotStatus}),
                kingPinStatus: OHP_ESData.kingPinStatus,
                lubeBrand: OHP_ESData.lubeBrand,
                lubeViscosity: OHP_ESData.lubeViscosity,
                ...(OHP_ESData.lubeType && { lubeType: OHP_ESData.lubeType}),
                currentGrease: OHP_ESData.currentGrease,
                currentGreaseGrade: OHP_ESData.currentGreaseGrade,
                zerkDirection: OHP_ESData.zerkDirection,
                zerkLocationType: OHP_ESData.zerkLocationType,
                wheelDiameter: OHP_ESData.wheelDiameter,
                conveyorSwing: OHP_ESData.conveyorSwing,
                ...(OHP_ESData.chainMaster && { lubeType: OHP_ESData.chainMaster}),
                ...(OHP_ESData.remoteStatus && { lubeType: OHP_ESData.remoteStatus}),
                ...(OHP_ESData.mountStatus && { lubeType: OHP_ESData.mountStatus}),
                ...(OHP_ESData.otherUnitStatus && { lubeType: OHP_ESData.otherUnitStatus}),
                ...(OHP_ESData.timerStatus && { lubeType: OHP_ESData.timerStatus}),
                ...(OHP_ESData.electricStatus && { lubeType: OHP_ESData.electricStatus}),
                ...(OHP_ESData.mightyLubeMonitoring && { lubeType: OHP_ESData.mightyLubeMonitoring}),
                ...(OHP_ESData.preMountType && { lubeType: OHP_ESData.preMountType}),
                ...(OHP_ESData.otherPreMountType && { lubeType: OHP_ESData.otherPreMountType}),
                ...(OHP_ESData.plcConnection && { lubeType: OHP_ESData.plcConnection}),
                ...(OHP_ESData.otherControllerNotes && { lubeType: OHP_ESData.otherControllerNotes}),
                ...(OHP_ESData.templateC_UnitType && { lubeType: OHP_ESData.templateC_UnitType}),
                templateC_InvertedA: OHP_ESData.templateC_InvertedA,
                templateC_InvertedB: OHP_ESData.templateC_InvertedB,
                templateC_InvertedE: OHP_ESData.templateC_InvertedE,
                templateC_InvertedS: OHP_ESData.templateC_InvertedS,
            },

            ...(OHP_ESData.wheelOpenType && { wheelOpenType: OHP_ESData.wheelOpenType }),
            ...(OHP_ESData.wheelClosedType && { wheelClosedType: OHP_ESData.wheelClosedType }),
            ...(OHP_ESData.openStatus && { openStatus: OHP_ESData.openStatus }),
            ...(OHP_ESData.freeWheelStatus && { freeWheelStatus: OHP_ESData.freeWheelStatus }),
            ...(OHP_ESData.guideRollerStatus && { guideRollerStatus: OHP_ESData.guideRollerStatus }),
            ...(OHP_ESData.openRaceStyleType && { openRaceStyleType: OHP_ESData.openRaceStyleType }),
            ...(OHP_ESData.closedRaceStyleType && { closedRaceStyleType: OHP_ESData.closedRaceStyleType }),
            ...(OHP_ESData.holeStatus && { holeStatus: OHP_ESData.holeStatus }),
            ...(OHP_ESData.actuatorStatus && { actuatorStatus: OHP_ESData.actuatorStatus }),
            ...(OHP_ESData.pivotStatus && { pivotStatus: OHP_ESData.pivotStatus }),
            ...(OHP_ESData.kingPinStatus && { kingPinStatus: OHP_ESData.kingPinStatus }),
            ...(OHP_ESData.railLubeStatus && { railLubeStatus: OHP_ESData.railLubeStatus }),
            ...(OHP_ESData.externalLubeStatus && { externalLubeStatus: OHP_ESData.externalLubeStatus }),
            ...(OHP_ESData.lubeBrand && { lubeBrand: OHP_ESData.lubeBrand }),
            ...(OHP_ESData.lubeViscosity && { lubeViscosity: OHP_ESData.lubeViscosity }),
            ...(OHP_ESData.sideLubeStatus && { sideLubeStatus: OHP_ESData.sideLubeStatus }),
            ...(OHP_ESData.topLubeStatus && { topLubeStatus: OHP_ESData.topLubeStatus }),
            ...(OHP_ESData.chainMaster && { chainMaster: OHP_ESData.chainMaster }),
            ...(OHP_ESData.timerStatus && { timerStatus: OHP_ESData.timerStatus }),
            ...(OHP_ESData.electricStatus && { electricStatus: OHP_ESData.electricStatus }),
            ...(OHP_ESData.pneumaticStatus && { pneumaticStatus: OHP_ESData.pneumaticStatus }),
            ...(OHP_ESData.mightyLubeMonitoring && { mightyLubeMonitoring: OHP_ESData.mightyLubeMonitoring }),
            ...(OHP_ESData.plcConnection && { plcConnection: OHP_ESData.plcConnection }),
            ...(OHP_ESData.otherControllerNotes && { otherControllerNotes: OHP_ESData.otherControllerNotes }),
            ...(OHP_ESData.ohpUnitType && { ohpUnitType: OHP_ESData.ohpUnitType }),
            ...(OHP_ESData.chainDrop && { chainDrop: OHP_ESData.chainDrop }),
            ...(OHP_ESData.ohpDiameter && { ohpDiameter: OHP_ESData.ohpDiameter }),
            ...(OHP_ESData.ohpWidth && { ohpWidth: OHP_ESData.ohpWidth }),
            ...(OHP_ESData.ohpHeight && { ohpHeight: OHP_ESData.ohpHeight })


        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "OHP_ES"
        });
        await req.user.save();
        return res.status(200).json({ message: "OHP_ES entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;