const express = require("express");
const { dbConnect } = require("../config/config");
const { authenticate } = require("./sessions");
const OHP_ES = require("../models/OHP_ES");
const templateA = require("../models/templateA");
const templateB = require("../models/templateB");
const templateC = require("../models/templateC");

const router = express.Router();

router.post("/", authenticate, async (req, res) => {
    try {
        const { OHP_ESData, numRequested } = req.body;
        const order = new OHP_ES({
            conveyorName: OHP_ESData.conveyorName,
            chainSize: OHP_ESData.chainSize,
            ...(OHP_ESData.otherChainSize && { otherChainSize: OHP_ESData.otherChainSize }),
            industrialChainManufacturer: OHP_ESData.industrialChainManufacturer,
            ...(OHP_ESData.otherChainManufacturer && { otherChainManufacturer: OHP_ESData.otherChainManufacturer }),

            conveyorLength: OHP_ESData.conveyorLength,
            conveyorLengthUnit: OHP_ESData.conveyorLengthUnit,
            conveyorSpeed: OHP_ESData.conveyorSpeed,
            conveyorSpeedUnit: OHP_ESData.conveyorSpeedUnit,
            conveyorIndex: OHP_ESData.conveyorIndex,
            ...(OHP_ESData.travelDirection && { travelDirection: OHP_ESData.travelDirection }),
            appEnviroment: OHP_ESData.appEnviroment,
            ...(OHP_ESData.ovenStatus && { ovenStatus: OHP_ESData.ovenStatus }),
            ...(OHP_ESData.ovenTemp && { ovenTemp: OHP_ESData.ovenTemp }),
            ...(OHP_ESData.otherAppEnviroment && { otherAppEnviroment: OHP_ESData.otherAppEnviroment }),
            ...(OHP_ESData.newMonitorStatus && { newMonitorStatus: OHP_ESData.newMonitorStatus }),
            ...(OHP_ESData.conveyorLoaded && { conveyorLoaded: OHP_ESData.conveyorLoaded }),
            ...(OHP_ESData.conveyorSwing && { conveyorSwing: OHP_ESData.conveyorSwing }),
            strandStatus: OHP_ESData.strandStatus,
            openBearings: OHP_ESData.openBearings,
            lubeStatus: OHP_ESData.lubeStatus,
            pointsOfLube: OHP_ESData.pointsOfLube,
            m12Plugs: OHP_ESData.m12Plugs,
            op201Controller: OHP_ESData.op201Controller,
            op201Order: OHP_ESData.op201Order,
            operatingVoltSingle: OHP_ESData.operatingVoltSingle,
            controlVoltSingle: OHP_ESData.controlVoltSingle,
            existingMonitor: OHP_ESData.existingMonitor,
            newMonitor: OHP_ESData.newMonitor,
            monitorData: new templateA({
                ...(OHP_ESData.templateA.dcuStatus && { dcuStatus: OHP_ESData.templateA.dcuStatus }),
                ...(OHP_ESData.templateA.dcuNum && { dcuNum: OHP_ESData.templateA.dcuNum }),
                ...(OHP_ESData.templateA.existingWindows && { existingWindows: OHP_ESData.templateA.existingWindows }),
                ...(OHP_ESData.templateA.existingHeadUnit && { existingHeadUnit: OHP_ESData.templateA.existingHeadUnit }),
                ...(OHP_ESData.templateA.existingDCU && { existingDCU: OHP_ESData.templateA.existingDCU }),
                ...(OHP_ESData.templateA.existingPowerInterface && { existingPowerInterface: OHP_ESData.templateA.existingPowerInterface }),
                ...(OHP_ESData.templateA.newReservoir && { newReservoir: OHP_ESData.templateA.newReservoir }),
                ...(OHP_ESData.templateA.reservoirSize && { reservoirSize: OHP_ESData.templateA.reservoirSize }),
                ...(OHP_ESData.templateA.otherReservoirSize && { otherReservoirSize: OHP_ESData.templateA.otherReservoirSize }),
                ...(OHP_ESData.templateA.newReservoirNum && { newReservoirNum: OHP_ESData.templateA.newReservoirNum }),
                ...(OHP_ESData.templateA.typeMonitor && { typeMonitor: OHP_ESData.templateA.typeMonitor }),
                ...(OHP_ESData.templateA.driveMotorAmp && { driveMotorAmp: OHP_ESData.templateA.driveMotorAmp }),
                ...(OHP_ESData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_ESData.templateA.driveMotorAmpNum }),
                ...(OHP_ESData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_ESData.templateA.driveTakeUpAir }),
                ...(OHP_ESData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_ESData.templateA.driveTakeUpAirNum }),
                ...(OHP_ESData.templateA.takeUpDistance && { takeUpDistance: OHP_ESData.templateA.takeUpDistance }),
                ...(OHP_ESData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_ESData.templateA.takeUpDistanceNum }),
                ...(OHP_ESData.templateA.driveTemp && { driveTemp: OHP_ESData.templateA.driveTemp }),
                ...(OHP_ESData.templateA.driveTempNum && { driveTempNum: OHP_ESData.templateA.driveTempNum }),
                ...(OHP_ESData.templateA.driveVibration && { driveVibration: OHP_ESData.templateA.driveVibration }),
                ...(OHP_ESData.templateA.driveVibrationNum && { driveVibrationNum: OHP_ESData.templateA.driveVibrationNum }),
                ...(OHP_ESData.templateA.dogPitch && { dogPitch: OHP_ESData.templateA.dogPitch }),
                ...(OHP_ESData.templateA.dogPitchNum && { dogPitchNum: OHP_ESData.templateA.dogPitchNum }),
                ...(OHP_ESData.templateA.paintMarker && { paintMarker: OHP_ESData.templateA.paintMarker }),
                ...(OHP_ESData.templateA.paintMarkerNum && { paintMarkerNum: OHP_ESData.templateA.paintMarkerNum }),
                ...(OHP_ESData.templateA.chainVision && { chainVision: OHP_ESData.templateA.chainVision }),
                ...(OHP_ESData.templateA.lubeVision && { lubeVision: OHP_ESData.templateA.lubeVision }),
                ...(OHP_ESData.templateA.trolleyVision && { trolleyVision: OHP_ESData.templateA.trolleyVision }),
                ...(OHP_ESData.templateA.trolleyDetect && { trolleyDetect: OHP_ESData.templateA.trolleyDetect }),
                ...(OHP_ESData.templateA.omniView && { omniView: OHP_ESData.templateA.omniView }),
                ...(OHP_ESData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_ESData.templateA.dcuUpgradeNum }),
                ...(OHP_ESData.templateA.itNameOne && { itNameOne: OHP_ESData.templateA.itNameOne }),
                ...(OHP_ESData.templateA.itIPOne && { itIPOne: OHP_ESData.templateA.itIPOne }),
                ...(OHP_ESData.templateA.itGatewayOne && { itGatewayOne: OHP_ESData.templateA.itGatewayOne }),
                ...(OHP_ESData.templateA.itSubnetOne && { itSubnetOne: OHP_ESData.templateA.itSubnetOne }),
                ...(OHP_ESData.templateA.itDNSOne && { itDNSOne: OHP_ESData.templateA.itDNSOne }),
                ...(OHP_ESData.templateA.itSMTPOne && { itSMTPOne: OHP_ESData.templateA.itSMTPOne }),
                ...(OHP_ESData.templateA.itNameTwo && { itNameTwo: OHP_ESData.templateA.itNameTwo }),
                ...(OHP_ESData.templateA.itIPTwo && { itIPTwo: OHP_ESData.templateA.itIPTwo }),
                ...(OHP_ESData.templateA.itGatewayTwo && { itGatewayTwo: OHP_ESData.templateA.itGatewayTwo }),
                ...(OHP_ESData.templateA.itSubnetTwo && { itSubnetTwo: OHP_ESData.templateA.itSubnetTwo }),
                ...(OHP_ESData.templateA.itDNSTwo && { itDNSTwo: OHP_ESData.templateA.itDNSTwo }),
                ...(OHP_ESData.templateA.itSMTPTwo && { itSMTPTwo: OHP_ESData.templateA.itSMTPTwo }),
                ...(OHP_ESData.templateA.itNameThree && { itNameThree: OHP_ESData.templateA.itNameThree }),
                ...(OHP_ESData.templateA.itIPThree && { itIPThree: OHP_ESData.templateA.itIPThree }),
                ...(OHP_ESData.templateA.itGatewayThree && { itGatewayThree: OHP_ESData.templateA.itGatewayThree }),
                ...(OHP_ESData.templateA.itSubnetThree && { itSubnetThree: OHP_ESData.templateA.itSubnetThree }),
                ...(OHP_ESData.templateA.itDNSThree && { itDNSThree: OHP_ESData.templateA.itDNSThree }),
                ...(OHP_ESData.templateA.itSMTPThree && { itSMTPThree: OHP_ESData.templateA.itSMTPThree }),
                ...(OHP_ESData.templateA.itAdditionalNotes && { itAdditionalNotes: OHP_ESData.templateA.itAdditionalNotes }),
                ...(OHP_ESData.templateA.piuDistance && { piuDistance: OHP_ESData.templateA.piuDistance }),
                ...(OHP_ESData.templateA.switchDistance && { switchDistance: OHP_ESData.templateA.switchDistance }),
                ...(OHP_ESData.templateA.ampPickup && { ampPickup: OHP_ESData.templateA.ampPickup }),
                ...(OHP_ESData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_ESData.templateA.fromAirTakeUpDistance }),
                ...(OHP_ESData.templateA.specialControllerOptions && { specialControllerOptions: OHP_ESData.templateA.specialControllerOptions })
            }),

            addFreeCarrier: OHP_ESData.addFreeCarrier,

            templateBData: new templateB({
                conveyorName: OHP_ESData.templateB.conveyorName,
                industrialChainManufacturer: OHP_ESData.templateB.industrialChainManufacturer,
                ...(OHP_ESData.templateB.otherChainManufacturer && { otherChainManufacturer: OHP_ESData.templateB.otherChainManufacturer }),
                wheelManufacturer: OHP_ESData.templateB.wheelManufacturer,
                ...(OHP_ESData.templateB.wheelManufacturer && { wheelManufacturer: OHP_ESData.templateB.wheelManufacturer}),
                conveyorSpeed: OHP_ESData.templateB.conveyorSpeed,
                conveyorSpeedUnit: OHP_ESData.templateB.conveyorSpeedUnit,
                conveyorIndex: OHP_ESData.templateB.conveyorIndex,
                ...(OHP_ESData.templateB.travelDirection && { travelDirection: OHP_ESData.templateB.travelDirection}),
                appEnviroment: OHP_ESData.templateB.appEnviroment,
                ...(OHP_ESData.templateB.otherAppEnviroment && { otherAppEnviroment: OHP_ESData.templateB.otherAppEnviroment}),
                surroundingTemp: OHP_ESData.templateB.surroundingTemp,
                orientationType: OHP_ESData.templateB.orientationType,
                operatingVoltage: OHP_ESData.templateB.operatingVoltage,
                controlVoltSingle: OHP_ESData.templateB.controlVoltSingle,
                compressedAir: OHP_ESData.templateB.compressedAir,
                ...(OHP_ESData.templateB.airSupplyType && { airSupplyType: OHP_ESData.templateB.airSupplyType}),
            existingMonitor: OHP_ESData.templateB.existingMonitor,
            newMonitor: OHP_ESData.templateB.newMonitor,
            templateA_BData: new templateA({
                ...(OHP_ESData.templateA.dcuStatus && { dcuStatus: OHP_ESData.templateA.dcuStatus }),
                ...(OHP_ESData.templateA.dcuNum && { dcuNum: OHP_ESData.templateA.dcuNum }),
                ...(OHP_ESData.templateA.existingWindows && { existingWindows: OHP_ESData.templateA.existingWindows }),
                ...(OHP_ESData.templateA.existingHeadUnit && { existingHeadUnit: OHP_ESData.templateA.existingHeadUnit }),
                ...(OHP_ESData.templateA.existingDCU && { existingDCU: OHP_ESData.templateA.existingDCU }),
                ...(OHP_ESData.templateA.existingPowerInterface && { existingPowerInterface: OHP_ESData.templateA.existingPowerInterface }),
                ...(OHP_ESData.templateA.newReservoir && { newReservoir: OHP_ESData.templateA.newReservoir }),
                ...(OHP_ESData.templateA.reservoirSize && { reservoirSize: OHP_ESData.templateA.reservoirSize }),
                ...(OHP_ESData.templateA.otherReservoirSize && { otherReservoirSize: OHP_ESData.templateA.otherReservoirSize }),
                ...(OHP_ESData.templateA.newReservoirNum && { newReservoirNum: OHP_ESData.templateA.newReservoirNum }),
                ...(OHP_ESData.templateA.typeMonitor && { typeMonitor: OHP_ESData.templateA.typeMonitor }),
                ...(OHP_ESData.templateA.driveMotorAmp && { driveMotorAmp: OHP_ESData.templateA.driveMotorAmp }),
                ...(OHP_ESData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_ESData.templateA.driveMotorAmpNum }),
                ...(OHP_ESData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_ESData.templateA.driveTakeUpAir }),
                ...(OHP_ESData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_ESData.templateA.driveTakeUpAirNum }),
                ...(OHP_ESData.templateA.takeUpDistance && { takeUpDistance: OHP_ESData.templateA.takeUpDistance }),
                ...(OHP_ESData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_ESData.templateA.takeUpDistanceNum }),
                ...(OHP_ESData.templateA.driveTemp && { driveTemp: OHP_ESData.templateA.driveTemp }),
                ...(OHP_ESData.templateA.driveTempNum && { driveTempNum: OHP_ESData.templateA.driveTempNum }),
                ...(OHP_ESData.templateA.driveVibration && { driveVibration: OHP_ESData.templateA.driveVibration }),
                ...(OHP_ESData.templateA.driveVibrationNum && { driveVibrationNum: OHP_ESData.templateA.driveVibrationNum }),
                ...(OHP_ESData.templateA.dogPitch && { dogPitch: OHP_ESData.templateA.dogPitch }),
                ...(OHP_ESData.templateA.dogPitchNum && { dogPitchNum: OHP_ESData.templateA.dogPitchNum }),
                ...(OHP_ESData.templateA.paintMarker && { paintMarker: OHP_ESData.templateA.paintMarker }),
                ...(OHP_ESData.templateA.paintMarkerNum && { paintMarkerNum: OHP_ESData.templateA.paintMarkerNum }),
                ...(OHP_ESData.templateA.chainVision && { chainVision: OHP_ESData.templateA.chainVision }),
                ...(OHP_ESData.templateA.lubeVision && { lubeVision: OHP_ESData.templateA.lubeVision }),
                ...(OHP_ESData.templateA.trolleyVision && { trolleyVision: OHP_ESData.templateA.trolleyVision }),
                ...(OHP_ESData.templateA.trolleyDetect && { trolleyDetect: OHP_ESData.templateA.trolleyDetect }),
                ...(OHP_ESData.templateA.omniView && { omniView: OHP_ESData.templateA.omniView }),
                ...(OHP_ESData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_ESData.templateA.dcuUpgradeNum }),
                ...(OHP_ESData.templateA.itNameOne && { itNameOne: OHP_ESData.templateA.itNameOne }),
                ...(OHP_ESData.templateA.itIPOne && { itIPOne: OHP_ESData.templateA.itIPOne }),
                ...(OHP_ESData.templateA.itGatewayOne && { itGatewayOne: OHP_ESData.templateA.itGatewayOne }),
                ...(OHP_ESData.templateA.itSubnetOne && { itSubnetOne: OHP_ESData.templateA.itSubnetOne }),
                ...(OHP_ESData.templateA.itDNSOne && { itDNSOne: OHP_ESData.templateA.itDNSOne }),
                ...(OHP_ESData.templateA.itSMTPOne && { itSMTPOne: OHP_ESData.templateA.itSMTPOne }),
                ...(OHP_ESData.templateA.itNameTwo && { itNameTwo: OHP_ESData.templateA.itNameTwo }),
                ...(OHP_ESData.templateA.itIPTwo && { itIPTwo: OHP_ESData.templateA.itIPTwo }),
                ...(OHP_ESData.templateA.itGatewayTwo && { itGatewayTwo: OHP_ESData.templateA.itGatewayTwo }),
                ...(OHP_ESData.templateA.itSubnetTwo && { itSubnetTwo: OHP_ESData.templateA.itSubnetTwo }),
                ...(OHP_ESData.templateA.itDNSTwo && { itDNSTwo: OHP_ESData.templateA.itDNSTwo }),
                ...(OHP_ESData.templateA.itSMTPTwo && { itSMTPTwo: OHP_ESData.templateA.itSMTPTwo }),
                ...(OHP_ESData.templateA.itNameThree && { itNameThree: OHP_ESData.templateA.itNameThree }),
                ...(OHP_ESData.templateA.itIPThree && { itIPThree: OHP_ESData.templateA.itIPThree }),
                ...(OHP_ESData.templateA.itGatewayThree && { itGatewayThree: OHP_ESData.templateA.itGatewayThree }),
                ...(OHP_ESData.templateA.itSubnetThree && { itSubnetThree: OHP_ESData.templateA.itSubnetThree }),
                ...(OHP_ESData.templateA.itDNSThree && { itDNSThree: OHP_ESData.templateA.itDNSThree }),
                ...(OHP_ESData.templateA.itSMTPThree && { itSMTPThree: OHP_ESData.templateA.itSMTPThree }),
                ...(OHP_ESData.templateA.itAdditionalNotes && { itAdditionalNotes: OHP_ESData.templateA.itAdditionalNotes }),
                ...(OHP_ESData.templateA.piuDistance && { piuDistance: OHP_ESData.templateA.piuDistance }),
                ...(OHP_ESData.templateA.switchDistance && { switchDistance: OHP_ESData.templateA.switchDistance }),
                ...(OHP_ESData.templateA.ampPickup && { ampPickup: OHP_ESData.templateA.ampPickup }),
                ...(OHP_ESData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_ESData.templateA.fromAirTakeUpDistance }),
                ...(OHP_ESData.templateA.specialControllerOptions && { specialControllerOptions: OHP_ESData.templateA.specialControllerOptions }),
                ...(OHP_ESData.templateA.operatingVoltage && { operatingVoltage: OHP_ESData.templateA.operatingVoltage })

                }),


                freeWheelStatus: OHP_ESData.templateB.freeWheelStatus,
                actuatorStatus: OHP_ESData.templateB.actuatorStatus,
                ...(OHP_ESData.templateB.pivotStatus && { pivotStatus: OHP_ESData.templateB.pivotStatus}),
                kingPinStatus: OHP_ESData.templateB.kingPinStatus,
                lubeBrand: OHP_ESData.templateB.lubeBrand,
                lubeViscosity: OHP_ESData.templateB.lubeViscosity,
                ...(OHP_ESData.templateB.lubeType && { lubeType: OHP_ESData.templateB.lubeType}),
                currentGrease: OHP_ESData.templateB.currentGrease,
                currentGreaseGrade: OHP_ESData.templateB.currentGreaseGrade,
                zerkDirection: OHP_ESData.templateB.zerkDirection,
                zerkLocationType: OHP_ESData.templateB.zerkLocationType,
                wheelDiameter: OHP_ESData.templateB.wheelDiameter,
                conveyorSwing: OHP_ESData.templateB.conveyorSwing,
                ...(OHP_ESData.templateB.chainMaster && { lubeType: OHP_ESData.templateB.chainMaster}),
                ...(OHP_ESData.templateB.remoteStatus && { lubeType: OHP_ESData.templateB.remoteStatus}),
                ...(OHP_ESData.templateB.mountStatus && { lubeType: OHP_ESData.templateB.mountStatus}),
                ...(OHP_ESData.templateB.otherUnitStatus && { lubeType: OHP_ESData.templateB.otherUnitStatus}),
                ...(OHP_ESData.templateB.timerStatus && { lubeType: OHP_ESData.templateB.timerStatus}),
                ...(OHP_ESData.templateB.electricStatus && { lubeType: OHP_ESData.templateB.electricStatus}),
                ...(OHP_ESData.templateB.mightyLubeMonitoring && { lubeType: OHP_ESData.templateB.mightyLubeMonitoring}),
                ...(OHP_ESData.templateB.preMountType && { lubeType: OHP_ESData.templateB.preMountType}),
                ...(OHP_ESData.templateB.otherPreMountType && { lubeType: OHP_ESData.templateB.otherPreMountType}),
                ...(OHP_ESData.templateB.plcConnection && { lubeType: OHP_ESData.templateB.plcConnection}),
                ...(OHP_ESData.templateB.otherControllerNotes && { lubeType: OHP_ESData.templateB.otherControllerNotes}),
                ...(OHP_ESData.templateB.templateB_UnitType && { lubeType: OHP_ESData.templateB.templateB_UnitType}),
                ...(OHP_ESData.templateB.templateB_InvertedB && { lubeType: OHP_ESData.templateB.templateB_InvertedB}),
                ...(OHP_ESData.templateB.templateB_InvertedE && { lubeType: OHP_ESData.templateB.templateB_InvertedE}),
                ...(OHP_ESData.templateB.templateB_InvertedG && { lubeType: OHP_ESData.templateB.templateB_InvertedG}),
                ...(OHP_ESData.templateB.templateB_InvertedH && { lubeType: OHP_ESData.templateB.templateB_InvertedH}),
                ...(OHP_ESData.templateB.templateB_InvertedK && { lubeType: OHP_ESData.templateB.templateB_InvertedK}),
                ...(OHP_ESData.templateB.templateB_InvertedT && { lubeType: OHP_ESData.templateB.templateB_InvertedT}),
                ...(OHP_ESData.templateB.templateB_InvertedU && { lubeType: OHP_ESData.templateB.templateB_InvertedU}),
                ...(OHP_ESData.templateB.templateB_InvertedV && { lubeType: OHP_ESData.templateB.templateB_InvertedV}),
                ...(OHP_ESData.templateB.templateB_InvertedW && { lubeType: OHP_ESData.templateB.templateB_InvertedW}),

            }),



            templateCData: new templateC({
                conveyorName: OHP_ESData.templateC.conveyorName,
                industrialChainManufacturer: OHP_ESData.templateC.industrialChainManufacturer,
                ...(OHP_ESData.templateC.otherChainManufacturer && { otherChainManufacturer: OHP_ESData.templateC.otherChainManufacturer }),
                wheelManufacturer: OHP_ESData.templateC.wheelManufacturer,
                ...(OHP_ESData.templateC.wheelManufacturer && { wheelManufacturer: OHP_ESData.templateC.wheelManufacturer}),
                conveyorSpeed: OHP_ESData.templateC.conveyorSpeed,
                conveyorSpeedUnit: OHP_ESData.templateC.conveyorSpeedUnit,
                conveyorIndex: OHP_ESData.templateC.conveyorIndex,
                ...(OHP_ESData.templateC.travelDirection && { travelDirection: OHP_ESData.templateC.travelDirection}),
                appEnviroment: OHP_ESData.templateC.appEnviroment,
                ...(OHP_ESData.templateC.otherAppEnviroment && { otherAppEnviroment: OHP_ESData.templateC.otherAppEnviroment}),
                surroundingTemp: OHP_ESData.templateC.surroundingTemp,
                orientationType: OHP_ESData.templateC.orientationType,
                guideWheelsEven: OHP_ESData.templateC.guideWheelsEven,
                operatingVoltage: OHP_ESData.templateC.operatingVoltage,
                controlVoltSingle: OHP_ESData.templateC.controlVoltSingle,
                compressedAir: OHP_ESData.templateC.compressedAir,
                ...(OHP_ESData.templateC.airSupplyType && { airSupplyType: OHP_ESData.templateC.airSupplyType}),
                existingMonitor: OHP_ESData.templateC.existingMonitor,
                newMonitor: OHP_ESData.templateC.newMonitor,
                templateA_CData: new templateA({
                ...(OHP_ESData.templateA.dcuStatus && { dcuStatus: OHP_ESData.templateA.dcuStatus }),
                ...(OHP_ESData.templateA.dcuNum && { dcuNum: OHP_ESData.templateA.dcuNum }),
                ...(OHP_ESData.templateA.existingWindows && { existingWindows: OHP_ESData.templateA.existingWindows }),
                ...(OHP_ESData.templateA.existingHeadUnit && { existingHeadUnit: OHP_ESData.templateA.existingHeadUnit }),
                ...(OHP_ESData.templateA.existingDCU && { existingDCU: OHP_ESData.templateA.existingDCU }),
                ...(OHP_ESData.templateA.existingPowerInterface && { existingPowerInterface: OHP_ESData.templateA.existingPowerInterface }),
                ...(OHP_ESData.templateA.newReservoir && { newReservoir: OHP_ESData.templateA.newReservoir }),
                ...(OHP_ESData.templateA.reservoirSize && { reservoirSize: OHP_ESData.templateA.reservoirSize }),
                ...(OHP_ESData.templateA.otherReservoirSize && { otherReservoirSize: OHP_ESData.templateA.otherReservoirSize }),
                ...(OHP_ESData.templateA.newReservoirNum && { newReservoirNum: OHP_ESData.templateA.newReservoirNum }),
                ...(OHP_ESData.templateA.typeMonitor && { typeMonitor: OHP_ESData.templateA.typeMonitor }),
                ...(OHP_ESData.templateA.driveMotorAmp && { driveMotorAmp: OHP_ESData.templateA.driveMotorAmp }),
                ...(OHP_ESData.templateA.driveMotorAmpNum && { driveMotorAmpNum: OHP_ESData.templateA.driveMotorAmpNum }),
                ...(OHP_ESData.templateA.driveTakeUpAir && { driveTakeUpAir: OHP_ESData.templateA.driveTakeUpAir }),
                ...(OHP_ESData.templateA.driveTakeUpAirNum && { driveTakeUpAirNum: OHP_ESData.templateA.driveTakeUpAirNum }),
                ...(OHP_ESData.templateA.takeUpDistance && { takeUpDistance: OHP_ESData.templateA.takeUpDistance }),
                ...(OHP_ESData.templateA.takeUpDistanceNum && { takeUpDistanceNum: OHP_ESData.templateA.takeUpDistanceNum }),
                ...(OHP_ESData.templateA.driveTemp && { driveTemp: OHP_ESData.templateA.driveTemp }),
                ...(OHP_ESData.templateA.driveTempNum && { driveTempNum: OHP_ESData.templateA.driveTempNum }),
                ...(OHP_ESData.templateA.driveVibration && { driveVibration: OHP_ESData.templateA.driveVibration }),
                ...(OHP_ESData.templateA.driveVibrationNum && { driveVibrationNum: OHP_ESData.templateA.driveVibrationNum }),
                ...(OHP_ESData.templateA.dogPitch && { dogPitch: OHP_ESData.templateA.dogPitch }),
                ...(OHP_ESData.templateA.dogPitchNum && { dogPitchNum: OHP_ESData.templateA.dogPitchNum }),
                ...(OHP_ESData.templateA.paintMarker && { paintMarker: OHP_ESData.templateA.paintMarker }),
                ...(OHP_ESData.templateA.paintMarkerNum && { paintMarkerNum: OHP_ESData.templateA.paintMarkerNum }),
                ...(OHP_ESData.templateA.chainVision && { chainVision: OHP_ESData.templateA.chainVision }),
                ...(OHP_ESData.templateA.lubeVision && { lubeVision: OHP_ESData.templateA.lubeVision }),
                ...(OHP_ESData.templateA.trolleyVision && { trolleyVision: OHP_ESData.templateA.trolleyVision }),
                ...(OHP_ESData.templateA.trolleyDetect && { trolleyDetect: OHP_ESData.templateA.trolleyDetect }),
                ...(OHP_ESData.templateA.omniView && { omniView: OHP_ESData.templateA.omniView }),
                ...(OHP_ESData.templateA.dcuUpgradeNum && { dcuUpgradeNum: OHP_ESData.templateA.dcuUpgradeNum }),
                ...(OHP_ESData.templateA.itNameOne && { itNameOne: OHP_ESData.templateA.itNameOne }),
                ...(OHP_ESData.templateA.itIPOne && { itIPOne: OHP_ESData.templateA.itIPOne }),
                ...(OHP_ESData.templateA.itGatewayOne && { itGatewayOne: OHP_ESData.templateA.itGatewayOne }),
                ...(OHP_ESData.templateA.itSubnetOne && { itSubnetOne: OHP_ESData.templateA.itSubnetOne }),
                ...(OHP_ESData.templateA.itDNSOne && { itDNSOne: OHP_ESData.templateA.itDNSOne }),
                ...(OHP_ESData.templateA.itSMTPOne && { itSMTPOne: OHP_ESData.templateA.itSMTPOne }),
                ...(OHP_ESData.templateA.itNameTwo && { itNameTwo: OHP_ESData.templateA.itNameTwo }),
                ...(OHP_ESData.templateA.itIPTwo && { itIPTwo: OHP_ESData.templateA.itIPTwo }),
                ...(OHP_ESData.templateA.itGatewayTwo && { itGatewayTwo: OHP_ESData.templateA.itGatewayTwo }),
                ...(OHP_ESData.templateA.itSubnetTwo && { itSubnetTwo: OHP_ESData.templateA.itSubnetTwo }),
                ...(OHP_ESData.templateA.itDNSTwo && { itDNSTwo: OHP_ESData.templateA.itDNSTwo }),
                ...(OHP_ESData.templateA.itSMTPTwo && { itSMTPTwo: OHP_ESData.templateA.itSMTPTwo }),
                ...(OHP_ESData.templateA.itNameThree && { itNameThree: OHP_ESData.templateA.itNameThree }),
                ...(OHP_ESData.templateA.itIPThree && { itIPThree: OHP_ESData.templateA.itIPThree }),
                ...(OHP_ESData.templateA.itGatewayThree && { itGatewayThree: OHP_ESData.templateA.itGatewayThree }),
                ...(OHP_ESData.templateA.itSubnetThree && { itSubnetThree: OHP_ESData.templateA.itSubnetThree }),
                ...(OHP_ESData.templateA.itDNSThree && { itDNSThree: OHP_ESData.templateA.itDNSThree }),
                ...(OHP_ESData.templateA.itSMTPThree && { itSMTPThree: OHP_ESData.templateA.itSMTPThree }),
                ...(OHP_ESData.templateA.itAdditionalNotes && { itAdditionalNotes: OHP_ESData.templateA.itAdditionalNotes }),
                ...(OHP_ESData.templateA.piuDistance && { piuDistance: OHP_ESData.templateA.piuDistance }),
                ...(OHP_ESData.templateA.switchDistance && { switchDistance: OHP_ESData.templateA.switchDistance }),
                ...(OHP_ESData.templateA.ampPickup && { ampPickup: OHP_ESData.templateA.ampPickup }),
                ...(OHP_ESData.templateA.fromAirTakeUpDistance && { fromAirTakeUpDistance: OHP_ESData.templateA.fromAirTakeUpDistance }),
                ...(OHP_ESData.templateA.specialControllerOptions && { specialControllerOptions: OHP_ESData.templateA.specialControllerOptions }),
                ...(OHP_ESData.templateA.operatingVoltage && { operatingVoltage: OHP_ESData.templateA.operatingVoltage })

                }),
                freeWheelStatus: OHP_ESData.templateC.freeWheelStatus,
                actuatorStatus: OHP_ESData.templateC.actuatorStatus,
                ...(OHP_ESData.templateC.pivotStatus && { pivotStatus: OHP_ESData.templateC.pivotStatus}),
                kingPinStatus: OHP_ESData.templateC.kingPinStatus,
                lubeBrand: OHP_ESData.templateC.lubeBrand,
                lubeViscosity: OHP_ESData.templateC.lubeViscosity,
                ...(OHP_ESData.templateC.lubeType && { lubeType: OHP_ESData.templateC.lubeType}),
                currentGrease: OHP_ESData.templateC.currentGrease,
                currentGreaseGrade: OHP_ESData.templateC.currentGreaseGrade,
                zerkDirection: OHP_ESData.templateC.zerkDirection,
                zerkLocationType: OHP_ESData.templateC.zerkLocationType,
                wheelDiameter: OHP_ESData.templateC.wheelDiameter,
                conveyorSwing: OHP_ESData.templateC.conveyorSwing,
                ...(OHP_ESData.templateC.chainMaster && { lubeType: OHP_ESData.templateC.chainMaster}),
                ...(OHP_ESData.templateC.remoteStatus && { lubeType: OHP_ESData.templateC.remoteStatus}),
                ...(OHP_ESData.templateC.mountStatus && { lubeType: OHP_ESData.templateC.mountStatus}),
                ...(OHP_ESData.templateC.otherUnitStatus && { lubeType: OHP_ESData.templateC.otherUnitStatus}),
                ...(OHP_ESData.templateC.timerStatus && { lubeType: OHP_ESData.templateC.timerStatus}),
                ...(OHP_ESData.templateC.electricStatus && { lubeType: OHP_ESData.templateC.electricStatus}),
                ...(OHP_ESData.templateC.mightyLubeMonitoring && { lubeType: OHP_ESData.templateC.mightyLubeMonitoring}),
                ...(OHP_ESData.templateC.preMountType && { lubeType: OHP_ESData.templateC.preMountType}),
                ...(OHP_ESData.templateC.otherPreMountType && { lubeType: OHP_ESData.templateC.otherPreMountType}),
                ...(OHP_ESData.templateC.plcConnection && { lubeType: OHP_ESData.templateC.plcConnection}),
                ...(OHP_ESData.templateC.otherControllerNotes && { lubeType: OHP_ESData.templateC.otherControllerNotes}),
                ...(OHP_ESData.templateC.templateC_UnitType && { lubeType: OHP_ESData.templateC.templateC_UnitType}),
                templateC_InvertedA: OHP_ESData.templateC.templateC_InvertedA,
                templateC_InvertedB: OHP_ESData.templateC.templateC_InvertedB,
                templateC_InvertedE: OHP_ESData.templateC.templateC_InvertedE,
                templateC_InvertedS: OHP_ESData.templateC.templateC_InvertedS,
            }),

            ...(OHP_ESData.wheelOpenType && { wheelOpenType: OHP_ESData.wheelOpenType }),
            ...(OHP_ESData.wheelClosedType && { wheelClosedType: OHP_ESData.wheelClosedType }),
            ...(OHP_ESData.openStatus && { openStatus: OHP_ESData.openStatus }),
            ...(OHP_ESData.freeWheelStatus && { freeWheelStatus: OHP_ESData.freeWheelStatus }),
            ...(OHP_ESData.guideRollerStatus && { guideRollerStatus: OHP_ESData.guideRollerStatus }),
            ...(OHP_ESData.openRaceStyleType && { openRaceStyleType: OHP_ESData.openRaceStyleType }),
            ...(OHP_ESData.closedRaceStyleType && { closedRaceStyleType: OHP_ESData.closedRaceStyleType }),
            ...(OHP_ESData.holeStatus && { holeStatus: OHP_ESData.holeStatus }),
            ...(OHP_ESData.actuatorStatus && { actuatorStatus: OHP_ESData.actuatorStatus }),
            ...(OHP_ESData.pivotStatus && { pivotStatus: OHP_ESData.pivotStatus }),
            ...(OHP_ESData.kingPinStatus && { kingPinStatus: OHP_ESData.kingPinStatus }),
            ...(OHP_ESData.railLubeStatus && { railLubeStatus: OHP_ESData.railLubeStatus }),
            ...(OHP_ESData.externalLubeStatus && { externalLubeStatus: OHP_ESData.externalLubeStatus }),
            ...(OHP_ESData.lubeBrand && { lubeBrand: OHP_ESData.lubeBrand }),
            ...(OHP_ESData.lubeViscosity && { lubeViscosity: OHP_ESData.lubeViscosity }),
            ...(OHP_ESData.sideLubeStatus && { sideLubeStatus: OHP_ESData.sideLubeStatus }),
            ...(OHP_ESData.topLubeStatus && { topLubeStatus: OHP_ESData.topLubeStatus }),
            ...(OHP_ESData.chainMaster && { chainMaster: OHP_ESData.chainMaster }),
            ...(OHP_ESData.timerStatus && { timerStatus: OHP_ESData.timerStatus }),
            ...(OHP_ESData.electricStatus && { electricStatus: OHP_ESData.electricStatus }),
            ...(OHP_ESData.pneumaticStatus && { pneumaticStatus: OHP_ESData.pneumaticStatus }),
            ...(OHP_ESData.mightyLubeMonitoring && { mightyLubeMonitoring: OHP_ESData.mightyLubeMonitoring }),
            ...(OHP_ESData.plcConnection && { plcConnection: OHP_ESData.plcConnection }),
            ...(OHP_ESData.otherControllerNotes && { otherControllerNotes: OHP_ESData.otherControllerNotes }),
            ...(OHP_ESData.railLubeStatus && { railLubeStatus: OHP_ESData.railLubeStatus }),
            ...(OHP_ESData.railLubeStatus && { railLubeStatus: OHP_ESData.railLubeStatus }),
            ...(OHP_ESData.railLubeStatus && { railLubeStatus: OHP_ESData.railLubeStatus }),
            ...(OHP_ESData.railLubeStatus && { railLubeStatus: OHP_ESData.railLubeStatus }),
            ...(OHP_ESData.ohpUnitType && { ohpUnitType: OHP_ESData.ohpUnitType }),
            ...(OHP_ESData.chainDrop && { chainDrop: OHP_ESData.chainDrop }),
            ...(OHP_ESData.ohpDiameter && { ohpDiameter: OHP_ESData.ohpDiameter }),
            ...(OHP_ESData.ohpWidth && { ohpWidth: OHP_ESData.ohpWidth }),
            ...(OHP_ESData.ohpHeight && { ohpHeight: OHP_ESData.ohpHeight })


        });
        req.user.cart.push({
            numRequested,
            productConfigurationInfo: order,
            productType: "OHP_ES"
        });
        await req.user.save();
        return res.status(200).json({ message: "OHP_ES entry added" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal server error" });
    }
});

module.exports = router;